### ISSUE TITLE
The wallet receives and accepts connections, but the subsequent credential offer is never received/presented.

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/bc-wallet-mobile#100]
Credential Issuing services tested:
- https://openvp-candy-dev.vonx.io/
  - Anchored on the CANdy Dev network.
- https://openvp-issuer.apps.silver.devops.gov.bc.ca/
  - Anchored on Sovrin StagingNet
- https://email-verification.vonx.io/
  - Anchored on Sovrin StagingNet

Steps to reproduce:
- Browse to one of the above services and fill out the information to request the credential.
- Using the BC Wallet, scan the resulting QR code.

Observed Behavior:
- The connection offer is received and accepted automatically.
- The expected credential offer is never presented (or perhaps never received).
- The services (logs) indicate they have successfully sent the credential offer. 

Expected Behavior:
- The credential offer to be received and presented for acceptance.

Version Info:
- BC Wallet Version: 0.0.1
- AMA-RN Version: 0.1.0

- Testing on iPhone 13 Pro
- iOS Version 15.2

**Comment by jleach** [comment]
This is because I forgot to add the `MEDIATOR_URL` as an environment parameter to the build; its normally a hidden `.env` file on my laptop so just magically works. Will fix.

**Comment by jleach** [comment]
Fixed in BC Wallet 1.0.1 Build 25. Tested with Verified Email. Not there is an issue displaying credentials. Will look into it for the next meaningful build. Plz confirm this fixing your exiting issue.

**Comment by WadeBarnes** [comment]
I'm not seeing an update for BC Wallet 1.0.1 Build 25 in Test Flight.  It's only showing BC Wallet 1.0.1 Build 18.

**Comment by WadeBarnes** [comment]
Thanks for pushing the update.  I was able to collect and use the credentials `openvp` and `openvp-candy` credentials.
