### ISSUE TITLE
Add "Report a problem" to menu options

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1000]
### Story
As a user, I would like an opportunity to report an issue, so that I can get the issue fixed.

### Acceptance criteria
Given that the holder is in the [menu/settings of BC Wallet](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/4917899e-116b-471b-ad96-771978860522)
When they select "Report a problem"
Then they are taken to the [Feedback form](https://www.surveymonkey.com/r/7BMHJL8) via an in-app browser
And the form also has a contact to DITrust@gov.bc.ca for further help

**Comment by bryce-mcmath** [comment]
as with #999 the implementation has been merged in but will remain commented out until we are ready to un-gate the feature. The survey can still be seen in developer mode from the home screen
