### ISSUE TITLE
Keyboard not displaying in the PIN screen (iOS)

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1005]
Device:  iOS version 16.3.1   Model name 1 Phone 12 Pro

**Comment by nodlesh** [comment]
@cvarjao is this the PIN creation screen, the Pin entry screen or both?

**Comment by nodlesh** [comment]
Is this on 1.0.8 (753) release version?

Tested The latest build(765) on 
iPhone 12 Pro iOS 14.8 (Pass)
iPhone 11 Pro iOS 16.3.1 (Pass)
iPhone 13 Pro Max iOS 16.3.1 (Pass)

Tested with build 753
iPhone 13 Pro Max iOS 16.3.1 (Pass)

Have requested the exact phone iOS combo from SauceLabs will get back when they provide it.

**Comment by nodlesh** [comment]
@cvarjao Can we get the person that had this issue, upgrade their phone to 16.4 and try again? I won't be able to get that phone with 16.3.1 on SauceLabs since that OS is no longer signed by Apple.

**Comment by cvarjao** [comment]
Unable to reproduce. Reinstalling the app resolves the issue
