### ISSUE TITLE
LSBC test credential card does not render attributes on card in French or Portugues

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1013]
LSBC test credential card does not render attributes on or the logo card in French or Portugues

Build 772
iOS and Android

[See screenshot](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/18eaed03-9f96-41d7-89da-558869a33c00)

**Comment by jleach** [comment]
@wadeking98 Is this one fixed already?

**Comment by wadeking98** [comment]
Yes I already fixed this
