### ISSUE TITLE
No indication of something clickable to get to remove contact

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#1016]
After clicking on a contact and you enter chat there should be something to indicate that you can click to the top right of the contact name to get into remove contact. There is another there on iOS (unsure if android is the same right now - will update). 
However this ticket may be irrelevant if we implement the UI in remove contact in #231

![IMG_0198.PNG](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/43723a8b-6826-4266-a39c-9c1b3266c494)

**Comment by wadeking98** [comment]
resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/736
