### ISSUE TITLE
Address Xcode 14.3 Yoga error

### ISSUE THREAD

**Issue by bryce-mcmath** [bcgov/bc-wallet-mobile#1021]
Late Friday the latest version of Xcode was released, 14.3. Using the version with unsupported versions of React Native causes an error with the Yoga package. Here is the issue: https://github.com/facebook/react-native/issues/36758

Two possible approaches:
  1. Peg version of xcode used in GHA, wait until we upgrade React Native to a supported version
  2. Use `patch-package` to fix the issue (see here:  https://stackoverflow.com/questions/75897834/use-of-bitwise-with-boolean-operands)

**Comment by jleach** [comment]
Estimate a 1, for No. 1 above, added 2 points for a longer term fix.

I'll peg Bifold and our build to xcode 14.2 to avoid this issue until the can do a RN fix (Yoga) or No. 2 above.
