### ISSUE TITLE
Notification switch to vertical scroll

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1028]
### Story
As a user, I want to clearly see all my notifications so that I can deal with them when I receive them

### Background
User research shows that people are not realizing they have multiple notifications in their list. People are missing the Person credential notification in particular as the notification gets hidden away when they try a proof request flow (that they can't complete) before they attempt to get their Person credential. This causes the [Person credential notification to appear behind the right fold](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/99a10316-3deb-4166-a8dd-ada69f50cb23) and people not seeing the "Person credential notification" and being confused. 

### Suggested fix
Some comments from users indicate that they have little use to the Home screen. The content on that screen seems due to real estate not being fully used. Suggests to change the horizontal scroll of notifications to vertical to make better use of real estate and have the list better clearly read.

**Comment by knguyenBC** [comment]
Reviewed with internal team. Concepts to be updated.

**Comment by nodlesh** [comment]
@knguyenBC I'm assuming no dev has been done for this yet? Both this and #1051 are design issues? And that 1051 is no longer a blocker for this one?

**Comment by knguyenBC** [comment]
No dev work. Separate tickets will be made for this. ticket 1051 are related, not necessarily blocked.
