### ISSUE TITLE
The wallet app crashes when trying to view the details of a credential

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/bc-wallet-mobile#103]
Steps to reproduce:
- Get a credential:
  - https://openvp-candy-issuer-dev.apps.silver.devops.gov.bc.ca/
- Navigate to the Credentials screen in the wallet app.
- Click on the credential.

Observed behavior:
- The app crashes.

Expected behavior:
- The app not to crash.
- The details of the credential to be displayed.

Version:
- BC Wallet 1.0.1 (25)

**Comment by cvarjao** [comment]
This has been fixed by #72
