### ISSUE TITLE
Error when declining credential offer

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#1034]
### Steps to Reproduce

``` gherkin
Given the holders wallet(build 795) is setup 
And there are no credentials or connections
When the holder receives a Credential Offer
And they decline the credential offer
Then they receive a message stating "Unable to reject credential offer"
```
This does not happen on build 791

### Screenshots of build 795
![Screenshot 2023-04-14 at 10.33.00 AM.png](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/a0fd8dc1-7793-4575-a4a7-46d635a26a6e)

### Expected Result
There would be an icon, that when clicked would resurface the original revocation notification message. 

 
### Environment
BC Wallet build 795
Android and iOS
Wallet has developer mode on and the environment is set to Test.
Issuer agent is a test agent not a demo agent. Unknown if this happens with a demo issuer. 

### Workaround
Go back to build 791

### Severity
High

### Priority
Medium

### Test Impact
T005.1

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/713

**Comment by nodlesh** [comment]
@wadeking98 This issue isn't fixed in build 798. It errored in last nights regression tests, and this morning in my tests locally. I could have sworn through I used this build yesterday afternoon with no error, but I could be wrong.

**Comment by wadeking98** [comment]
@nodlesh does build 798 have a bifold sub module updated with the latest changes?

**Comment by nodlesh** [comment]
Verified fixed in build 823.
