### ISSUE TITLE
Extend the range of devices the Automated Regression tests run on daily

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#1035]
Right now we are testing 14+ on iOS 
and 10+ on Android. 

We have to come up with an execution plan that includes older OS/devices without the regression taking too long. 
Currently have one run of all tests that picks a potential different OS level for each test in the suite, but at 14+(iOS) and 10+(Android). We may need this separated and more obvious as we extend the range of devices. This suite takes 4-5 hours to run now, we can't duplicate all the tests across all device/OS levels, it will take days to execute. 

Possible options:
- Only run smoke tests on older OS/devices. 
- Another full suite that randomizes older devices/OS
- TBD

Risks:
- Sauce Labs may not have devices/OS that is old enough for us to test on.

**Comment by cvarjao** [comment]
Device restrictions have been removed
