### ISSUE TITLE
French translations of BC Wallet

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1037]
BC Wallet still contains English content when in configured to French.

**Comment by andrewwhitehead** [comment]
IMO it would be better to remove the French translation if it is incomplete.

![image](https://github.com/bcgov/bc-wallet-mobile/assets/10636507/3396299e-6df8-49e2-8dbe-406ac7c51bb7)

**Comment by jeffaudette** [comment]
@knguyenBC to ask delivery team, what is needed for translations

**Comment by jeffaudette** [comment]
Clecio will bring it up in this week's SM/PO meeting @cvarjao

**Comment by knguyenBC** [comment]
Asked delivery team. A few members of the Delivery team prefer the language settings available. Reasoning being that it's nice to show that there's language capabilities and that any language translations is better than no translations (as long as the translations are proper).

**Comment by knguyenBC** [comment]
New policy in affect April 1st 2024 that requires French translations: https://news.gov.bc.ca/releases/2024IGRS0002-000007
