### ISSUE TITLE
Portuguese translations of BC Wallet

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1038]
BC Wallet still contains English content when in configured to Portuguese.

**Comment by jeffaudette** [comment]
@knguyenBC to ask delivery team, what is needed for translations

**Comment by jeffaudette** [comment]
@knguyenBC to ask delivery team, what is needed for translations

**Comment by jeffaudette** [comment]
Clecio will bring it up in this week's SM/PO meeting @cvarjao

**Comment by cvarjao** [comment]
closing as stale issue
