### ISSUE TITLE
Unable to tell credentials appart

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/bc-wallet-mobile#104]
Steps to reproduce:
- Get some credentials:
  - https://openvp-candy-issuer-dev.apps.silver.devops.gov.bc.ca/
  - https://openvp-issuer-dev.apps.silver.devops.gov.bc.ca/
- Navigate to the Credentials screen in the wallet app.

Observed behavior:
- There is no way to distinguish the credentials apart.
![image](https://user-images.githubusercontent.com/10504350/148654659-2f238f3d-6385-4f6a-9ad8-2f168334a41e.png)

Expected behavior:
- To be able to tell the credentials apart.

Version:
- BC Wallet 1.0.1 (25)

**Comment by cvarjao** [comment]
- Display Credential Name instead of "Credential"
- Show Issue Timestamp
