### ISSUE TITLE
Hamburger menu not working from "give feedback" modal

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1045]
The button doesn't do anything. There is not an intuitive way to go back other than the "Exit".

![signal-2023-04-24-125656](https://user-images.githubusercontent.com/1348549/234102669-ba579b09-8246-45cb-b4ad-d2ff69ab57ee.jpeg)

**Comment by knguyenBC** [comment]
Please hide the navigation bar with the modal. The menu and Home header shouldn't be there. If people want to exit the survey, they will need to tap "exit". Please sure that screen readers would not be able to detect the hidden navigation bar.
