### ISSUE TITLE
Person Credential rendering

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1047]
In the "credential offer" and "credential details" screens, it is showing attributes that are not used by BC Person Credential.
While the schema has a list of all possible attributes, the Capture Base overlay defines an ordered list of attributes applicable to a schema or credential definition ID.

https://github.com/bcgov/bc-wallet-mobile/blob/92cb4a0a91a4f032dbb5b308673b1df8a0fdde48/app/src/assets/branding/credential-branding.ts#L148

For example, "Picture" and "Expiry Dateint" are not attributed we are using for BC Person Credential (yet)

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/730
