### ISSUE TITLE
Welcome to BC Wallet In App Guide buttons have the same TestID

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#1049]
The new Welcome to BC Wallet App Guide selector that displays when the wallet first initializes, has both buttons as the same testID, `com.ariesbifold:id/Okay`. One TestId should represent `Use app guides` and a different one for `Don't use app guides`.

**Comment by bryce-mcmath** [comment]
They should now have the testIDs 'Primary' and 'Secondary' respectfully
