### ISSUE TITLE
Increase touch target for buttons

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1059]
Tough targets of buttons are too small, making it difficult to activate the button on the first try. Please ensure that touch targets for all buttons meet WCAG standards of 44x44 px except when:

- The target is available through an equivalent link or control on the same page that is at least 44 by 44 CSS pixels;
- The target is in a sentence or block of text;

Find [location of buttons in this document](https://docs.google.com/document/d/1AusKgpxSpqMODTEFKfDxvX6ZQjgxE1SSIApTJrS0COU/edit?usp=sharing).

**Comment by cvarjao** [comment]
@knguyenBC, can you list the places where you fount that the touch target is too small?

**Comment by knguyenBC** [comment]
Updated with a document that calls out where the button touch target is too small
