### ISSUE TITLE
Setup the Google Play store

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#106]
The Google Play store needs to be setup so that we can expand the test group. This includes a description of the app, screen shots, and artwork. This can be changed at a later date.

What is needed:

### Graphics

- Your app icon must be a transparent PNG or JPEG, up to 1 MB, 512 px by 512 px, and meet our [design specifications](https://developer.android.com/google-play/resources/icon-design-specifications) and [metadata policy](https://support.google.com/googleplay/android-developer/answer/9898842)

[BC Wallet Icon here](https://drive.google.com/file/d/1-4CBR0KOZsBbB7OdduMIZJeI-gbACchF/view?usp=sharing)

- Your feature graphic must be a PNG or JPEG, up to 1MB, and 1,024 px by 500 px

[Google Play feature graphic here](https://drive.google.com/file/d/1-jj0KREvffH9aVfMQh1VEAmc5A6b-okc/view?usp=sharing)

### Phone

**Phone screenshots**

- Upload 2-8 phone screenshots. Screenshots must be PNG or JPEG, up to 8 MB each, 16:9 or 9:16 aspect ratio, with each side between 320 px and 3,840 px

[Google Play phone screenshots here](https://drive.google.com/drive/folders/1-UyLNfH0E6Y0tqLuQ0wbpV4kU-ZX-uNG?usp=sharing)

### Tablet

**7-inch tablet screenshots**

- Upload up to eight 7-inch tablet screenshots. Screenshots must be PNG or JPEG, up to 8 MB each, 16:9 or 9:16 aspect ratio, with each side between 320 px and 3,840 px

**10-inch tablet screenshots**

- Upload up to eight 10-inch tablet screenshots. Screenshots must be PNG or JPEG, up to 8 MB each, 16:9 or 9:16 aspect ratio, with each side between 320 px and 3,840 px

**Comment by jleach** [comment]
@alexgmetcalf @knguyenBC FYI.

**Comment by knguyenBC** [comment]
I can deal with the more visual elements of the this. @alexgmetcalf if you want to work with the description of the app.

**Comment by knguyenBC** [comment]
@jleach Do the screenshots for the other devices (7 and 10 inch tablets) need to be different than the phone ones? Or can we just use the same ones?

**Comment by knguyenBC** [comment]
@alexgmetcalf @jleach The graphical elements for this are done. Please review and let me know if there's any changes necessary.

**Comment by alexgmetcalf** [comment]
Meeting with Jason at 9:30am Feb 8 to discuss.

**Comment by knguyenBC** [comment]
@jleach Realized there were mistakes in the google play graphics so I've uploaded to more correct versions in the same folder.

**Comment by alexgmetcalf** [comment]
See text in App Store ticket.

**Comment by alexgmetcalf** [comment]
@jleach Do you want to send me a screenshot of the stores so I can review, or shall I just move this ticket to Done?

**Comment by jleach** [comment]
I'd just mark it as done. We still have two tickets to track the text changes, those are not done. But since we're using both iTunes and Google Play for distributing beta apps I think they're done.
