### ISSUE TITLE
mobile verifier support for showcase credentials

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1062]
The credentials issued by the showcases (all environments) should work with the mobile verifier templates.

TODO:
- Gather the credential definition ids for Person/Lawyer credentials in the DEV/TEST/PROD instances of the showcase
- Update proof request templates to accept a credential from any of the showcase environments and/or personas/use-case

**Comment by wadeking98** [comment]
I believe I already resolved by https://github.com/bcgov/bc-wallet-mobile/pull/1064
