### ISSUE TITLE
Setup the Apple iTunes Store 

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#107]
The Apple iTunes Store needs to be setup before the application can go live. Should have similar content to the Google Play store.

### Phone screenshots
Both 6.5 inch and 5.5 inch screenshots can be found here: https://drive.google.com/drive/folders/11SnN4QjpgyZr5xxm6l__EpsiJWtgmVss?usp=sharing

**Comment by jleach** [comment]
@alexgmetcalf @knguyenBC FYI.

**Comment by knguyenBC** [comment]
See the ["Setup the Google Play store" ticket](https://app.zenhub.com/workspaces/bc-wallet-6148e7423fe04b001444e2bd/issues/bcgov/bc-wallet-mobile/106) for the graphics.

Note that there's an iOS version of screenshot 5.

**Comment by alexgmetcalf** [comment]
Meeting with Jason at 9:30am Feb 8 to discuss.

**Comment by knguyenBC** [comment]
@jleach added app store screenshots

**Comment by alexgmetcalf** [comment]
@jleach @knguyenBC Content for your feedback:


Promotional text:
(none yet)


Description:

BC Wallet is a digital wallet app from the Government of British Columbia.

With it you can securely receive and store digital credentials, and control when and where you confidentially use them. Digital credentials can be IDs, licenses, memberships, permits, and more.

Privacy is a focus of BC Wallet. The Government of British Columbia is not informed when you receive or use your credentials. You only use the parts of your credentials that are needed for any given situation. Also, credentials are only used over secure, private connections, and you approve each use.

BC Wallet works with credentials in the Verifiable Credential format. Credentials can be “issued” (sent) to your wallet from any source you choose, including businesses, government, and organizations.

BC Wallet is built from open source code by the Government of British Columbia.


Keywords: credential,verifiable,VC,british,columbia,digital,id,identity,ssi,holder,verified,canada,provincial,license


Copyright:
2022 Government of British Columbia


Support URL:
https://digital.gov.bc.ca/digital-trust/contact/

**Comment by knguyenBC** [comment]
I think the description focuses a lot on VCs but I think it would benefit to add why BC Wallet is useful. So something along the lines "Use BC Wallet to securely prove your identity to access online services". Or maybe that's something that live in the promotional text?
 
I would add to keywords (if there isn’t a max cap): wallet, BC, B.C.,

**Comment by alexgmetcalf** [comment]
Yes I'll add a sentence along those lines, also expanding its purpose beyond identity.

For the keywords, we don't need to use keywords that are already in the title. However, I can add B.C. for sure.

**Comment by knguyenBC** [comment]
Oh I see, Perfect. Then I'm fine with it. Though I wonder, since this is a "public"-ish release, should there be approval from Charles?

**Comment by alexgmetcalf** [comment]
Update:

Promotional text:
(none yet)

Description:

BC Wallet is a digital wallet app from the Government of British Columbia.

With it you can securely receive and store digital credentials, and control when and where you confidentially use them. Digital credentials can be IDs, licenses, memberships, permits, and more. This means BC Wallet lets you securely and confidently prove your identity and other things about yourself, in order to access online services and simplify processes.

Privacy is a focus of BC Wallet. The Government of British Columbia is not informed when you receive or use your credentials. You only use the parts of your credentials that are needed for any given situation. Also, credentials are only used over secure, confidential connections, and you approve each use.

BC Wallet works with credentials in the Verifiable Credential format. Credentials can be “issued” (sent) to your wallet from any source you choose, including businesses, government, and organizations.

BC Wallet is built from open source code by the Government of British Columbia.

Keywords: credential,verifiable,VC,british,columbia,digital,id,identity,B.C.,ssi,holder,verified,canada,provincial,license

Copyright:
2022 Government of British Columbia

Support URL:
https://digital.gov.bc.ca/digital-trust/contact/

**Comment by alexgmetcalf** [comment]
Final version:

Promotional text:
(none to start)

Description:
BC Wallet is a digital wallet app from the Government of British Columbia.

With it you can securely receive and store digital credentials, and control when and where you use them. While initial use cases are limited, digital credentials could be IDs, licenses, memberships, permits, and more. This means BC Wallet will let you securely and confidently prove your identity and other things about yourself, to access online services and simplify processes.

Privacy is a focus of BC Wallet. The Government of British Columbia is not informed when you receive or use your credentials. You only use the parts of your credentials that are needed for any given situation. Also, credentials are only used over secure, confidential connections, and you approve each use.

BC Wallet works with credentials in the Verifiable Credential format, an emerging technology. Credentials can be “issued" (sent) to your wallet from any source you choose, including businesses, government, and organizations.

BC Wallet is built from open source code by the Government of British Columbia.

Keywords: credential,verifiable,VC,british,columbia,digital,id,identity,B.C.,ssi,holder,verified,canada,provincial,license

Copyright:
2022 Government of British Columbia

Support URL:
https://digital.gov.bc.ca/digital-trust/contact/

**Comment by knguyenBC** [comment]
> Final version:
> 
> Promotional text: (none to start)
> 
> Description: BC Wallet is a digital wallet app from the Government of British Columbia.
> 
> With it you can securely receive and store digital credentials, and control when and where you use them. While initial use cases are limited, digital credentials could be IDs, licenses, memberships, permits, and more. This means BC Wallet will let you securely and confidently prove your identity and other things about yourself, to access online services and simplify processes.
> 
> Privacy is a focus of BC Wallet. The Government of British Columbia is not informed when you receive or use your credentials. You only use the parts of your credentials that are needed for any given situation. Also, credentials are only used over secure, confidential connections, and you approve each use.
> 
> BC Wallet works with credentials in the Verifiable Credential format, an emerging technology. Credentials can be “issued" (sent) to your wallet from any source you choose, including businesses, government, and organizations.
> 
> BC Wallet is built from open source code by the Government of British Columbia.
> 
> Keywords: credential,verifiable,VC,british,columbia,digital,id,identity,B.C.,ssi,holder,verified,canada,provincial,license
> 
> Copyright: 2022 Government of British Columbia
> 
> Support URL: https://digital.gov.bc.ca/digital-trust/contact/

Sounds good to me.

**Comment by cvarjao** [comment]
@knguyenBC / @alexgmetcalf, let's use this [google docs](https://docs.google.com/document/d/1JsB2qTCXPFv46EDnNLl7dUU-CLcudSLIJTS-AJfWhtE/edit) to track the app store listing elements. We will need to get that reviewed by execs and GCPE.

**Comment by jleach** [comment]
This has been added to the iOS and Google Play stores where applicable.
