### ISSUE TITLE
issues with using the wallet after timeout

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1089]
At least in iOS, after some idling time and re-authenticating the mobile verifier feature doesn't work as expected.

- Open wallet
- Let it idle until it auto-locks
- unlock app again
- use the verifier

Needs to be re-tested after AFJ 0.4.0

**Comment by bryce-mcmath** [comment]
@cvarjao Any more details for this one?

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/879

**Comment by hiteshgh** [comment]
not able to reproduce , closing, if the issue re-occurs will open a new issue later
