### ISSUE TITLE
Screen reader should read the issuer name and credential name

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1095]
Screen reader reads "Credential details" and not the issuer and credential name. If someone was using a screen reader, they would not know how to find their credential.

**Comment by cvarjao** [comment]
@knguyenBC, is this from the credential list?

**Comment by knguyenBC** [comment]
Yes this is in the credential list. Also only on Android.

**Comment by cvarjao** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BC-Wallet-6148e7423fe04b001444e2bd/issues/bcgov/bc-wallet-mobile/1095?planning-poker) with Zenhub @jleach @wadeking98 @bryce-mcmath @nodlesh @knguyenBC

**Comment by cvarjao** [comment]
duplicates #1097
