### ISSUE TITLE
Can't double tap credential in credential list screen to open to credential details with screen reader on

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1097]
Issue appears on Android only. iOS works fine. 
- With the screen reader on, in the credential list screen, the credential details of a credential won't open when I try to activate the credential. 
- When the focus is on a credential in the credential list, it reads "credential details". 
 
**Expected behaviour:**
- It should read out the credential issuer name and credential name.
- Double tap to activate the focused credential should open its credential details screen

**Comment by cvarjao** [comment]
@knguyenBC, is this from the credential list screen?

**Comment by knguyenBC** [comment]
Yes, this was from the credential list screen.

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/796
