### ISSUE TITLE
Integration with Functional Testing Service with CI/CD pipeline

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#110]
As part of the build/release/CD pipeline
- [x] Upload iOS/Android packages
- [ ] Every time we do a build, pull testing harness and run test using the respective build packages

**Comment by nodlesh** [comment]
@jleach zip file contains example actions to run the test harness. Ping me for allure creds that need to be setup as secrets.
[https://app.zenhub.com/files/429950091/88ba363c-5259-4462-a822-f4c03a169f0e/download](https://app.zenhub.com/files/429950091/88ba363c-5259-4462-a822-f4c03a169f0e/download)
