### ISSUE TITLE
Accessibility 101

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1116]
- [React Native Accessibility](https://reactnative.dev/docs/accessibility)
- [BC Gov Accessibility Guide](https://www2.gov.bc.ca/gov/content/home/accessible-government/toolkit/accessible-digital-content)
- [Web Content Accessibility Guidelines 2.0](https://www.w3.org/TR/WCAG20/)
- [Web Content Accessibility Guidelines 3.0 - draft](https://www.w3.org/TR/wcag-3.0/)
- Mobile Screen Reader setup/use
- Mobile Voice Over setup/use

**Comment by bryce-mcmath** [comment]
Here is snippet for setting autofocus in React Native (useful for setting focus on a header for example) https://github.com/cds-snc/covid-alert-app/blob/main/src/shared/useAccessibilityAutoFocus.ts

**Comment by bryce-mcmath** [comment]
Added to Accessibility and Testability Guide discussion in Bifold repo: https://github.com/hyperledger/aries-mobile-agent-react-native/discussions/711
