### ISSUE TITLE
Define "more content" hint as part of design guide

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1117]
### User story
As a user, I want to visibly see if there is more content to scroll so that I don't miss any content hiding below the fold. 

### Design
In style guide: https://xd.adobe.com/view/eb9e0945-61d7-40ca-8e8e-bf4bd0c72934-becd/screen/096d0603-d83f-4677-ab49-fc92485e4ba3/specs/ 

### Acceptance criteria
Given that the navigation tab is present on the screen
When there is content below the navigation tab
Then the content is blurred

**Comment by knguyenBC** [comment]
Have a concept design. To review with internal and pan-can team.

**Comment by knguyenBC** [comment]
Clecio approved design. Review with devs.

**Comment by nodlesh** [comment]
Does this need another story for devs? I can't find one, if one exists can someone mention it here to create the link between the issues?
