### ISSUE TITLE
Buttons with animated icons change size when animating

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#1123]
Buttons with animated images, like the one pressed to enter the PIN change size when the icon displays and the animation begins.

https://images.zenhubusercontent.com/429950091/1e221cce-7bd9-4e6d-a31b-0a53b1eb76e3/buttonchangessize.mov

### Expected Behaviour

The button should remain a constant width as should the text.

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/804

**Comment by nodlesh** [comment]
This is still and issue, in the exact place Jason mentions. Tested on iPhone 6S, iOS 15.7.1

**Comment by jleach** [comment]
@nodlesh I think this one is fixed. I tested on the same device as my original issue and the button frame stays the same size when transitioning to to animation. Here is a [video](https://fullboarca-my.sharepoint.com/:v:/g/personal/jason_leach_fullboar_ca/Ea5XCkfWpVROvsz16k00DpgB6BuM6fX26bqsZV3Yas68iA?e=mTXspE). If you're still seeing the issue are you able to post a video. Ty.

**Comment by nodlesh** [comment]
This one is indeed fixed in the latest build.
