### ISSUE TITLE
Contacts and Messages "Date" should be "DateTime"

### ISSUE THREAD

**Issue by swcurran** [bcgov/bc-wallet-mobile#1125]
On both the Contacts list screen and (after clicking on a Contact) the Message list screen for a specific content, the date appears in the list.  Please change the display from being a date, to a date/time so we can see when the Contacts and Messages are updated.

Screenshots:

![ContactsList](https://github.com/bcgov/bc-wallet-mobile/assets/1018050/8cb1dc1c-1e15-42a8-ae64-510c30a8f75f)

![MessagesList](https://github.com/bcgov/bc-wallet-mobile/assets/1018050/f081e23d-120a-4a2b-9afe-2de8ff184e2d)

**Comment by nodlesh** [comment]
@cvarjao  Has the development for this ticket been done? I notice that the contacts screen doesn't have a date now, and the chat screen has date time as requested.

**Comment by knguyenBC** [comment]
Checked. messages are timestamped.
