### ISSUE TITLE
Unable to approve proof request for dev showcase (joyce)

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1145]
### Description of problem
Getting Error Code 1027 - unsupported URL

### Expected behavior
Credential to be successfully shared and received by the showcase

### Steps to reproduce
- setup wallet
- access the dev showcase site
- pick Joyce
- follow the showcase until you get to "Using your credentials" and select "Court Services"

### Screenshots and/or log output
![MicrosoftTeams-image (17)](https://github.com/bcgov/bc-wallet-mobile/assets/1348549/f723db02-be9e-4a4f-91d0-13af9933134d)

### Environment
- [ ] Occurs on Android
- [x] Occurs on iOS

Build #:
926

Android Device Model: 

iOS Device Model: 
iPhone 7, iOS 15.7.5

### Workaround
none

### Severity
- [ ] High
- [ ] Medium
- [x] Low

**Comment by jleach** [comment]
I tested in Dev, Test and Prod. All work except I get a different issue in prod. I can use the proof but but the response message never arrives. [Here](https://fullboarca-my.sharepoint.com/:v:/g/personal/jason_leach_fullboar_ca/Ebq4lsooPJFEsmC5hUs7UeQBcRhgnw_MJIKhe7m6zE8_Lg?e=kymnH7) is a video showing what i get. I think @wadeking98 will need to look into this one. The video is low quality but the proof data never shows up on the web view in the background. It does in `dev` and `test`, just not prod.
