### ISSUE TITLE
OOB Connectionless Proof Request Results in Invalid QR Code

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#1147]
### Description of problem
When an out-of-band invitation is created with a proof request attachment the wallet will show "Invalid QR Code" when scanning. 
An interesting note is that if I then close the error/scan window the app has my proof request in the notifications. I can then proceed to do the proof request successfully. I can then check the contacts and it does not have my verifier as a contact.

### Expected behavior
The QR code would be scanned without error and immediately show me the proof request screen.

##### General Reproduction
- Get an unverified person credential from https://openvp-candy-issuer-test.apps.silver.devops.gov.bc.ca/
- Start or use a verifier agent looking at the CANdy ledger https://raw.githubusercontent.com/ICCS-ISAC/dtrust-reconu/main/CANdy/test/pool_transactions_genesis
- Verifier calls `/present-proof/create-request` with the following proof request
```
{
   "name": "unverified-person",
   "version": "0.0.1",
   "requested_attributes": {
      "person_attrs": {
         "names": [
               "given_names",
               "family_name",
               "birthdate",
               "street_address",
               "postal_code",
               "locality",
               "region",
               "country"
            ],
         "restrictions": [
               {
                  "schema_name": "unverified_person",
                  "schema_version": "0.1.0"
               },
               {
                  "schema_name": "unverified_person",
                  "schema_version": "0.2.0"
               }
         ]
      }
   },
   "requested_predicates": {}
}
```
- With the created proof request in the previous call, get the thread id and do a GET /present-proof/records with the id to get the presentation exchange id.  
- call `/out-of-band/create-invitation` with the presentation exchange id and a type of "present-proof" added to the attachments section of the payload. 
- Create a QR code with the invitation returned from the create-invitation call and scan it with the wallet.

There are multiple ways to do the above steps when investigating this issue. 
#### Get Sheldon to run the test
Get together with Sheldon and he can run the test in the debugger in VS Code and stop where the QR code is created. This QR code can be scanned by any phone or emulator, local or remote. So if you would like to see what is happening in the phone on your local dev machine, you can do this.

#### Run the full regression test in AMTH - T009.1-Proof
```
git clone https://github.com/hyperledger/aries-agent-test-harness
cd aries-agent-test-harness
./manage build -a acapy-main
GENESIS_URL=https://raw.githubusercontent.com/ICCS-ISAC/dtrust-reconu/main/CANdy/test/pool_transactions_genesis AGENT_CONFIG_FILE=/aries-backchannels/acapy/read_only_ledger_verifier_config.yaml ./manage start -b acapy-main -n

git clone https://github.com/hyperledger/aries-mobile-test-harness
cd aries-mobile-test-harness
./manage build -w bc_wallet
./manage run -d SauceLabs -u <device_cloud_username> -k <device_cloud_access_key> -p iOS -a BCWallet-926.ipa -i "CANdy_UVP;https://openvp-candy-issuer-test.apps.silver.devops.gov.bc.ca/" -v "AATH;http://0.0.0.0:9030" -t @bc_wallet -t @T009.1-Proof
```
In the above run command you can get device cloud username and password from Sheldon. This will run the test with an iOS device in Sauce Labs. You can log in to SauceLabs and see device logs and appium logs, along with  video of the test run.

#### Run the Paired Down Debug Test Scenario in VC Code- T009.1.debug-Proof
```
git clone https://github.com/hyperledger/aries-agent-test-harness
cd aries-agent-test-harness
./manage build -a acapy-main
GENESIS_URL=https://raw.githubusercontent.com/ICCS-ISAC/dtrust-reconu/main/CANdy/test/pool_transactions_genesis AGENT_CONFIG_FILE=/aries-backchannels/acapy/read_only_ledger_verifier_config.yaml ./manage start -b acapy-main -n

git clone https://github.com/hyperledger/aries-mobile-test-harness
cd aries-mobile-test-harness
./manage build -w bc_wallet
```
Setup VS Code for test development. Using the following launch.json config.
```
        {
            "name": "Python: Behave current file Sauce Labs Connectionless",
            "type": "python",
            "request": "launch",
            "module": "behave",
            "console": "integratedTerminal",
            "cwd": "${workspaceFolder}/aries-mobile-tests",
            "env": {
                "SAUCE_USERNAME": "get from sheldon",
                "SAUCE_ACCESS_KEY": "get from sheldon",
                "SL_REGION": "us-west-1",
                "DEVICE_CLOUD": "SauceLabs",
                "TEST_RETRY_ATTEMPTS_OVERRIDE": "1"
            },
            "args": [
                "${file}",
                "--tags=@T009.1.debug-Proof",
                "-k",
                "-D",
                "Issuer=CANdy_UVP;https://openvp-candy-issuer-test.apps.silver.devops.gov.bc.ca/",
                "-D",
                "Verifier=AATH;http://0.0.0.0:9030"
            ]
        },
```
- You will need the libraries that the test harness uses installed locally, so Behave etc. Try running the debugger with that debug config and with the proof.feature file open and install libraries it complains about. 
- Put a breakpoint on line 426 in proof.py and when it stops get the qrcode.png from the test harness directory and scan it with your phone or emulator. 

### Screenshots and/or log output
![Screenshot 2023-06-01 at 3.11.49 PM.png](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/6ee37e89-ae6e-4a2e-988b-64eab64437c2)

Video:
https://images.zenhubusercontent.com/429950091/5f68056a-11d5-4bb2-ab33-1261b73d8cb2/oobconnectionlessproof480.mov

### Environment
- [ X] Occurs on Android
- [ X] Occurs on iOS

Build #: 942

Android Device Model: All

iOS Device Model: All

### Workaround
Close the scan error message and continue on.

### Severity
- [X ] High
- [ ] Medium
- [ ] Low

**Comment by cvarjao** [comment]
That is a super dense QR code

**Comment by nodlesh** [comment]
It is, but I've seen worse.

**Comment by jleach** [comment]
@nodlesh That's a pretty gnarly setup to reproduce. Do any of our demos produce this problem?  We can create OOB proofs with our verifier app and they seem to work fine. Are you able to send me 3 QR codes that I can use locally for testing. At least to see what the error message is under-the-hood.

**Comment by nodlesh** [comment]
No demo that I know of reproduces with OOB.

I'm building a dev container for the test harness so anyone can attach VS Code to it without all the setup. In the meantime we can get together and I can run it and give you the QR code to scan while my test agents are running. 

The OOB proofs in the verifier app does not have the proof attachment as far as I understand.

**Comment by nodlesh** [comment]
Took a deep dive here with BC Wallet build 1363, the test continued to fail in the nightly regression tests however I didn't notice it was for a different reason. Right now the BC Wallet accepts an OOB message with a presentation attached, no issue. 
However, the test is failing at the very end from an ACA-Py perspective. After it gets a web hook of presentation received, it errors out. 
I think this issue can be closed, and an investigation in ACA-Py take place on the resulting issue.
