### ISSUE TITLE
Set Wallet name during onboarding

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1148]
### Description of feature / user story
As a person who connects with other people and organizations,
I want to be able to set how I'm represented in other people's wallets
so that my contacts can easily distinguish me from other contacts.

This user story can be accomplished by allowing users to name their wallet. Whatever they name their wallet will be shown to others when a connection is made. This feature also is a precursor for multi-tenant wallets. 

### Acceptance Criteria
Given the holder has just installed BC Wallet
And is going through the onboarding process
When the holder continues from the "Lock biometrics screen"
Then they are presented with the option to name their wallet
And the default name of the wallet is "My Wallet"
And they are presented with the option to tap "not now" to complete this step later

### Wireframes or relevant image assets / links
[Wireframes
](https://xd.adobe.com/view/0900b5b9-22d7-44aa-b9ee-e3693e33a5f3-5c53/)

### Decisions
Default wallet name: "My Wallet - <random-4-digit-numbers>"
Acceptable Characters: Any character (including `\`, `"`)
Minimum Characters: 1
Maximum character count: 50

**Error messages**
title: Character count exceeded
body: You've exceeded the maximum character count of 50 characters. Please reduce your character count.

title: Wallet name can't be empty
body: This is the name people see when connecting with you. Please enter a wallet name.

Please follow [Text Fields](https://xd.adobe.com/view/eb9e0945-61d7-40ca-8e8e-bf4bd0c72934-becd/screen/8dcbeef8-7739-483c-bf74-50c8ab219853/specs/) and [notifications](https://xd.adobe.com/view/eb9e0945-61d7-40ca-8e8e-bf4bd0c72934-becd/screen/3bb2426a-f6e5-481b-ab16-c08c817b8fd4/specs/) UI specifications from style guide.

**Comment by bryce-mcmath** [comment]
@knguyenBC Did we decide that the not now button wouldn't be an option?

**Comment by bryce-mcmath** [comment]
And this is ready for development now, correct?

**Comment by knguyenBC** [comment]
Needs minor updates and specs based on our conversation during refinement. This includes removing the not now button

**Comment by knguyenBC** [comment]
Updates the style guide specs to include text fields. Updated tickets to include error message content. Removed "not now" button and added a 4 digit string to default wallet name to wireframes.

**Comment by nodlesh** [comment]
Question: What happens when this feature is turned on, and users already having the wallet installed with an older version, upgrades to this version?

**Comment by bryce-mcmath** [comment]
They are assigned a random name following this pattern: 'My Wallet - ####'. They don't go back through onboarding or see the wallet name screen

**Comment by knguyenBC** [comment]
@bryce-mcmath Still can't test this feature. I can go into dev mode from onboarding but there isn't an option to turn on wallet name.

**Comment by wadeking98** [comment]
tested in testflight, confirmed working
