### ISSUE TITLE
Add on-boarding carousel screen content

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#115]
Add content for new on-boarding carousel screens to bc variant build.

**Comment by nodlesh** [comment]
This story has been tested in the integration tests. 
Full test Specification  for the Onboarding feature is located here.
https://github.com/hyperledger/aries-mobile-test-harness/blob/main/aries-mobile-tests/features/bc_wallet/onboarding.feature
This PR closes the testing for this feature. hyperledger/aries-mobile-test-harness#34
Test results can be seen here, https://allure-mobile.vonx.io/allure-docker-service-ui/projects/android-one-device-smoke

@cvarjao Should we have a place we reference the behavioural specification in the tests in one place? Like maybe the GitHub wiki for the project?
