### ISSUE TITLE
The photo displays as base64 in for OCA bundle is specified.

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#1150]
When using the dev showcase site the Picture attribute shows up as base64 encoded data in the credential offer when using the Bifold version of the iOS application. I think this data is meant for a machine and should be abstracted away in no OCA is set, perhaps just show a placeholder image or text saying "no image available".

![Screenshot 2023-06-05 at 10.40.48 AM.png](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/dfcb7dbe-2575-48ac-bbee-517235edf6c3)

**Comment by swcurran** [comment]
The data is the image.  I would think even without the OCA, the wallet should be able to detect that the data value is a data URL and decode it appropriately, displaying the image.

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/814

**Comment by nodlesh** [comment]
This is now working in automated regression test T002.1-CredentialOffer & T008-CredentialOffer. Image is showing on both platforms in build 978.
