### ISSUE TITLE
Remove Contact with credential not showing can't remove message without closing previous window

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#1151]
### Description of problem
When removing a contact that has issued a credential this this holder, when you click Remove Contact, nothing happens. You have to close the window with the X or Cancel, then the message appears that you can't remove this contact because of the Credential.

### Expected behavior
When selecting Remove Contact it should display the message right away that you can't remove this contact. 

### Steps to reproduce
Get a credential in your wallet. 
Go to contacts and select Remove Credential
On the modal that pops up, select Remove Credential.

### Screenshots and/or log output
Video:
https://images.zenhubusercontent.com/429950091/d8f2d60c-9e55-4de2-acf8-f78d06a47f63/rpreplay_final1686150853.mp4

### Environment
- [ ] Occurs on Android
- [ ] Occurs on iOS

Build #: 947

Android Device Model: 

iOS Device Model: iOS 15.7.1 iPhone 6S

### Workaround
Just close the modal.

### Severity
- [ ] High
- [X ] Medium
- [ ] Low

**Comment by nodlesh** [comment]
Relating to story #231

**Comment by knguyenBC** [comment]
Tested on Android and iOS. works fine.
