### ISSUE TITLE
Give Feedback Button missing from Home on Android

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#1153]
### Description of problem
The Give Feedback button as defined in #1002 is missing on Android devices

### Expected behavior
not missing 

### Steps to reproduce
Open it.

### Screenshots and/or log output
![Screenshot 2023-06-07 at 2.30.12 PM.png](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/11ff2a00-bfb9-43d9-8150-52975083191c)

### Environment
- [X ] Occurs on Android
- [ ] Occurs on iOS

Build #: 926

Android Device Model: All

iOS Device Model: 

### Workaround
None

### Severity
- [ ] High
- [ X] Medium
- [ ] Low

**Comment by cvarjao** [comment]
This feature is only available in developer mode

**Comment by nodlesh** [comment]
Closing. This is a non issue.
