### ISSUE TITLE
Erroneous "Not Available"

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1157]
### Description of problem
I've tested creating a cred def with and without spaces in the tag. The one without spaces works as expected.
 
### Expected behavior

not seeing a "Not Available" and proof request marked a not able to fulfill

### Steps to reproduce
- Create a schema with the following attributes:
   ```json
  {
  "attrNames": [
    "family_name",
    "given_names",
    "expiry_date_dateint"
  ],
  }
   ```
- Create a Cred Definition ID with spaces in the tag, such as `Demo (For Demo)`
- Connect to a wallet and issue a proof request
```json
{
    "name": "proof-request",
    "nonce": "1234567890",
    "version": "1.0",
    "requested_attributes": {
      "Person": {
        "names": [
          "given_names",
          "family_name"
        ],
        "non_revoked": {
          "from": 1686187529,
          "to": 1686187529
      },
        "restrictions": [
          {
            "cred_def_id": "3k63ryz8JPPDpW8P1RPGBm:3:CL:838186:Demo (For Demo)"
          }
        ]
      }
    },
    "requested_predicates": {
      "not_expired": {
        "name": "expiry_date_dateint",
        "p_type": ">=",
        "p_value": 20230527,
        "restrictions": [
          {
            "cred_def_id": "3k63ryz8JPPDpW8P1RPGBm:3:CL:838186:Demo (For Demo)"
          }
        ]
      }
    }
  }
```
  Note: Adjust `cred_def_id` to reflect the new one created
- The proof request shows a "Not available" message, but still allows to share the credential.
### Screenshots and/or log output

![signal-2023-06-07-160645_002](https://github.com/bcgov/bc-wallet-mobile/assets/1348549/ed594645-9b47-4705-85f1-2780ce2b32eb)

### Environment
- [ ] Occurs on Android
- [x] Occurs on iOS

Build #:

Android Device Model: 

iOS Device Model: 

### Workaround
 - Avoid spaces in the tag when creating cred def  
### Severity
- [ ] High
- [x] Medium
- [ ] Low

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/818
