### ISSUE TITLE
Test ID Missing from Developer Options Environment

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#1158]
### Description of problem
Starting in build 949 the testID for Developer Options Environment is no longer there. Reverted to trying to retrieve the element by an accessibilityID of "Environment" and that didn't work either. 
This caused all tests to fail in the nightly regression since switching to the test environment is one of the first things done in a test scenario.

### Environment
- [x] Occurs on Android
- [x] Occurs on iOS

Build #: 949+

Android Device Model: 

iOS Device Model: 

### Workaround
I have to turn off switching environments. 

### Severity
- [X ] High
- [ ] Medium
- [ ] Low

**Comment by jleach** [comment]
Fixed. I can see them all in Appium Inspector.

**Comment by jleach** [comment]
@nodlesh The smoke test ran with one failure. Not sure why. I watched the video and it just goes dark at the end. In any case LMK if this fixes the issue.

**Comment by nodlesh** [comment]
Yes that fixed it. The iOS smoke test passed. The android test got hung up on scanning the QR code from the verifier. I'll investigate in the morning.
