### ISSUE TITLE
Display predicates on proof request in a human readable way (v2) | Design

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1171]
**Background**
Supported Operators:[ >=, >, <=, <](https://hyperledger.github.io/anoncreds-spec/#predicate_info)
Supported Types: Numbers, DateInt

In a proof request asking for a Student Card that hasn't expired at the time of request, it currently displays
ex: ">=20230314" which does not make sense to a lot of people.

Please display the date in a more human readable way such as (if using the example date above): 
 Exceed March 13, 2023.

### Acceptance Criteria

**if DateInt**
- ">=" ---"is after [date-1]. ex. ">=20230314" ---"Birthdate is after 20230313"
- "<=" --- "is before [date+1]. ex. "<=20230314" --- "Birthdate is before 20230315"
- ">" --- "is after [date]". ex. ">20230314" --- "Expiry date is after 20230314"
- "<" --- "is before [date]". ex. "<20230314" --- "Expiry date is before 20230314"

**Other Integers**
- ">=" --- "is or greater than or equal to [integer]. ex. ">=20230314" --- "Weight is or greater than or equal to 100"  
- "<=" --- "is or less than or equal to [integer]" ex. "<=20230314" --- "Amount is or less than or equal to 10"
-  ">" --- "is greater than [integer]" ex. "<20230314" --- "Quantity is greater than 20"
-  "<" ---  "is less than [integer]" ex. ">20230314" --- "Cost is less than 300"

**Comment by cvarjao** [comment]
We can identify if the attribute format is a date and maybe use terms like "newer than", "older than"

**Comment by knguyenBC** [comment]
Clecio approved. closing.
