### ISSUE TITLE
Update Proof Request Detail Screen

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1172]
### background
Some people saw the UI of the current iteration and thought they were text field. They tried to tap to edit the text.

### Design
Update list of fields to be a bullet list

[Wireframes](https://xd.adobe.com/view/0a112c19-6f28-48cd-8ba6-3d80c7cd3771-5f42/screen/5e0ea247-8230-427c-82fc-0daf7584f20c)

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/828

**Comment by knguyenBC** [comment]
Attributes should not be bold. Removing the bold from the attributes but keeping the bold in the credential name helps to quickly visually differentiate between the two different pieces of information.
