### ISSUE TITLE
Change content on Proof request QR code screen 

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1173]
### Background
Current proof request QR code screen confuses the holder as they believe the instruction is for them (the intent was that the instructions is for the person scanning the QR code). 

Layout also does not maximize screen size for easier QR code scanning. Layout is also not ideal for increase in font size as text enlargement will push the QR code down and require users to scroll

### Suggested changes
[See wireframe](https://xd.adobe.com/view/0a112c19-6f28-48cd-8ba6-3d80c7cd3771-5f42/screen/017256fe-dca6-4daf-ac50-2e73686d22b5)
- Increase QR code size to fit maximum space
- reorder text
- Update content 
- Change button to "Refresh QR code"
- remove the "Share link" button
- White background

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/838

**Comment by knguyenBC** [comment]
Not part of ticket but when QR code is refreshed, the app needs a better loading icon than the one being used. I'll create a ticket for it. Otherwise, looks good.
