### ISSUE TITLE
Automatically Increase Screen Brightness to max when showing QR Code

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1174]
### Background
QR codes are sometimes difficult to scan. Increasing the brightness helps. 

### Success Criteria
Given the holder's device is not set at max brightness
When the holder is in the "My QR code" screen or "Proof request QR code" screen
Then the holder's device screen brightness is set to max

Given the holder's device is not set at max brightness
When the holder moves away from the "My QR code" screen or "Proof request QR code" screen
Then the holder's device screen brightness reverts back to it's original setting

**Comment by jleach** [comment]
We could consider using the [Expo brightness package](https://docs.expo.dev/versions/latest/sdk/brightness/). This will need us to request permissions from our users. To make it smooth, let's add a screen to explain why we need access to their brightness settings. This could increase our chances of gaining access. Please note that the brightness adjustments won't be permanent on iOS and will reset each time the app closes. So the user experience will slightly differ between iOS and Android.

**Comment by cvarjao** [comment]
closing as stale issue
