### ISSUE TITLE
Update proof request response screen

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1176]
The current proof request response screen is confusing as it's coloured green and has a checkmark that gives the impression that the information in the proof request is correct/approved. 

[Current screenshot](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/20bf8371-6358-481b-ae66-3d07a5f3bf0b)

Suggested change:
[Design
](https://xd.adobe.com/view/0a112c19-6f28-48cd-8ba6-3d80c7cd3771-5f42/screen/432ebd7d-e710-49b5-bc4f-a9cffa0428bc)

- Update Icon/Banner
- Update buttons

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/842
