### ISSUE TITLE
add Scan my QR code tab to scanner

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1179]
### Background
Some people on instinct make a connection with a person prior to interacting with them. There's a desire to highlight connections. Similar to adding a person as a contact prior to messaging people. The current flow, "create a connection invitation" doesn't embody that similar interaction. Suggestion is to follow "add a contact" flows used by messaging apps. 

### Design
[Wireframes](https://xd.adobe.com/view/0a112c19-6f28-48cd-8ba6-3d80c7cd3771-5f42/)

### Acceptance criteria
Given holder is in Home screen
When holder taps the Scan button
Then they are taken to the Scan QR code tab 
And a tab bar is available with the tab options: Scan QR code (default) and My QR Code

Given the holder is in the Contacts screen
When the holder taps the "+" button
Then the holder is taken to the My QR Code tab

Given the holder is in the menu options
When the holder taps "Scan my QR code"
Then they are taken to the My QR Code tab

**Comment by bryce-mcmath** [comment]
@cvarjao is this also supposed to be feature flagged? It changes screens pretty dramatically so feature flagging it could prove quite difficult

**Comment by cvarjao** [comment]
@bryce-mcmath , how much of a dramatic change? Mobile verifier is not going GA just yet, so I would prefer that it was feature flagged. This would appear when enabling the existing "Use connection invite capability" instead of showing the QR Code screen in the Menu, it would show in the Scan screen. How much of an estimation change?

**Comment by bryce-mcmath** [comment]
So with that toggled on, there is a right header button in Contacts that goes to the new Scan screen (with the dual tabs) and the dual tab Scan screen shows when users hit Scan, but without it toggled on, the right header button disappears and when users press 'Scan' from the home screen the old Scan screen in shown with it's previous styling and no tabs? I'd probably take it from a 5 to an 8.

**Comment by hiteshgh** [comment]
Its in Test-flight, @knguyenBC to test and close

**Comment by knguyenBC** [comment]
Test on iOS and Android build 1087. Works as described in AC.
