### ISSUE TITLE
Update Terms and Conditions Text

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#118]
CM will provide the text from lawyers

### Acceptance Criteria
Given the Holder is first going through the onboarding screens
When the Holder is at the Terms and Conditions Screen
Then the Holder is presented with content that matches exactly the terms and conditions within the following document: [https://app.zenhub.com/files/429950091/85f29998-e55e-417e-a8c0-b00531b3caba/download](https://app.zenhub.com/files/429950091/85f29998-e55e-417e-a8c0-b00531b3caba/download)

**Comment by knguyenBC** [comment]
@cvarjao the document linked here still references "to store your proof of COVID-19 vaccination QR code". The current build of the wallet seems to have fixed this already (it states "...to store your digital credentials (the "Services")." So I'm not sure what text the current build is referencing too. Is this technically done?

**Comment by jleach** [comment]
I think we need the final copy.

Regards,

Jason Leach
