### ISSUE TITLE
Mobile Verifier acknowledgement of acceptance of the proof request

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1180]
### User Story
As a verifier I want to know when the proof request QR code has ben scanned so I can turn my attention back to my mobile device. 

### **Acceptance Criteria**
Given the verifier is presenting a proof request QR code from the mobile verifier
When the holder scans the QR code (when the connection protocol starts?) 
Then the verifier's mobile device provides haptic feedback

**Comment by wadeking98** [comment]
I believe this is already in prod
