### ISSUE TITLE
Header not showing on biometrics pin unlock screen (iOS)

### ISSUE THREAD

**Issue by bryce-mcmath** [bcgov/bc-wallet-mobile#1192]
### Description of problem
When changing biometrics settings and seeing the pin unlock screen, the header area is not visible, causing the status bar to be difficult to see and the logo to be too high up.

### Expected behavior
There should be a blue header area and the logo should be appropriately low.

### Steps to reproduce
On iOS, open the settings menu, and tap on 'Biometrics'. Then tap on the switch to change the setting.

### Screenshots and/or log output
What it looks like on iOS:
![biometrics_unlock.png](https://images.zenhubusercontent.com/63bc52dfbcde5d544793e7d3/073585fe-ea3a-4d7d-8e55-6c69334efec8)

What it looks like on Android (correct):![biometrics_unlock_android.png](https://images.zenhubusercontent.com/63bc52dfbcde5d544793e7d3/df3d85ba-7699-45b0-ba56-bc06ce9612eb)

### Environment
- [ ] Occurs on Android
- [x] Occurs on iOS

Build #: 972

Android Device Model: Pixel 4

iOS Device Model: iPhone 13 iOS 16

### Workaround
N/A

### Severity
- [ ] High
- [ ] Medium
- [x] Low

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/850

**Comment by hiteshgh** [comment]
tested and works as expected , closing
