### ISSUE TITLE
Bad state call when navigating to 'Terms' screen

### ISSUE THREAD

**Issue by bryce-mcmath** [bcgov/bc-wallet-mobile#1193]
### Description of problem
There is a bad state call in the Terms screen that causes a warning log to pop up
I 
### Expected behavior
There should be no warning log

### Steps to reproduce
Navigate to the settings menu and then select 'Terms of use' for the first time

### Screenshots and/or log output
![stack_navigator_eula.png](https://images.zenhubusercontent.com/63bc52dfbcde5d544793e7d3/97dda16c-0782-4186-966c-445ddaad1f65)![stack_navigator_set_state.png](https://images.zenhubusercontent.com/63bc52dfbcde5d544793e7d3/3e9d40c6-7b82-4871-b0bf-2ea2ff84ddd8)

### Environment
- [x] Occurs on Android
- [x] Occurs on iOS

Build #: 972

Android Device Model: Pixel 4

iOS Device Model: iPhone 13

### Workaround
N/A

### Severity
- [ ] High
- [ ] Medium
- [x] Low

**Comment by jleach** [comment]
Confirmed fixed in latest main.
