### ISSUE TITLE
Error when declining a proof request

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1195]
### Description of problem
Declining a proof request throws an error. It seems to be related to connectionless proof request

### Expected behavior
No errors

### Steps to reproduce
- go to https://a2a-test.apps.silver.devops.gov.bc.ca/dars/pre-vc-auth/
- scan QR Code
- Decline proof request

### Screenshots and/or log output
![signal-2023-06-16-091355_002](https://github.com/bcgov/bc-wallet-mobile/assets/1348549/3d06fb1d-6541-44a9-967e-bcf10155e0c4)

### Environment
- [ ] Occurs on Android
- [x] Occurs on iOS

Build #:

Android Device Model: 

iOS Device Model: 

### Severity
- [ ] High
- [x] Medium
- [ ] Low

**Comment by nodlesh** [comment]
This appears to be working in 1077, however 1271 is an issue with this workflow. Setting this one to done.
