### ISSUE TITLE
Update Wallet Name

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1200]
Relates to #1148 

### Acceptance Criteria
Give the holder is in the menu
When the holder taps the "edit" pencil icon
Then they are presented with the option to edit their wallet name
And the current name of the wallet is displayed in the text field
And they are able to save or cancel the action

Given the holder is in the scan my QR code screen
When the holder taps the "edit" pencil icon
Then they are presented with the option to edit their wallet name
And the current name of the wallet is displayed in the text field
And they are able to save or cancel the action

Given the holder has changed their wallet name
When the holder is in the "Menu" or "My QR code" screen
Then the wallet name is automatically updated to the latest wallet name

### Wireframes or relevant image assets / links
[Wireframes
](https://xd.adobe.com/view/0900b5b9-22d7-44aa-b9ee-e3693e33a5f3-5c53/)

TODO:
- [ ] In the Setting/Menu screen, align left, truncate right
- [ ] In the QR Code Screen, centered, word wrapped

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/961

**Comment by knguyenBC** [comment]
@wadeking98  Minor thing. With a really long name, only on android devices does the long name push the edit icon pass the edge of the screen. [See screenshot](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2VRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--021af00fc71e90c1fcea79eaed081e8a089eaa94/myqrcode%20screenshot.jpg)

**Comment by nodlesh** [comment]
Bug #1532 has been created to track the long name alignment issue. This has been tested manually and in test automation.  Closing this story.
