### ISSUE TITLE
Missing scrim on modals

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1202]
### Description of problem
Modals do not have the translucent overlay (scrim) that darkens the content below the modal. People think that the button in the header are functional.

### Expected behavior
Modals should have a scrim that darkens the content below the modal. 

### Steps to reproduce
Delete credential or remove contacts will display a modal.

### Environment
- [x] Occurs on Android
- [x] Occurs on iOS

Build #: 975

Android Device Model: all

iOS Device Model: all

### Workaround
none 

### Severity
- [ ] High
- [ ] Medium
- [x] Low

**Comment by jleach** [comment]
Verified in 1.0.15-1452
