### ISSUE TITLE
Buttons on modals on a small screen are cut off at the bottom

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1203]
### Description of problem
Buttons on modals on a small screen are cut off at the bottom

### Expected behavior
There should be padding at at the bottom of the screen so that no elements are ever on the edge of the screen (this includes text, buttons, images, etc.)

### Steps to reproduce
To see an example, delete a credential to view the delete a credential modal.
This appears in all modals

### Screenshots and/or log output

Default text
![20230717_165656.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/c454e70b-703b-49e2-bb2a-f6948d9143af)

Max text enlargement
![20230717_165639.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/02f91d4e-c73d-47c7-b6bb-2cce11fda512)

### Environment
- [X] Occurs on Android
- [X] Occurs on iOS

Build #: 975

Android Device Model: 

iOS Device Model: 

### Workaround
none

### Severity
- [ ] High
- [ ] Medium
- [X] Low

**Comment by hiteshgh** [comment]
@knguyenBC to additional Screen shot and plan next steps

**Comment by knguyenBC** [comment]
Added screenshots.

**Comment by jleach** [comment]
Verified in 1.0.15-1452
