### ISSUE TITLE
Send proof request modal/bottom slide does not match UI in styleguide

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1205]
When sending a proof request in the Contact details screen using the "+" button, the modal/bottom slider that appears does not match style guide.

### Issue
[Screenshot from build 975 (iOS)](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/a7867a79-19f3-4103-aa81-0f7367a18b82)

### Expected behaviour
[Modals style guide
](https://xd.adobe.com/view/eb9e0945-61d7-40ca-8e8e-bf4bd0c72934-becd/screen/4c69b7e3-3b7e-4f99-844e-2b65ec172bbf/specs/)

on iOS and Android

**Comment by cvarjao** [comment]
Fixed
