### ISSUE TITLE
Show all in credential details always reads "Hide all" in Voice Over

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#1208]
### Description of problem
With voice over/talkback turn on when the user looks at the credential details screen, the `Show all` toggle is always read as "Hide All". 

### Expected behavior
When Show All is displayed it would read as "Show All"

### Steps to reproduce
Turn on Voice Over or TalkBack on your phone 
Get a credential
Go to the credentials screen
double tap a credential to get to the credential details screen
single tap on "Show All"

### Screenshots and/or log output
![IMG_482831826F57-1.jpeg](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/269166d0-0b12-4735-949e-7d1427f58e7a)

### Environment
- [ X] Occurs on Android
- [ X] Occurs on iOS

Build #: 978

Android Device Model: 

iOS Device Model: 

### Workaround
None

### Severity
- [ ] High
- [ X] Medium
- [ ] Low

**Comment by knguyenBC** [comment]
@nodlesh There shouldn't be a "Show all" button. That button should only ever be a "Hide all". The reason being is to deter people from simply showing their credential details screen rather than through a proof request. I created a new ticket to address this: #1261.

**Comment by knguyenBC** [comment]
That being said. This bug has been fixed.
