### ISSUE TITLE
Button Alignment off on What is a Contact when in iOS zoomed mode

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#1209]
### Description of problem
When iOS zoomed display is on in Settings/Display & Brightness, the What is a Contact screen that shows when you click the `[i]` on the contact added from the proof request or red offer screen, has a wonky button. 

### Expected behavior
No wonky button

### Steps to reproduce
Turn on zoomed display is on in Settings/Display & Brightness
Get a Credential Offer
on the offer screen, in the Added to contacts box click the `[i]` info button

### Screenshots and/or log output
![IMG_0203.PNG](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/02ee22eb-b7c1-4331-8ed1-8bab643a58b3)

### Environment
- [ ] Occurs on Android
- [x] Occurs on iOS

Build #: 978

Android Device Model: 

iOS Device Model: iPhone 6s iOS 15.7.1

### Workaround
Turn off zoom, but no functional impact. 

### Severity
- [ ] High
- [ ] Medium
- [x] Low

FIXED IN: Build 1079

**Comment by knguyenBC** [comment]
Checked on iOS and Android build 1087 with and without text enlargement. Looks good.
