### ISSUE TITLE
BC Theme applied consistently

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#121]
- [x] Splash Screen / Loading Icon
- [x] Home Screen
     - [x] take out bifold logo from home screen
     - [x] notifications
- [x] Contacts screen
- [x] Scan Screen
- [x] Credentials List Screen

Lower Priority
- [x] Settings Screen

**Comment by jleach** [comment]
The first step in this I think is going to be to go through the app and apply the Aries Style Guide that Kim created. We need to have more control over theme rather than just black, white, and green. The colours used in the base bifold need to be compatible with the colours in the BC Theme.
