### ISSUE TITLE
Keyboard for PIN Entry after phone sleep not showing and cannot unlock wallet

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#1211]
### Description of problem
When the What is a Contact screen is displayed from a proof request or a credential offer (and may be other areas of the app that uses that type of modal?), when you let the wallet sleep long enough to have to unlock with the PIN, you can't get the keyboard to display to enter said PIN. 

### Expected behavior
Able to enter PIN

### Steps to reproduce
Get a Credential Offer
on the offer screen, in the Added to contacts box click the [i] info button
The What is a contact screen is displayed. 
Put the phone down and let is sit a while so that you wallet locks and requires a PIN entry
Open the phone.
The wallet will go to the PIN entry screen but you will not be able to activate the keyboard to enter the PIN. 

### Screenshots and/or log output
![IMG_0202.PNG](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/c64cd356-d2d8-4cee-9798-f7d8a7c3bf08)

### Environment
- [ ] Occurs on Android
- [x] Occurs on iOS

Build #: 978

Android Device Model: 

iOS Device Model: iPhone 6s, iOS 15.7.1

### Workaround
Close the wallet and reopen.

### Severity
- [ ] High
- [x] Medium
- [ ] Low

**Comment by jleach** [comment]
@nodlesh Are you able to confirm this issue with the new workflow. When I scan a QR code I go to the Chat screen now. If the app locks here the PIN screen does display the keyboard.


![Screenshot 2023-07-17 at 1.40.44 PM.png](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/898a590c-5e6b-457b-8bce-30f17bff2182)

![Screenshot 2023-07-17 at 1.40.34 PM.png](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/ac923cdf-ee5a-4a89-aede-69bbe3adc6dc)

**Comment by nodlesh** [comment]
I'll check again, but it happens from the proof request or credential offer, is the "What is a Contact" link gone from the request and offer?

**Comment by nodlesh** [comment]
This is still an issue with build 1071.

**Comment by bryce-mcmath** [comment]
Just an update. The issue exists on both the app store version and our latest build. Only seems to happen on iOS. Happens whenever the wallet sleeps with a modal open (which includes the 'What are Contacts' modal). I also noticed that the 'You've been logged out' modal does not appear or need to be dismissed like it usually does when the app is woken up.

**Comment by nodlesh** [comment]
This is fixed in 1094.
