### ISSUE TITLE
After filling out PIN & confirmation fields presented with a blank view

### ISSUE THREAD

**Issue by jamesdphillips** [bcgov/bc-wallet-mobile#1212]
### Description of problem

After filling out the PIN & confirmation inputs I am presented with a blank view. If I restart the application it once again prompts me to create a PIN.

See screenshots below.

### Expected behavior

I would like to be able to use the software!

### Steps to reproduce

Presumably you want to start with a clean slate, start the application, and attempt to navigate through the initial flow.

### Screenshots and/or log output

<p align="center">
<img width="320" src="https://github.com/bcgov/bc-wallet-mobile/assets/194892/dad03dd9-9e93-4e20-bea6-4656be51ae9d" />
<img width="320" src="https://github.com/bcgov/bc-wallet-mobile/assets/194892/3646ac00-4bc6-4c04-b144-94dd974d2dcd" />
</p>

### Environment
- [ ] Occurs on Android
- [x] Occurs on iOS

Build #: ~~(presumably latest version available on the App Store.)~~ v1.0.8

Android Device Model: n/a

iOS Device Model: iPhone 13 Pro; more importantly iOS 17.0 (21A5268h)

### Workaround

Not that I know of.

### Severity
- [ ] High
- [ ] Medium
- [ ] Low

**Comment by jamesdphillips** [comment]
Additional context: I've noticed that this occurs _after_ I enter the sixth number in the PIN confirmation input but _before_ I click "Create PIN".

**Comment by nodlesh** [comment]
I've tried this on an iPhone 13 Pro with iOS 15.7 and 16.4.1. This issue did not manifest. I wonder if it has to do with iOS 17? it is still in beta. My advice would be to go back to an official iOS release. Otherwise, when iOS 17 is officially released we will revisit this issue if it exists.

**Comment by cvarjao** [comment]
@jamesdphillips , we are no longer using the individual boxes, please try again with 1.0.9, and if the issues is till there please re-open this issue.
