### ISSUE TITLE
Proof Request with Photo Attribute

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1214]
### User story
As a verifier, I want to be able to receive a photo attribute from the holder so I can compare a photo to the holder

### Wireframes
[Screen of a proof request with a photo attribute
](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/b0c9820d-93b0-42a5-89da-e5b5a5fd3786)

**Design notes:**
Photo should have a white background (in case the photo has a transparent background) to ensure visibility
Photo should have a 1px border to divide the image background from the credential background

**Comment by nodlesh** [comment]
Verified working on iOS and Android in 1077 in the automated regression tests.
