### ISSUE TITLE
QR Code Density

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1218]
The generated QR Codes are too dense and sometimes hard to scan depending on environment and lighting.
- Connection vs connectionless proof requests

Solutions
- URL Shortening service
- Ephemeral/Temporary Connections
  - when do we know it is done?
 - Other?

**Comment by wadeking98** [comment]
Going to try playing with the qrcode error correction to reduce the density

**Comment by wadeking98** [comment]
Tried setting the error correction level. It made it a little less dense but it still didn't help on my phone
![image.png](https://images.zenhubusercontent.com/5fc52e1a365e55a8d5b3f428/60df7db6-f455-4eff-962a-d5817e84b7bb)

**Comment by wadeking98** [comment]
Clecio and I decided to use a temporary connection with goal codes. currently the askar migration has broken some functionality on the mobile verifier present proof functionality and is blocking progress

**Comment by wadeking98** [comment]
finished testing the functionality and confirmed working using goalCodes/temp connections
