### ISSUE TITLE
as verifier, Option to enlarge photo attribute in the presentation

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1220]
### Description of feature / user story
As a verifier I want to be able to enlarge the picture attribute so that I can compare the picture and the person in more detail 

### Acceptance Criteria
Given I'm in a proof request
When I tap/activate the photo attribute
Then the photo is enlarged and overlayed 
And a close button is available

### Wireframes or relevant image assets / links

https://xd.adobe.com/view/0a112c19-6f28-48cd-8ba6-3d80c7cd3771-5f42/screen/49d6d7c0-f482-4d92-a4f9-265e049f554c

**Comment by knguyenBC** [comment]
@bryce-mcmath Is there a proof request that requests for a photo ID that I can test this ticket on?

**Comment by bryce-mcmath** [comment]
If you enable dev mode and then enable the option for dev-only templates you should find one that is person full name and photo. The test showcase person credential has a photo

**Comment by knguyenBC** [comment]
ACs met. closing
