### ISSUE TITLE
Mobile Verifier, Use this proof request causes error

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#1225]
### Description of problem
Selecting A proof to use then selecting `Use this proof request`
causes error, `Unable to generate proof request`
Hitting Show details says, 
`Error code 1038 - Only indy proof format is supported...`

### Expected behavior
Successful generation of proof. 

### Steps to reproduce
Turn on the Mobile Verifier in developer options
Go to Sent a proof request in Menu
Select any proof
Select Use this proof request

### Environment
- [X ] Occurs on Android
- [ X] Occurs on iOS

Build #: 987

Android Device Model: 

iOS Device Model: 

### Workaround
None

### Severity
- [X ] High
- [ ] Medium
- [ ] Low

**Comment by nodlesh** [comment]
@jleach this is still an issue in 991.

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/863

**Comment by hiteshgh** [comment]
Assigned to Sheldon for technical testing

**Comment by nodlesh** [comment]
Verified fixed in build 1077.
