### ISSUE TITLE
Change iOS Distribution profile type to one of Ad Hoc, Enterprise, or Development

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#1227]
In trying to determine why the occasional iOS tests getting skipped, Sauce Labs is requesting we change the  iOS Distribution profile type.

> Looking at the logs, the app that you were testing (
> https://app.saucelabs.com/tests/cfa009ebf79d481ab1c17b546b1bedd3#0)
> has iOS Distribution (App Store) profile type, which is not supported on Sauce Labs for Real Device testing:
> https://docs.saucelabs.com/mobile-apps/automated-testing/ipa-files/#building-an-ipa-file
> You can use all but App Store:
> Ad Hoc, Enterprise, or Development.

We've have been working fine for the most part with the app set to App Store, but wondering if we can try something else to see what happens? I have a feeling it is not the issue but would like to go back to them with proof.

Acceptance Criteria:
- Automated re-signing and uploading to sauce labs using anything other than "App Store"

**Comment by jleach** [comment]
I think to test with SL we can take the artifacts produced by the build and manually re-sign them with the Ad Hoc certificate or Development certificate and then replace the one uploaded by the CICD pipeline. If it does not make anything better it might not be worth changing the pipeline permanently.

**Comment by nodlesh** [comment]
Agreed.

**Comment by jleach** [comment]
A few notes on this: Ad Hoc isn't going to work. The notes on that method say "Install on designated devices". This means we need to register the SauceLabs device IDs in our iTunes account. Will be a hassle to keep them in sync and manage them. Developer is more doable and that's what I'm experimenting with now. The caveat with this approach is that a "Development" certificate is tied to a specific developer. We don't have a broad "Development" signing certificate for the BC Gov.
