### ISSUE TITLE
Implement goal codes for automated connection handling 

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#1232]
We would like to introduce goal codes to enhance our understanding and handling of connections, following the flow outlined in [this document](https://hackmd.io/@wrf54Y6BSmWpzuBx9yJg_Q/HJi5kN8vh).

While goal codes can be applied to any message, in our case, they will specifically be added to invitations. To ensure the propagation of these goal codes along with the connection, we need to extract them from the record using the existing AFJ API during URL parsing and record creation. Subsequently, we can assign a `goalCode` tag to the connection. In the `Connections.tsx` file, we can monitor for this goal code and utilize it accordingly.

When implementing this feature, please consider the following:

1. Include the implementation for the "this is taking too long" scenario if the intended purpose of the goal code is not achieved within the specified timeframe.
2. If the above situation (1) occurs and the `autoRedirectConnectionToHome` flag is enabled in the configuration, automatically navigate back to the home page instead of updating the on-screen text. Thiago has introduced this feature.

Ref. #1141

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/880 and https://github.com/hyperledger/aries-mobile-agent-react-native/pull/888
