### ISSUE TITLE
as a holder, Missing "open presentation" button from the chat window

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1237]
### Description
I just see a a line "you shared information" but no way to see what information was shared.

### Screenshot
![20230711_110946.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/9c57dcec-88d7-4823-bb0d-d2f6872baa35)

### Steps to reproduce
- Receive a connected proof request
- approve proof request
- Go to contact connection
- View that you've shared information but can't see what was shared

### Expected behaviour
- Receive a connected proof request
- approve proof request
- Go to contact connection
- View that you've shared information
- View the information shared

[Wireframes for flow
](https://xd.adobe.com/view/be5d6531-658b-4d7c-8ec2-634825d724fe-eb0e/screen/2896cd43-607d-4a86-af5b-8883260725be/)

**Comment by knguyenBC** [comment]
I think this is a bug. I used to be able to see the "open" button but now I don't.

**Comment by wadeking98** [comment]
resolved by https://github.com/hyperledger/aries-mobile-agent-react-native/pull/884

**Comment by hiteshgh** [comment]
assigned to @wadeking98 to confirm if this was tested in " Test flight " and if working close it

**Comment by nodlesh** [comment]
Setting to done. New ticket opened for button name. #1273
