### ISSUE TITLE
as a verifier, missing waiting screen after QR Code is scanned while wait for presentation

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1238]
### Description of feature / user story
As a verifier I want feedback whether or not the QR code was scanned affectively so that I can tell if there was an error or not. 

### Acceptance Criteria
Given the holder and verifier are using the mobile verifier
When the QR code is scanned by the holder
Then the QR code screen on the verifier device changes to the proof request sent loading screen
And there's a "go back" button that takes them back to the request for proof screen (qr code screen)

### Wireframes or relevant image assets / links
[Mobile verifier scan flow ](https://app.mural.co/t/digitalidentityandtrust0399/m/digitalidentityandtrust0399/1634147263262/84c4b0f485a1366bd5cd451bed26c833fb14a621?wid=0-1686691294766)

[Wireframes of loading behaviour](https://xd.adobe.com/view/0a112c19-6f28-48cd-8ba6-3d80c7cd3771-5f42/screen/017256fe-dca6-4daf-ac50-2e73686d22b5/)

**Comment by knguyenBC** [comment]
Dev ticket created #1355.
