### ISSUE TITLE
Connection erroneously being deleted

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1239]
After connecting using the verifier "Connection Invitation" feature, the connection gets deleted

### Environment
- [ ] Occurs on Android
- [ ] Occurs on iOS

Build #:

Android Device Model: 

iOS Device Model: 

### Severity
- [ ] High
- [ ] Medium
- [ ] Low

**Comment by wadeking98** [comment]
I can't reproduce this on main

**Comment by hiteshgh** [comment]
assigned to @wadeking98 to confirm if this was tested in " Test flight " and if working close it

**Comment by nodlesh** [comment]
Cannot reproduce in build 1087.
