### ISSUE TITLE
Enable iPad support

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1241]

**Comment by jleach** [comment]
Updated to a two. Its a quick change to but needs some testing on an actual device.

**Comment by jleach** [comment]
Added iPad support and tested on iPad mini. See [this video](https://fullboarca-my.sharepoint.com/:v:/g/personal/jason_leach_fullboar_ca/EY5Q7SM63yxFheBZZE5iPQwB2fSxnIzqVeZQc47rauD3IA?e=vFDY5U).
