### ISSUE TITLE
as a holder, missing "view request" button in proof request chat screen

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1245]
### Description of problem
When receiving a proof request through a connection/contact, the proof request is missing the "view request" button, so the holder is unable open the proof request

### Expected behavior
When receiving a proof request, the holder should be able to see a "view request" button alongside the proof request message in the chat screen

![image.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/e433c4b0-7ac9-4b20-9c7b-d8a76fc450f4)

### Steps to reproduce
- Make a connection with another device
- Send through the connection a proof request
- The receiver views the proof request in the chat screen shared with the contact/connection
- The should receive the proof request but unable to open it in the chat screen

### Screenshots and/or log output
![20230711_110455.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/01a20f7e-60ce-4e71-bd1e-31639fe83a8a)

### Environment
- [ ] Occurs on Android
- [ ] Occurs on iOS

Build #:

Android Device Model: Android OnePlus 6

iOS Device Model: Iphone SE

### Workaround
You can open the proof request in your notifications

### Severity
- [ ] High
- [X] Medium
- [ ] Low

**Comment by wadeking98** [comment]
Resolved by https://github.com/hyperledger/aries-mobile-agent-react-native/pull/884

**Comment by hiteshgh** [comment]
assigned to @wadeking98 to confirm if this was tested in " Test flight " and if working close it

**Comment by nodlesh** [comment]
Setting to done. New ticket opened for button name. #1273
