### ISSUE TITLE
Notification switch to vertical scroll

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1249]
### Background
As a user, I want to clearly see all my notifications so that I can deal with them when I receive them

See wireframes in ticket #1051

### Acceptance Criteria
- [x] Notifications scroll vertically
- [x] Navigation tab changed to "Notifications" from "Home"

Update: This feature is in testflight

**Comment by knguyenBC** [comment]
ACs are met. Closing.
