### ISSUE TITLE
as a holder, Missing "view offer" button from the chat window

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1251]
### Description of problem
When receiving a credential offer through a connection/contact, the credential offer is missing the "view offer" button, so the holder is unable open the credential offer

### Expected behavior
When receiving a credential offer, the holder should be able to see a "view offer" button alongside the credential offer message in the chat screen

![image.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/48b04d65-a576-4cde-9a17-c5749a0bfbf1)

### Steps to reproduce
- Go through the student showcase
- Receive the student credential offer but do not accept offer
- Go to the BestBC College contact
- You will see a credential offer message but unable to open it

### Screenshots and/or log output
![20230711_110332.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/f4023744-78e7-47f1-9d3a-e01954244bfd)

### Environment
- [X] Occurs on Android
- [X] Occurs on iOS

Build #:

Android Device Model: Android OnePlus 6

iOS Device Model: Iphone SE

### Workaround
You can open the proof request in your notifications

### Severity
- [ ] High
- [X] Medium
- [ ] Low

**Comment by wadeking98** [comment]
resolved by https://github.com/hyperledger/aries-mobile-agent-react-native/pull/884

**Comment by hiteshgh** [comment]
assigned to @wadeking98 to confirm if this was tested in " Test flight " and if working close it

**Comment by nodlesh** [comment]
Setting to done. New ticket opened for button name. #1273
