### ISSUE TITLE
Contacts list timestamps are not in order from most recent to oldest

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1252]
### Description of problem
Contacts list timestamps are not in order from most recent to oldest.

### Expected behavior
Contact list should display the timestamp of the most recent interaction and be reordered according to most recent interaction to oldest interaction from top to bottom in the contact list.

### Steps to reproduce
- Add a few contacts
- Send a proof request over a connection
- The contact does not appear at the top of the list

### Screenshots and/or log output

![20230711_121556.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/6c70c11d-f93b-468e-9fec-1ab4f922ec58)

### Environment
- [X] Occurs on Android
- [X] Occurs on iOS

Build #: 1003

Android Device Model: onePlus 6

iOS Device Model: iPhone SE

### Severity
- [ ] High
- [ ] Medium
- [X] Low

**Comment by knguyenBC** [comment]
@jleach  why is this ticket in icebox?

**Comment by knguyenBC** [comment]
estimated as a 3.

**Comment by jleach** [comment]
Tested in build 1.0.17 Build 1740. Still an issue see screenshot below.


![Image](https://github.com/bcgov/bc-wallet-mobile/assets/390891/84fa72d2-b598-4014-a276-0022e8c9f874)

**Comment by jleach** [comment]
Tested in 1.0.17 1744. Ok.
