### ISSUE TITLE
QR Code too big for tablet devices

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1254]
### Environment
- [ ] Occurs on Android
- [x] Occurs on iOS

Build #:

Android Device Model: 

iOS Device Model: 

### Severity
- [ ] High
- [ ] Medium
- [x] Low

**Comment by knguyenBC** [comment]
Thinking about it again. Large QR code might actually be a feature. As people won't need to approach the counter too closely. Though one of the downsides is if there's a chance people can snipe the QR code from afar.
