### ISSUE TITLE
Connectionless proof request flow not working

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1258]
### Description of problem
The users is redirected to a contact chat screen

### Expected behavior
it is expected to automatically open the proof request

### Steps to reproduce
1. go to https://a2a-test.apps.silver.devops.gov.bc.ca/dars/pre-vc-auth/
1. scan QR Code

### Environment
- [x] Occurs on Android
- [x] Occurs on iOS

Build #:

Android Device Model: 

iOS Device Model: 

### Severity
- [x] High
- [ ] Medium
- [ ] Low

**Comment by knguyenBC** [comment]
@jleach Tested on iOS and Android, build 1087. Proof request is stuck in loading screen. ![20230726_132812.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/d5a2ca05-f91c-40d9-b010-f15087454f77) Is this a new bug?

**Comment by jleach** [comment]
Fixed in Build 1088

**Comment by knguyenBC** [comment]
The proof request opens automatically so this bug in particular is fixed. However theres a new issue related to this #1309
