### ISSUE TITLE
Style of tab bar in scan screen does not match nav bar in home

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1267]
### Issue
Style of tab bar in scan screen does not match nav bar in home. 
- Font is larger
-  icons are smaller. 
- No shadow  
- height is slightly larger
- missing bolded font on active tab

Affects both Android and iOS device.

### Expected behaviour
Font size and icon size should match with nav bar in home,

### Screenshot

![nav bar issues.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/5d0f72df-f684-4455-9f97-1e6b3f44a09b)

**Comment by jleach** [comment]
Confirmed. Tested in 1.0.12 1365.
