### ISSUE TITLE
Making a connection does not automatically take user to contact chat screen.

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1269]
### Description of problem
A person scanning (scanner) another person's QR code (holder) to connect does not automatically take the holder to the contact chat screen. The holder is stuck in the loading screen. Only when the scanner sends a proof request does the screen change to the contact chat screen.

### Expected behavior
Once a connection is made, the screen should change to the contact chat screen for both parties automatically

### Steps to reproduce
- With 2 separate devices, scan one device's qr code with the other device
- wait for the connection for both
- to change screen for the holder, send a proof request from the scanner's device

### Screenshots and/or log output
**From the scanner's perspective**
https://images.zenhubusercontent.com/429950091/9517f23b-eae5-4b9d-b80e-4d3cbbd79cd9/20230718_1605248359.mp4

**From the holder's perspective**
https://images.zenhubusercontent.com/429950091/cf350ca6-9f81-496d-9861-a873870e84df/20230718_1607136158.mp4

### Environment
- [X] Occurs on Android
- [X] Occurs on iOS

Build #: 1075

Android Device Model: OnePlus 6

iOS Device Model: iPhone SE

### Workaround
Sending a proof request to the holder

### Severity
- [X] High
- [ ] Medium
- [ ] Low

**Comment by hiteshgh** [comment]
Possible linked #1271

**Comment by jleach** [comment]
Verified, this works as expected. I can establish a connection only and I get navigated to the Chat screen. See [this video](https://fullboarca-my.sharepoint.com/:v:/g/personal/jason_leach_fullboar_ca/ERjHSEASdA9Ol5YQahT6woABPVi2DUfBzU9TIXNTDVF8WA?e=CQRHJb).
