### ISSUE TITLE
Making a connection with BCVP Pilot or CANDy UVP does not automatically take user to contact chat screen

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#1272]
### Description of problem
Scanning a QR code from here, https://bcvcpilot-issuer-test.apps.silver.devops.gov.bc.ca/?invite_token=23974aa6-009d-405a-a60b-0891c55cf277
or here https://openvp-candy-issuer-test.apps.silver.devops.gov.bc.ca
Does not go to the chat screen. It perpetually spins on the connection screen. The issue says a connection has been made and a credential sent, but nothing happens in the app. 

### Environment
- [ ] Occurs on Android
- [ ] Occurs on iOS

Build #: 1077

Android Device Model: 

iOS Device Model: 

### Severity
- [ X] High
- [ ] Medium
- [ ] Low

**Comment by hiteshgh** [comment]
@nodlesh to test again with Build # 10.79

**Comment by jleach** [comment]
@nodlesh If this is related to [1269](https://app.zenhub.com/workspaces/bc-wallet-6148e7423fe04b001444e2bd/issues/gh/bcgov/bc-wallet-mobile/1269) then FYI 1269 checks out Ok.

**Comment by nodlesh** [comment]
This is fix in build 1079. Closing.
