### ISSUE TITLE
Support for landscape mode

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1274]
****Description of feature / user story****

-iOS/Android tablets should support all orientations 

****Acceptance Criteria****

- Rotate devices on all 4 orientations seamlessly
- All Apps functionality should be useable on all orientations on tablet devices
- iOS/Android phone should be locked to portrait mode

****Wireframes or relevant image assets / links****

https://xd.adobe.com/view/eb9e0945-61d7-40ca-8e8e-bf4bd0c72934-becd/

**Comment by cvarjao** [comment]
Switch from `Dimensions.get (‘window’)` to `useWindowDimensions`
https://reactnative.dev/docs/0.66/usewindowdimensions

**Comment by jleach** [comment]
I created issue #1330 to implement split screen on Android.

**Comment by jleach** [comment]
All PRs merged. Moving to QA.

**Comment by knguyenBC** [comment]
@jleach Tried on iPad build 1156, did not work. I made sure that the rotation lock was off. Is there something else I should be doing?

**Comment by nodlesh** [comment]
Also not working for me in build 1179 for both iOS and Android. Attached is a photo from an iOS Device and a video from Android. Should we move this to Sprint Backlog or Estimated/Ready?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbjF4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7a684b15e4ace8d493692cfa5aeb4e9b14f40d27/Screenshot%202023-09-06%20at%209.57.59%20AM.png)


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb3h4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e343e301def2d40623204bdcf28f4f7e14b47a2f/video.mp4)

**Comment by nodlesh** [comment]
Never-mind, I'm in the wrong column...

**Comment by bryce-mcmath** [comment]
This is working now right? I just tested on a simulator and it works well for me

**Comment by nodlesh** [comment]
Yes, this is working now. I've noticed it in the nightly regression testing.
