### ISSUE TITLE
Remove "added to my contacts" warning when using ephemeral connections

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1275]
### Description of feature / user story
As ephemeral connections delete the connection after the proof request flow is complete, this "Added to my Contacts" warning/alert is not true to the user. Please remove "added to my contacts" warning/alert in a proof request when using ephemeral connections.

### Acceptance Criteria

Given that a proof request is using an ephemeral connection
When the holder is in the proof request screen
Then the "Added to the contacts" warning is now displayed

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/898

**Comment by knguyenBC** [comment]
@wadeking98 ticket #1298 is related to this ticket well.
