### ISSUE TITLE
Error thrown in presentation request screen

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#128]
Using the [chat demo](https://pctftest-test.vonx.io/home), I am unable to accept the verifier connection request as shown in the screenshots below:

![Screenshot_20220124-155846_BC Wallet](https://user-images.githubusercontent.com/1348549/151019338-4f22ad4e-72b7-46a8-983d-bd7dbe8a4e4b.jpg)

![Screenshot_20220124-155854_BC Wallet](https://user-images.githubusercontent.com/1348549/151019366-953bc4a0-fa59-447f-8a7c-c3c13d980b94.jpg)

**Comment by amanji** [comment]
This issue has to do with a proof request where no credential satisfies the proof. The UI/UX is not indicative of the problem. So the screens need to be updated to reflect the wireframes in this scenario.
