### ISSUE TITLE
Update Practicing lawyer and person photo attribute proof request template

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1287]
### Description of feature / user story
As a corrections facility officer, I want to be able to request for the following attributes from the Person and the Lawyer Member Card credential

### Acceptance Criteria
Proof request:

**From a non-revoked Person credential**
- Given Names
- Family Name
- Photo

**From a non-revoked LSBC issued lawyer member card** 
- Given Names
- Surname
- Membership Status
- Member Status code

Name of proof request template = **Lawyer Status and Photo**

### Wireframes or relevant image assets / links

**Comment by hiteshgh** [comment]
@wadeking98  - assume you are already working on this story, if yes can you pls update the estimate move to In-progress column

**Comment by wadeking98** [comment]
Right now this is blocked by: https://github.com/hyperledger/aries-framework-javascript/issues/1536

**Comment by knguyenBC** [comment]
double check proof request definition if member status code is necessary.

**Comment by hiteshgh** [comment]
unblocked and moved to In progress( per Aug 15 refinement )

**Comment by knguyenBC** [comment]
I had updated the proof request name to "Lawyer Status and Photo" as its not specifically asking for a practising lawyer, just asking for lawyer status.

**Comment by knguyenBC** [comment]
Regarding the request for the practicing code, its best to leave the code in as LSBC is unsure how they'll deal with the code when they add other member types to register to LSBC. Ex. paralegals are currently not registered but might be in the future and their practicing code MAY differ.

**Comment by wadeking98** [comment]
Resolved by https://github.com/bcgov/bc-wallet-mobile/pull/1390

**Comment by knguyenBC** [comment]
Looks good. Works.
