### ISSUE TITLE
Enable acceptance of non-production credentials in proof request template

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1288]
### Description of feature / user story
As a developer, I want to toggle proof requests to accept or not accept non-production credentials, so that I'm able to test the mobile verifier with non-production credentials. 

### Acceptance Criteria
Given the user has enabled developer mode
When the user enables "Accept non-production credentials?" 
Then the proof request templates accept non-production credentials

Given the user has not enabled developer mode
When the user uses a proof request template
Then the proof request does NOT accept non-production credentials

### Wireframes or relevant image assets / links
![Mobile Verifier non-prod flow.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/2b62665b-3b15-4c03-bb13-012cd499a9cf)

**Comment by wadeking98** [comment]
Resolved by: https://github.com/bcgov/bc-wallet-mobile/pull/1392
