### ISSUE TITLE
Mobile Verifier Unverified Person proof not working even though Holder has an Unverified Person Credential

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#1296]
### Description of problem
Holder with an unverified person credential from https://openvp-candy-issuer-test.apps.silver.devops.gov.bc.ca, and the verifier with "use development verifier templates" turned on.
Scan the QR code from the verifier for any of the unverified person proof, holder wallet says the credential is "Not available"

### Expected behavior
Any Unverified person credential can fulfill the proof. 

### Environment
- [x] Occurs on Android (holder)
- [x] Occurs on iOS (verifier)

Build #: 1087

Android Device Model:  UMIDIGI A3S Android 10

iOS Device Model: iPhone 6S iOS 15.7.1

### Workaround
None

### Severity
- [ ] High
- [x] Medium
- [ ] Low

**Comment by knguyenBC** [comment]
related to #1314

**Comment by wadeking98** [comment]
I think this is probably because I used the wrong openvp instance in the templates, I think I used the bcovrin one instead of Candy

**Comment by knguyenBC** [comment]
The proof request template "Unverified Person full name and Birth date" doesn't work with any un-verified person credential (tried person credential from demo and prod showcase and revocable unverified person credential)

**Comment by nodlesh** [comment]
Verified fixed on build 1179. Closing.
