### ISSUE TITLE
Mobile Verifier Flow - Holder not seeing proof contents in proof request from contacts 

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#1297]
### Description of problem
When using the mobile verifier, the holder gets a proof request but doesn't share it. In this case the proof request is wanting a proof from a cred that is reported as not available. When the holder goes to the contacts screen for the verifier and select View Request. The request contents do not load. 

### Expected behavior
See the contents of the request. 

### Screenshots and/or log output
![Screenshot_2023-07-26-16-30-09.png](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/d31eaacf-3e9e-429f-a300-9180f5d2465b)### Environment

- [X ] Occurs on Android (Holder)
- [ ] Occurs on iOS

Build #:

Android Device Model: UMIDIGI A3S Android 10

iOS Device Model: 

### Workaround
None

### Severity
- [ ] High
- [x] Medium
- [ ] Low

**Comment by knguyenBC** [comment]
Works as intended.
