### ISSUE TITLE
Remove "added to my contacts" warning when opening proof request over a connection

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1298]
**Description of feature / user story**
Since a proof request was sent over an existing connection, this "Added to my Contacts" warning/alert is not true to the user. Please remove "added to my contacts" warning/alert in a proof request when a proof request is sent over an existing connection

### Acceptance Criteria
Given that a proof request is sent over an existing connection
When the holder is in the proof request screen
Then the "Added to the contacts" warning is NOT displayed

Given that a proof request is sent over an a new connection with goal code
When the holder is in the proof request screen
Then the "Added to the contacts" warning is displayed

Given that a proof request is sent over an ephemeral connection
When the holder is in the proof request screen
Then the "Added to the contacts" warning is NOT displayed

**Wireframes or relevant image assets / links**

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/1035
