### ISSUE TITLE
Updates to the "Presentation request declined" screen 

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1299]
### Description of feature / user story
Updates to the "Presentation request declined" screen as the current one does not conform to style guide and is not streamlined. 

### Acceptance Criteria
Given the holder declines the proof request
When the verifier receives acknowledgement that the request was declined
Then they should be presented with a clear UI that says the request was declined
And they should be presented with a button to attempt a new proof

### Wireframes or relevant image assets / links
https://xd.adobe.com/view/0a112c19-6f28-48cd-8ba6-3d80c7cd3771-5f42/screen/c33df5a4-95f5-4907-83f7-2a78f65c953a/specs/

**Comment by jeffaudette** [comment]
backlog review - only minor word changes. Input to change the wording to "Proof request declined, information not shared" as a caption

**Comment by bryce-mcmath** [comment]
Waiting on publish of latest bc-wallet with latest bifold

**Comment by jleach** [comment]
@bryce-mcmath Does this need to be tested with the verifier? I didn't see the change in declining a proof with the showcase with v 1.0.13 1395.

**Comment by bryce-mcmath** [comment]
Yes, this is for what the verifier sees when another user declines their proof request

**Comment by bryce-mcmath** [comment]
@jleach ^

**Comment by jleach** [comment]
Verified in 1.0.15-1452
