### ISSUE TITLE
Remove Credential

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#130]
As a holder I want to remove credentials from my wallet so that I can keep my wallet organized and clear of unnecessary credentials

Wireframes:
https://xd.adobe.com/view/5edd5ca1-8978-4b3f-bf87-9ef21548b877-0b8e/ 

GIVEN the holder is in a credential detail screen
WHEN the holder selects "Remove from wallet"
THEN the holder is taken to an intermediary screen with more details of credential removal
AND a "Remove credential from wallet" button is available.

GIVEN the holder is in the intermediary screen with more details of credential removal
WHEN the holder selects "Remove credential from wallet"
THEN the holder is taken to the Credential List screen
AND a success temporary toast notifications appears

BLOCKED BY:
- https://github.com/hyperledger/aries-framework-javascript/pull/716

**Comment by cvarjao** [comment]
It will need changes to the react hooks library which might slow the release

**Comment by cvarjao** [comment]
When Wallet/AFJ provides a list of credentials eligibly to fulfill a presentation request it is currently including deleted credentials.

**Comment by Przytua** [comment]
@cvarjao I've already added draft PR in `react-hooks` (https://github.com/hyperledger/aries-framework-javascript-ext/pull/113) but it needs to be released in `core` first so the `react-hooks` dependency can be updated.

**Comment by nodlesh** [comment]
This is manually tested but needs Test Automation for regression testing.
