### ISSUE TITLE
BC Wallet gets stuck in loading the proof request after scanning the QR code

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1301]
### Description of problem
BC Wallet gets stuck in loading the proof request after scanning the QR code. 

### Expected behavior
Should open the proof request

### Steps to reproduce
- Scan the proof request from test application of ACM: https://a2a-test.apps.silver.devops.gov.bc.ca/dars/pre-vc-auth/

Note: Proof request works fine in prod application of ACM: https://justice.gov.bc.ca/dars/pre-vc-auth/

### Screenshots and/or log output
![20230726_132812.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/4120ebdc-aaa6-4ec2-b46f-707494fd8819)

### Environment
- [X] Occurs on Android
- [X] Occurs on iOS

Build #: 1087

Android Device Model: OnePlus 6

iOS Device Model: iPhone SE

### Workaround
None

### Severity
- [X] High
- [ ] Medium
- [ ] Low

**Comment by nodlesh** [comment]
Probably related to #1297

**Comment by knguyenBC** [comment]
Proof request loads now but sending the proof request is not consistent. Sometimes the information is sent, sometimes I get an error code 1027. I'll close this ticket but open up a new one for the new issue.
