### ISSUE TITLE
Dev Showcase not issuing student credential in

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1303]
### Description of problem
Showcase not issuing credentials. The flow gets stuck at the "your credential is on the way" loading screen after accepting the credential offer. 

### Expected behavior
Should accept the credential, add it to your wallet and display the "added to wallet" screen

### Steps to reproduce
- Go to test showcase https://bc-wallet-demo-dev.apps.silver.devops.gov.bc.ca/digital-trust/showcase/demo
- Select student use case or lawyer use case
- attempt to complete to acquire a credential

### Environment
- [x] Occurs on Android
- [X] Occurs on iOS

Build #: 1087

Android Device Model: 

iOS Device Model: iPhone SE

### Workaround
None

### Severity
- [ ] High
- [X] Medium
- [ ] Low

**Comment by nodlesh** [comment]
Seeing this as well in build 1089.

**Comment by nodlesh** [comment]
I have also seen this happen with build 1089 with the test agents in the automated regression tests as well, so may indicate this is a wallet issue and not a showcase issue?

**Comment by jleach** [comment]
I've tested on the Showcase "test" and prod instances several times with v1.0.10 and v1.0.9. All issue credentials fine. You can rule out a showcase or wallet issue by repeating the test with a different showcase instance. I generally test agains [production](https://digital.gov.bc.ca/digital-trust/showcase) and my backup is [test](https://bc-wallet-demo-test.apps.silver.devops.gov.bc.ca/digital-trust/showcase). 

Please retest agains one of these.

**Comment by knguyenBC** [comment]
tested. works fine. on iOS and android
