### ISSUE TITLE
Showcase does not register information sent over

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1304]
### Description of problem
Information sent successfully but showcase does not register information. 

### Expected behavior
After sharing information. The showcase should acknowledge the information sent over and allow the user to move forward.

### Steps to reproduce
- Open the prod showcase : https://digital.gov.bc.ca/digital-trust/showcase/uc/store
- attempt the student showcase
- use credentials and get a student discount

### Environment
- [X] Occurs on Android
- [ ] Occurs on iOS

Build #: 1087

Android Device Model: 

iOS Device Model: iPhone SE

### Severity
- [ ] High
- [X] Medium
- [ ] Low

**Comment by jleach** [comment]
@knguyenBC I can reproduce this in v1.0.9 and v1.0.10 if I have a credential issued from a different showcase instance. For example, if I have Student Card from test (displays as brown color) **and** I have one form prod (displays as green color) and I respond to a production proof, the wallet will use the first credential issued, in my case brown, and the issue above surfaces.

The showcase URL above is for prod. Please delete any other credentials from different Showcase environments. You should only have the (green) credential with branding.

![IMG_454ACC7732BD-1.jpeg](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/400af048-a0d2-4b59-b97c-08943220cb5f)

**Comment by knguyenBC** [comment]
Odd. I thought the wallet automatically selects the latest issued credential. Not the oldest issued credential. Might be a different bug then. Either way, tested the prod showcase with 1.0.10. works fine.
