### ISSUE TITLE
Lawyer prod showcase - unable to accept proof request

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1305]
### Description of problem
For the lawyer showcase in PROD. Received an "Unable to accept proof request." error. Error code 1027. After attempting the proof request.

test ACM app is inconsistent. Sometimes it works, other times, it doesnt.

### Expected behavior
Should send information over

### Steps to reproduce
- Go to prod showcase https://digital.gov.bc.ca/digital-trust/showcase/uc/courtServices
-  Attempt lawyer use case and acquire credentiaks
-  Attempt to use credentials to access court materials online

### Environment
- [X] Occurs on Android
- [ ] Occurs on iOS

Build #: 1087

Android Device Model: OnePlus 6

iOS Device Model: 

### Severity
- [ ] High
- [X] Medium
- [ ] Low

**Comment by jleach** [comment]
@knguyenBC Please re-test following the same rules about the origination of a credential from #1304.

**Comment by knguyenBC** [comment]
works fine both on iOS and Android
