### ISSUE TITLE
Keyboard does not pop up when entering wallet PIN

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1306]
### Description of problem
OS keyboard does not appear when at enter PIN screen. App worked well before and this is a recent issue.

**From customer support email:**
"I am unable to enter my wallet PIN because the number pad does not pop up to allow me to enter it.  Please let me know what I can do to fix the problem.  I have an Iphone 12. "

"The app did work for me before, and it was only in the past few days that the keyboard does not pop up for the PIN. ... even uninstalling and re-installing the app and adding the credentials again did not help. It was only a temporary fix and the keyboard popped up directly after the re-installation, but now it does not work again.  When I try to get back on the BC Wallet app again, the keyboard is missing again"

### Expected behavior
keyboard should appear automatically or appear when tapping the PIN text input

### Steps to reproduce
See above description

### Environment
- [ ] Occurs on Android
- [X] Occurs on iOS

Build #: TBD

Android Device Model: 

iOS Device Model: iPhone 12

### Workaround
only a temporary fix: uninstalling/reinstalling the app. The keyboard does not appear a second time.

### Severity
- [ ] High
- [X] Medium
- [ ] Low

**Comment by bryce-mcmath** [comment]
@knguyenBC Are they using a TestFlight build or the most recent release?

**Comment by knguyenBC** [comment]
Most recent release.

**Comment by knguyenBC** [comment]
The lawyer who experienced this issue has reported that the issue has been fixed with the new release (1.0.10). The other keyboard bug that was fixed must have been the solution.
