### ISSUE TITLE
User displaying their QR code to connect does not automatically take them to the new Contact page

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1307]
### Description of problem
User displaying their QR code to connect does not automatically take them to the new Contact page after the connection has been made. The user who scanned the QR code experiences the expected behaviour. 

### Expected behavior
After a connection was made, both parties (the user displaying the QR code and the user scanning the QR code) should be navigated to the new Contact page automatically.

### Steps to reproduce
- enable verifier capability and connection inviter capability
- with one device, scan My QR code on another device 

### Environment
- [X] Occurs on Android
- [X] Occurs on iOS

Build #: 1087

Android Device Model: OnePlus 6

iOS Device Model: iPhone SE

### Workaround
- exit the loading screen and go to contact manually

### Severity
- [ ] High
- [ ] Medium
- [X] Low

**Comment by jeffaudette** [comment]
may have been fixed, moved to ready for review

**Comment by jleach** [comment]
Confirmed fixed with two iOS devices running 1.0.12 1325 from TestFlight.
