### ISSUE TITLE
Proof request must be in a valid state for "Share" to be shown

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#1311]
A proof request must be in "request-recieved" state in order for the "Share" button to be enabled on the proof request screen. If a proof is sent, but an error occurs, the proof request can be moved into the "presentation-sent" state which will cause the proof screen to error out on subsequent retries.

https://images.zenhubusercontent.com/429950091/9d3d2b3a-da89-432a-89e1-c12656d923e1/proofrequestreuse.mov

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/1052

**Comment by jleach** [comment]
I don't recall how I produced this but after some testing I cannot reproduce it by any means.
