### ISSUE TITLE
Update header and navigation bar from Home to Notifications

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1312]
### Description of feature / user story
Home screen is switching into being a notification list. That will require changes to the header and the nav bar. 

### Acceptance Criteria
- Change Home to Notifications in the header and nav bar

### Wireframes or relevant image assets / links
https://xd.adobe.com/view/9f288cb7-c8ee-4003-8233-f4acb46de5a3-ca7b/

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/916

**Comment by knguyenBC** [comment]
meets AC. closing
