### ISSUE TITLE
Data retention toggle in settings for credential presentations

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1313]
### Description of feature / user story
As a verifier, I want to be able to not store any historical data of a proof exchange, so that I may comply to my privacy policies.

### Acceptance Criteria
- As verifier has ability to turn on/off records of presentation 
- the credential presentation record is removed right after being displayed
- "Show usage history" button removed from proof request summary screen

### Wireframes or relevant image assets / links
[Link to design story
](https://app.zenhub.com/workspaces/bc-wallet-6148e7423fe04b001444e2bd/issues/gh/bcgov/bc-wallet-mobile/1230)

https://xd.adobe.com/view/f239cc67-e22a-4178-84ae-4cf06b1dff23-a76a/

**Comment by knguyenBC** [comment]
Needs logic before it can be estimated.

**Comment by knguyenBC** [comment]
Reduced scope of this ticket to simply toggle. Kim to update wireframes.

**Comment by wadeking98** [comment]
Resolved by https://github.com/hyperledger/aries-mobile-agent-react-native/pull/935

**Comment by knguyenBC** [comment]
@wadeking98 Please also remove the "Show usage history" button from the proof request template.

**Comment by knguyenBC** [comment]
Updated the AC.

**Comment by knguyenBC** [comment]
Looks good. Closing.
