### ISSUE TITLE
Proof request templates unable to accept proof requests

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1314]
### Description of problem
When attempting to do a proof request using the mobile verifier templates the following happens

"**Practising Lawyer and Person Photo Attribute**", and "**Person full name and Picture**": does not accept the following credentials (states not available in wallet):
- Person credential from lawyer test showcase from [here](https://bc-wallet-demo-dev.apps.silver.devops.gov.bc.ca/digital-trust/showcase/)

The proof only accepts credentials from the [prod showcase](https://digital.gov.bc.ca/digital-trust/showcase/demo). However the prod showcase does not issue a Person credential with a picture attribute. 

The holder can still share the information however the verifier will not receive a response.  

~"**19+ and Full Name**", "**Over 19 years of age**", "**Over some years of age**": Unable to accept proof request error. Invalid structure. Caused by: Predicate is not satisfied~ (works fine in build 1094)

~"**Unverified Person Full Name**:", "**Unverified Person Full name and Birthday**" does not accept any unverified person credentials.~ see ticket #1296

### Expected behavior
- The proof request should allow dev/test credentials from the links above
- When information is sent, the verifier should receive the information that was shared.
- No error

### Steps to reproduce
- On one device, acquire the unverified person credential, and person credential from both the prod and test showcases on one device
- Acquire the lawyer credential from the showcase
- on the other device, choose the Practising Lawyer and Person Photo Attribute proof request template in mobile verifier
- have the other device scan the QR code to accept proof request and share information
- try again with a "19+ and full name" proof request.

### Screenshots and/or log output
![IMG_0197.PNG](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/ce807b79-1fd4-4941-9955-4de5674520ec) 

### Environment
- [X] Occurs on Android
- [X] Occurs on iOS

Build #: 1089 (iOS) 1091(Android)

Android Device Model: OnePlus 6

iOS Device Model: iPhone SE

### Workaround
None

### Severity
- [ ] High
- [x] Medium
- [ ] Low

**Comment by knguyenBC** [comment]
related to #1296

**Comment by jleach** [comment]
@knguyenBC You **must** have a revocable unverified person credential. The wallet will send either but ACM will only work with a revocable cred. Please delete any existing Unverified Person and issue a new one from here then re-test. Ty. 

https://openvp-rev-issuer-test.apps.silver.devops.gov.bc.ca/

**Comment by knguyenBC** [comment]
@jleach @wadeking98 Deleted all unverified and verified person credentials. Acquired a revocable unverified person credential. Proof requests requesting for an unverified person credential does not detect the credential. Will give "not available".

**Comment by knguyenBC** [comment]
@wadeking98 Just tested the mobile verifier. The unverified person templates don't seem to work with any unverified person templates (I tried the revocable unverified person, non-revocable unverified person, the person from the test demo and person from prod demo) all of them come up with a "not available" error. That said, those proof requests are not mandatory for release. Other proofs work just fine. I can't test properly the practising lawyer and photo template because I don't have a verified person credential with a photo.

**Comment by wadeking98** [comment]
Resolved by: https://github.com/bcgov/bc-wallet-mobile/pull/1334 not in testflight yet

**Comment by knguyenBC** [comment]
Is this now in testflight @wadeking98 ?

**Comment by knguyenBC** [comment]
Followed the steps to reproduce and do not experience the error.
