### ISSUE TITLE
Get your Person credential notification remains after getting your person credential

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#1317]
### Description of problem
After getting the Person Credential (did it on Test env), the Get your Person credential notification didn't disappear.

**Also Note** While trying to duplicate this, with the same wallet with a Person credential, I tried to get a BC Pilot Credential from https://bcvcpilot-issuer-admin-test.apps.silver.devops.gov.bc.ca but when I received the pilot credential, the notification to get the person credential did not display. Should it?
Removing the Person credential did not make the notification to get the person credential to display.
Removing the Pilot credential and reissuing that didn't cause the notification to display.

### Expected behavior
Notification would go away after getting the person credential

### Screenshots and/or log output
![IMG_A33C9926C2C8-2.jpeg](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/6aecaeed-8b36-4f1d-9929-59c93ff5a227)

![IMG_A33C9926C2C8-1.jpeg](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/0ea3c36a-d2d5-4274-a183-a32505c3d1c9)

### Environment
- [ ] Occurs on Android
- [X] Occurs on iOS

Build #: 1089

Android Device Model: 

iOS Device Model: iPhone 6s iOS 15.7.1

### Workaround
None

### Severity
- [ ] High
- [x] Medium
- [ ] Low

**Comment by bryce-mcmath** [comment]
@nodlesh does this issue still exist? I think it may have been fixed indirectly, just checking

**Comment by nodlesh** [comment]
@bryce-mcmath I'll check and let you know.

**Comment by jleach** [comment]
Confirmed. Tested in 1.0.12 1365.
