### ISSUE TITLE
Text alignment not correct on mobile verifier proof decline screen

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#1323]
### Description of problem

The text is not aligned correctly on the proof declined screen. See screenshot.

### Screenshots and/or log output

![IMG_0065.PNG](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/88835e77-2cdb-48d5-848a-4ea5f62468ba)

### Environment
- [ ] Occurs on Android
- [x] Occurs on iOS

Build #:

1.0.10 Build 1094

Android Device Model: 

iOS Device Model: 

### Severity
- [ ] High
- [ ] Medium
- [x] Low

**Comment by bryce-mcmath** [comment]
The verifier proof request declined screen has changed so that this red section is no longer present
