### ISSUE TITLE
The terms of service is not scrollable via Voice Control 

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#1325]
### Description of problem

On iOS the Terms and Conditions screen is not scrollable by voice command like other screens.

### Expected behavior

When you say "Scroll down" or "Scroll to bottom" the screen should scroll appropriately.

### Steps to reproduce

1. With Voice Control on;
2. With a new wallet install;
3. When you are on the Terms and Conditions screen speak, "Scroll down". 

### Screenshots and/or log output

![IMG_0067.PNG](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/38e20fd0-3fc2-4662-858d-bd2f235a81a4)

### Environment
- [ ] Occurs on Android
- [x] Occurs on iOS

Build #:

1.0.10 Build 1097

Android Device Model: 

iOS Device Model: 

### Severity
- [ ] High
- [ ] Medium
- [x] Low

**Comment by bryce-mcmath** [comment]
Seems to be working as intended on iPhone 13 with iOS 17.1.2. Retest?

**Comment by jleach** [comment]
Verified in 1.0.15-1452
