### ISSUE TITLE
EPRM :operation not permitted

### ISSUE THREAD

**Issue by PenguinTaro** [bcgov/bc-wallet-mobile#1338]
Hi, 
I cloned the repo and when I ran 

> yarn install

I encounter following issue, so can someone help me resolve this?
PFA the screenshot

![Screenshot 2023-08-10 090120](https://github.com/bcgov/bc-wallet-mobile/assets/99000637/161300eb-3044-4ae4-8632-7cd14e51af79)

**Comment by cvarjao** [comment]
closing as stale. We don't use windows, but symlinks are no longer needed, so it is theoretically fine now
