### ISSUE TITLE
Features missing from new vertical notificaitons

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#1340]
### Description of problem

The following requested features were not implemented in #1249:

- [ ] Background color to white( for group of items ) 
- [ ] Adding padding that show Grey between each group of items 

For the first point above I think we could implement something like this:
https://snack.expo.dev/@heytony01/keyboard-function-component-example

Although, I do believe this feature isn't overly in-demand. I don't expect many people to get enough notifications to warrant pagination - if they do then we probably have a different problem that will start to become a time sync.

### Environment

- [x] Occurs on Android
- [x] Occurs on iOS

Build #:

Android Device Model: 

iOS Device Model: 

### Severity
- [ ] High
- [ ] Medium
- [x] Low

**Comment by hiteshgh** [comment]
Removed Notification load limit from AC, if required in future we can create a another story for Notification load limit

**Comment by knguyenBC** [comment]
Looks good!
