### ISSUE TITLE
Back TestID Missing from Credential Details

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#1341]
### Description of problem
The Back button on the Credential Details page does not have a TestID. Expecting com.ariesbifold:id/Back
I've been using the Accessibility label of "Back" but for some reason the click even on this element doesn't seem to do anything in Appium anymore. Hoping a real TestID will behave better. 

### Screenshots and/or log output
![Screenshot 2023-08-11 at 3.37.36 PM.png](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/06ff1e5e-bb03-4f6b-9564-db6a7c65cca7)

### Environment
- [ ] Occurs on Android
- [x] Occurs on iOS

Build #: 1109

Android Device Model: 

iOS Device Model: 

### Workaround
None in test automation

### Severity
- [ ] High
- [x] Medium
- [ ] Low

**Comment by cvarjao** [comment]
closing as stale
