### ISSUE TITLE
Unable to receive credential with a photo attribute

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1342]
The app hangs at the credential offer with a photo at 38kb

Image Sizes:
- Current production largest image size: 22k
- Target/Supported largest image size: 50Kb (must)
- What is the maximum/recommened supported attribute value size?

**Comment by wadeking98** [comment]
Resolved by: https://github.com/bcgov/bc-wallet-mobile/pull/1356

**Comment by nodlesh** [comment]
Where is this fix testable? @wadeking98

**Comment by nodlesh** [comment]
Tested in build 1179 with the help of Wade issuing a credential with a large image. Closing.
