### ISSUE TITLE
Request another proof button in decline screen of mobile verifier response screen

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1343]
### Description of feature / user story
As a verifier, I want to know a request another proof button when a holder declines a proof request so that I can immediately attend to the next holder.

### Acceptance Criteria
Given a holder has declined a proof request
When the verifier is taken to the proof request declined screen
Then a request another proof button is available (that takes them back to the QR code screen of the proof request)
And a back to proof request list is available

### Wireframes or relevant image assets / links
[Wireframes](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/59fb89c3-acdc-45fa-bf7f-2ab95197ccd6)

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/938

**Comment by jleach** [comment]
Moving to QA. As noted above this is resolved.

**Comment by knguyenBC** [comment]
Meets AC.
