### ISSUE TITLE
Improve quick access to mobile verifier

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1346]
### Description of feature / user story
As a person who uses the app exclusively for the mobile verifier, I want to quickly access my commonly used proof request so that I can quickly verifier a person's identity

### Acceptance Criteria
- Static QR codes
- option to turn off sleep mode
- Revert to last screen after going to sleep
- Kiosk mode

### Wireframes or relevant image assets / links

**Comment by cvarjao** [comment]
closing as stale
