### ISSUE TITLE
Auto-lock timeout settings

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1348]
As a verifier who wants to continues verify proofs I need a way to turn auto-lock on/off so that the app is always ready for verification as quick as possible

Enable/Disable auto-lock idle timeout

- Under mobile verifier settings, add a new setting for turning on/off

### Acceptance Criteria
- User has the ability to turn auto-lock on/off

**Comment by bryce-mcmath** [comment]
Should this be feature-flagged?

**Comment by knguyenBC** [comment]
Works as intended. tried on both iOS and Android.
