### ISSUE TITLE
Enable kiosk mode | Design

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1349]
### Description of feature / user story
As a person that primarily uses the mobile verifier, I want to be able to lock BC Wallet to a certain proof request flow, so that I can quickly verify a person's identity.

-Enable kiosk mode

### Acceptance Criteria

- lock to verifier mode in a specific proof request template
- automatically open the app in that flow while in kiosk mode
- option to turn off 5 minute lockout timer

### Wireframes or relevant image assets / links

"Kiosk" mode or the above Acceptance Criteria is accomplished via existing tickets.
- #1348
- #1347

**Comment by hiteshgh** [comment]
Kim to add addtional description and AC
