### ISSUE TITLE
Connect the Get Started button on the on-boarding tutorial screen

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#135]
As a user, when I press the "Get Started" button the the tutorial screen I would like to move to the next step in the on-boarding workflow.

**Comment by nodlesh** [comment]
This story has been tested in the integration tests.
Full test Specification for the Onboarding feature is located here.
https://github.com/hyperledger/aries-mobile-test-harness/blob/main/aries-mobile-tests/features/bc_wallet/onboarding.feature
This PR closes the testing for this feature. hyperledger/aries-mobile-test-harness#34
Test results can be seen here, https://allure-mobile.vonx.io/allure-docker-service-ui/projects/android-one-device-smoke
