### ISSUE TITLE
Inform users when disclosing PI flagged elements | development

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1351]
### Todo

- [ ]  Update showcase to flag the photo attribute in the Fictions Person Credential 
- [ ]  Mock OCA bundle for some and all attributes used in a proof request being flagged

Wireframes: https://xd.adobe.com/view/ba82ae35-0c11-44fe-b24a-090f1fa64987-efd1/

**Comment by knguyenBC** [comment]
@wadeking98 added link to wireframes to ticket and to story epic.

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/968

**Comment by knguyenBC** [comment]
@wadeking98 Proof requests show the flagged alert sometimes. I opened the following tickets #1486 and #1485

**Comment by nodlesh** [comment]
I would argue that when stories like this don't match the acceptance criteria or wireframes they just go back to Sprint Backlog instead of logging new issues. Thoughts?

**Comment by knguyenBC** [comment]
Right. Fair enough. The only downside is that tickets will stay in progress and it might affect our burndown, especially when it's a big ticket like this. We can discuss in our next retro.
