### ISSUE TITLE
Add waiting screen after QR Code is scanned while wait for presentation

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1355]
### Description of feature / user story
As a verifier I want feedback whether or not the QR code was scanned affectively so that I can tell if there was an error or not.

### Acceptance Criteria
Given the holder and verifier are using the mobile verifier
When the QR code is scanned by the holder
Then the QR code screen on the verifier device changes to the proof request sent loading screen
And there's a "go back" button that takes them back to the request for proof screen (qr code screen)

### Wireframes or relevant image assets / links
See wireframes and user flow from ticket #1238

**Comment by knguyenBC** [comment]
Looks good.

**Comment by knguyenBC** [comment]
@wadeking98 There's a bug when I follow these steps:
- Scan QR code from verifier
- Verifier taps "go back" on the "Waiting for response" screen
- Holder shares information
- Verifier goes to their home screen and sees a new proof request notification that errors out when you try to open it (on Android) or has a perpetual load (on iOS). You can't delete/dismiss or cancel this proof request notification, you have to close the app and open it again and try to delete/dismiss/cancel the proof request notification again.

Note: error behaviour is different for Android and iOS.

**Comment by wadeking98** [comment]
Can we make a separate ticket for this? I think I know what's causing it and it'll need a fix in credo

**Comment by knguyenBC** [comment]
> @wadeking98 There's a bug when I follow these steps:
> 
> * Scan QR code from verifier
> * Verifier taps "go back" on the "Waiting for response" screen
> * Holder shares information
> * Verifier goes to their home screen and sees a new proof request notification that errors out when you try to open it (on Android) or has a perpetual load (on iOS). You can't delete/dismiss or cancel this proof request notification, you have to close the app and open it again and try to delete/dismiss/cancel the proof request notification again.
> 
> Note: error behaviour is different for Android and iOS.

This issue seems to be fine now in build 1877 for both iOS and Android @wadeking98
