### ISSUE TITLE
Inform people of current list of available digital credentials

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1358]
### Description of feature / user story
As a citizen who stumbled upon and installed BC Wallet, I want to know what credentials I can add to my wallet, so that I know what to expect

From our feedback survey, many people expect they can add other credentials that BC Wallet does not support such as vaccine card, driver's license, their BC ID, and other documents. We should inform people beforehand so we can manage expectations, ensure people aren't downloading the app needlessly, and avoid negative reviews of the app not working.

**Feedback quotes**
"You could provide a list of items that are available to be used in the digital wallet"
"Tired to enter the QR code on my BC vaccination card and the app says it's invalid. Why make the app available if it doesn't work? This reflects very poorly on our government agencies and the people who are responsible for these services."

### Wireframes or relevant image assets / links

**Comment by cvarjao** [comment]
closing as stale
