### ISSUE TITLE
App Attestation (v1) | development

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1363]
- [ ] Additional library for handling app attestation (maybe)
- [ ] A scalable server-side component for integrating with the app stores attestation process.
- [ ] Create a VC schema with minimal information about the attestation process
  - [ ] Creation date?
  - [ ] Attestation Method? (Google Play, App Store)
  - [ ] Wallet/Product Name (BC Wallet)
- [ ] Automatically Issue a Verifiable credential to the holder

### Acceptance Criteria
- A VC is issued when the app attestation process is successful
- the VC is hidden from the list of credential
- The is a dev mode setting for showing those hidden credentials

**Comment by nodlesh** [comment]
@jleach @cvarjao When I have an existing app with credentials, upgraded to the latest app, I turn on app attestation in the dev options, should I see some sort of credential come into the credentials list? I don't see anything, maybe it takes some time once it is turned on? Maybe it only works for official releases and not test flight releases?
