### ISSUE TITLE
Push notification (V1) | design

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1366]
### Description of feature / user story
Notifications require OS level permissions to allow push notifications, alerts, badges etc. The wallet will need a place to request the permission.

### Acceptance Criteria
Given the user has not been presented the notifications prompt to enable/disable push notifications
When they continue from the EULA or when they tap "Notifications" in the menu
Then they are presented with the [Notifications screen](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbGs5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ca57967b063e10f7e2ee37921131b5c500eab047/image.png) that gives them details on what sort of push notifications they'll receive
And an OS prompt asking for notifications permission will appear when the user taps "Continue"

Given the user is using an iOS device
When they tap Notifications in the menu
Then they are taken to a [Notifications screen](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbG85IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c9b781796dfa78cb245dd8bfd497425a8b435398/image.png) that details how to change their notification settings on their mobile device

Given the user is using an Android device
When they tap Notifications in the menu
Then they are taken to a [Notifications screen](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbHM5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f2c79be890d749de920131031a5af3b3c456e864/image.png) with a notification toggle where it's state is at the current notification permissions state (on/off)

### Wireframes or relevant image assets / links
[Notifications permissions user flow](https://app.mural.co/t/digitalidentityandtrust0399/m/digitalidentityandtrust0399/1689347560527/654debc347743b42d4424b7d8ec87df3c0404b15?wid=0-1692722313102)

[updated onboarding flow ](https://xd.adobe.com/view/35c82052-5c29-4343-bab0-7dc84cebb129-609b/)

[updated menu
](https://xd.adobe.com/view/f239cc67-e22a-4178-84ae-4cf06b1dff23-a76a/)

**Comment by jamshale** [comment]
In my upcoming PR it currently asks the first time you login and go to the home screen. I'm happy to change it if UX/UI people have any other ideas.

**Comment by knguyenBC** [comment]
iOS allows specifying the body content of the OS level notification permission but not Android so we've generally added a intermediary screen that helps explain for both OS's . We also try to ask the permissions in context. See how we do camera permissions.

**Comment by knguyenBC** [comment]
Updated the AC, screens and flow

**Comment by jamshale** [comment]
@knguyenBC I'm trying to get this feature closer to being able to merge so I was going to implement your designs. 

However I don't have access to the zenhub page.

Edit: Sorry Ignore that. I was clicking on the wrong links.

**Comment by knguyenBC** [comment]
@jamshale I believe I saw your note in the mural board. Could the Notification screen/prompt be placed after the PIN is created? Example, placing it after the Biometrics enabling screen?

**Comment by jamshale** [comment]
> @jamshale I believe I saw your note in the mural board. Could the Notification screen/prompt be placed after the PIN is created? Example, placing it after the Biometrics enabling screen?

It can't. It needs to connect to the mediator before it can check if it supports push notifications. This connection happens after the PIN code.

I made it so it pops up immediately after the pin code and connecting. It will only occur the first time logging on when push notifications are supported by the mediator.
