### ISSUE TITLE
Style notifications as per the designs

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#138]
The toast notifications were missed during theming. The need to be updated to reflect the app Theme and style.

[Reference to style guide](https://xd.adobe.com/view/1ac84b48-4eed-4334-a59a-9a99e3633e1b-4f9b/)

**Comment by knguyenBC** [comment]
@jleach Can I get screenshots of the different notifications styles you have themed in the wallet? Errors, no button, with button, etc. Thanks!
