### ISSUE TITLE
Update Android target level to Android 13 (API level 33)

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1394]
As og August 31, 2023:

> New apps must target Android 13 (API level 33) or higher; except for Wear OS apps, which must target Android 11 (API level 30) or up to Android 13 (API level 33).
> Existing apps must target API level 31 or above to remain available to users on devices running Android OS higher than your app's target API level. Apps that target API level 30 or below (target API level 29 or below for Wear OS), will only be available on devices running Android OS same or lower than your apps’ target API level.

https://support.google.com/googleplay/android-developer/answer/11926878

The docs mentions 2 places: "app's Gradle file" and and Android "manifest file".
https://developer.android.com/google/play/requirements/target-sdk

**Comment by nodlesh** [comment]
Shouldn't that be a target of Android 13 API 33? I believe we are already targeting 12/31.

**Comment by nodlesh** [comment]
Checked build 1179 in Google Play Console. Looks like it is set to SDK 33 there. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcVZ4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b03f189f58edb081c2c3c3663994c570638636d3/Screenshot%202023-09-06%20at%2010.17.18%20AM.png)
