### ISSUE TITLE
Update mobile verifier Person and LSBC proof requests to only accept credentials from newer RevRegs

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1395]
### Description of feature / user story
With the fix to CL Signatures (via ACA-Py), existing credentials will need to be revoked and reissued. 
The fix includes revoking a credential in one registry and reissuing it to another registry.
Current proof requests may need to be updated in the future to only accept the "new” one, if that feature is added to CL Signatures, AFJ and Bifold.

### Wireframes or relevant image assets / links

**Comment by swcurran** [comment]
No change will be needed in the mobile verifier to accept both flawed and new credentials — that is automatic.

What may be needed in the future (although it is debatable…) is that there is a flag the mobile verifier could use to to reject “flawed” credentials.  That change will not be needed for some months.

**Comment by swcurran** [comment]
Updated the title and description a bit.
