### ISSUE TITLE
Get BC Digital ID

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#140]
The VP VC flow wireframes: 
https://xd.adobe.com/view/de0de348-9fef-481b-864e-d6c295e1e4cc-8b5e/ 

Detailed diagram: 
https://app.mural.co/t/digitalidentityandtrust0399/m/digitalidentityandtrust0399/1646684933683/e94524d1dac5d1d8764a608ee9799c447431424f?wid=0-1647542875263

**Comment by jmdkumar08** [comment]
This Epic is done
