### ISSUE TITLE
push notifications (v1) | design

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1400]
### User story / Description
As a user, I want to see that I have new notifications in BC Wallet without opening the app so I know to open the app and respond to them.

As a user, I want to be able to toggle on/off push notifications so that I can control the number of notification I get in my phone

### Acceptance Criteria
- User is able to turn on/off push notifications
- User is provided a push notification that adequately informs them of a new notification from BC Wallet

**Comment by knguyenBC** [comment]
Duplicate of #1366
