### ISSUE TITLE
App Crash on Install/startup on iOS < 14

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#1408]
### Description of problem
On Sauce Labs real devices, when the app is installed and starts up the app will crash if the iOS version is below 14. 
This may be in part, some of the "skipped" tests that show up in the nightly regression tests. 
I can make this happen by running manually with the latest build on an iPhone 6s with iOS 13.5.1. 
You can find this device here, https://app.saucelabs.com/live/app-testing/file/60679c22-705c-438e-88dd-528789562c2d/device

Attached is a device log from this device in case there is something in there that may help diagnose the issue. 
Also attached is a device log from a successful startup on an iOS 14 device. 
Both device logs are from a manual execution on Sauce Labs so the Aries Mobile Test Harness is excluded from the environment. Though the issue could still be from the SL infrastructure. SL has this info and are looking into it. 
I would also like to find an iOS device outside of SL that is lower than iOS 14 that I could verify this issue on. 

Here is a test that failed in the regression 
https://app.saucelabs.com/tests/eb75848f523c44bd83e14cc906782d37#0

Here is the manual test execution that represents the failed device log below
https://app.saucelabs.com/tests/a28db265d7f24c1b953df4d94620367f

### Steps to reproduce
Use Sauce Labs

### Screenshots and/or log output
Failed -> [SauceLabs_Log_iPhone_6S_13_5_real_us_2023-08-23_09-02.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2N1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--52a4858cec92760ffdb65ffc722d940876a88732/SauceLabs_Log_iPhone_6S_13_5_real_us_2023-08-23_09-02.txt)
Passed -> [SauceLabs_Log_iPhone_8_Plus_14_real_us_2023-08-23_09-20.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa3d1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5f935052d626b0cbaed54e8eddaec555590ff4fd/SauceLabs_Log_iPhone_8_Plus_14_real_us_2023-08-23_09-20.txt)

### Environment
- [ ] Occurs on Android
- [x] Occurs on iOS

Build #: 1136

Android Device Model: 

iOS Device Model: iPhone 6s iOS 13.5.1
However, I have tried this with an iOS 12 and a 13.7 device with the same outcome.

### Workaround
None

### Severity
- [x] High
- [ ] Medium
- [ ] Low

**Comment by cvarjao** [comment]
closing as stale. I've tested with iPhone 8 - iOS 13.2 (using saucelabs) and it seems to be working
