### ISSUE TITLE
Android back button/gesture takes to an empty screen

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1409]
### Description
After scanning a QR Code, it takes to the chat screen. When using the back button/gesture, it takes to an empty screen

### Expected Behaviour
After scanning a QR Code, it takes to the chat screen. When using the back button/gesture, it takes to the main/home screen

Note:
- Make sure the navigation stack is being manipulated correctly. Sometimes you may need to re-set the stack to a known state.

**Comment by knguyenBC** [comment]
Checked on Android. works as intended.
