### ISSUE TITLE
Developer screen missing scrollview

### ISSUE THREAD

**Issue by bryce-mcmath** [bcgov/bc-wallet-mobile#1416]
### Description of problem
As the developer settings screen gets more and more options, it need to be scrollable

### Expected behavior
It should be scrollable

### Steps to reproduce
Go to the developer screen with large font size settings, attempt to scroll

### Screenshots and/or log output
N/A

### Environment
- [x] Occurs on Android
- [x] Occurs on iOS

Build #: 1167

Android Device Model:
N/A

iOS Device Model:
N/A

### Workaround
N/A

### Severity
- [ ] High
- [ ] Medium
- [x] Low

**Comment by knguyenBC** [comment]
Scrolls on iOS and Android.
