### ISSUE TITLE
QR code sharer is stuck on connection screen during connection invitation

### ISSUE THREAD

**Issue by bryce-mcmath** [bcgov/bc-wallet-mobile#1417]
### Description of problem
When scanning another wallet's QR code to create a connection between two wallets, the scanner wallet will successfully be transferred to the chat screen but the QR code sharer wallet will be stuck on the connection screen.

### Expected behavior
Both wallet users should be taken to the chat screen after a successful connection.

### Steps to reproduce
Enable connection invitations in developer settings in two instances of the app, then share your connection QR code with one (by navigating to contacts list and tapping the plus icon) and scan it with the other.

### Screenshots and/or log output
N/A

### Environment
- [x] Occurs on Android
- [x] Occurs on iOS

Build #: 1167

Android Device Model:
N/A

iOS Device Model:
N/A 

### Workaround
Go back to home and then go to contacts list. The new contact will be there.

### Severity
- [ ] High
- [x] Medium
- [ ] Low

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/955

**Comment by bryce-mcmath** [comment]
This has been fixed in the latest build. Closing
