### ISSUE TITLE
Refactor application navigation mechanics

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#142]
We need to refactor the application navigation / navigator mechanics so it goes from 5 tabs to two as per the design documents.

As a holder I want the most frequent tasks to be easily accessible so that I can quickly get to the most frequent tasks with least amount of taps/clicks

As a proponent of secure and privacy preserving VC I want to the credential and connection list to be tucked away so that it deters users from visually showing their credentials

#### Scenario: Main Navigation Bar
Given the holder has setup their BC Wallet App
When the app successfully loads
Then holder can see the "Home" button in the [main navigation bar](https://xd.adobe.com/view/efd8f0c6-3ba0-436e-b72c-2dad62569aa2-ba8b/screen/ceb22cc9-6c2a-4da0-8a07-52e56b54420d/)
 and holder can see the "Scan" button in the main navigation bar
 and holder can see the "Credential" button in the main navigation bar

#### Scenario: Credential Screen
Given BC Wallet App has successfully started
When the holder selects the "Credential" button in the main navigation bar
Then ["Manage" screen](https://xd.adobe.com/view/5edd5ca1-8978-4b3f-bf87-9ef21548b877-0b8e/) is displayed with the "Credentials" screen
 And a list of stored credentials is displayed

#### Scenario: Scan Screen
Given BC Wallet App has successfully started
  And the user has allowed the use of camera
When the holder selects the "Scan" button in the main navigation bar
Then the Scan screen is displayed

#### Scenario: Settings screen
Given BC Wallet App has successfully started
When the Holder selects the "Settings" button in the top navigation bar
Then the Settings screen is displayed
And a the App setting, Contacts, More information, and App version is listed.

#### Scenario: Connection List in Settings
Given the Holder is in "Settings" Screen
When the holder selects "Manage your Contacts" under the Contact heading
Then a [list of connections](https://xd.adobe.com/view/be5d6531-658b-4d7c-8ec2-634825d724fe-eb0e/screen/7c3a63b4-c8b8-44d2-bf64-26e1818b36c1/) is displayed

#### Scenario: Home Screen without any pending notification
Given BC Wallet App has successfully started
When the holder selects the "Home" button in the main navigation bar
Then the Home screen is displayed

#### Scenario: Home Screen with pending notifications
Given BC Wallet App has successfully started
When the app successfully loads
Then the number of pending notifications is displayed in the "Home" button in the main navigation bar

**Comment by cvarjao** [comment]
The icons are not showing up properly on Android devices
![Screenshot_20220224-171915_BC Wallet](https://user-images.githubusercontent.com/1348549/156028529-1db5af80-d89e-457e-979e-1fb03cf1557f.jpg)
