### ISSUE TITLE
Notification badge location wrong on iPad

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#1428]
As per the image below when on displayed on an iPad the notification badge is not located in the correct place:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBazF1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8550ca33d14c711623ecf1d64fcba23b6505c483/IMG_1886.PNG)

**Comment by nodlesh** [comment]
Checked in build 1179 but was not fixed in that build. Will check the next one.
