### ISSUE TITLE
Wallet name special characters should be preserved

### ISSUE THREAD

**Issue by bryce-mcmath** [bcgov/bc-wallet-mobile#1429]
### Description of problem
Some special characters used in wallet naming become jumbled 'unknown' characters when viewed from a connected wallet. The wallet name is preserved properly in the original wallet but something happens during the connection to another wallet to jumble it up. 

### Expected behaviour
All characters should be preserved in connected wallets

### Steps to reproduce
Fresh install a wallet, tap the welcome header 10 times to get into dev mode, enable wallet naming, enter a wallet name like "Wade’s Wallet" (using a smart apostrophe). Then connect with another BC Wallet and check the contact name that appears.

### Screenshots and/or log output
![jumbled_wallet_name](https://github.com/bcgov/bc-wallet-mobile/assets/32586431/670c496b-62d1-4eb5-825c-a5ec27c2d6ba)

### Environment
- [x] Occurs on Android
- [x] Occurs on iOS

Build #: 
1079

Android Device Model: 
N/A

iOS Device Model: 
N/A

### Workaround
N/A

### Severity
- [ ] High
- [x] Medium
- [ ] Low

**Comment by cvarjao** [comment]
You can also replicate by using emojis in the wallet name.
I've decode the generated QRCode, ,and it looks like the characters are properly encoded and carried over to the encoded OOB Invitation object

**Comment by bryce-mcmath** [comment]
So the root of this issue is caused by a patch that allows larger credentials (with large images) to work, but that patch is not needed after the RN 0.72 upgrade so I'm marking this issue as blocked by that work
