### ISSUE TITLE
Mobile verifier - Information received screen does not show that credentials shared is revoked

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1437]
### Description of problem
During a proof request sent via the mobile verifier, the information received screen does not show that revoked credentials shared are revoked. 

### Expected behavior
If the proof does NOT allow revoked credentials to be shared, BC Wallet should not allow information to be shared. 
If the proof DOES allow revoked credentials to be shared, the credential Card UI should reflect the revoked state at the information received screen

### Steps to reproduce
- Acquire revoked credentials from device A
- Send a proof request from device B to device A
- Send information from revoked credentials from device A
- Review the information received from device B

### Environment
- [X] Occurs on Android
- [X] Occurs on iOS

Build #: 1182

Android Device Model: Oneplus 6

iOS Device Model: iPhone SE

### Severity
- [X] High
- [ ] Medium
- [ ] Low

**Comment by nodlesh** [comment]
I'm not sure I agree with showing the verifier the revoked status. If the verifier does a proof not specifying a proof of non-revocation, then they are saying they don't care about that status, and maybe it shouldn't be disclosed to them.

**Comment by cvarjao** [comment]
Works as intended. A verifier cannot check for revocation if it hasn't explicitly requested proof of non revocation.
