### ISSUE TITLE
Proof request templates should not accepts revoked credentials

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1439]
### Description of problem
Proof request templates in mobile verifier allows holders to share information from revoked credentials

### Expected behavior
For now, proof request templates should not accept revoked credentials. 

We want to go through all the proof templates that relate to LSBC, ACM or OK Corrections and make sure the templates ask for non-revoked credentials only.

### Steps to reproduce
- Have a revoked credential
- Receive a proof request
- Send information over

### Environment
- [X] Occurs on Android
- [X] Occurs on iOS

Build #: 1193

Android Device Model: 

iOS Device Model: 

### Severity
- [X] High
- [ ] Medium
- [ ] Low

**Comment by knguyenBC** [comment]
@wadeking98 Proof request with revoked credentials still allows for people to tap the share button. Also, the revoked state of the LSBC credential isn't showing up in a proof request. It's only showing the flagged state. Made a new ticket to tackle the latter issue #1485.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFBGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5df37159d2e3071a840a3ca7b386caf085933565/Screenshot_20230921-093725-r.jpg)

**Comment by wadeking98** [comment]
Tested in testflight, revocation branding shows up and share button is disabled
