### ISSUE TITLE
Credential issuance link from proof request for missing credentials (v1) | Design

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1444]
### Acceptance Criteria
- User is able to see a link to the issuance page of a missing credential.

### Wireframes
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcGFRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ae5425ed155c3cd6757a88c39bbf1efbd5f00ef4/image.png)

**Comment by cvarjao** [comment]
duplicates #1753
