### ISSUE TITLE
Unable to handle deeplink

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1459]
### Description of problem
When trying to get a person credential using the BCSC App integration, after accepting the BSCS Terms, the app is presented with the "Unable to handle deeplink" error, I can still see the Credential Offer and ultimately get the credential

### Expected behavior
no error message

### Steps to reproduce
- Start with a fresh new wallet app (make sure BCSC App is installed and setup in the same device)
- get a lawyer credential or invitation to get person credential
- follow the prompts which will take you to BCSC App
- Authorize access
- After authorizing, and switching back to BC Wallet, the user is presented with that error message
- 
### Screenshots and/or log output
![signal-2023-09-12-171337](https://github.com/bcgov/bc-wallet-mobile/assets/1348549/809f1ab4-4589-4ef4-8fee-788de778b179)

### Environment
- [x] Occurs on Android
- [ ] Occurs on iOS (not tested)

Build #:
1.0.11 (1193)
Android Device Model: 
PIxel 6, Android 13

iOS Device Model: 

### Severity
- [ ] High
- [x] Medium
- [ ] Low

**Comment by knguyenBC** [comment]
Tested build 1238/1230 on android and iOS with the showcase. Deep links work. minor bug #224 identified with issuing person credential on iOS.

**Comment by bryce-mcmath** [comment]
@knguyenBC that bug you linked (#224) takes me to a closed french translation ticket, did you mean to link to something else?

**Comment by knguyenBC** [comment]
Works. No bug.
