### ISSUE TITLE
Missing BC Wallet-specific icons in settings menu

### ISSUE THREAD

**Issue by bryce-mcmath** [bcgov/bc-wallet-mobile#1468]
### Description of problem
The icons for the Help and More Information sections are not showing up

### Expected behavior
They should show up

### Steps to reproduce
Navigate to the settings menu

### Screenshots and/or log output
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdmloIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--96c3824c46aa285855be3b92fa27f2bcda8a6f2a/settings_menu.jpeg)

### Environment
- [x] Occurs on Android
- [x] Occurs on iOS

Build #: 1081

Android Device Model: N/A

iOS Device Model: N/A

### Workaround
N/A

### Severity
- [ ] High
- [ ] Medium
- [x] Low

**Comment by knguyenBC** [comment]
Icons are there.
