### ISSUE TITLE
non-production credential don't have non-production labels or watermark

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1481]
### Description of problem
Credentials that should but do not have any non-production labels inline with credential name (test, dev, non-production etc.) or the watermark:
- The student card from the showcase
- The LSBC member card from the showcase has the watermark but does not have the label 
- The Person credential from the showcase has the watermark but does not have the label 
- LSBC member card from their test environment has no watermark

### Expected behavior
Credentials should have the non-production labels and the watermark

### Environment
- [X] Occurs on Android
- [X] Occurs on iOS

Build #: 1203

Android Device Model: OnePlus 6

iOS Device Model: iPhone SE

### Severity
- [ ] High
- [ ] Medium
- [X] Low

**Comment by jleach** [comment]
Confirmed 1.0.12 1325. Non-prod showcase credentials contain a water mark "NON-PRODUCTION".
