### ISSUE TITLE
Remove PI flags from LSBC and Person credentials

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1484]
### Description of problem
When receiving a proof request asking for either the LSBC member card or Person credential, the entire credentials (all the attributes) are flagged as sensitive information. 

### Expected behavior
Issuers IDIM and LSBC have not defined what attributes (if any) are labelled as flagged. None of their credentials should be flagged as PI/sensitive

### Steps to reproduce
- Receive the LSBC member card and/or the Person credential (prod or test)
- receive a proof request asking for either or both the LSBC member card or Person credential

### Environment
- [X] Occurs on Android
- [X] Occurs on iOS

Build #: 1203

Android Device Model: OnePlus 6

iOS Device Model: iPhone SE

### Severity
- [X] High
- [ ] Medium
- [ ] Low

**Comment by wadeking98** [comment]
Resolved by: https://github.com/bcgov/aries-oca-bundles/pull/83

**Comment by knguyenBC** [comment]
@wadeking98 is this ticket done considering LSBC and IDIM decided to keep the flags?
