### ISSUE TITLE
Lawyer credential doesn't show both flagged and revoked state when in a proof request

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1485]
### Description of problem
LSBC issued member card credential does not accurately show both the flagged and revoked state when presented in a proof request. 

### Expected behavior
If the credential is both revoked and has flagged attributes, then the card UI in a proof request should reflect both states. The Person credential accurately depicts both states

Person credential with BOTH the flagged and revoked state 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaVBGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--605e5fe1bd360056b04c8c227f58712d59f4aac8/original-A5AC2E4F-597F-4247-8F8C-17E13AA446E7-R.jpeg)

### Steps to reproduce
- Get a lsbc member card
- revoke the credential
- receive a proof request asking for the lsbc member card

### Screenshots and/or log output
LSBC member card with missing revoked state
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaHZGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cd6a6cd24a2fd5ec05df954e1e40b7140ae13eba/Screenshot_20230921-093725-r.jpg)

### Environment
- [X] Occurs on Android
- [X] Occurs on iOS

Build #: 1203

Android Device Model: OnePlus 6

iOS Device Model: iPhone SE

### Severity
- [ ] High
- [X] Medium
- [ ] Low

**Comment by wadeking98** [comment]
Tested in testflight and can confirm it is working as expected
