### ISSUE TITLE
Flagged info alert not showing in proof request

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1486]
### Description of problem
Proof request asking for credentials with flagged attributes (ex. age) does not bring up flagged information alert. The alert appears sometimes when the Person credential is requested but not when it's just the age (predicate).

### Expected behavior
Proof request should bring up alert if flagged information is being requested

### Steps to reproduce
- Get a person credential and LSBC member card on one device
- Go to any proof request asking for age or any proof request just asking for the lawyer credential in mobile verifier
- Scan the QR code to get the proof request

### Screenshots and/or log output
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanZGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6a017b8aa2e394fe4f3b65277ef48deaa2110828/Screenshot_20230921-093725.jpg)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanpGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7100075aa95e61e846f77210f8d1f9db978baa9f/Screenshot_20230921-102758_r.jpg)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBajNGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7105bb3798aa1181af09d56bb69c939b370a6bcc/Screenshot_20230921-102510_r.jpg)

### Environment
- [X] Occurs on Android
- [X] Occurs on iOS

Build #: 1203

Android Device Model: OnePlus 6

iOS Device Model: iPhone SE

### Severity
- [ ] High
- [X] Medium
- [ ] Low

**Comment by wadeking98** [comment]
@cvarjao I thought we decided against flagging predicates as PII since they are zero knowledge proofs

**Comment by knguyenBC** [comment]
@wadeking98 Oh you're right. Then the bug fix should remove the flagged UI on the card itself. In the screenshot, where it's asking for JUST the age, there's the warning icon and the font is amber. That should not be the case.

**Comment by wadeking98** [comment]
seems to be resolved in testflight now

**Comment by knguyenBC** [comment]
Just checked. Looks like it works as intended now.
