### ISSUE TITLE
Next and Back buttons in onboarding too close to bottom

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#149]
The pager and next and back buttons are too close to the bottom of the screen. It should be lifted up to a consistent 40px margin. This margin should be consistent across the entire app. 

![image.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/47a80ef3-8dda-403c-b0e5-db6cb70a2de6)

**Comment by knguyenBC** [comment]
@jleach is this fixed as a result of [this ticket](https://app.zenhub.com/workspaces/bc-wallet-6148e7423fe04b001444e2bd/issues/bcgov/bc-wallet-mobile/150)? Shall this be moved to done?

**Comment by jleach** [comment]
Yes/No. I've bumped it up quite a bit to let shel do some testing. I need to put ti back to a sane location.

**Comment by jleach** [comment]
Ok, I've moved it to a better location.
