### ISSUE TITLE
Update onboarding screens (v3) | Design

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1498]
### Description of feature / user story
As a person who is misinformed on the purpose of BC Wallet, I want to be properly informed so that I am not disappointed when it doesn't work as expected

### Acceptance Criteria
Given the user has just downloaded the app
When they open the app
Then they are presented with a screen that requires their confirmation that they've read and understood the purpose of BC Wallet

### Wireframes or relevant image assets / links
[Links to updates to onboarding screens](https://xd.adobe.com/view/35c82052-5c29-4343-bab0-7dc84cebb129-609b/)

[Content for the onboarding screens](https://docs.google.com/document/d/1naPt6GVhNETDiyGmjvg1PhZb2IRvD_tYK7HhJwX8uk4/edit?usp=sharing)

**Comment by nodlesh** [comment]
@knguyenBC @jleach I'm assuming this a design ticket only? I don't see any changes to the onboarding screens in the latest release. If it is a design ticket can we add the design label?

**Comment by knguyenBC** [comment]
Design ticket. To be reviewed with Clecio and then a dev ticket will form from it.
