### ISSUE TITLE
Support For Indigenous Languages (UTF-8)

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1503]
- Invitation label: Wallet / Issuer/Verifier Name
- Credential Attribute Name
- Credential Attribute Value
- Schema Name
- Credential Definition ID (tag)
- OCA Labels/Descriptions

**Comment by nodlesh** [comment]
Tested with Schema Name and Credential Definition ID containing Special Characters. This is with an ACA-Py Issuer and Verifier. The test passed except for the display of the credential name. 
"credential_definition_id": "AmzL2hSP2gPm9DuQBLVcy8:3:CL:77962:drivers_license_!@#$%^&*(0", 
"schema_id": "AmzL2hSP2gPm9DuQBLVcy8:2:drivers_license_!@#$%^&*(0:1.0.0"
Credential Name displays as `Drivers License 0` in BC Wallet. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcW5iIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--70a180d1ac15e5e831965801c90cc410a01748c4/Screenshot%202023-09-26%20at%203.01.59%20PM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcXJiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--addcca8560d4c53dbd1af613ad6c66678b8a30b4/Screenshot%202023-09-26%20at%203.02.40%20PM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcXpiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5d2ee8c3b46050bdacc9f65fb1cfc32e4cc14265/Screenshot%202023-09-26%20at%203.04.57%20PM.png)

**Comment by cvarjao** [comment]
@nodlesh, we are talking about characters outside the ASCII table. Emojis are example of such characters.

**Comment by nodlesh** [comment]
'credential_definition_id': 'GK9qMoQLZdPHXEAEvLWJG6:3:CL:77998:drivers_license_😀'
'schema_id': 'GK9qMoQLZdPHXEAEvLWJG6:2:drivers_license_😀:1.0.0'

Receiving the credential did ok and even displayed in BC Wallet correctly. However, the proof didn't work and the Credential name was displayed improperly in BC Wallet. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcDNjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c1344465e0a8566987cf0fd2f357bcc5ffa3172c/Screenshot%202023-09-26%20at%205.14.48%20PM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcURjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a7b415a23e58cd5e6d9b2423c44c6923e880a1f0/Screenshot%202023-09-26%20at%205.15.24%20PM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcVBjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a6d476a482d761085a902fc50a6d9e81cb2c2f1d/Screenshot%202023-09-26%20at%205.16.03%20PM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWJjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ca00ee3555757d8fbbb4da8a43f2bb055557d114/Screenshot%202023-09-26%20at%205.16.26%20PM.png)

This seems to be an issue with BC Wallet or AFJ and not in the ACA-Py Verifier. The verifier sends the proof request and never hears back from the Wallet.

**Comment by cvarjao** [comment]
@nodlesh , what version of aca-py is AMTH using?

**Comment by nodlesh** [comment]
@cvarjao This above was right out of main. We mostly test the wallet with ACA-Py main.  I can just as easily do the official ACA-Py release version if that helps?

**Comment by cvarjao** [comment]
@nodlesh ,  I am confused how you get it working in your tests. What build of BC Wallet did you run against?

**Comment by nodlesh** [comment]
@cvarjao  It was 1215 or 1216. Not sure what the confusion is? AMTH uses AATH agents as Issuer and Verifier agents for testing the wallet. Those agents can be built from main or release.

**Comment by cvarjao** [comment]
Have you tried using an emoji in the invitation label? where I see as "aca-py.Acme"/"aca-py.Bob"?

**Comment by nodlesh** [comment]
Not yet.

**Comment by cvarjao** [comment]
closing as stale issue
