### ISSUE TITLE
The CICD pipeline stopped publishing failures to rocket chat

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#1506]
When the build fails for iOS or Android the results were published to Rocket Chat. This is broken. We get an error about bad credentials.

**Comment by nodlesh** [comment]
Waiting on seeing a build failure on main show up in the ditp-digital-wallet-core-team rocket channel before closing this one.

**Comment by jeffaudette** [comment]
discussed at scrum on Thurs Nov 9, it is failing again. @jleach can you take a look? Not hi priority

**Comment by jleach** [comment]
This does not work because I'm not an admin or the likes in the `#ditp-bc-wallet-core-team` channel. I tried with cURL and it fails with the error `{"success":false,"error":"error-not-allowed"}` when I point the hook at this channel. When I point the hook at a channel where I am an admin `#test` it works with the message `{"success":true}`.

**Comment by jleach** [comment]
Fixed. The correct user was added to the channel. Manually verified with a cURL test.
