### ISSUE TITLE
Credential branding is wrong

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1508]
### Description of problem
Branding of the LSBC issued and IDIM issued credential is wrong. This affects both prod and non-production credentials. 

### Expected behaviour
Person credential should display the following information:
issuer: Service BC
Credential name: Person

LSBC credential should display the following information
issuer: Law Society of BC
Credential name: Member Card

### Steps to reproduce
- Acquire a person and LSBC member card (both prod and non-prod)

### Screenshots and/or log output
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBckRyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--921271b257d65f3822dec0bddc9d3f89855cda54/20230928_132414.png)

### Environment
- [x] Occurs on Android
- [x] Occurs on iOS

Build #: 
1216

Android Device Model: OnePlus 6

iOS Device Model: iPhone SE

### Workaround
N/A

### Severity
- [ ] High
- [x] Medium
- [ ] Low

**Comment by wadeking98** [comment]
Resolved by: https://github.com/bcgov/aries-oca-bundles/pull/84

**Comment by knguyenBC** [comment]
Checked build 1246. Looks good.
