### ISSUE TITLE
Fix issue with outdated nodes in genesis blocks

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#1521]
Quite a few IPs are dead in the current genesis blocks. We need to update them to prevent unnecessary delays when using the BC Wallet.

- Fix issue with outdated nodes in genesis blocks.
- Enable genesis block build in CICD pipeline.

**Comment by swcurran** [comment]
How did you fix the outdated nodes?  From the initial assessment, you were using the latest. Not so?
