### ISSUE TITLE
Connection stays even when data retention turned off

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1529]
### Description of problem
When the verifier's phone falls asleep or leaves the mobile verification flow before the information is sent over. The verifier can go back into Contacts and see a connection with the holder and review information. 

### Expected behavior
When data retention is off, Connection/Contact should be deleted after the information is reviewed.

### Steps to reproduce
- verifier sends a proof request
- holder scans proof request
- verifier puts app to sleep or navigate back to home
- holder accepts the proof request
- Holder successfully sends information
- Wake the verifier's phone or go to contact list
- Open the holder chat
- Open the information sent over
- See that the information sent over is gone but the connection stays

### Environment
- [X] Occurs on Android
- [X] Occurs on iOS

Build #: 1246

Android Device Model: Oneplus 6

iOS Device Model: iPhone SE

### Workaround
- Turn off sleep mode

### Severity
- [ ] High
- [X] Medium
- [ ] Low

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/995

**Comment by jeffaudette** [comment]
needs re-test

**Comment by knguyenBC** [comment]
@wadeking98 Connection still stays if the lawyer declines the proof request (works fine if the lawyer accepts). Also, when the lawyer rejects the proof request, if the lawyer is in some other screen, it doesn't display a new message notification in the notification list.

**Comment by wadeking98** [comment]
got it, I'll fix for instance where proof is declined

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/997
