### ISSUE TITLE
Visible token in wallet re-enter pin accessibility label

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#1536]
Build 1252. As per the screen shot there is the token `{{new}}` in the re-enter pin accessibility label:

![IMG_0078](https://github.com/bcgov/bc-wallet-mobile/assets/390891/0ced55c4-0a17-4ebe-a3da-dab29f0e1c80)

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/998
