### ISSUE TITLE
The EULA title is a little cramped

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#1537]
- Update title to "Terms of Use"
- Update top info bar from "terms and conditions" to "terms of use"

Build 1252
With little to no zoom or font scaling the label for the EULA screen is a little cramped:

![IMG_0080](https://github.com/bcgov/bc-wallet-mobile/assets/390891/27af1b7b-3434-45d9-8f73-2d76eba1a6be)

**Comment by knguyenBC** [comment]
Talked with David Bigsby and Oli. They're not aware of any requirement that the EULA needs to be called "End User License Agreement".

**Comment by jleach** [comment]
Verified in 1.0.15-1452
