### ISSUE TITLE
App crashing on startup on Android 8 and lower.

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#1550]
### Description of problem
BC Wallet app is crashing on Android devices at OS versions lower than Android 9, API level 28.
Tested on 6, 7, and 8

This bug will relate to #391 & #1414

### Screenshots and/or log output
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3BMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d0fcdd8550bcb25b8bc78bf8cc237fa7523c4c5a/Screenshot%202023-10-18%20at%2010.43.04%E2%80%AFAM.png)

[Uploading... device-log.zip]

### Environment
- [x] Occurs on Android
- [ ] Occurs on iOS

Build #: 1256 but happens as low or maybe lower than 1136.

Android Device Model: 
Tested on 6, 7, and 8 on Sauce Labs
7.1.2 Mason G450A1
8.0.0 Huawei Mate 10 Pro
8.0.0 Samsung Galaxy S7 Edge
8.0.0 LG V30
6.0.1 Samsung Galaxy S6 Edge+
6.0.1 Samsung Galaxy J7 2016
6.0.1 Samsung Galaxy S5

iOS Device Model: 

### Workaround
None Known

### Severity
- [x] High
- [ ] Medium
- [ ] Low

**Comment by cvarjao** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BC-Wallet-6148e7423fe04b001444e2bd/issues/bcgov/bc-wallet-mobile/1550?planning-poker) with Zenhub @bryce-mcmath @jleach @wadeking98

**Comment by cvarjao** [comment]
I've tested with LG device with Android 8 and it worked fine. I will re-test it using latest build with credo/camera updates

**Comment by nodlesh** [comment]
This is still happening on Sauce Labs real devices. But if you have success on a "real" real device then maybe we can say it might be something to do with the test infrastructure on Sauce Labs. 

Here are a couple device logs for what's happening on SL devices.
[Android7.log](https://github.com/bcgov/bc-wallet-mobile/files/15266309/Android7.log)
[Android8.log](https://github.com/bcgov/bc-wallet-mobile/files/15266312/Android8.log)

**Comment by jleach** [comment]
I tested on a LG V30 Android 8.0.0. The exception seems to be from a missing library called [backtraceio](https://docs.saucelabs.com/error-reporting/platform-integrations/android/setup/). I'm not much of an Java developer so perhaps this is a non-issue because its related to SauceLabs rather than the BC Wallet. @cvarjao thoughts?

[SauceLabs_Log_LG_V30_real_2024-05-23_11-01.txt](https://github.com/bcgov/bc-wallet-mobile/files/15420930/SauceLabs_Log_LG_V30_real_2024-05-23_11-01.txt)

```
11:00:49 E AndroidRuntime : FATAL EXCEPTION: main
11:00:49 E AndroidRuntime : Process: ca.bc.gov.BCWallet, PID: 22241
11:00:49 E AndroidRuntime : java.lang.NoClassDefFoundError: Failed resolution of: Lbacktraceio/library/BacktraceCredentials;
11:00:49 E AndroidRuntime : at com.saucelabs.rdcinjector.backtrace.BacktraceCollector.<init>(BacktraceCollector.java:18)
11:00:49 E AndroidRuntime : at com.saucelabs.rdcinjector.backtrace.BacktraceCollector.install(BacktraceCollector.java:35)
11:00:49 E AndroidRuntime : at com.saucelabs.rdcinjector.image.SauceApplication.onCreate(SauceApplication.java:31)
11:00:49 E AndroidRuntime : at ca.bc.gov.BCWallet.MainApplication.onCreate(MainApplication.java:56)
11:00:49 E AndroidRuntime : at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
11:00:49 E AndroidRuntime : at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5933)
11:00:49 E AndroidRuntime : at android.app.ActivityThread.-wrap1(Unknown Source:0)
11:00:49 E AndroidRuntime : at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
11:00:49 E AndroidRuntime : at android.os.Handler.dispatchMessage(Handler.java:105)
11:00:49 E AndroidRuntime : at android.os.Looper.loop(Looper.java:164)
11:00:49 E AndroidRuntime : at android.app.ActivityThread.main(ActivityThread.java:6703)
11:00:49 E AndroidRuntime : at java.lang.reflect.Method.invoke(Native Method)
11:00:49 E AndroidRuntime : at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
11:00:49 E AndroidRuntime : at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
11:00:49 E AndroidRuntime : Caused by: java.lang.ClassNotFoundException: Didn't find class "backtraceio.library.BacktraceCredentials" on path: DexPathList[[zip file "/data/app/ca.bc.gov.BCWallet-WME202GZ1SrgF-3H5iUdCA==/base.apk"],nativeLibraryDirectories=[/data/app/ca.bc.gov.BCWallet-WME202GZ1SrgF-3H5iUdCA==/lib/arm64, /data/app/ca.bc.gov.BCWallet-WME202GZ1SrgF-3H5iUdCA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
11:00:49 E AndroidRuntime : at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
11:00:49 E AndroidRuntime : at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
11:00:49 E AndroidRuntime : at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
11:00:49 E AndroidRuntime : ... 14 more
```

The next line looks like its being forced to close:
```
2024-05-23 11:00:49.342	WARN:	ActivityManager : Force finishing activity ca.bc.gov.BCWallet/.MainActivity
```

The log message "ActivityManager: Force finishing activity" in an Android app typically means that the Android system has decided to forcibly terminate an activity. This can happen for several reasons including a crash or exception: The activity has encountered an unhandled exception or crash, and the system is terminating it to prevent further issues.

**Comment by cvarjao** [comment]
@nodlesh, based on the stack trace, I think SauceLabs  is trying to do something and injecting "backtrace" service, do you know anything about it? is there a way to turn it off?

**Comment by nodlesh** [comment]
I'll investigate.

**Comment by nodlesh** [comment]
I have confirmed that turning off instrumentation settings in Sauce Labs for the Android app fixes the app crash and that "backtrace" error is not there anymore. However, this instrumentation is where we enable image injection and biometrics interception, both needed in testing the app. Sauce Labs is aware of the issue. I suggest we leave this issue open for just a little while longer in case SL comes back with an app config setting that we could change in the app that might make this work. If it is entirely on their side, then we will close this issue.

**Comment by nodlesh** [comment]
The last response I received from Sauce Labs below. 
> Upon further investigation, I found that we have received previous reports from customers regarding this issue.
> 
> However, it's important to note that debugging features at this level are supported on the top three major versions. Regrettably, this implies that the issue will not be resolved or attended to for Android version 8 or below.

This may be a reason to move to a different Device Cloud Service Provider, but we may have the same issue with another service. 
So two resulting work items from this is, 

1.  investigate other device cloud services on their support for image injection and biometrics interception on Android 8 and below.
2. Change the nightly Android regression run to exclude Android 8 and below to avoid known failures. 

This issue can be closed.
