### ISSUE TITLE
Proof request template updater (v1) 

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1559]
### Description of feature / user story
Currently, BC Wallet needs to be deployed every time a new use case using the mobile verifier requires a different proof request. This is not scaleable.

As a developer, I want to update the proof request templates without having to deploy the wallet so that use cases are not delayed until a release is available

NOT IN SCOPE
As a verifier, I want to be able to create my own templates so that I don't need to rely on a different team/organizations to create my templates and I have more control.

### Acceptance Criteria
- proof request templates can be updated and accessed in BC Wallet without having to release a new version

### Wireframes or relevant image assets / links

**Comment by bryce-mcmath** [comment]
Can we please get links to wireframes for this ticket? I can't seem to find any

**Comment by knguyenBC** [comment]
I didn't think there was a need for one as it's not meant to be user facing yet and just for our internal team to easily update.

**Comment by cvarjao** [comment]
Proof request templates can now be updated from a github branch
