### ISSUE TITLE
Proof request template updater (v1)  | dev

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1564]
- cache on build
- refresh cache when wallet starts

**Comment by jleach** [comment]
@wadeking98 How would I test this one so it can be closed?

**Comment by wadeking98** [comment]
@jleach if the templates show up in the mobile verifier then it's successfully fetched the proof templates (you may notice a slight delay until the templates show up, about 1/2 second). After that the templates are cached until the app restarts so there won't be any loading delay when visiting the proof template screen

**Comment by wadeking98** [comment]
@jleach if the templates show up in the mobile verifier then it's successfully fetched the proof templates (you may notice a slight delay until the templates show up, about 1/2 second). After that the templates are cached until the app restarts so there won't be any loading delay when visiting the proof template screen

**Comment by jleach** [comment]
Confirmed in 1.0.13 1367.
