### ISSUE TITLE
App Attestation (v1) - Showcase

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1572]
New Scenario:
- Proof Request for App Attestation (hidden) under Lawyer/Joyce

**Comment by jleach** [comment]
I don't see the option under Cmd-K on the "dev" instance of the Showcase. @wadeking98

**Comment by wadeking98** [comment]
the option is to show hidden use cases:


![Image](https://github.com/bcgov/bc-wallet-mobile/assets/36937407/973ec1cf-3d3d-49c3-93ba-6e1e1e1565b2)

**Comment by jleach** [comment]
Closing as per screen shots.
