### ISSUE TITLE
"Add your credentials" button freezes the app

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1580]
### Description of problem
When tapping the "Add your credentials" button. It takes you to a static loading screen and freezes.

### Expected behavior
When tapping the "add your credentials" button, it should take the person to the camera permissions if it's their first time opening the scan button. Otherwise, it would open the camera.

### Steps to reproduce
- go to the credentials tab
- tap on the "add your credentials" button (delete all credentials in the list to see that button)

### Environment
- [ ] Occurs on Android
- [X] Occurs on iOS

Build #: 1.0.11 (1256)

Android Device Model: 

iOS Device Model: 

### Severity
- [ ] High
- [X] Medium
- [ ] Low

**Comment by jleach** [comment]
Tested on FT 1.0.12 Build 1325 and works as expected. The button is now called "Add your first credential" and as expected it takes me to the camera permissions  screen on first use. Selecting Ok shows the camera ready to scan a QR code.

**Comment by knguyenBC** [comment]
I tried it with the latest build on iOS. it seemed to have fixed itself.
