### ISSUE TITLE
Expiry Date shows "Invalid Date:" - Person Credential

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1581]
### Description of problem
IDIM is not issuing credentials with expiry date atm. That means the field is empty.

### Expected behavior
1. Unused filelds should be hidden
2. the date parsing/rendering function should check for empty values

### Screenshots and/or log output
![signal-2023-10-24-123411](https://github.com/bcgov/bc-wallet-mobile/assets/1348549/24faa7d5-3b2b-40aa-8a81-b7931f98176d)

### Environment
- [x] Occurs on Android
- [x] Occurs on iOS

Build #:

Android Device Model: 

iOS Device Model: 

### Severity
- [ ] High
- [ ] Medium
- [x] Low

**Comment by wadeking98** [comment]
resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/1038

**Comment by jleach** [comment]
Confirmed in 1.0.13 1395. I no longer see expiration date in Person credential.
