### ISSUE TITLE
Missing timestamp in the contact list on android

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1589]
On Android:
![signal-2023-11-06-140711](https://github.com/bcgov/bc-wallet-mobile/assets/1348549/9059eed6-66cb-423c-87df-e4087378176a)

iOS:
![signal-2023-11-06-140737_002](https://github.com/bcgov/bc-wallet-mobile/assets/1348549/4abea857-2b54-4b05-8f27-7f80d06641c1)

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/1044
