### ISSUE TITLE
URL detection in chat is case sensitive

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1590]
## Acceptance Criteria
Given that a message contains a URL (mixed case) then present as a clickable hyperlink

**Comment by jeffaudette** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BC-Wallet-6148e7423fe04b001444e2bd/issues/bcgov/bc-wallet-mobile/1590?planning-poker) with Zenhub @jeffaudette

**Comment by wadeking98** [comment]
resolved by: https://github.com/openwallet-foundation/bifold-wallet/pull/1176

**Comment by knguyenBC** [comment]
Checked on iOS and Android. Works as expected.
