### ISSUE TITLE
Change buttons in information received screen

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1591]
### Description of feature / user story
Most verifiers only verify using a single proof request template. The current screen prioritizes going back to the list of proof requests (primary button) rather than requesting another proof using the same template (secondary button).

To streamline the verification flow, please change the primary button to request another proof using the same template and the secondary button to go back to the list of templates

Change the buttons in proof request to the following
- Request another proof -> this button takes people to the QR code screen with a new generated QR code
- Back to list -> this button takes people to the list of proof request

### Acceptance Criteria
Given the verifier either has received information or has their proof request declined
When the verifier taps "Request another proof" 
Then they are taken to the QR code screen with a new generated QR code

Given the verifier either has received information or has their proof request declined
When the verifier taps "Back to list"
Then they are taken to the list of proof requests

### Wireframes or relevant image assets / links
https://xd.adobe.com/view/0a112c19-6f28-48cd-8ba6-3d80c7cd3771-5f42/screen/c33df5a4-95f5-4907-83f7-2a78f65c953a/

**Comment by wadeking98** [comment]
resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/1032

**Comment by jleach** [comment]
Confirmed in 1.0.13 1367.
