### ISSUE TITLE
Remove Skip button from onboarding

### ISSUE THREAD

**Issue by bryce-mcmath** [bcgov/bc-wallet-mobile#1593]
### Description of feature / user story
The Skip button for onboarding should be disabled in BC Wallet. So it will need to be made configurable first

### Acceptance Criteria
The Skip button should not show up, users should have to slide through all the onboarding pages.

### Wireframes or relevant image assets / links
N/A

**Comment by jleach** [comment]
Confirmed. This no longer exists in 1.0.12 Build 1325.
