### ISSUE TITLE
Organize interview with lawyers

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#16]

**Comment by conhibit** [comment]
Mendocino county jail's water is severely contaminated.  Showers caused severe wrinkling, Perma dandruff, crowsfeet, lizard scales, rashes, chemical burns that turn into bloody sores, etc. Drinking water caused a fuckton of stomach, gas, and intestinal problems all of the sudden after 2.5 years housed there. 

I was coerced into over 8 gladiator fights, infact my nickname was Rooster and I hated it. I came in with Anterior Wedging of Thoracic segment 11, and I came out with a shattered spine, levo scoliosis, bone spurs, narrowing of the spine, arthritis in the sacroiliac joints, and age deterioration despite being 30 yrs old

 frequent thirst, dry mouth, bloody coughs from likely sinus or lung infection trapped by deformed spine , debilitating migraines every other day,  lost two teeth from dry mouth despite brushing and flossing  daily,

 I was denied college, and c.os would call us Alligator men and Rollypollys based on shower waters damage, it happened to about 30+% of detainees alot were unaware or in denial.

This case should b able to pull someone multimillions based on related cases, my future ability to enjoy life is destroyed, I got mental anguish, PTSD, ADHD, and lots of incurable medical damages.

I have shopped up and down California for 8 years contacting police misconduct lawyer s but no one will offer to champion for me 

I was wrongfully convicted of 500 lbs marijuana cultivation in 2014 where I first experienced the shower's wrinkling of my skin , this lead me subliminally to kill my father via baseball bat in 2015 even though there was alot of self defense elements to the story as well (he was in the middle of a psychotic break knife lunging frenzy). I fought it until spring 2019 when I was medically coerced into a plea deal for 8 years voluntary Manslaughter. It is easily appealable as I had constitution violations for speedy trial, ineffective counsel, medically coerced confession, and federal double jeapordy as a tribal court considered me not guilty before the superior court s decision. Even tho obvious self defense elements involved.

Later In prison a Southsider stole my corn chips and walked off so I limped after him and shoved him against the tray serving slot a couple times until a Mexican c.o. bashed me in the head with a nightstick, made me seizure out for the first time, broke my jaw, caused hematoma of the brain, verebral bleeding, and brain swelling, my head hurt so bad I got sent to an outside hospital for 2 weeks where I watched Anime and was  put on morphine temporarily.

My statute of limitations is still active for 2+ years as I was denied law library and phone calls for 10 years and I have documentation of this....



Also I am currently illegally committed to an electronics less rehab in Lake County. And wouldn't mind an injunction out of it...  

I am a 2nd or 3rd generation victim of police harassment and misconduct. My dad would get gangbeat and tased by Mendocino PD on his own property my entire  life . He got his property via motorcycle accident settlement that cut up his brain tissue .  He was not mentally functioning and abused me physically, sexually, mentally. It was like being nurtured by a single bridge bum.  He was medically diagnosed skizophrenic and prescribed Prozac  And some witnesses claimed I was a 12 year old taking care of a mentally disabled adult.

It's a long story and not many get much worst than this. Please be the one to champion for me and avenge the class warfare I've had to endure. Or else I'll go to my 420channel .org folks,  or even file the motions myself. i got all the paperwork necessary and would very much appreciate a jury decision. A settlement, an acquittal, a release from parole conditions so I can travel to Japan and Costa Rica someday with my homie Cricket who owns a coffee plantation, and cafe in Costa Rica and wants to experiment with cannabis fusion recipes. As some of my immediate family are two of the most earliest pioneer potfarmers of the emerald triangle grow scene. We just fell behind the regulated end of the weed game so now we are the underdog in this battle. thank you.

**Comment by conhibit** [comment]
Why
