### ISSUE TITLE
Determine a method to use for Wallet to Attestation Controller communicaiton

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#1603]
We need a mechanism for the Wallet to communicate to the Agent responsible for issuing attestation credentials other than DIDComm basic messaging. Some ideas include:

1) [HTTP/s over DIDComm](https://github.com/hyperledger/aries-rfcs/tree/main/features/0335-http-over-didcomm) may be an option but we need to know if it is suitable and if so, if it is implemented in AFJ. If not in AFJ are we able to help with implementation? Ref: [Chat](https://chat.developer.gov.bc.ca/group/ditp-bc-wallet-core-team?msg=fm5t3Y3qXrajXNoeA)

2) As per [Stephen's comment ACA-py on Discord](https://discord.com/channels/905194001349627914/941706593739894804/1154183392947085314) the protocol used should be formalized in its own RFC and become a separate entity to Basic Message. This would require designing the protocol, writing an RFC, and pushing ahead with the adoption of the the RFC.

**Comment by bryce-mcmath** [comment]
Jason and I and Stephen agree about going with the first approach. See comments [here](https://github.com/hyperledger/aries-cloudagent-python/issues/2616) and [here](https://github.com/hyperledger/aries-framework-javascript/issues/1642) about implementing in ACA-Py and AFJ

**Comment by jleach** [comment]
Chatted with Stephen today. I think we're going with option (1) as our "crawl".
