### ISSUE TITLE
App Attestation (v1) | HTTP Over DIDComm | development

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1608]
prerequisites:
- [ ] ACA-py implementation of HTTP Over DIDComm
- [ ] AFJ implementation of HTTP Over DIDComm

**Comment by jleach** [comment]
No longer doing HTTP over DIDComm. This will be more like a gRPC feature added to ACA-py.

**Comment by swcurran** [comment]
Not gRPC (which is pretty heavyweight), but instead [JSON-RPC](https://www.jsonrpc.org/specification), which is just right, I think.
