### ISSUE TITLE
yarn install fails in windows 10 with workspace not found error

### ISSUE THREAD

**Issue by nelaturuk** [bcgov/bc-wallet-mobile#1619]
### Description of problem
After cloning the repo next step is to do yarn install. Yarn install fails with aries-bifold@workspace:^ workspace not found error

### Expected behavior
yarn install to install the dependencies successfully. 

### Steps to reproduce
On Windows powershell clone bc-wallet-mobile repo. Do yarn install. 

### Screenshots and/or log output
![image](https://github.com/bcgov/bc-wallet-mobile/assets/3939682/ba5ecc3e-47ef-4fb8-8930-4477e14bbcf6)

### Environment
 Occurs on Windows

Build #:

### Severity
- [X] High
- [ ] Medium
- [ ] Low

**Comment by cvarjao** [comment]
[bifold-core](https://github.com/bcgov/bc-wallet-mobile/blob/main/bifold-core) needs to be a symbolic to `./bifold/packages/legacy/core`. Make sure you `git` is setup to handle symbolic links

**Comment by nelaturuk** [comment]
Thank you. 
I tried enabling symbolic links using the following command: ` git config --global core.symlinks true`

It still shows the same error on `yarn install`. Is there anything else we need to do?

Am I supposed to move bifold code somewhere? Also ,this is being tried on the Windows powershell.

**Comment by cvarjao** [comment]
Unfortunately, we don't test build on windows, and the team uses Mac, so I am unable to reproduce.
However, we are removing the symlink requirement and that might help.
See PR #1647 for progress

**Comment by cvarjao** [comment]
closing stale issues
