### ISSUE TITLE
Credential offer and proof request not received after making a connection

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1628]
### Description of problem
Mediator connection not available on app download. No offer or proof is received after connecting.

### Expected behavior
Credential offer and proof request not received after making a connection. 

### Steps to reproduce
- Install BC Wallet from Testflight build 1325 and above
- Acquire a credential offer or proof request
- check to see if received

### Environment
- [X] Occurs on Android
- [X] Occurs on iOS

Build #: 1325 and up

Android Device Model: 

iOS Device Model: 

### Severity
- [X] High
- [ ] Medium
- [ ] Low

**Comment by wadeking98** [comment]
@knguyenBC I believe this is fixed by Jason now
