### ISSUE TITLE
Unlock in-app guides

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1650]
All guides need to be unlocked

There is no in app guide for the scanner yet

**Comment by jeffaudette** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BC-Wallet-6148e7423fe04b001444e2bd/issues/bcgov/bc-wallet-mobile/1650?planning-poker) with Zenhub @bryce-mcmath @jleach @wadeking98

**Comment by bryce-mcmath** [comment]
If both in-app guides and push notifications become GA then there will be two modals mounted at once when the wallet is first opened, which will freeze the app on iOS. There will need to be a check added to make sure they don't mount at the same time.

**Comment by jleach** [comment]
Confirmed enabled in 1.0.13 1395
