### ISSUE TITLE
Add troubleshooting logging 

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1654]
Existing logging libraries we could integrate with:
- [winston](https://github.com/winstonjs/winston)
- [pino](https://www.npmjs.com/package/pino)
- [bunyan](https://www.npmjs.com/package/bunyan)

Acceptance Criteria
- Enable/Disable via dev mode
- If logging enabled, set collection level to "debug" level
- keep logging file to a reasonable small size
- a way to extract and send to us
-

Reference:
- [Example of integrating with Pino](https://github.com/cvarjao/afj-perf-test/blob/main/src/index.ts)
- [React Native FS](https://www.npmjs.com/package/react-native-fs#API)

**Comment by cvarjao** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BC-Wallet-6148e7423fe04b001444e2bd/issues/bcgov/bc-wallet-mobile/1654?planning-poker) with Zenhub @bryce-mcmath @jleach @wadeking98

**Comment by jleach** [comment]
I tried both Pino and Winston. Bunyan looks ok but was last published 3 years ago and I'm hesitant to hitch our horse to that wagon. No updates means no fixes for security. Winston does not work at all because has a dependency on the `os` package and both Pino and Winston give me a error when registering a transport:

```
 ERROR  TypeError: _pino.default.transport is not a function (it is undefined), js engine: hermes
```

If I don't use any transports, I can get Pino to log to the terminal:

```
 DEBUG  {} Connection completed, requesting mediation
 DEBUG  {} Mediator invitation has already been granted
 DEBUG  {} Mediator routing record not loaded yet, retrieving from storage
 INFO  {} Starting implicit pickup of messages from mediator '0d1b045a-cdd2-44e0-bb8b-65c521c9c1af' undefined
 DEBUG  {} resolving didUrl did:peer:1zQmWMkXtqSSdgCWrbARHgovkSGGP4w4XfTUPPnU2CV1gj3H
```

**Comment by bryce-mcmath** [comment]
Do you think something like `react-native-logs` would maybe work? https://www.npmjs.com/package/react-native-logs Looks like it has custom transports, not sure if the issue is with the logging libs themselves or with using it them with the aries agent
