### ISSUE TITLE
Spike: Review surveymonkey survey builder

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1655]
Find a location in the survey that will display the custom variable (the error message) so that when the survey is submitted, the error message is saved and viewable.

Survey Monkey does not have an easy way to show a custom variable.

Alternatives is to use a different survey tool.

**Comment by cvarjao** [comment]
[Jira Service Management](https://www.atlassian.com/software/jira/service-management) might be an option

**Comment by jleach** [comment]
Estimated as a 3, unable to update "Estimate" field.
