### ISSUE TITLE
Fetch app attestation credential on first use

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#1661]
When a proof request requires the app attestation credential as part of it if the credential is missing then the proof should be delayed while the credential is automatically retrieved. This process should be transparent to the user. Once the credential is received the proof should be un-blocked and continue as normal. This process should be gated by "Developer" mode being enabled. If it is not enabled, and the proof is missing, the standard screen(s) should show as if any other credential was missing from a proof.

## Acceptance Criteria
- When receiving a proof request for app attestation, if there is no app attestation credential that satisfies the proof request, start the process (in the background) to get a new one
- For now, Credential Offer and Proof request will be visible to the user
- Single flow
    - Receive Proof Request
    - check if proof request can be satisfied
    - if not, start attestation
       - wait for credential offer
       - auto-accept attestation offer
       - resume to proof request
     - user can then accept/decline proof request)

## Notes
- Proof request JUST for app attestation
- Proof request WITH app attestation

**Comment by jleach** [comment]
I estimated this as a 5 because we need to make changes to the wallet, and we may need to rework the controller so that the wallet can start the process by requesting a nonce.

**Comment by jeffaudette** [comment]
![Image](https://github.com/bcgov/bc-wallet-mobile/assets/32339583/aaaf923c-9457-4867-9a81-0d4fd768c310)

**Comment by jleach** [comment]
Tested in v1.0.15 Build 1542.
