### ISSUE TITLE
Sync Bifold and BC Wallet dependencies

### ISSUE THREAD

**Issue by bryce-mcmath** [bcgov/bc-wallet-mobile#1663]
Tools that may come in handy: 
- cli.js in bifold core
- npm-check-updates

npm version carets and tildes should be removed so that Podfile generation is deterministic
All bifold packages and bc wallet should be synced as much as possible

**Comment by wadeking98** [comment]
this is resolved by the new update to bc-wallet that adds support for credo-ts
