### ISSUE TITLE
Add LCRB proof requests to dev mobile verifier templates

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1664]
### Description of feature / user story
As an LCRB inspector, I want to check the certifications of an individual so that I know if the person has the qualifications to sell or serve certain products.

LCRB want to show a demo using their test credentials. The proof requests should only be available with "development verifier templates" and "accept dev credentials" enabled 

### Acceptance Criteria
There are 3 separate proof requests that should be added only with dev templates and dev credentials enabled:

1. Person + Serving it Right
2. Person + Selling it Right
3. Person + Special Event Server

For all three proof requests request the following attributes:

**From a non-revoked Person credential**
- Given Names
- Family Name
- Photo

**From a non-revoked Serving it right/Selling it right/Special Event Server**
- Given names
- Family Name
- Certification number

List of schemas/credential definition IDs
Person
- Schema ID: Pxz2FTVZFxrx6jVvun92xW:2:Person:1.2
- Credential Definition ID: TeT8SJGHruVL9up3Erp4o:3:CL:116290:Person

Selling It Right
- Schema ID: TeT8SJGHruVL9up3Erp4o:2:LCRB:1.1.1
- Credential Definition ID: TeT8SJGHruVL9up3Erp4o:3:CL:224665:Selling It Right

Serving It Right
- Schema ID: TeT8SJGHruVL9up3Erp4o:2:LCRB:1.1.1
- Credential Definition ID: TeT8SJGHruVL9up3Erp4o:3:CL:224665:Serving It Right

Special Event Server
- Schema ID: TeT8SJGHruVL9up3Erp4o:2:LCRB:1.1.1
- Credential Definition ID: TeT8SJGHruVL9up3Erp4o:3:CL:224665:Special Event Server

http://test.bcovrin.vonx.io:3707/tx/BCOVRIN_TEST/domain/224665

### Wireframes or relevant image assets / links

**Comment by cvarjao** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BC-Wallet-6148e7423fe04b001444e2bd/issues/bcgov/bc-wallet-mobile/1664?planning-poker) with Zenhub @bryce-mcmath @jleach @wadeking98

**Comment by jleach** [comment]
Verified in 1.0.15-1452. I don't have a serving it right credential so I could not confirm they work as expected.
