### ISSUE TITLE
Update "Member Card" credential name to "Member Credential"

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1669]
### Background
LSBC has a printable credential online that is called the "Member Card". LSBC wants to change the credential name of their VC from "Member Card" to "Member Credential".

### Acceptance Criteria
- Update the credential name to "Member Credential" in their OCA bundle

Reference:
- https://github.com/bcgov/aries-oca-bundles

**Comment by jleach** [comment]
Verified in 1.0.15-1452
