### ISSUE TITLE
Explore accessing an external website using the Mobile OS "secure browser" feature

### ISSUE THREAD

**Issue by swcurran** [bcgov/bc-wallet-mobile#168]
In preparation for integrating with IDIM to authenticate and receive and Verified Person credential, please explore using the "secure browser" (e.g. browser within an app) that is available in iOS and Android to:

- [x] Click a button in the BC Wallet
- [x] Open up a simple website on the secure browser within BC Wallet
- [x] Close the browser when button on the website is hit to exit the browser

Presumably, any website can be used for testing.  I'm not sure what the "Return to BC Wallet" button on the website needs to do -- perhaps a "close window" or "close tab" action.

Once you understand the flow, please consider where this is should go in the BC Wallet stack as I think it will generally be useful. Is it an AFJ (nah...), AFJ-Ext (maybe?), Bifold or BC Wallet feature?  Obviously the specific uses of it will be BC Wallet, but should be component itself be higher up the stack?

Once this is possible in the BC Wallet, we'll be ready to use this with the IDIM flow that will be part of the wallet initialization flow.  FYI - we are likely to use this for more than just the IDIM/VP Issuance flow. For example, there might be another credential about the Wallet itself that is issued by the "Wallet manufacturer" (e.g. another BC Gov issuer -- not IDIM).

The recent VP flow wireframes demonstrated the use of this, so that is a source of more information.

Questions welcome!! @cvarjao is familiar with the "secure browser" feature in the mobile OSs, as is Marcos from IDIM.

Scope:
- Wallet connects to the issuer via DID
- Open up a secure browser as a modal, pass a connection id as argument to the URL
- Somewhere there might be a "done" or "close"  button, and then we wait for credential offer.
- Can we issue an credential without an offer?

User selects "Get Bc Digital ID", a browser pops up, issuer makes an presentation request, user accepts presentation request, goes back to browser (continue flow with some quicks), get to a done page, and ends with a credential offer.

**Comment by jleach** [comment]
Confirmed there are no issues doing this in the BC Wallet. I was able to:

1. Get a decent component installed (was originally in RN but moved to a separate package).
2. Open the WebView and get it to open a URL for display;
3. Pass a parameter from RN to said mentioned URL so we can add params to the query string as needed if BCSC needs anything. This would be processed by whatever serves up the web content;
4. Put a button on the above mentioned HTML and when I click it communicate back to RN. We can use this to either pass back (form the HTML page) any useful information to do what we like with or just close the WebView.

I don't know about this "Can we issue a credential without an offer?". Maybe ask Ian. Also I interpreted "secure browser" to mean a HTTPs connection which worked well in testing. I used ngrok to service up the page as HTTPs.


https://images.zenhubusercontent.com/429950091/d414f1e3-29eb-452d-b6df-85e68ead4cd7/webview.mov

**Comment by jleach** [comment]
@knguyenBC Do we need to communicate back to the BCSC team this is doable? Anything else to do?

**Comment by knguyenBC** [comment]
@jleach A-mazing. I'll update the people who need to know. @swcurran is probably one of them.

**Comment by marcos-carretero** [comment]
@jleach, I believe that @swcurran was referring to what I called more secure and best practice "in app browser tabs", instead of a WebView. As per, [RFC8252 OAuth2.0 for Native Apps BCP - 8.12](https://www.rfc-editor.org/rfc/rfc8252.html#section-8.12) _This best current practice requires that native apps MUST NOT use embedded user-agents to perform authorization requests._

I'm not sure of the RN support for this, but the native components are 

- iOS: [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession)
- Android [Custom Tabs](https://developer.chrome.com/docs/android/custom-tabs/)

The WorkBC mobile app demonstrates this in their login flow. There are usability and security considerations (poorer UX, better security).

**Comment by swcurran** [comment]
Sorry if there was confusion on this -- we are looking to use the "in app browser tabs" -- aka "secure browser" session.  I had thought that the only alternative to what @marcos-carretero was talking about was opening the default browser -- e.g. going outside the app and returning after.  I didn't realize that there was also the WebView option.

Obviously this was not clear enough in the task description. Sorry about that.

**Comment by marcos-carretero** [comment]
Sounds like its time for a joint design review session to hash this out, along with the parameters that we'll need on the BCSC side. :-)

**Comment by jleach** [comment]
Reading the RFC and wondering if it'll be an issue? We have no 3rd party as we're all part of the same team / org. We could fork and use our own module so we're control the code better given its a sensitive component. Maybe given this it would be an ok "crawl" phase we could expand to use the actual recommendations. We / BCSC or us jointly could develop the package.

```text
 Embedded user-agents are an alternative method for authorizing native
   apps.  These embedded user-agents are unsafe for use by third parties
   to the authorization server by definition, as the app that hosts the
   embedded user-agent can access the user's full authentication
   credential, not just the OAuth authorization grant that was intended
   for the app.
```
