### ISSUE TITLE
Add missing push notifications entitlement

### ISSUE THREAD

**Issue by bryce-mcmath** [bcgov/bc-wallet-mobile#1696]
### Description of problem
As mentioned by MG, our app is missing an entitlement for push notifications and because of that we are receiving warnings from the app store.

### Expected behavior
Full entitlements for push notifications

### Steps to reproduce
N/A

### Screenshots and/or log output
N/A

### Environment
- [ ] Occurs on Android
- [x] Occurs on iOS

Build #:
1418

Android Device Model: 
N/A

iOS Device Model: 
N/A

### Workaround
N/A

### Severity
- [ ] High
- [ ] Medium
- [x] Low

**Comment by jleach** [comment]
Verified in 1.0.15-1452
No reports (email) of this issue.
