### ISSUE TITLE
Unable to receive credential

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#170]
Wallet is stuck at “your credential is on the way” does not complete. https://openvp-candy-dev.vonx.io/issue-credential is stuck on “credential offer sent waiting for you to accept” if I cancel on the wallet, there is a vp credential in the wallet but it is not valid, does not work.

It works for Android devices. But not for iOS/iPhone devices.

**Comment by jleach** [comment]
Fixed in [219](https://github.com/hyperledger/aries-mobile-agent-react-native/pull/219). Working on getting the build working again.

**Comment by jleach** [comment]
Fixed in Build 87.
