### ISSUE TITLE
Wallet font is not BC Sans

### ISSUE THREAD

**Issue by alexgmetcalf** [bcgov/bc-wallet-mobile#171]
Font currently appears to be Helvetica Neue or similar. Needs changing to BC Sans.

**Comment by knguyenBC** [comment]
@jleach There seems to be a mix of BC Sans and a different font (not sure what it is). This is all over the app. 
![image.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/7abd28d3-b410-4977-8768-907ef435dea0)

![image.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/f7715b4c-fd05-4a60-901d-9da6aab86102)

**Comment by jleach** [comment]
@knguyenBC @alexgmetcalf @amanji Yes, it'll be left over in places we have not refactored the UI extensively by eliminating a component that really doesn't add much. One of us will need to make a pass through the app and ax all the older components. I just added the font to the wallet making it accessible to iOS and Android.

**Comment by knguyenBC** [comment]
@jleach are we iceboxing this ticket until a thorough pass through is done? This ticket is put in done but I doubled checked and it's still inconsistent in many areas.
