### ISSUE TITLE
Register App Attestation Schema

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1714]
- What agent/tenant will own it: New tenant
- Define schema v1
- Register schema in CANDY Dev, Test, and Prod

Reference:
- https://openid.net/specs/openid4vc-high-assurance-interoperability-profile-sd-jwt-vc-1_0.html#name-wallet-attestation-schema
- https://candyscan.idlab.org/tx/CANDY_DEV/domain/33510

**Comment by jleach** [comment]
Proposed v1 schema:
```json
{
  "attributes": [
    "issue_date_dateint",
    "validation_method",
    "app_version",
    "app_vendor",
    "app_id",
    "operating_system",
    "operating_system_version"
  ],
  "schema_name": "app_attestation",
  "schema_version": "1.0"
}
```

**Comment by jleach** [comment]
I've created a new Traction Dev instance and plumbed it to the CANdy-dev ledger and our deployed attestation controller. Once we agree on v1.0 of the schema (proposed above) we can publish it and this ticket can be closed.

**Comment by jleach** [comment]
Published Schemas

- [x] Dev: https://candyscan.idlab.org/tx/CANDY_DEV/domain/33557
- [x] Test: https://candyscan.idlab.org/tx/CANDY_TEST/domain/120
- [x] Prod: https://candyscan.idlab.org/tx/CANDY_PROD/domain/655
