### ISSUE TITLE
Update LCRB proof requests templates

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1716]
### Issue
LCRB has three different credentials
- Serving it Right
- Selling it Right
- Special Events Server
In the LCRB proof request templates, when a verifier is asking for one of those credentials (ex. verifier asks for the Serving it Right), the user, if they have all three types of credentials, can choose to share either of the three in the proof request. 

This may be due to the fact that the credentials share the same credential schema but have different credential IDs. 

The proofs should restrict a user to change credentials only if they're the same credential ID, not schema. 

### Steps to reproduce
- User has the Serving it Right, and Selling it Right credentials
- User scans the proof request QR code asking for the Serving it Right credential
- User has the options to change credential to the Selling it right credential

### Acceptance Criteria
- Person + Selling it Right: Accepts BC person credential AND Selling it Right credential (only)
- Person + Serving it Right: Accepts BC person credential AND Serving it Right credential (only)
- Person + Special Event Server: Accepts BC person credential AND Special Event Server (only)

### notes
- might need #1730

**Comment by cvarjao** [comment]
@knguyenBC, can they submit a PR to https://github.com/bcgov/bc-wallet-mobile/tree/proof-template-bundle?

**Comment by wadeking98** [comment]
Resolved by: https://github.com/bcgov/bc-wallet-mobile/pull/1759
