### ISSUE TITLE
Error message confusing when "Create" hit without filling out both PIN fields

### ISSUE THREAD

**Issue by swcurran** [bcgov/bc-wallet-mobile#172]
When I enter a PIN and hit create without filling in the second field, I get the error "The PIN entered must be 6 digits long" (give or take). This caused me to try several more times until I realized that the error was "The PINs do not match".  Perhaps a single message that combines both scenarios?

As I type this, boy do I feel dumb...

**Comment by WadeBarnes** [comment]
This has happened to me to.  The Create button should not be enabled until both pin fields have been filled out and contain matching strings.  Also I find the second pin field is not very obvious, it hides in the background and is easy to miss.

**Comment by cvarjao** [comment]
Fixed in build 203+
