### ISSUE TITLE
Remote logging UX | design

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1721]
### User story
As technical support, I would like to see usage logs of a user so that I can understand where the underlying issue is

### Acceptance Criteria
Given a user is experiencing an issue
And is asked by technical support to turn on remote logging
When the user enables remote logging
Then they are presented with the [remote logging](https://xd.adobe.com/view/f8350525-0d7b-4421-8606-b50ded8220fe-ad66/)
And this screen displays the Session ID
And the turn on button is only enabled when the checkbox is checked

Given the user wants to turn on remote logging
When the user turns on remote logging
Then remote logging starts
And [a static red banner is displayed underneath the header](https://xd.adobe.com/view/f8350525-0d7b-4421-8606-b50ded8220fe-ad66/screen/76c90f73-8c82-4d27-b816-0534e7503344) for that screens that lets people know that remote logging is on
And the red banner has the session ID number displayed

**Comment by knguyenBC** [comment]
To be reviewed with dev team.
