### ISSUE TITLE
Push Notification Permission Screen (dev)

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1729]
- Add notification screen as part of onboarding
- Add in the the menu to turn on/off
- Add notification screen after updating the app 

### Acceptance Criteria
Given the user has NOT been presented the notifications prompt to enable/disable push notifications
When they continue from the biometrics enable prompt from onboarding 
Then they are presented with this [Notifications screen](https://github.com/bcgov/bc-wallet-mobile/assets/68872187/de031073-c5ea-490f-b86b-b8b4e5c40484)
And tapping Continue displays the OS notifications prompt

Given the user HAS been presented the notifications prompt to enable/disable push notifications
When they tap Notifications from the menu
Then they are presented with this [Notifications screen](https://github.com/bcgov/bc-wallet-mobile/assets/68872187/49be6254-04bd-4145-b611-01700a269073)
and tapping the toggle with change the current state of the notifications

Given the user has enabled/disabled notifications from the OS level
When they tap Notifications from the menu
Then they are presented with this [Notifications screen](https://github.com/bcgov/bc-wallet-mobile/assets/68872187/fe180db6-0dfe-4bba-bf6e-f194deee5582) that informs them of how to change the notifications settings in their device settings

### Wireframes or relevant image assets / links
[Notifications permissions user flow](https://miro.com/app/board/uXjVNoMp-VI=/?moveToWidget=3458764581578015957&cot=14)

[updated onboarding flow ](https://xd.adobe.com/view/35c82052-5c29-4343-bab0-7dc84cebb129-609b/)

[updated menu
](https://xd.adobe.com/view/f239cc67-e22a-4178-84ae-4cf06b1dff23-a76a/)

**Comment by wadeking98** [comment]
Resolved by: https://github.com/bcgov/bc-wallet-mobile/pull/1858

**Comment by knguyenBC** [comment]
tested 1592 on iOS and Android, the push notification screen appears before entering your PIN. Should it not appear after? When opening an updated BC Wallet, the screens go in this particular order initialization > push notification > PIN Screen. It should go initalization > PIN screen > Onboarding updates (ex. push notifications)

**Comment by knguyenBC** [comment]
Also, the Continue button has very little padding between it and the content above. Please sure that there is always padding between buttons and other elements on the screen. Please see the style guide: https://xd.adobe.com/view/eb9e0945-61d7-40ca-8e8e-bf4bd0c72934-becd/screen/a04cb4c7-7d15-48d9-bfb1-993a47e9e8dd/

**Comment by knguyenBC** [comment]
Continue button missing accessibility label. 
Voice over also skips the "enable notifications..." header

**Comment by knguyenBC** [comment]
Change push notification toggle accessibility label from "button" to "toggle notification"

**Comment by jleach** [comment]
Fixed. Tested with 1.0.17 Build 1740. Checked on-boarding and Settings.
