### ISSUE TITLE
Onboarding carousel UX issues

### ISSUE THREAD

**Issue by alexgmetcalf** [bcgov/bc-wallet-mobile#173]
- [x] Header label should be “BC Wallet”, not “Onboarding”
- [x] On the last carousel slide, “Skip” link should be hidden
- [x] Update images to match latest designs
- [x] On the last carousel slide, remove “Learn more about BC Wallet”
- [x] On last carousel slide, add more white space between link and ‘Get Started’ button
- [x] On last carousel slide, remove exclamation mark from Get Started button text
- [x] Vertically align ‘Next’ and ‘Back’ buttons relative to the circles
- [x] Image on ‘Share only what is necessary’ looks wrong for the content; has Kim been asked about this?

**Comment by jleach** [comment]
@alexgmetcalf For this one "Text content for carousel still to be finalized" do you mean you need to work on it more or that we need to put the correct text in the app? If its the first case are you able to create a separate ticket else this one will probably sit open for site time.

**Comment by alexgmetcalf** [comment]
@jleach No, go ahead and close this and I'll raise separately, thx.

**Comment by jleach** [comment]
Moved carousel content to issue #213

**Comment by jleach** [comment]
@alexgmetcalf Done all but "Vertically align ‘Next’ and ‘Back’ buttons relative to the circles". Not sure where to go with this one. Designs and implementation look quite similar. LMK.
