### ISSUE TITLE
Home Screen UX issues

### ISSUE THREAD

**Issue by alexgmetcalf** [bcgov/bc-wallet-mobile#174]
Note: These issues only relate to the default (no credentials) state of the Home Screen, such as if just installed.

- [x] Header label should be "BC Wallet"
- [x] "You have no...." line should end in a period
- [x] 'No notifications' text should be regular weight, not bold
- [x] More space needed below notification (and before heading / "You have" line)
- [x] There is no settings icon in top-right of header
- [x] Font is not BC Sans (see separate ticket)
- [x] Margin on right side of notifications blue panel should be the same as on left side
- [x] Right margin between notification text box (e.g. containing “You have no new notifications”) and right edge of blue box should be wider, to match margin between info icon and left edge of blue box.
- [x] Top header area needs shadow onto body area

**Comment by amanji** [comment]
>Header label should be "BC Wallet"

This needs to be added at build time.

**Comment by amanji** [comment]
>Right margin between notification text box (e.g. containing “You have no new notifications”) and right edge of blue box should be wider, to match margin between info icon and left edge of blue box.

The designs show the info boxes as left aligned. Should they be centered?
