### ISSUE TITLE
Detect if the BCSC app is installed

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1750]
### Description of feature / user story
As a person getting my Person credential, I want to be able to know if I need to install the BCSC app, so that I don't have to think for myself whether or not I have it. 

In user research, we found that many people got stuck at the Person credential page in BC Wallet that described the Person credential and it's requirements. They skipped over the content specifying the requirements and tried to issue their Person credential. If they did not have their BCSC app, they would be met with an invalid URL/broken link. This would be a dead end for people as they would not have a way to move forward. 

### Acceptance Criteria
Given the user does NOT have the BCSC app installed
When they are at the Person credential screen in BC Wallet
Then they are [notified that they do not have the BCSC app installed](https://xd.adobe.com/view/1281a7c0-bab1-4d5e-989e-a6760467020d-47d2/screen/06bb0c33-a927-47ce-a4d3-90cbbc0617c7)
And that they need to download it
And there's a button to download it
And that button opens the appropriate BCSC app store.

Given the user DOES have the BCSC app installed
When they are at the Person credential screen in BC Wallet
Then they are [notified that they can create their Person credential](https://xd.adobe.com/view/1281a7c0-bab1-4d5e-989e-a6760467020d-47d2/screen/e4ad82a7-79b5-4377-a0d5-88de7af6e5e6)
And there's a button to create their Person credential
And that button starts the process to issue the Person credential (note: where that link goes depends on whether the issuance continues to use the in-app webview or changes to app-to-app)

### Wireframes or relevant image assets / links

[Person credential issue flow v3 
](https://xd.adobe.com/view/1281a7c0-bab1-4d5e-989e-a6760467020d-47d2/)

[See list of BC Wallet reccomendations
](https://ditp-bc.atlassian.net/wiki/spaces/DESIGN/pages/131661887/Summary+of+recommendations+from+Person+credential+issuance+research#BC-Wallet-recommendations)

**Comment by cvarjao** [comment]
Duplicates #1751
