### ISSUE TITLE
Update Person credential page 

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1751]
### Description of feature / user story
As someone getting my Person credential, I want the steps on how to get my person credential clearer and simpler, so that I don't have to think too hard and read through too much content so understand what I need to do next

In user research, we found that many people got stuck at the Person credential page in BC Wallet that described the Person credential and it's requirements. They skipped over the content specifying the requirements and tried to issue their Person credential. People wanted simpler instructions that told them exactly what to do. They indicated that they did not read much of the content itself and were looking actions to do. We observed people tapping on the most visually present button without understanding what they were doing.

### Acceptance Criteria
- The new UI features a clear Step 1, Step 2 process.
- The next step the user should be doing has the biggest visual presence
- Link at the bottom go to the corresponding gov.bc.ca webpages

Given the user does NOT have the BCSC app installed on this device
When they are at the Person credential screen in BC Wallet
Then as Step 1, they are shown the ["Install the app" button](https://xd.adobe.com/view/1281a7c0-bab1-4d5e-989e-a6760467020d-47d2/screen/06bb0c33-a927-47ce-a4d3-90cbbc0617c7) as the most prominent button
And that button opens the appropriate BCSC app store.
And they are shown the "I have it on another device" button that takes them to[ Step 2 screen](https://xd.adobe.com/view/1281a7c0-bab1-4d5e-989e-a6760467020d-47d2/screen/e4ad82a7-79b5-4377-a0d5-88de7af6e5e6)
And Step 2 is displayed in a medium grey 2 (#757575) 

Given the user DOES have the BCSC app installed on this device
When they are at the Person credential screen in BC Wallet
Then, as Step 2, they are shown the ["Start the process" button" 
](https://xd.adobe.com/view/1281a7c0-bab1-4d5e-989e-a6760467020d-47d2/screen/e4ad82a7-79b5-4377-a0d5-88de7af6e5e6)And that button takes them to the webview flow.
And Step 1 is greyd out in a medium grey 2(#757575) 

### Wireframes or relevant image assets / links
[Person credential page UI](https://xd.adobe.com/view/1281a7c0-bab1-4d5e-989e-a6760467020d-47d2/screen/06bb0c33-a927-47ce-a4d3-90cbbc0617c7)

[BC Wallet reccomendations](https://ditp-bc.atlassian.net/wiki/spaces/DESIGN/pages/131661887/Summary+of+recommendations+from+Person+credential+issuance+research#BC-Wallet-recommendations)

**Comment by wadeking98** [comment]
resolved by https://github.com/bcgov/bc-wallet-mobile/pull/1763

**Comment by knguyenBC** [comment]
Looks good.
