### ISSUE TITLE
Add link to credential issuance process from BC Wallet proof request

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1753]
### Description of feature / user story
As a person who has missing credentials to satisfy a proof request, I want to see a button or link to get those missing credentials, so that I can start getting them right from the wallet and not have to search elsewhere on what I need to do next.

A proof request screen that displayed missing credentials was a dead-end to people as they did not know at this point where to get the missing credential. 

### Acceptance Criteria
Given the user does not have their Person credential
When they receive a proof request asking for their Person credential
Then they are presented with a proof request with a [missing credential UI](https://xd.adobe.com/view/09c5a07e-3051-4dd6-b708-441c52319713-5c96/)
And the UI displays a "Get this credential" button that links to the start of the [Person credential issuance screen](https://xd.adobe.com/view/1281a7c0-bab1-4d5e-989e-a6760467020d-47d2/screen/06bb0c33-a927-47ce-a4d3-90cbbc0617c7/).

Given the user does not have their Member Card credential
When they receive a proof request asking for their Member Card credential
Then they are presented with a proof request with a [missing credential UI](https://xd.adobe.com/view/09c5a07e-3051-4dd6-b708-441c52319713-5c96/)
And the UI displays a "Get this credential" button that links to the [law society of BC member portal webpage](https://www.lawsociety.bc.ca/lsbc/apps/members/login.cfm)

### Wireframes or relevant image assets / links
[Wireframe of the missing credential proof request](https://xd.adobe.com/view/09c5a07e-3051-4dd6-b708-441c52319713-5c96/)

[BC Wallet reccomendations
](https://ditp-bc.atlassian.net/wiki/spaces/DESIGN/pages/131661887/Summary+of+recommendations+from+Person+credential+issuance+research#BC-Wallet-recommendations)

[Summary of research findings](https://ditp-bc.atlassian.net/wiki/spaces/DESIGN/pages/134250536/Summary+of+findings+for+Person+credential+research#Finding%3A-People-did-not-feel-confident-using-decline-action)

**Comment by knguyenBC** [comment]
I don't see these changes at all on build 1514 for both iOS and Android.

**Comment by knguyenBC** [comment]
The lsbc credential's new credential name "Member Credential" doesn't get reflected when the credential is missing in a proof request. It still states "Member Card".

**Comment by bryce-mcmath** [comment]
@knguyenBC here is a screenshot from Testflight build 1514: 

![credential_help_actions](https://github.com/bcgov/bc-wallet-mobile/assets/32586431/541a5288-4fb3-4ac3-b128-672b24bb50a6)

What steps are you taking to show this feature? I am receiving a mobile verifier proof request asking for the Lawyer Status and Photo without having either credential.

**Comment by knguyenBC** [comment]
I'm using the production court services branch website

**Comment by knguyenBC** [comment]
Tested 1546 on both iOS and Android. Links work fine. However the branding for the Member Credential isn't reflected as mentioned in previous comment. I'll create a new ticket for that issue.
