### ISSUE TITLE
Change disabled Share button to Cancel button

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1754]
### Description of feature / user story
As a user, I want a button to go back so that I'm not stuck on the proof request screen

In user research, when people were met with the proof request screen with missing credentials, they did not know where to go next. They were presented with the options to "share", which was a disabled button and "decline" which people were hesitant to tap as they thought that it cancelled their entire process. 

### Acceptance Criteria
Given a person receives a proof request asking they can't fulfill (missing or revoked)
When is in the proof request screen
Then the button is changed from "Share" to "Cancel"
and a screen appears to let people know that their information wasn't shared
and cancelling the proof request will decline the offer

### Wireframes or relevant image assets / links
https://xd.adobe.com/view/09c5a07e-3051-4dd6-b708-441c52319713-5c96/

**Comment by knguyenBC** [comment]
Update design to not disable the share button but to add additional information for why they can't share.

**Comment by cvarjao** [comment]
I think I prefer if buttons visibility are always consistent. I think this might create some confusion while troubleshooting as they might be seeing different things depending on the state

**Comment by knguyenBC** [comment]
tested on Android and iOS build 1636. Looks good.
