### ISSUE TITLE
Add links to gov.bc.ca Person pages on Person credential screen

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1758]
### Background/User Story
As a user who received an offer to Get their Person credential in their BC Wallet, I want to know what the Person credential is, so that I can learn more on what it is, where I can use it and find help if I have any issues trying to get it.

### Acceptance Criteria
Given a user has started the Person credential issuance process in BC Wallet
When they are at the [Person credential issuance page in BC Wallet](https://xd.adobe.com/view/50a1d463-0698-4584-a7eb-dfd5ca17be90-05f2/)
Then they are given the option to learn "What is a Person credential"
And they are given the option to contact "Help"

Links will take the user to an external weblink to Person credential gov.bc.ca pages
These links are TBD.

### Wireframes
https://xd.adobe.com/view/50a1d463-0698-4584-a7eb-dfd5ca17be90-05f2/

**Comment by knguyenBC** [comment]
@knguyenBC Add the prod URLs to the ticket of the person and contact information

**Comment by bryce-mcmath** [comment]
@knguyenBC are we worried about giving users options to navigate away from BC Wallet while attestation is in progress?

**Comment by knguyenBC** [comment]
That's actually a really good point. Maybe hold this feature until we figure out how to minimize the "loading" time.
