### ISSUE TITLE
New device security onboarding screen

### ISSUE THREAD

**Issue by alexgmetcalf** [bcgov/bc-wallet-mobile#176]
There is a new wireframe available for the device security onboarding screen. It's based on feedback from the testing sessions. It requires some minor adjustments to the current text content, the image size, and the number of available buttons (the update has fewer buttons).

**Comment by cvarjao** [comment]
@alexgmetcalf, can you update the ticket with a link to the wireframes?

**Comment by alexgmetcalf** [comment]
@cvarjao this is superceded by the work Kim's done in the meantime, so this can be closed
