### ISSUE TITLE
Release 1.0.15

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#1770]
Test 1.0.15 Build 1514

- [x] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [ ]  LSBC Test Environment
    - [x]  LSBC Prod environment
    - [ ]  Accessibility: Voice Control, Labels
    - [ ]  Get Person Credential with BCSC App
- [ ] Automated testings are passing
- [x] Mobile Verifier with Default and Dev Mode settings
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [ ] Single Device experience using showcase (deep linking)
- [ ] Use names/values supporting Indigenous Languages
- [ ] Upgrade from 1.0.14 -> 1.0.15

Change notes:
```text
TBD
```

**Comment by jleach** [comment]
**Work-in-Progress**

Test 1.0.15 Build 1514 on iOS

- [x] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [x]  LSBC Test Environment
    - [ ]  LSBC Prod environment
    - [x]  Accessibility: Voice Control, Labels
    - [x]  Get Person Credential with BCSC App
- [x] Automated testings are passing (Confirmed by Shel)
- [x] Mobile Verifier with Default and Dev Mode settings
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [x] Single Device experience using showcase (deep linking)
- [x] Use names/values supporting Indigenous Languages
- [x] Upgrade from 1.0.14 -> 1.0.15

**Notes**
- Automated tests confirmed by Shel
- ACM works fine but I cannot pass the proof because of a credential name mismatch "User Login Failed
No Permission - The Verifiable Credentials name "Francis Goodxxxxxx (mc123XX|VC|XX)" does not match the BC Person ID name "Jason Leach". An administrator must confirm the names to enable login."
- To test Indigenous languages I installed the "Cowlitz Salish Keyboard" on iOS and was able to enter and send messages using characters from that keyboard.
- Went through the app with voice control and interacted with the Student demo on the showcase.

**Comment by nodlesh** [comment]
Automated Regression tests for iOS are passing. 
Automated Regression tests for Android are Cancelling in the highly regression. However, the last non-cancelled run was with build 1581 and was normal.

**Comment by bryce-mcmath** [comment]
Test 1.0.15 Build 1598 on iOS
- [x] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [x]  LSBC Test Environment
    - [ ]  LSBC Prod environment
    - [x]  Accessibility: Voice Control, Labels
    - [x]  Get Person Credential with BCSC App
- [x] Automated testings are passing (Android tests haven't run in a while but iOS have and are passing)
- [x] Mobile Verifier with Default and Dev Mode settings
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [x] Single Device experience using showcase (deep linking)
- [ ] Use names/values supporting Indigenous Languages
- [ ] Upgrade from 1.0.14 -> 1.0.15 (**FAILED**)

Test 1.0.15 Build 1598 on Android
- [x] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [x]  LSBC Test Environment
    - [ ]  LSBC Prod environment
    - [ ]  Accessibility: Voice Control, Labels
    - [x]  Get Person Credential with BCSC App
- [x] Automated testings are passing (Android tests haven't run in a while but iOS have and are passing)
- [x] Mobile Verifier with Default and Dev Mode settings
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [x] Single Device experience using showcase (deep linking)
- [ ] Use names/values supporting Indigenous Languages
- [ ] Upgrade from 1.0.14 -> 1.0.15 (**FAILED**)

**Notes**
- The "enter pin" screen seems to get put on the navigation stack twice in quick succession (it slides over the previous screen twice). It's not very noticeable or a big issue but still. Here's a video of it happening: 
https://github.com/bcgov/bc-wallet-mobile/assets/32586431/3e6d8af5-8c0d-4468-98f1-4d3bdad77052
- The text on the connection screen eg. "Credential added to your wallet" seems to be bold now but I don't remember if it used to be
- When upgrading from a previous 1.0.15 version, the new terms and push notifications screens showed up as expected, but when upgrading from 1.0.14 auth fails with an 'incorrect walletId' error message
- On Android, after scanning a valid QR code, the camera screen can kind of appear "stretched" horizontally. Not sure what causes that

**Comment by knguyenBC** [comment]
Test 1.0.15 build 1598

**Android**
- [x] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [X]  LSBC Test Environment
    - [x]  LSBC Prod environment
    - [X]  Accessibility: Voice Control, Labels. **FAIL**: missing accessibility label on continue button on the push notification screen
    - [X]  Get Person Credential with BCSC App
- [ ] Automated testings are passing
- [x] Mobile Verifier with Default and Dev Mode settings
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [x] Single Device experience using showcase (deep linking)
- [x] Use names/values supporting Indigenous Languages
- [x] Upgrade from 1.0.14 -> 1.0.15

**iOS**
- [x] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [x]  LSBC Test Environment
    - [x]  LSBC Prod environment
    - [X]  Accessibility: Voice Control, Labels. **FAIL**: missing accessibility label on continue button on the push notification screen
    - [X]  Get Person Credential with BCSC App
- [ ] Automated testings are passing
- [x] Mobile Verifier with Default and Dev Mode settings
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [x] Single Device experience using showcase (deep linking)
- [x] Use names/values supporting Indigenous Languages
- [x] Upgrade from 1.0.14 -> 1.0.15. FAIL. AskarWalletL incorrect key for wallet 'walletid' error when upgrading appstore version to testflight version

**Comment by bryce-mcmath** [comment]
Test 1.0.15 build 1603

**iOS**
- [x] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [x]  LSBC Test Environment
    - [ ]  LSBC Prod environment (Clecio tested)
    - [X]  Accessibility: Voice Control, Labels. **PASS**: missing labels have been added
    - [X]  Get Person Credential with BCSC App
- [ ] Automated testings are passing
- [x] Mobile Verifier with Default and Dev Mode settings
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [x] Single Device experience using showcase (deep linking)
- [x] Use names/values supporting Indigenous Languages
- [x] Upgrade from 1.0.14 -> 1.0.15. **PASS**

I'm confident in this release from an iOS perspective but my Android device (personal phone) is acting up so I'm not able to thoroughly test with it. Found no issues on Android emulator

**Comment by jleach** [comment]
Test 1.0.15 build 1603

**Android**
- [x] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [X] LSBC Test Environment
    - [ ]  LSBC Prod environment
    - [X] Accessibility: Voice Control, Labels. 
    - [X] Get Person Credential with BCSC App
- [ ] Automated testings are passing
- [x] Mobile Verifier with Default and Dev Mode settings
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [x] Single Device experience using showcase (deep linking)
- [x] Use names/values supporting Indigenous Languages
- [x] Upgrade from 1.0.14 -> 1.0.15

**iOS**
- [x] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [x] LSBC Test Environment
    - [ ] LSBC Prod environment
    - [ ] Accessibility: Voice Control, Labels. 
    - [x] Get Person Credential with BCSC App
- [ ] Automated testings are passing
- [x] Mobile Verifier with Default and Dev Mode settings
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [x] Single Device experience using showcase (deep linking)
- [x] Use names/values supporting Indigenous Languages
- [x] Upgrade from 1.0.14 -> 1.0.15

**Comment by knguyenBC** [comment]
Test 1.0.15 build 1603

**Android**
- [x] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [X]  LSBC Test Environment
    - [x]  LSBC Prod environment
    - [X]  Accessibility: Voice Control, Labels.
    - [X]  Get Person Credential with BCSC App
- [ ] Automated testings are passing
- [x] Mobile Verifier with Default and Dev Mode settings
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [x] Single Device experience using showcase (deep linking)
- [x] Use names/values supporting Indigenous Languages
- [x] Upgrade from 1.0.14 -> 1.0.15
- [x] push notifications

**iOS**
- [x] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [x]  LSBC Test Environment
    - [x]  LSBC Prod environment
    - [X]  Accessibility: Voice Control, Labels. **FAIL**: missing accessibility label on continue button on the push notification screen
    - [X]  Get Person Credential with BCSC App
- [ ] Automated testings are passing
- [x] Mobile Verifier with Default and Dev Mode settings
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [x] Single Device experience using showcase (deep linking)
- [x] Use names/values supporting Indigenous Languages
- [x] Upgrade from 1.0.14 -> 1.0.15. 
- [x] push notification 

Note: the T&C update and push notifications should appear AFTER the Enter PIN screen. See #1841 for intended order of screens. But...not a blocker.
