### ISSUE TITLE
Proof request "missing credentials" content is inconsistent

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1776]
### Issue
Proof request screens when asking for missing credentials is inconsistent. 

When the proof request is asking for a predicate and the user does not have the credential, the content above the listed missing credentials (...is requesting the following information from n credentials) is overwritten with the content that usually appears if the user does not meet the requirements (you do not meet the requirements of this proof request from...."

### Fix
The message that appears when requirements are not met should be consistent, no matter if the reason is due to:
- predicates/ZKP not met,
- revoked credentials
- missing credentials

### Wireframes
https://xd.adobe.com/view/e27e2aee-9293-4a8a-9b8b-456c41d9550c-b72d/

Given the holder receives a proof request they cannot fulfill
When they open the proof request
Then an error notification appears informing people that they are unable to respond due to the following reasons
And they are presented with credentials that they are missing, revoked, and/or where requirements aren't met
And the share and decline buttons are replaced with a Cancel button

### Screenshots
[screenshot showing the proof request when asking for credentials the user does not have](https://github.com/bcgov/bc-wallet-mobile/assets/68872187/4570b8ab-7d60-4c4c-8359-9efed28b358e)

[screenshot showing a proof request when asking for a predicate AND credentials the user does not have](https://github.com/bcgov/bc-wallet-mobile/assets/68872187/266c896f-f025-45fd-b075-d35d30323c49)

**Comment by bryce-mcmath** [comment]
Not sure why this ticket is in QA, it still seems reproducible and I haven't seen any PRs related to it. I have a potential fix, but I'll wait until tomorrow to see if it's not needed

**Comment by knguyenBC** [comment]
The message is consistent however the wireframes included an additional warning message "you can't respond due to the following reasons..."

**Comment by bryce-mcmath** [comment]
Oh oops, I didn't see that. I'll add that quick

**Comment by knguyenBC** [comment]
Looks good.
