### ISSUE TITLE
Missing credential layouts (OCA)

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1779]
### Description of problem
It was reported that the credential layouts have stopped working, and the credentials were being displayed without any branding.
It happens on 2 phones. For 1 of them, it got fixed after restarting the phone.

### Expected behavior
Credentials to be formatted as expected

### Screenshots and/or log output
![missing-oca](https://github.com/bcgov/bc-wallet-mobile/assets/1348549/ed0b089a-ef71-4853-b1c9-816856d2eac2)

### Environment
- [ ] Occurs on Android (not reported)
- [x] Occurs on iOS

Build #: 1418

Android Device Model: 

iOS Device Model: 
iOS 17.3

### Severity
- [ ] High
- [x] Medium
- [ ] Low

**Comment by wadeking98** [comment]
@cvarjao I'm wondering if we can get this person using remote logging so that we can troubleshoot because I'm not able to reproduce the issue
