### ISSUE TITLE
Invalid QR code scan error has poor colour contrast

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#178]
When scanning an invalid QR code, the error message appearing does not match the design. The text should be white to ensure proper colour constrast.

**Screenshot of prototype**
![20220224_163931.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/7c5917d3-4d76-404a-ad36-1f01d889b2ec)

Wireframes
![image.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/f1ba0a67-36d9-4336-a9f3-15f4d40df7f4)

**Comment by cvarjao** [comment]
@knguyenBC , can you please provide a screenshot?

**Comment by knguyenBC** [comment]
@amanji The error message is still black text on iOS. Android looks fine. I tested build 125 for iOS. Oddly enough, the most updated version I have for android is build 117.
