### ISSUE TITLE
Refactor ProofRequestDetails screen to use CredentialCard and OCA

### ISSUE THREAD

**Issue by bryce-mcmath** [bcgov/bc-wallet-mobile#1781]
### Description of feature / user story
Currently the screen a user sees before they send a template proof request (`ProofRequestDetails.tsx`) doesn't make use of OCA or the Credential Card component. For consistency, it should.
  
### Acceptance Criteria
As a user of the mobile verifier templates
When I get to the Proof Request Details screen and issuer_did or cred_def_id is defined
I should see [OCA branding on CredentialCard components](https://xd.adobe.com/view/0a112c19-6f28-48cd-8ba6-3d80c7cd3771-5f42/screen/49b99799-19ae-40c7-a830-a44f7cfaa29f/)

As a user of the mobile verifier templates
When I get to the Proof Request Details screen and NO OCA bundle found
I should see the credential Name, and attributes name as non human format

As a user of the mobile verifier templates
When I get to the Proof Request Details screen and NO issuer_did or cred_def_id is defined
I should see the [credential Name, and attributes name as defined (generically) by the schema](https://xd.adobe.com/view/0a112c19-6f28-48cd-8ba6-3d80c7cd3771-5f42/screen/5e0ea247-8230-427c-82fc-0daf7584f20c/)

### Wireframes or relevant image assets
What it looks like currently:
![Image](https://github.com/bcgov/bc-wallet-mobile/assets/32586431/0d217d26-5dab-4b6f-b56d-c48b7662ec6b)

**Comment by jleach** [comment]
Fixed. Tested with 1.0.17 Build 1740 w/ Lawyer Status + Photo proof.
