### ISSUE TITLE
Update build SDK version of BC Wallet for iOS

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#1787]
Update the BC Wallet (and Bifold) SDK version as per the following:

```text
Hello,

We noticed one or more issues with a recent delivery for the following app:

  *   BC Wallet
  *   Version 1.0.15
  *   Build 1527

Although delivery was successful, you may want to correct the following issues in your next delivery. Once you've corrected the issues, upload a new binary to App Store Connect.

ITMS-90725: SDK version issue - This app was built with the iOS 16.2 SDK. Starting April 29, 2024, all iOS and iPadOS apps must be built with the iOS 17 SDK or later, included in Xcode 15 or later, in order to be uploaded to App Store Connect or submitted for distribution.

Apple Developer Relations
```

**Comment by jleach** [comment]
This needs to be changed via the CICD build mechanics. We need to be building with Xcode 15 which will have the proper SDK. Currently the GitHub runner `macos-latest` ships with xcode 14:

```console
Run xcode-select -p
/Applications/Xcode_14.2.app/Contents/Developer
```

As per the [docs](https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job) `macos-14` which should have xcode 15 (and the correct SDK) version is currently beta. I think I'll move this back to the "ready" and give that a few more weeks to come out of beta. If not we can manually change the runner from  `macos-latest` to  `macos-14` to fix this issue.

**Comment by cvarjao** [comment]
We would need to switch to `macos-13` (or `macos-14` which is still beta) as `macos-latest` is still based on `macos-12`:

https://github.com/actions/runner-images?tab=readme-ov-file#available-images
https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode

**Comment by jleach** [comment]
Looks like they did update the version in macos-13 as per [these docs](https://github.com/actions/runner-images/releases/tag/macos-13%2F20231218.2). I'll see about selecting it.
