### ISSUE TITLE
Unable to get Person Credential from Android

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1795]
There is a problem on Android devices where repeatedly fetching the Person credential fails after the first time.

**Steps to Reproduce**

On an Android device, with the BC Wallet & BCSC Apps installed which has not issued a Person credential before do steps 1-3. If you have an Person credential skip to step 2.

1. Issue yourself a Person credential, on a device with the BCSC app installed;
2. Remove it, keep the connection to IDIM. Just remove the VC;
3. Issue yourself another Person credential on the same device.

**Blocks**

- #1770

**Comment by jleach** [comment]
Making notes here. I was able to get the Person credential on my Android test device but I have BCSC on my iPhone so I used a pairing code. Will try the way you describe later but I'll have to see about moving my BSCS card over or maybe test with the "Dev" version.

**Comment by jleach** [comment]
I can reproduce this on Android 14 Pixel 7a. I'm still digging into why it impacts Android and not iOS. It appears to be because, when multiple connections with the same invitation exists, AFJ (Credo) selects the "first one" which does not seem to be sorted in chronological order and as such results may vary between iOS and Android depending on the backing store. I can fix the problem on Android if I sort the connections chronologically and choose the most recent connection.


This screen shot iterates the results of fetching the connections on both Android and iOS. Based on the dates they're not in chronological order so the "first" may vrry:

![Image](https://github.com/bcgov/bc-wallet-mobile/assets/390891/b45448ab-51bd-459a-8fd1-8e28c10508d2)

**Comment by jleach** [comment]
I have conducted some tests and it seems that sorting the connections may not be the issue. However, I will run one more test to confirm. On Android, if I repeat the process and always decline the credential, the process never hangs. However, if I accept a credential at any point, then remove it and repeat the process, it always fails. The last message in the logs is always 'Failed to process revocation notification message' and I need to restart the app to complete the workflow. On iOS, the process always works and the next log message is 'WebSocket message event received.' This never happens on Android, even though the WebSocket seems to be working fine. On Android, can immediately go to the Showcase and get a student card without having to restart the app.

**Comment by jleach** [comment]
Several of us are working from the office today and the problem seems to have remedied itself. All devices that failed yesterday are working on both Android 13 and 14. All versions, 1.0.15 and 1.0.14 tested and working fine repeatedly.

**Comment by jleach** [comment]
Problems again today with users working from home on various networks (LTE / 5G / TELUS / Shaw):

I can reproduce the problem reliably on LTE. I did notice that to trigger it, I always have to start with removing an existing credential. If after restarting the app 2x to clear the issue and get my offer I "decline" that credential, the next time I do the test it works fine. The only real difference I can think of in this scenario is that in the first case there is a credential to revoke; on the 2nd case there is none. Maybe the revocation message is causing the issue. But why the app needs to be restarted 2x, each time getting 1 new message from the mediator is a mystery. I'll check the mediator logs.

In addition. I can reproduce this on 1.0.14 and 1.0.15-1538. But, I have two Pixel phones side-by-side and one works and one fails repeatedly. 🤷‍♂️

More testing required but this appears in the log at approximately the same time as a failure:

```
2024-02-23 19:26:43,067 aries_cloudagent.transport.inbound.ws ERROR Unexpected Websocket message type received: WSMsgType.CLOSED: None, None
2024-02-23 19:26:50,243 aries_cloudagent.transport.inbound.ws ERROR Unexpected Websocket message type received: WSMsgType.CLOSED: None, None
2024-02-23 19:26:52,578 aries_cloudagent.core.conductor WARNING Cannot queue message for delivery, no supported transport
2024-02-23 19:26:52,859 aries_cloudagent.core.conductor WARNING Cannot queue message for delivery, no supported transport
2024-02-23 19:26:53,335 aries_cloudagent.core.conductor WARNING Cannot queue message for delivery, no supported transport
2024-02-23 19:27:07,967 aries_cloudagent.transport.inbound.ws ERROR Unexpected Websocket message type received: WSMsgType.CLOSED: None, None
2024-02-23 19:27:11,014 aries_cloudagent.transport.inbound.ws ERROR Unexpected Websocket message type received: WSMsgType.CLOSE: 1000,
```

**Comment by jleach** [comment]
After a few days of testing by the team these are some more observations:

- This issue does not happen the first time a Person credential is issued.
- Removing all connections to IDIM seems to fix this issue.
- This issue can be triggered by using the BCSC on the device with BC Wallet or from another device using a pairing code.
- Repeating the process but continuously declining the credential does not trigger this issue. The credential must be accepted for this problem to surface.
- Leaving the credential in the wallet and just issuing a second credential does not impact this issue. It persists regardless of the previous credential(s) being removed or not.
- If the wallet is restarted, each time the wallet restarts one additional messages is received from the mediator: After the first message a BasicMessage is receive from IDIM indicating that the credential was revoked. After the second restart the offer is finally received.
- Waiting several minutes for the messages / offer to arrive does nothing.
- Following a failure, immediately returning to the home screen and working through a "Showcase" demo scenario works as expected.
- Tester B was able to receive the messages by backgrounding the app. This is not consistent behaviour for other testers.
- Tester A was able to consistently reproduce this issue on Pixel 8 but on a Pixel 7A the problem does not present itself. 
- Using the Pixel 8, Tester A was able to races through getting the credential in under 15 seconds the problem does not present itself. This is not consistent behaviour among other testers who race through to acquire a credential.
- Using the Pixel 7A, Tester A was able to wait 30 seconds in the BCSC application and trigger this issue.
- This problem presents itself on various devices with various Android versions 12, 13 & 14; Samsung and Pixel phones.
- This issue can be reproduced in the current production 1.0.14 release and next (1.0.15 releases)
- This issue may temporarily resolve for some users then appear some time in the future (overnight)
- Switching to use different mediators has no impact on this issue.
- This issue does not impact iOS.
- Stopping and starting mediator message pickup has no impact on the delivery of subsequent messages.
- The last message in the logs appears to be receiving the revocation notification. This notification exists in "Notifications" when returning to the home screen.
```JSON
 LOG  INFO :
{
  "message": "Processing revocation notification v1",
  "data": {
    "message": {
      "@type": "https://didcomm.org/revocation_notification/1.0/revoke",
      "@id": "8e2abd1b-ee2d-41ad-b513-8c54954a3234",
      "thread_id": "indy::RGjWbW1eycP7FrMf4QJvX8:4:RGjWbW1eycP7FrMf4QJvX8:3:CL:13:Person:CL_ACCUM:f954f297-07cd-444a-ba9b-96a126297ef2::1449",
      "comment": "Reason: You chose to issue yourself a new credential, and that revokes all your previous credentials."
    }
  }
}
 LOG  TRACE :
{
  "message": "Getting record by query for revocation notification:",
  "data": {
    "anonCredsRevocationRegistryId": "RGjWbW1eycP7FrMf4QJvX8:4:RGjWbW1eycP7FrMf4QJvX8:3:CL:13:Person:CL_ACCUM:f954f297-07cd-444a-ba9b-96a126297ef2",
    "anonCredsCredentialRevocationId": "1449",
    "connectionId": "0969a9cb-e000-4a11-8b7c-01f1bfac16c1"
  }
}
 LOG  TRACE :
{
  "message": "Emitting RevocationNotificationReceivedEvent"
}
```

**Comment by jleach** [comment]
Tested with several team members. Working well now.
