### ISSUE TITLE
App does not take you to Credential List screen after an accepted credential offer

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#180]
After accepting a credential offer, the app takes me to the credential detail screen of the accepted credential. It should take me to the credential list screen and show the accepted credential at the top

**Comment by cvarjao** [comment]
@knguyenBC, is that he behavior we want to implement? Whenever something is added to a list, it takes tot he list as opposed to the new item added?

**Comment by knguyenBC** [comment]
I believe that's the appropriate behaviour. Seeing their credential alongside their other credentials really helps communicate that the process is done as they can see the "card" in the wallet. I think there's value in displaying the credential detail so that people can review the contents but they also just saw the same information as they were accepting it and I'm concerned that people will be stuck thinking there's more to do.
