### ISSUE TITLE
Enable Push Notification for the build

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1802]
- update build environment variable

**Comment by knguyenBC** [comment]
tested 1592 on iOS and Android, the push notification screen appears before entering your PIN. Should it not appear after? When opening an updated BC Wallet, the screens go in this particular order initialization > push notification > PIN Screen. It should go initalization > PIN screen > Onboarding updates (ex. push notifications)

**Comment by knguyenBC** [comment]
The above comment is better suited for ticket #1729 . I'll close this on and add the above to that ticket.
