### ISSUE TITLE
Missing non-production watermark in credential details screen

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1805]
### Background
People are unable to tell if the credential is a demo/test credential from the credential details screen or proof request screen.

### Acceptance Criteria
Given the credential is a non-production credential
When the user is in a proof request or credential details screen
Then the watermark should be present in the credential card UI

### Wireframes
https://xd.adobe.com/view/045a1969-719a-4aa5-848f-637ef1b7051a-5109/screen/6f5562f2-088c-49df-9db5-47dadafa852d/

**Comment by knguyenBC** [comment]
@jleach checked iOS and Android build 1576, the watermark isn't present in the credential details screen.

**Comment by jleach** [comment]
@knguyenBC  I can see them in 1.0.15 1594.

**Comment by knguyenBC** [comment]
Tested 1598 on iOS and Android, watermark is on the details screen
