### ISSUE TITLE
Aspect ratio distorted after first scan on Android

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#1806]
There is an issue with the camera aspect ratio on Android devices after scanning the first QR code. To reproduce this issue, please follow these steps:

1. Close and restart the Android app.
2. Open the camera and view some items. Everything should appear normal.
3. Scan a QR code.
4. Open the camera again and view some items. The aspect ratio will now be incorrect.
5. Scan another QR code. The code will scan correctly, but the image will appear distorted.

![Image](https://github.com/bcgov/bc-wallet-mobile/assets/390891/2ffa33a5-f8fb-4e51-aa0a-7edd6659d2c9)

**Comment by cvarjao** [comment]
unable to reproduce. It may have been indirectly fixed.
