### ISSUE TITLE
LSBC new credential name doesn't get reflected when the credential is missing in proof request

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1832]
### Issue
The lsbc credential's new credential name "Member Credential" doesn't get reflected when the credential is missing in a proof request. It still states "Member Card".

Odd as it's correctly depicted everywhere else. 

Build 1546 on iOS and Android

### Screenshots

![Image](https://github.com/bcgov/bc-wallet-mobile/assets/68872187/70df5ed5-d6a1-46da-86dc-3dc892432b08)

### Acceptance Criteria
- OCA Bundle Matching Priority: cred_def_id, schema_id + issuer_did, schema_id, <default bundle>:
    ```
    cred_def_id
    schema_id:issuer_did
    schema_id
    ```
- Change how aries-oca-bundles generates `ocabundles.json`
- Change bifold/OCA to implement the priority/fallback lookup defined above

**Comment by bryce-mcmath** [comment]
Fixed in 1.0.18
