### ISSUE TITLE
Unable to present revocable credential

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#184]
Steps to reproduce:
1. Run the ACA-py faber demo with revocation enabled
1. Issue a credential
1. Send Proof Request
![signal-2022-02-28-100717.png](https://images.zenhubusercontent.com/5c75a872bb88ef3edd6c33ec/2caa54e5-6b5f-4301-bb6a-5304be932cd1)

**Comment by amanji** [comment]
Issue arises if a tails server is not setup. Please consult documentation at: https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/AliceGetsAPhone.md#run-an-instance-of-indy-tails-server and https://github.com/bcgov/bc-wallet-mobile/discussions/206
