### ISSUE TITLE
single invitation can be used to connect multiple times

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1840]
- investigate if the invitation URL/QR Code is actually single use
  - same device, or different devices
- investigate if the connection is improperly reaching 'active' state

**Comment by knguyenBC** [comment]
Tested build 1567. Behaviour works as intended. But I can still scan the used QR code with a different device and successfully create a connection.

**Comment by jleach** [comment]
@knguyenBC I think that's expected behaviour for a muti-use invitation. If that's not the intended behaviour then its probably not a BC Wallet bug but ACA-py or whatever is generating the invitation URLs.
