### ISSUE TITLE
Update EULA

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1841]
- Update [EULA content (v2)](https://docs.google.com/document/d/1PW2WLkSsGi0hEBq0IgrurCHNkyXpNkRu?rtpof=true&usp=drive_fs)
- Add new EULA after user updates the app and user can re-accept ("What's new flow")
   - Present the whole new EULA with a banner that just says "something has been updated"

### Wireframes and flows
[Onboarding updates flow](https://miro.com/app/board/uXjVNoMp-VI=/?moveToWidget=3458764581307802305&cot=14)

![Image](https://github.com/bcgov/bc-wallet-mobile/assets/68872187/ada97292-eff2-4d47-af9b-dd0b374b7e04)

### Acceptance Criteria
- [ ] The terms is displayed on fresh install
    - [ ] The checkbox is removed
    - [ ] Rename button from "Continue" to "Accept"
- [x] The terms is displayed after updating the app with an updated terms
    - [x] The checkbox is removed
    - [ ] The is an info alert/notification communicating to the user there's an updated T&C
- [ ] The "Accept" button is always shown in the bottom and there is a little fading to indicate that there is scrollable text
- [ ] The text and paragraph formatting as displayed in the word document linked above is the same (bold, links, paragraph styles, etc.)
- [ ] Version and date updated is included
- [ ] Onboarding Screen Order:
   1. Enter PIN (existing install only)
   1. Is this App For you (fresh install only)
   1. Carrousel (fresh install only)
   1. EULA (fresh install or updated)
   1. Create PIN (fresh install only)
   1. Biometrics (fresh install only) 
   1. Push Notification (fresh install, or haven't seen this feature)
   1. Name Your Wallet (fresh install, or haven't seen this feature - still in dev mode)

**Comment by knguyenBC** [comment]
Just want to call out the spelling mistake in the Terms of use update alert. It currently states "...please **reveiw** and accept the updated terms."
