### ISSUE TITLE
🐛[Bug] - Unable to exit remote logging screen selection

### ISSUE THREAD

**Issue by esune** [bcgov/bc-wallet-mobile#1844]
### Description of problem
When entering the view to enable remote logging from the developer options, it is not possible to back out - the only option is to close the app and start over.

### Expected behavior
It should be possible to go back to the previous screen without enabling remote logging, if desired, by hitting the "back" gesture and/or a dedicated UI control.

### Steps to reproduce
- Open BC Wallet
- After enabling "developer options", turn on the switch for "remote logging"
- Try to back out of the screen without enabling remote logging

### Screenshots and/or log output
N.A.

### Environment
- [X] Occurs on Android
- [ ] Occurs on iOS: unsure, don;t have an iOS device to test with

Build #: 1561

Android Device Model: Pixel 6 Pro

iOS Device Model: N.A.

### Workaround
Use the task manager to kill the BC Wallet app and reopen it.

### Severity
- [ ] High
- [ ] Medium
- [X] Low

**Comment by cvarjao** [comment]
This might have been fixed in recent update, we can'r replicate it. Please re-test it and feel free to re-open

**Comment by esune** [comment]
Tested on 1.0.16 (1625) on Android and now there is a control to go back to the previous screen. Thanks!
