### ISSUE TITLE
Enable Person credential for general availability

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1849]
Right now you need an LSBC or Invitation credential for the "Get your person credential" mechanics to activate. We will need to remove this requirement in 1.0.15 to make the Person credential generally available.

### Acceptance Criteria
- Anyone with BC Wallet app (fresh or updated) can see "Get your person credential" if it hasn't been dismissed
- App Attestation feature toggle removed from dev mode

**Comment by knguyenBC** [comment]
1.0.16. Works as expected on both iOS and Android.
