### ISSUE TITLE
Canceling does not cancel the credential offer

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#185]
During a credential offer, when I accept a credential offer, and then cancel the offer, I'm taken back to the credential offer screen with the approve button disabled. When I leave to go back to home, and check the credential list, the credential is still added to the wallet. 

The app should behave is described in the Acceptance criteria of ticket #83. 

note: I believe the feature is still in the backlog. I would remove the button altogether until the feature functions correctly.

**Comment by cvarjao** [comment]
#83 has not been implemented yet.
