### ISSUE TITLE
Inconsistent Credential Rendering between verifier and holder view

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1856]
Related to ticket #1778 & #560. 

### Acceptance criteria
- Ensure credential issuer is visible
- credential name is consistent
- formats are consistent
- 

The verifier sees:
<img src="https://github.com/bcgov/bc-wallet-mobile/assets/1348549/f6aa6c1e-3697-4b75-a4af-bfa7a786fb4b" width="200" />
<img src="https://github.com/bcgov/bc-wallet-mobile/assets/1348549/ca6b1b43-b211-49f8-aa04-d55e80c4a3f4" width="200" />

The holder sees:
<img src="https://github.com/bcgov/bc-wallet-mobile/assets/1348549/3e9cb26b-6e20-473d-bf9b-702ede8e8e72" width="200" />
<img src="https://github.com/bcgov/bc-wallet-mobile/assets/1348549/0a1db128-277f-4810-ab76-97e21e430ab1" width="200" />

**Comment by knguyenBC** [comment]
Credentials names are consistent. Issuer names appear even when credential is not available, dates are consistent.
