### ISSUE TITLE
Enter PIN screen gets mounted twice on app open

### ISSUE THREAD

**Issue by bryce-mcmath** [bcgov/bc-wallet-mobile#1864]
### Description
When the app is first opened (after onboarding has been completed) the Enter PIN screen appears to be mounted twice. See below:
https://github.com/bcgov/bc-wallet-mobile/assets/32586431/43361685-cb8f-42b5-a607-92e2b7a7b921

**Comment by knguyenBC** [comment]
Works as intended. Tried on iOS and Android v 1.0.16 build 1636.
