### ISSUE TITLE
Watermark on credential cards are missing or are not visible

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1866]
- Missing watermark on credential card UI for Student Card.
- Watermark on LSBC Member Credential is almost transparent. It's really hard to see. 
- The watermark on the person credential seems to overlap each other where the darker blue is (horizontal part).

**Comment by jleach** [comment]
Fixed, confirmed in 1.0.17 1740. See screenshot. Watermarks seem Ok.


![Image](https://github.com/bcgov/bc-wallet-mobile/assets/390891/ca48399e-5aa4-4177-8a6f-4b61842ee82f)
