### ISSUE TITLE
Share button disabled in proof request with correct credentials

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1870]
### Issue
A few lawyers are experiencing a proof request screen where they see a disabled share button despite having the correct credentials. Lawyer has tried to uninstall and reinstalled the app a few times and that did not work.

Affects app store build 1.0.15

**Comment by knguyenBC** [comment]
Had a call with a lawyer and they seem to have all the necessary credentials. She declined to use remote troubleshooting and would rather wait for the new release of the BC Wallet in the hopes that it fixes their issue.

**Comment by cvarjao** [comment]
Unable to get a hold of reporter. We can reopen if we get new reports
