### ISSUE TITLE
Wait for sending presentation before opening WebView

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1887]
- Connect to IDIM
- Wait for up to 10s for App Attestation Proof Request, if received
   - If App attestation credential is available and can be used on the app attestation proof request
   - Otherwise, we start app attestation proceed, wait for app attestation credential, and present app attestation credential
  - Present app attestation credential
- Display BCSC Authentication WebView

### Acceptance Criteria
Could I suggest the following AC:
Given than the user is on the Person Credential Issuance flow
When the user taps on "Start Process"
Then user sees a "Please wait as we get things ready for you"
And a Cancel button (?)

**Comment by knguyenBC** [comment]
Could I suggest the following AC:
Given than the user is on the Person Credential Issuance flow
When the user taps on "Start Process"
Then user sees a "Please wait as we get things ready for you"
And a Cancel button
