### ISSUE TITLE
Identify App Attestation Performance/Speed bottlenecks

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1894]
- identify bottlenecks: create private keys, validating app attestation, issuing/accepting credential

Future work:
- pre-request app attestation credential when app startup

**Comment by jleach** [comment]
I've texted dozens of times triggering attestation from Traction via a test script causing both the prod and a dev version to fetch an attestation credential. It usually completes in ~10 seconds.

**Comment by bryce-mcmath** [comment]
Some test data has been collected and formatted now that logging has been updated. Sheet located here: https://docs.google.com/spreadsheets/d/1jIHR3WvOiJFfxKjcJ8rWiS_sFeniOFzGIOBaVmGM4xQ/edit?usp=sharing
