### ISSUE TITLE
OCA for credentials from SIT environment do not have the "non production" watermark

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1896]
It might be just a simple update to the OCA Bundle for SIT environment
review all Person Credential bundle that are non-production (DEV/SIT/Showcase)

**Comment by jleach** [comment]
Fixed, confirmed in 1.0.17 1740.



![Image](https://github.com/bcgov/bc-wallet-mobile/assets/390891/185676de-f17d-4599-a50e-5a61212f69dd)
