### ISSUE TITLE
Restarting the person workflow not always successful

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#1901]
When starting, then abandoning the Person credential workflow, subsequently restarting the process does not always work correctly.

**Steps to Reproduce**

Android 1.0.16 1636, Pixel 8

1. Press the "Start the process" button;
2. Go back (X in upper left)
3. Press the "Start the process" button;

Step 3 above will intermittently show the "The link is not valid" error screen shown in the last screen shot.

![Image](https://github.com/bcgov/bc-wallet-mobile/assets/390891/624a754e-1430-4a7b-9604-9f3bc7dba6e2)

![Image](https://github.com/bcgov/bc-wallet-mobile/assets/390891/73a87713-625d-490c-9b37-f75c5e466926)

![Image](https://github.com/bcgov/bc-wallet-mobile/assets/390891/1a697166-61c9-4a02-b6d7-e1aedb014d91)

**Comment by jleach** [comment]
Reported by Lucas.

**Comment by jleach** [comment]
Assigning to me. Will test reliability after #1986 is merged. This will be after 1.0.17 is shipped.

**Comment by jleach** [comment]
Fixed in #1986

**Comment by bryce-mcmath** [comment]
Can no longer reproduce this issue, closing
