### ISSUE TITLE
Error "Timeout has occcured" appears when trying to open BC Wallet 1.0.16

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1910]
**Issue**
People are unable to get into their BC Wallet after updating the app to 1.0.16. They receive an error message "Timeout has occured" 

### Steps to reproduce
- The app was installed from the app stores
- opened the app, followed the steps (EULA, notifications, PIN etc.)
- quit the app and launch again
- Asked for PIN or Biometrics
- Shows initialization
- then fails

### Screenshot
![Image](https://github.com/bcgov/bc-wallet-mobile/assets/68872187/0522bc71-debb-48c7-ad22-b4561642ba42)

### Affected devices
iOS users so far
- iPhone 14, iOS 17.3.1
- iPhone 12 iOS 17.1.1

Version
App store version (1.0.16 build 1636)

**Comment by jleach** [comment]
Emiliano reported something similar. Hey was getting a timeout and I was able to reproduce it on both iOS and Android. Then everything started working again. My though is there was some issue with the infrastructure. Maybe DNS or the mediator. I watched the firewall on my end for traffic to the mediator and saw there was no connection being opened. Then after a while it just started working.

**Comment by jleach** [comment]
Just tested on iOS. BC Wallet 1.0.16 1636 and I was able to get my person credential.

**Comment by knguyenBC** [comment]
tested on my iPhone 12, updating the app from .15 to .16. everything worked fine.

**Comment by knguyenBC** [comment]
Lawyer experiencing the issue on their iPhone 12 has their issue magically resolved as well. However the other person who flagged the issue is still having the same problem.

**Comment by jleach** [comment]
Fixed, tested in build 1.0.17 Build 1740
