### ISSUE TITLE
Mobile verifier holders app crashes when scanning QR code

### ISSUE THREAD

**Issue by aaunger** [bcgov/bc-wallet-mobile#1916]
### Describe the problem
Mobile Verifier was used to complete a connectionless proof request 'over 19 years of age' and the holders app crashes. 

### Expected behavior
Proof request is successful, and the holders application completes the process successfully. 

### Steps to reproduce
1. Verifier opens mobile verifier with build 1636
2. Selects over 19 years of age
3. verifier presents QR code to holder
4. Holder opens BC Wallet and opens camera with build 1636
5. Holder scans QR code

Verifier: iPhone 14 Pro Max
Holder/Prover:  iPhone 14 Pro

### Screenshots and/or log output
Video attached
https://github.com/bcgov/bc-wallet-mobile/assets/38864896/7b0d55de-712c-49e9-ab82-e620e9e3d96c
https://github.com/bcgov/bc-wallet-mobile/assets/38864896/4447a081-c442-4aa3-a80c-06c18d0dc445

### Environment
- [ ] Occurs on Android
- [X] Occurs on iOS

Build #: 1636

Android Device Model: N/A 

iOS Device Model: Unknown

### Workaround
None known

### Severity
- [ ] High
- [X] Medium
- [ ] Low

### Related Issues
- #1943

**Comment by jleach** [comment]
Looking into this one. Just confirming which was the device that actually crashed.

**Comment by jleach** [comment]
Confirmed the crash occurred on the iPhone 14 Pro.

**Comment by jleach** [comment]
Tested several times with 1.016-1636 with an iPhone 14 Pro (iOS 17.4.1) as the holder/provider and an iPhone X, Pixel 7a and 8 as the verifier. All worked as expected with an age 19+ proof.

**Comment by jleach** [comment]
I'm going to close this issue for now since it appears to be working. I'll update the person who noted the bug and let them know to LMK if it occurs again or next time they're at the office and we can test with their defice.
