### ISSUE TITLE
Timeout error occurs periodically causing the app to fail to start

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#1917]
The BC Wallet intermittently times out. This was reported by a wider team member yesterday, by another user today as well as Google Play automated testing. 

@bryce-mcmath noted the issue appears to occure between [step 5 and 6](https://github.com/bcgov/bc-wallet-mobile/blob/8921fbd14f27fd88b2fdc3e5a0c77c6fb2fc36ef/app/src/screens/Splash.tsx#L379) of the app initialization.

The following screen captures were reported by Google Play automated testing.

![Image](https://github.com/bcgov/bc-wallet-mobile/assets/390891/cfc77eb9-cb53-40bc-8517-d395ecbeeb2e)

**Comment by jleach** [comment]
Something to keep an eye on is it was reported ~2pm today and yesterday. Worth noting if this happens at a specific time of the day.

**Comment by jleach** [comment]
If I keep re-installing the app I can somewhat reliably get delay where it is sending device info to the mediator. Presumably this is for push notifications. Notice the timestamp on the right. I wonder if this delay gets to 30+ seconds it causes the "Timeout" error.

![Image](https://github.com/bcgov/bc-wallet-mobile/assets/390891/1d89395a-b853-421c-a8a0-ed9b8ca2bddf)

**Comment by jleach** [comment]
Issue occurred about about 9:15-9:30 today April 15th. Production Android showed issue. Harder to reproduce in dev setup. Issue occurs after ~20 seconds.

**Comment by jleach** [comment]
Issue occurred about about 9:15-9:30 today April 15th. Production Android showed issue. Harder to reproduce in dev setup. Issue occurs after ~20 seconds. I was able to reproduce on iOS 1.0.16-1636 from the App Store. I was also able to reproduce on 1.0.15-1607 previous app store release. 


When the problem occurs on my dev setup I can see the connection to the mediator in the firewall. Each time I "retry" a new connection to the mediator is created but the connection times out. The network status `FIN_WAIT_2:ESTABLISHED` hints that there is something odd going on:

**FIN_WAIT_2**: This state means that the device has received an acknowledgment of its termination request (the FIN packet it sent) from the remote device but is still waiting for the remote device to finish sending its data.

**ESTABLISHED**: This indicates that the connection is still open and data can continue to be sent and received. This side of the connection has not initiated a close and has not received a FIN packet from the remote endpoint.

![Image](https://github.com/bcgov/bc-wallet-mobile/assets/390891/856373f6-882d-4980-b713-9b76aa7796d2)

**Comment by bryce-mcmath** [comment]
After some investigating and adding some logging in AFJ, I found the timeout originates at the end of the `getMediationConnection` method. It gets stuck here: https://github.com/openwallet-foundation/credo-ts/blob/eb2c51384c077038e6cd38c1ab737d0d47c1b81e/packages/core/src/agent/Agent.ts#L247

This aligns with the 20 seconds before timeout that we have been experiencing as well: https://github.com/openwallet-foundation/credo-ts/blob/eb2c51384c077038e6cd38c1ab737d0d47c1b81e/packages/core/src/modules/connections/services/ConnectionService.ts#L883-L884

**Comment by jleach** [comment]
Resolved by bcgov/openshift-aries-mediator-service/#39

**Comment by jleach** [comment]
Resolved by bcgov/openshift-aries-mediator-service#39
