### ISSUE TITLE
Viewing a credential causes messages to become out of order

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#1918]
Viewing a revoked person credential causes the message sort order to be come out of order as the "offer" messages seems to have its timestamp updated. This process can be repeated, each time the "offer" will be updated and appear as the last message. This does not, as far as I can tell, impact a non-revoked Person credential. I don't know if it impacts all credentials that are revoked or just person credentials that are revoked.

https://github.com/bcgov/bc-wallet-mobile/assets/390891/075d86e8-51f7-43ca-99ab-f11553bc813d

**Comment by bryce-mcmath** [comment]
Possibly caused by credential metadata being updated when the revocation notice is seen on the `CredentialDetails` screen, which in turn causes the `CredentialExchangeRecord.updatedAt` property being changed (and thus the position of the CER changing in `Chat` screen)

**Comment by bryce-mcmath** [comment]
Tested in the latest build, not happening anymore
