### ISSUE TITLE
Update Serving It Right MV proof for Pilot

### ISSUE THREAD

**Issue by krobinsonca** [bcgov/bc-wallet-mobile#1921]
### Description of feature / user story
For the existing Serving it Right MV proof, the following changes are required for the pilot:
1. Add the Expiry_Date from the Training Certificate Credential (bonus: would be nice to mark it RED or something to indicate if expiry_date is in the past. We do NOT want a restriction though. We want the verifier to know what the expiry date value is.
2. Change the cred_def restriction to be the Production Issuer "LCRB" for the training credential - value of this will come from @esune 

### Acceptance Criteria
Proof request and result should contain Expiry Date for Certificate
Proof should be restricted to only accept production Person credential issued from IDIM and production Training Certificate credential issued from LCRB

### Wireframes or relevant image assets / links
N/A

**Comment by knguyenBC** [comment]
Task assigned to Credivera

**Comment by krobinsonca** [comment]
This is the file to update: https://github.com/bcgov/bc-wallet-mobile/blob/proof-template-bundle/proof-templates.json
