### ISSUE TITLE
Person credential offer isn't sent after webapp 

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1923]
### Description of problem
Every now and then, when getting the Person credential, after returning to BC Wallet (after tapping the "Create Person credential" from the webapp), the offer doesn't appear. The "Start the process" button is enabled and tapping on it produced an invalid link error on the webapp. 

The solution is to close the app and try again and it works a second time.

### Expected behavior
The offer should appear automatically.

### Steps to reproduce
- Get the Person credential as normal
- After tapping "Create Person credential" and the app goes back to the wallet app
- the offer isn't received

### Environment
- [X] Occurs on Android
- [ ] Occurs on iOS

Build #: 1648

Android Device Model: Google pixel 8

iOS Device Model: 

### Severity
- [ ] High
- [X] Medium
- [ ] Low

### Acceptance Criteria
- Wallet should check if the connection is fully ready/established before opening webview
   - Maybe we send a [ping](https://github.com/hyperledger/aries-rfcs/blob/main/features/0048-trust-ping/README.md) message and wait for a response
- Check if this is related to attestation proof not being completed

**Comment by jleach** [comment]
Confirmed. I see this sometimes also but I cannot reliably reproduce it. Will watch for it.
