### ISSUE TITLE
Share/Load Invitation URL

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1929]
At the moment, we can only connect 2 wallets by scanning a QR Code from the camera.
An alternative way it to let users Copy/Paste/Share the invitation URL

#### Consuming the URL/Pasting a URL
Given the holder has copied a URL to either connect, receive a proof request or credential offer
When the holder taps the "paste a URL" button (represented by a link icon)
Then they are presented with the "Paste a URL" screen
And they can paste the URL via the OS's keyboard
And When the holder pastes the URL into the text area
Then the 'Continue' and 'Clear' button changes from disabled to active/enabled

Given the holder has pasted a proper DIDComm URL into the text area
When the holder taps 'Continue'
Then the holder will be presented with a loading screen
And then the holder will be presented with the appropriate screen that the URL was meant for (proof request, connection, credential offer)

Given the holder has NOT pasted a proper DIDCom URL into the text area
When the holder taps 'Continue'
Then the holder will be presented with a "URL not recognized" error message
And be given the option to try again
And When the holder taps try again
Then they are moved back to the 'Paste a URL' screen

Given the holder has NOT pasted a URL
When the holder taps 'Continue'
Then the holder will be presented with a "Textbox empty" error message
And be given the option to try again
And When the holder taps try again
Then they are moved back to the 'Paste a URL' screen

#### Sharing a URL
Given the Holder wishes to share a connection invitation or proof request
When the holder taps the "Share URL" (represented by a 'Share' icon)
Then they are presented with the OS's app selection drawer
And When they select an option to share via the OS's app share drawer
Then a the URL is shared via the chosen app

### Wireframes or relevant image assets / links
[For dev  mode specs](https://www.figma.com/file/mfUqAvZIeOsgxPqWTTp0SU/BC-Wallet-app?type=design&node-id=89%3A71&mode=dev)

Flows
- [Paste URL](https://www.figma.com/proto/mfUqAvZIeOsgxPqWTTp0SU/BC-Wallet-app?type=design&node-id=238-1095&viewport=669%2C-308%2C0.54&t=4UabjU4UpA0wtGog-0&scaling=scale-down&starting-point-node-id=238%3A1095&show-proto-sidebar=1)
- [Share connection QR code](https://www.figma.com/proto/mfUqAvZIeOsgxPqWTTp0SU/BC-Wallet-app?type=design&node-id=89-72&viewport=669%2C-308%2C0.54&t=4UabjU4UpA0wtGog-0&scaling=scale-down&starting-point-node-id=89%3A72&show-proto-sidebar=1)
- [Share proof request](https://www.figma.com/proto/mfUqAvZIeOsgxPqWTTp0SU/BC-Wallet-app?type=design&node-id=284-810&viewport=669%2C336%2C0.54&t=4UabjU4UpA0wtGog-0&scaling=scale-down&starting-point-node-id=284%3A810&show-proto-sidebar=1)

### Related Issue(s)
- #1930

**Comment by knguyenBC** [comment]
Wireframes added

**Comment by wadeking98** [comment]
resolved by https://github.com/openwallet-foundation/bifold-wallet/pull/1173

**Comment by knguyenBC** [comment]
Getting a connection or proof via URL take a lot longer than scanning the QR code. 
I had thought that the feature didn't work so closed the phone. The BC Wallet got a push notification but the notification list was empty. Realized that there was a push notification for a successful connection.
