### ISSUE TITLE
Buttons in the credential offer are incorrectly aligned

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#193]
The accept and decline buttons should be aligned to the bottom of the screen.
- It is not absolute fixed at the bottom
- ergonomically accessible if not enough content to scroll

### Prototype screenshot (wrong)
![20220301_144407.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/12498e41-073d-4344-ba23-5c4c67561c8b)

### Wireframes (correct)
![image.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/5418381e-55a2-4298-bd22-ba62656a4e56)

**Comment by cvarjao** [comment]
Giving how the app is organized and implemented, It is currently difficult to implement.

**Comment by amanji** [comment]
Blocked by https://github.com/hyperledger/aries-mobile-agent-react-native/issues/386

**Comment by bryce-mcmath** [comment]
The bottom tabs have been removed from this view but it's quite finicky to get the buttons to stick to the bottom if there isn't a full screen of content but still be scrollable if there is. It's also a rare case that there isn't enough content to fill the screen so in the interest of prioritizing I've closed this ticket.
