### ISSUE TITLE
Unable to decline/delete proof request from mobile verifier

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1943]
### Steps to reproduce
1) Phone 1 creates an ephemeral proof request
2) Phone 2 scans QR Code from phone 1
3) Phone 2 closes app (without accepting/declining)
4) Phone 2 opens app and see the proof request in the home screen
5) User tried to decline/delete proof request from home screen (error here)

### Environment
- [x] Occurs on Android
- [x] Occurs on iOS

Build #:

Android Device Model: 

iOS Device Model: 

### Severity
- [ ] High
- [x] Medium
- [ ] Low

**Comment by wadeking98** [comment]
Think this may be the same issue as the cred delete issue caused by credo. What's the error message?

**Comment by jleach** [comment]
Fixed, confirmed in 1.0.17 1740 w/ Practicing Lawyer proof. Killed app, saw proof in home screen. Was able to decline it.
