### ISSUE TITLE
Wallet gets stuck on "Verifying onboarding" after background timeout

### ISSUE THREAD

**Issue by bryce-mcmath** [bcgov/bc-wallet-mobile#1950]
### Description
When an existing wallet is backgrounded / unused and locks the user out, unlocking causes it to get stuck on "Verifying onboarding" splash screen step. Closing and reopening the app is a interim fix

![Image](https://github.com/bcgov/bc-wallet-mobile/assets/32586431/990106c0-7cb4-4ca2-8e36-798973a1a29c)

Build: 1673

**Comment by loneil** [comment]
Another note on this case. If my BC Wallet app is in the sate where it would trigger this stuck condition, then attempting to log in with a VCAuthN environment with a deep link will trigger this error in the wallet.

![image](https://github.com/bcgov/bc-wallet-mobile/assets/17445138/d0f3bf00-ba5c-4fad-8c3e-9aa21980d0b3)

**Comment by bryce-mcmath** [comment]
Still investigating this.

The bug seems to rear it's head in a variety of ways. Sometimes it has the behaviour above, other times it skips the lockout and reopens the app with either socket or closing wallet error (both unhandled promise rejections.)

**Comment by jleach** [comment]
Fixed, tested in build 1.0.17 Build 1740.
