### ISSUE TITLE
Gibberish characters when receiving/presenting credentials without OCA

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1951]
### Screenshots

![Image](https://github.com/bcgov/bc-wallet-mobile/assets/1348549/ffd7b18e-fc3a-4ed1-a298-301795773ba4)

**Comment by bryce-mcmath** [comment]
I just tried to reproduce this using an unbranded credential issued from my dev Traction and it seems to have been fixed, no jumbled characters. Moving to QA for now

**Comment by jleach** [comment]
Fixed, confirmed in 1.0.17 1740 w. Showcase credentials.
