### ISSUE TITLE
Cannot get Person Credential (stalls at Step 2) again after deleting.

### ISSUE THREAD

**Issue by loneil** [bcgov/bc-wallet-mobile#1954]
### Description of problem

I deleted my Person Cred and when to re-add it I get it stalling at Step 2. 

If I back out or close/reopen the app I see the Attestation cred offer(s). Multiple offers if I repeat the steps.
Note I have dev mode on so that's why I see the offer(?)

Trying to manually accept attestation errors out

### Expected behavior

Should go on to open my BCSC app

### Steps to reproduce

- Remove Person Cred (note I ran into https://github.com/bcgov/bc-wallet-mobile/issues/1952, but the cred did delete)

- Use prompt to re-add person cred

- Wait at step 2 for a while and then close and reopen app when it does nothing

- On app open, see the Attestation offer

- Go in and accept Attestation offer, error

- Use Person Cred prompt again, repeat loop, see another attestation offer.

### Screenshots and/or log output

![image](https://github.com/bcgov/bc-wallet-mobile/assets/17445138/8e778de9-fed2-4225-9c33-81c5533e2897)

![image](https://github.com/bcgov/bc-wallet-mobile/assets/17445138/9fa81776-887d-4fef-82b4-fd7d569fa6e0)

![image](https://github.com/bcgov/bc-wallet-mobile/assets/17445138/2611ea01-5cd7-4f8a-b2df-e068190163d9)

![image](https://github.com/bcgov/bc-wallet-mobile/assets/17445138/e33fe825-814c-47ae-b20e-073169514baa)

![image](https://github.com/bcgov/bc-wallet-mobile/assets/17445138/f340464d-fde8-4a49-ba6f-09bdd90c639a)

### Environment
- [x] Occurs on Android
- [ ] Occurs on iOS

Build #:

**1676**

Android Device Model: 

**Pixel 8**

iOS Device Model: 

### Severity
- [ ] High
- [ ] Medium
- [ ] Low

**Comment by loneil** [comment]
After accepting the Attestation cred, with the error, I **can** get through Step 2 of the person cred flow.
Not sure if this has anything to do with my attempting to accept the Attestation cred or not, or something ephemeral happened.

But when going through the BCSC flow and authorizing successfully there I now get this error coming back:

![image](https://github.com/bcgov/bc-wallet-mobile/assets/17445138/84370999-6653-4ef9-9eba-ebd0288970a1)


It **did** revoke my Person Cred on my iPad (other device I had the cred on) as part of this.

**Comment by loneil** [comment]
I ended up on this state on my iPad on **1636** as well. Could not get past Step 2 (spinning and not prompting for BCSC app login or anything).

The case on the iPad was that I'd had the cred revoked, removed it and tried to get it again as well.

Uninstalling and Reinstalling the BC Wallet app allowed me to proceed on the iPad and get the cred successfully.

I tried to reproduce this case on the iPad by revoking (through id.gov.bc.ca), removing, and re-adding, but it worked fine that time. So I'm not sure what state it was in when failing right before that...

Android Phone remains in broken state at this time. Can't get Person Cred on it and have not re-installed app yet.

**Comment by esune** [comment]
I see this error also with a different Credential (LCRB SIR on CANdy Test): I receive the offer, but get an error when I try to accept it.
![Media](https://github.com/bcgov/bc-wallet-mobile/assets/2395873/23ecacf7-381b-413d-8116-4ff97b22fe36)

**Comment by bryce-mcmath** [comment]
I believe this issue is fixed by the same PR that addressed #1966 , moving to QA

**Comment by jleach** [comment]
Fixed in 1.0.17 Build 1740
