### ISSUE TITLE
defect(1.0.17): unable to enter PIN after session/idling timeout

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1967]
### Steps to reproduce
- Fresh install with Biometrics disabled
- background the app and wait for at least 5min
- The PIN textbox is disabled, and I am unable to enter PIN

NOTE: it works if biometrics is enabled

### Environment
- [ ] Occurs on Android (no problem with Android)
- [x] Occurs on iOS

Build #: 1692

Android Device Model: 

iOS Device Model: 

### Severity
- [ ] High
- [ ] Medium
- [ ] Low

**Comment by bryce-mcmath** [comment]
@cvarjao the only way I can repro this is by having a modal open when I background the app. Can you check if this happens for you with / without a modal open? Trying to determine if there's a separate problem that I can't repro

**Comment by bryce-mcmath** [comment]
we've decided to put this one on the backburner for now as it only happens when a modal is open

**Comment by bryce-mcmath** [comment]
@cvarjao just to confirm, this is still happening sometimes with the current main? any specific way to repro?

**Comment by cvarjao** [comment]
Yes, it sill happening in some undetermined conditions. The timeout is so long that I keep forgetting.

**Comment by cvarjao** [comment]
I had it happening very frequently yesterday ... I haven't got a single one today (build 1847)
