### ISSUE TITLE
defect(1.0.17): Unable to enter PIN after foregrounding app when biometrics is enabled

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1968]
### Environment
- [x] Occurs on Android
- [ ] Occurs on iOS 

Build #:

Android Device Model: 

iOS Device Model: 

### Severity
- [ ] High
- [ ] Medium
- [ ] Low

**Comment by bryce-mcmath** [comment]
I cannot reproduce this one exactly, with or without a modal being open, but I do notice that the cursor for the PIN flickers in this situation. (It still allows me to type my PIN in and stops flickering after the first character is entered.) I can try to fix the flickering and see if that fixes the original issue for those affected but for now I will move on to another ticket.

**Comment by jleach** [comment]
WFM on a Pixel 8. What I do:

- Open the app, background it for 5+ minutes 
- Cover my camera, open the app so that biometrics fails
- When it fails, I enter my PIN
- Press the unlock button and I'm propelled into the app as expected

**Comment by knguyenBC** [comment]
This worked fine for me (pixel 8, build 1892). I had:
- opened BC Wallet
- opened up another app, and waited 5 minutes for BC Wallet to timeout
- covered my front camera, opened BC Wallet
- cancelled biometrics
- typed in my PIN (cursor was flickering)
- got in

**Comment by bryce-mcmath** [comment]
Closing as it doesn't seem to be reproducible anymore
