### ISSUE TITLE
Credentials in the wallet are not revoking

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1969]
### Description of problem
When revoking a credential, the wallet does not:
- display a notification that the credential has been revoked
- it does not update the card UI
- Went used in a proof request, the card UI doesn't update, allowing the user to continue to share information

The credential is revoked but the wallet doesn't seem to properly receive that information.
This affects the Member Card and Person credential.

### Expected behavior
When a credential is revoked, the status of the credential should be updated immediately 

### Steps to reproduce
- Get a person credential
- revoke the credential by getting a new one in a different device
- use the credential in a proof request

### Environment
- [X] Occurs on Android
- [X] Occurs on iOS

Build #: 1692

Android Device Model: Google pixel

iOS Device Model: 

### Severity
- [x] High
- [ ] Medium
- [ ] Low

**Comment by loneil** [comment]
I tried the same credential from the same tenant and revoked the same way and:

iPad on 1636: revokes fine ✅ 

Android on 1692: no revocation shown ❌ 


Rev reg entries for these 2 revocations

![image](https://github.com/bcgov/bc-wallet-mobile/assets/17445138/b831cdd1-5faa-4b26-8e39-fc3207533929)

**Comment by cvarjao** [comment]
still happening on build 1707

**Comment by jleach** [comment]
Fixed. Tested in 1.0.17 1740 with Showcase Lawyer example.
