### ISSUE TITLE
Person credential is displayed in a proof request even when the wallet does not have a person credential 

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1971]
### Description of problem
When the Person credential is not in your wallet and you receive a proof request asking for a Person credential, a person credential is displayed (without OCA) with correct information. 

You're able to share information and the wallet displays that the information is shared successfully.

Clearing cache did not work.

### Expected behavior
If the wallet does not have the correct credentials, it should not be displayed in a proof request. Unsure how the proof request is displaying information that shouldn't exist as well.

### Steps to reproduce
- Wallet app originally had the Person credential that was then removed from the wallet
- Receive a proof request that asks for a Person credential
- Share the information

### Screenshots and/or log output

[video of the issue](https://photos.google.com/share/AF1QipM0hSBgPcY8GbNrMKyNoEiW1VSVOH0FJHo79bdr7FsgaHoMAWFRCFGFTYqxJJsh8w/photo/AF1QipOD99cCGS_3LKjdR1RZLU1kFiJNX6N8yJcGfuUg?key=TFRGb1l3Q012a25QS3FROGFhdWF5NlhRWGRHdGxR)

![Image](https://github.com/bcgov/bc-wallet-mobile/assets/68872187/ce7802fc-33c4-4830-a621-91f534e01156)

### Environment
- [X] Occurs on Android
- [ ] Occurs on iOS

Build #: 1692

Android Device Model: Pixel 8

iOS Device Model: 

### Workaround
Clear storage (essentially uninstalled the app)

### Severity
- [X] High
- [ ] Medium
- [ ] Low

**Comment by jleach** [comment]
Assigning to @bryce-mcmath as his work on another ticket might fix this one also.

**Comment by wadeking98** [comment]
I checked and I wasn't able to reproduce this using showcase credentials on latest from main

**Comment by bryce-mcmath** [comment]
Still happens with credentials issued in 0.4.2

**Comment by jleach** [comment]
Fixed, tested with 1.0.17 1740 w/ Showcase lawyer credentials. Had credential, deleted it, shown as missing in proof request.
