### ISSUE TITLE
Sharing information through the mobile verifier, verifier received "proof request declined"

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1972]
### Description of problem
When receiving a proof request through the mobile verifier, and sharing the information successfully, on the verifier's screen, they receive "Proof request declined, Proof verification failed" screen

### Expected behavior
When sharing information and the information was sent successfully, the verifier should receive the information sent.

### Steps to reproduce
- Enable mobile verifier for both devices
- One device using the app store build, the other with the latest build
- Device with latest build sends proof request
- Device with app store build share's information

### Screenshots and/or log output
![Screenshot_20240503-101719](https://github.com/bcgov/bc-wallet-mobile/assets/68872187/75364ef6-01ab-41f1-b813-c7051485f5ea)

### Environment
- [X] Occurs on Android
- [ ] Occurs on iOS

Build #: 1692

Android Device Model: Pixel 8

iOS Device Model: 

### Severity
- [X] High
- [ ] Medium
- [ ] Low

**Comment by jleach** [comment]
I've tested 1.0.16 to 1.0.16 and things work as expected. Sending a proof works. I think this may be related to 1.0.17 (holder) to 1.0.16 (verifier). This will probably work itself out when we get some updates to fix other verifier issues like [1973](https://github.com/bcgov/bc-wallet-mobile/issues/1973). I'll keep the ticket open for retesting but for now there is nothing to be done.

@wadeking98 @bryce-mcmath FYI.

**Comment by jleach** [comment]
Confirmed this is still an issue with 1.0.17 1744 (tested on iOS 1.0.17 1744 as verifier, Android 1.0.16 as holder)

**Comment by bryce-mcmath** [comment]
Issue has been debugged and findings are with the Credo team. We may not be able to have backwards compatibility for the verifier this release. Putting in icebox for now

**Comment by jleach** [comment]
@bryce-mcmath Able to share the root cause? Any update?

**Comment by bryce-mcmath** [comment]
@jleach unfortunately there is a backwards compatibility issue that causes 1.0.16 and before to not work with 1.0.17 and after. I haven't been able to repro this issue when both wallets are 1.0.17 or above
