### ISSUE TITLE
Unable to share information using the mobile verifier

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1973]
### Description of problem
When sharing information using the mobile verifier, An error 1027 appears. This error appears for the test and prod member card and test person credential (so far). 

### Steps to reproduce
- Get a credential
- Receive a proof request requesting said credential
- Send the information over

### Screenshots and/or log output

![Screenshot_20240503-102230](https://github.com/bcgov/bc-wallet-mobile/assets/68872187/bbc8301d-87b1-4926-96d0-3a33fa90876e)

### Environment
- [X] Occurs on Android
- [ ] Occurs on iOS

Build #: 1692

Android Device Model: pixel 8

iOS Device Model: 

### Severity
- [x] High
- [ ] Medium
- [ ] Low

**Comment by cvarjao** [comment]
Still happening on build 1707

**Comment by jleach** [comment]
@cvarjao I think [this error](https://github.com/search?type=code&q=org%3Ahyperledger+%22Schema+not+provided+for+ID%3A%22) comes from one of our shared rust libraries. I'll see if I can track down where in credo it is being called. 

Cc: @wadeking98

**Comment by jleach** [comment]
Fixed in 1.0.17 1744. Tested on iOS w/ Practicing Lawyer credential.
