### ISSUE TITLE
Firebase mediator plugin not including devicePlatform in PN toggle response

### ISSUE THREAD

**Issue by bryce-mcmath** [bcgov/bc-wallet-mobile#1976]
### Description of problem
The firebase mediator plugin isn't including the `devicePlatform` in it's response to the message to turn on / off notifications. It doesn't seem to cause any problems with notifications being sent but it does cause an error message in the BC Wallet logs.

### Expected behavior
Device platform is included and there are no error logs.

### Steps to reproduce
Toggle notifications in BC Wallet

### Screenshots and/or log output
`Error validating message undefined`
`devicePlatform must be a string`

### Environment
- [x] Occurs on Android
- [x] Occurs on iOS

Build #:
1650 and later

### Workaround
N/A (notifications still work)

### Severity
- [ ] High
- [ ] Medium
- [x] Low

**Comment by jleach** [comment]
Fixed in hyperledger/aries-mediator-service#163

**Comment by bryce-mcmath** [comment]
Used the latest main BC Wallet with the dev mediator (where these changes have been deployed) and there is no longer any error messages related to push notifications. Nice
