### ISSUE TITLE
OCA not getting picked up for credentials issued in AFJ (Credo) 0.4.2

### ISSUE THREAD

**Issue by bryce-mcmath** [bcgov/bc-wallet-mobile#1993]
### Description

Credentials that have an associated OCA bundle appear unbranded in Credo 0.5.3 if they were issued in AFJ 0.4.2

This is likely due to unqualified identifiers being converted to qualified identifiers. So the fix should be backwards compatible so that both old and new `aries-oca-bundles` entries are respected. Preference should be given to qualified identifiers as those will be newer.

**Comment by jleach** [comment]
Fixed, tested with 1.016 -> 1.0.17 1740 w/ Showcase credentials.
