### ISSUE TITLE
Review and normalize how we handle deep links and scanning

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1996]
### Description
Deeplink handling has some pieces that are not included in the scanning handling, and scanning handling has some pieces that are not included in deeplink handling. To normalize and cleanup, and then test with all the different methods is a decent amount of work. Estimating as a 5.

Added to this ticket: Show a 'show details' as part of the scanner error message 'Invalid QR code' that shows the root error message and add support for `_oob` query param handling. Check if changes fix vc authn deeplinking issues

Related issues:
- https://github.com/bcgov/bc-wallet-mobile/issues/1956

**Comment by jleach** [comment]
Closing. No actionable items to test. Related ticket fixed.
