### ISSUE TITLE
Recommend users to update the app when there is a new version

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#2006]
Given that the user has the app installed
When there is a new version release
   and the user opens the app
   and has unlocked the app
Then the users sees a message/popup informing of a new version and recommending update

Given that there's a new version release
When the user skips the message informing of a new version and recommending update
Then a persistent banner appears in the menu
   and tapping on that banner will take the user to the appropriate app store

### Reference

**UX resources**
- [user flows](https://miro.com/app/board/uXjVNoMp-VI=/?moveToWidget=3458764581307802305&cot=14)
- [wireframes](https://www.figma.com/design/mfUqAvZIeOsgxPqWTTp0SU/BC-Wallet-app?node-id=2946-2933&t=tq0wvehE3IWllOYi-1)

**Dev resources**
- https://github.com/tschoffelen/react-native-check-version
- https://github.com/kimxogus/react-native-version-check

**Comment by knguyenBC** [comment]
Added user flow for updates to new app.

**Comment by knguyenBC** [comment]
Design is complete. Dev ticket is available.
