### ISSUE TITLE
Get a deeplink error message when getting Person credential

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#2007]
### Description of problem
When attempting too get Person credential on version 1.0.17 build 1740 on an android device, after tapping "Create Person credential" from id.gov.bc.ca and returning to the BC Wallet app, a deep linking error appears.

Dismissing the error will eventually display the credential offer and everything works smoothly.

### Expected behavior
no error.

### Steps to reproduce
- Get you person credential on v 1.0.17 build 1740

### Environment
- [x] Occurs on Android
- [ ] Occurs on iOS

Build #:

Android Device Model: Google Pixel 8

iOS Device Model: 

### Severity
- [ ] High
- [x] Medium
- [ ] Low

**Comment by jleach** [comment]
Tested in iOS and Android 1.0.17 1744 (tested on iOS). iOS was Test env while Android was Prod. Both Ok.
