### ISSUE TITLE
Deeplink error messages when getting Person Credential

### ISSUE THREAD

**Issue by krobinsonca** [bcgov/bc-wallet-mobile#2010]
### Description of problem
Error messages displayed when getting the Person Credential issued to BC Wallet

### Expected behavior
No error messages shown through process

### Steps to reproduce
1. Install BC Wallet Build 1740
2. Click Start to get Person Credential
3. Followed all "happy path" steps
4. When I get to the step clicking the button "Create Person Credential", the next screen show error "Unable to handle deeplink. There was a problem handing a deeplink." Click Show Details... "Unable to handle deeplink. Error code 1039 - Network request failed"
5. Click OK on error screen, it shows the Credential Offer screen
6. All details are correct, click Accept
7. Credential is added successfully

### Screenshots and/or log output

![Screenshot_20240613_082630_BC Wallet](https://github.com/bcgov/bc-wallet-mobile/assets/96077962/1093d481-1801-4fd0-a5b7-dde6b2be1ddb)
![Screenshot_20240613_082635_BC Wallet](https://github.com/bcgov/bc-wallet-mobile/assets/96077962/215932ca-face-4700-b47d-d02a33f6d366)

### Environment
- [X] Occurs on Android
- [] Occurs on iOS

Build #: 1740

Android Device Model: Samsung Galaxy S23 Ultra

iOS Device Model: 

### Workaround
Well, it still issued the PC to my wallet

### Severity
- [ ] High
- [X] Medium
- [ ] Low

**Comment by cvarjao** [comment]
Fixed in build # 1744
