### ISSUE TITLE
Unable to present non-production credentials in proof requests

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#2027]
### Description of problem
Even when enabling acceptance of non-production credential in dev mode, when sending a proof request, the holder is not able to share non-production credentials.

### Expected behavior
When the verifier has enabled the acceptance of on-production credential in dev mode, the holder should be able to present and share non-production credentials if they have them in their wallet.

### Steps to reproduce
- Enable non-production credential in dev mode
- Send a proof request to a holder that has non-prod credentials

### Environment
- [X] Occurs on Android
- [X] Occurs on iOS

Build #: 1.0.17 build 1760

Android Device Model: Google pixel 8

iOS Device Model: iPhone SE

### Severity
- [ ] High
- [x] Medium
- [ ] Low

**Comment by knguyenBC** [comment]
Seems fixed now.

**Comment by rahulbatham767** [comment]
how to fix this issue
