### ISSUE TITLE
App attestation proof request from anywhere/any issuer

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#2047]
### Acceptance Criteria
When scanning a QR Code or opening a deep link
If receives a proof request for app attestation, stays in "wait/load" screen
after successful presentation
- if there is no goal code, sends to chat
- if there is goal code, wait for Credential Offer or another non-attestation Proof Request

### Implementation Notes
- Will need to create some testing scripts that interacts with traction for emulating the flow
- We might not be able to use goal codes in the same way, we need some isolation so that the app attestation credential offer doesn't interfere with the actual credential offer

### References
- https://github.com/cvarjao/anoncreds-api-flows
- https://github.com/cvarjao/afj-perf-test

**Comment by jleach** [comment]
@cvarjao I think the logic needs to be: if a proof comes in just for attestation, respond to it. If its attestation + any other credential, just make sure we have an attestation credential. The user must respond as per the acceptance criteria. Really its just like any other proof request at that point.

**Comment by bryce-mcmath** [comment]
has been working without issue for quite a while now, closing
