### ISSUE TITLE
Proof request with date ZKP display is not aligned with the presentation

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#2049]
From the Mobile Verifier Proof Request Template:
![Image](https://github.com/bcgov/bc-wallet-mobile/assets/1348549/0e72f392-9018-41f9-bb63-09438eba44aa)

The presentation seen by the verifier
![Image](https://github.com/bcgov/bc-wallet-mobile/assets/1348549/fe79040d-144a-4741-81b3-7073fb2dea21)

The proof request by the holder
![Image](https://github.com/bcgov/bc-wallet-mobile/assets/1348549/e1da45ce-b1fd-4045-a715-c788e6ec0432)

**Comment by knguyenBC** [comment]
Checked both iOS and Android. Looks good!
