### ISSUE TITLE
Spike: Investigate using react-native-modalfy

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#2050]
https://github.com/colorfy-software/react-native-modalfy

**Comment by bryce-mcmath** [comment]
It's a very heavy lift to convert all modals in BC Wallet and Bifold to use Modalfy and introduces yet another dependency, so as a team we decided to address the main pain points (in app guides and lockout) with another approach and agreed to use modals sparingly going forward.
