### ISSUE TITLE
The "?_url=" deep link handler does not load the proof if the wallet is not already open (Android)

### ISSUE THREAD

**Issue by loneil** [bcgov/bc-wallet-mobile#2052]
### Description of problem
Have been experiencing this on Android while trying out the new `?_url` handler with deep links. (have not tried on an iOS device)

Using a deep link in VCAuth-N and setting it up to use `?_url` instead of `?c_i` and it works successfully to load the connectionless proof in the wallet, and integrate the user actions from that proof back to the VCAuth-N browser session.
Provided the wallet is already open.

If the wallet is not open, then the deep link opens the BC Wallet, but nothing seems to happen. 

All this is for connectionless, but I see the same with OOB if I do not have the wallet open (IE, nothing happens).

### Expected behavior
If the Wallet is not open, using the deep link opens the wallet and brings up the proof, same as it's currently working if the wallet is already open.

### Steps to reproduce
Use a deep link including the `?_url` handler with a format such as 
`bcwallet://aries_proof-request?_url=<base64 encoded link>`
Where the base64 is the URL the wallet should nav to to get the connectionless or OOB proof payload.

See video and more details below.

### Screenshots and/or log output

**00:00 - 00:40** The Wallet is not open. Show clicking deep link a few times and re-closing the app to demonstrate that nothing is happening in the wallet.

**00:40 - 01:01** Leave the wallet open this time and then go back and refresh and try the deep link. This is now working as expected. Do a decline and a share to show working states.

**01:10 - end** Show the deep link text, show the base 64 url link, show what the link resolves to. These printed below.

https://github.com/bcgov/bc-wallet-mobile/assets/17445138/741fec83-39a4-4404-b710-309df6a74c95

```
bcwallet://aries_proof-request?_url=aHR0cHM6Ly8zYTdmLTEwOC0xODAtMTcxLTI4Lm5ncm9rLWZyZWUuYXBwL3VybC9wcmVzX2V4Y2gvM2ZiZWQyNzktYWE3OS00ZWZiLWJjOTQtMTBkNmEwZGVhNjhk
```

```
https://3a7f-108-180-171-28.ngrok-free.app/url/pres_exch/3fbed279-aa79-4efb-bc94-10d6a0dea68d
```

```
{
    "@id": "feb91b1b-477e-4b43-9950-aa8bdf1d303e",
    "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/present-proof/1.0/request-presentation",
    "request_presentations~attach": [
        {
            "@id": "libindy-request-presentation-0",
            "mime-type": "application/json",
            "data": {
                "base64": "eyJub25jZSI6ICIzMjgyMTkzMjQwMDA3Mzg2MDQzOTk2NDUiLCAibmFtZSI6ICJwcm9vZl9yZXF1ZXN0ZWQiLCAidmVyc2lvbiI6ICIwLjAuMSIsICJyZXF1ZXN0ZWRfYXR0cmlidXRlcyI6IHsicmVxX2F0dHJfMCI6IHsibmFtZXMiOiBbImdpdmVuX25hbWVzIiwgImZhbWlseV9uYW1lIiwgImNvdW50cnkiXSwgInJlc3RyaWN0aW9ucyI6IFt7InNjaGVtYV9uYW1lIjogIlBlcnNvbiIsICJpc3N1ZXJfZGlkIjogIkw2QVNqbUREYkRIN3lQTDF0MnlGajkifSwgeyJzY2hlbWFfbmFtZSI6ICJQZXJzb24iLCAiaXNzdWVyX2RpZCI6ICJRRXF1QUhrTTM1dzRYVlQzS3U1eWF0In0sIHsic2NoZW1hX25hbWUiOiAiUGVyc29uIiwgImlzc3Vlcl9kaWQiOiAiTTZkaHVGajVVd2JoV2tTTG12WVNQYyJ9XSwgIm5vbl9yZXZva2VkIjogeyJmcm9tIjogMTcyMDQxNDU4NiwgInRvIjogMTcyMDQxNDU4Nn19fSwgInJlcXVlc3RlZF9wcmVkaWNhdGVzIjoge319"
            }
        }
    ],
    "comment": null,
    "~service": {
        "recipientKeys": [
            "DY1virT55aGaRp6ahET9joiFeVNMa45o3V1ha6Rt542h"
        ],
        "routingKeys": null,
        "serviceEndpoint": "https://cf35-108-180-171-28.ngrok-free.app"
    }
}
```

### Environment
- [x] Occurs on Android
- [ ] Occurs on iOS

Build #: 1.0.18 Build(1782)

Android Device Model: Pixel 8

iOS Device Model: 

### Workaround
Go back and refresh now that the app is open and try the deep link again.

### Severity
- [ ] High
- [ ] Medium
- [ ] Low

**Comment by loneil** [comment]
There is a `USE_URL_DEEP_LINK` that can be set in local VCAuthN we can do for trying this out. Or I can set on the dev environment to coordinate testing.

**Comment by jleach** [comment]
This may be a know issue. See here: https://github.com/facebook/react-native/issues/32350

**Comment by wadeking98** [comment]
@loneil is there an instance of vc-authn publicly available? I can't reproduce it on the showcase

**Comment by loneil** [comment]
@wadeking98 you can use https://a2a-dev.apps.silver.devops.gov.bc.ca/pre-vc-auth/ to reproduce on an Android (haven't tried this on an iPhone). That environment has `?_url` handler at this time.
Just tried it there right now, works for me if I have the app already open, doesn't work if the app isn't already open.

On the page with the deep link if you tap the BC logo 10 times it will show you the link at the bottom as well if you need to verify that.

**Comment by wadeking98** [comment]
strange, it works fine in the dev environment using metro and everything but once I use a release version of the app from testflight then I run into this issue

**Comment by wadeking98** [comment]
I'm running into the same issue on the showcase too when I use the play store version of the app

**Comment by cvarjao** [comment]
@loneil , @esune , there is a fix for this in the latest beta build (1872), if you have a chance, can you test it?

**Comment by loneil** [comment]
@cvarjao just tried with 1872 Android and the deep links **do** work for me now, both for `c_i` and `_url` when the wallet is unopened (and still work when the wallet _is_ open) 🎉 


https://github.com/user-attachments/assets/84de0b6b-3aa0-402d-b5f2-d60c99466352
