### ISSUE TITLE
Can change credential to a credential that does not fulfil the proof request

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#2055]
### Description of problem
When receiving a proof request and the "change credential" option is available, tapping that button opens a list that includes credentials that do not fullfil the proof request.

### Expected behavior
The "change credential" button should only be available if there are multiple credentials that can fulfill the proof request. The list of credential to change to should only include credentials that can fulfill the proof request.

### Steps to reproduce
- Acquire 2 of the same credential (Person (prod and demo) or LSBC credential (prod))
- Revoke one of them
- Receive a proof request asking for those credentials (ex. full name, practicing lawyer)
- Tap "Change credential"
- See that the list includes both the non-revoked and revoked credential

Enabled: dev mode, non-prod credentials, connection inviter capability, verifier capability, dev templates

### Environment
- [X] Occurs on Android
- [X] Occurs on iOS

Build #: 1.0.18 1782

Android Device Model: pixel 8

iOS Device Model: iPhone SE

### Severity
- [ ] High
- [ ] Medium
- [X] Low

**Comment by wadeking98** [comment]
resolved by https://github.com/openwallet-foundation/bifold-wallet/pull/1212

**Comment by bryce-mcmath** [comment]
Can no longer select revoked credentials for a non-revoked proof request
