### ISSUE TITLE
Remove lockout modal and replace with updated lockout UI

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#2057]
**Background**
The lockout modal may cause an error if another modal is mounted overtop.
To reduce the risk and simplify the UI, remove the lockout modal and simply update the UI to communicate the users they have been locked out

**Wireframes**
![image](https://github.com/bcgov/bc-wallet-mobile/assets/68872187/4912546c-567d-430e-90fb-d22a883997b8)

**Comment by knguyenBC** [comment]
Works on iOS but Android doesn't seem to lock out anymore, tested after 5 minutes, the app did not lock. Did not have auto-lock disabled.

**Comment by bryce-mcmath** [comment]
Did we find out if this behaviour existed in the current release as well? My changes shouldn't really affect how it locks out, just that it's a bit of text shown instead of a modal

**Comment by knguyenBC** [comment]
I checked the app store version on iOS and it doesn't seem like it times out with the app open, phone awake. So I guess having the phone lock out after 5 minutes is a new feature. @cvarjao

**Comment by bryce-mcmath** [comment]
Perhaps we can make a new ticket for that feature and close this one then

**Comment by cvarjao** [comment]
sounds good. we can close this one and start a new one for the "5min idling lockout"
