### ISSUE TITLE
Proof not accepted from vc-authn

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#2061]
### Environment
- [ ] Occurs on Android
- [ ] Occurs on iOS

Build #:

Android Device Model: 

iOS Device Model: 

### Severity
- [ ] High
- [ ] Medium
- [ ] Low

**Comment by knguyenBC** [comment]
Is this error related? from feedback survey.

![Image](https://github.com/user-attachments/assets/7bdc9fcf-713d-4bda-9dab-facc3b5e8fcf)

**Comment by cvarjao** [comment]
closing stale issues
