### ISSUE TITLE
QR Code scanner screen is black when using "back" function in Android

### ISSUE THREAD

**Issue by krobinsonca** [bcgov/bc-wallet-mobile#2070]
### Description of problem
QR code scanner screen is black when using the "back" function in Android. Use case is that I scanned a QR code, but scanned the wrong one. Android users often click "back" go to a previous screen when they did something by mistake. (Confirmed by @loneil)

### Expected behavior
QR code scanner screen uses the camera function (to scan a QR code)

### Steps to reproduce
1. Open QR code scanner
2. Scan a valid QR code for a proof (I used Dev ACM vc-authn)
3. Click the "back" navigation button
4. QR code scanner screen shows again but picture is black and cannot scan another QR code

### Environment
- [ X] Occurs on Android
- [ ] Occurs on iOS

Build #: 1760

Android Device Model: Samsung Galaxy S23 Ultra

iOS Device Model: 

### Workaround
Don't use back button, instead use Home button and relaunch QR code scanner

### Severity
- [ ] High
- [ ] Medium
- [X] Low

**Comment by jleach** [comment]
I don't think this is an issue any longer. There is no "back" button on the proof screen nay longer, just "cancel" and "home" if you can not fulfill the proof or "accept", "decline" and "home" if you can. Verified in 1.0.21. I also tried the hardware back gesture on a Pixel 7a and it is not enabled. Maybe we need an actual hardware button?

**Comment by loneil** [comment]
I can still reproduce this on 1.0.21 1932 with my Pixel 8 and the back gesture:


https://github.com/user-attachments/assets/0a80513c-0dd8-4843-af4a-f331ef4e7702

**Comment by al-rosenthal** [comment]
On a OnePlus 10 Pro I was able to reproduce the issue with version 1.0.20 (from the play store) but I am unable to reproduce this bug with version 1.0.21

**Comment by al-rosenthal** [comment]
@krobinsonca Is this still an issue with the latest build? I'm only able to reproduce the issue with the older version of the app (1.0.20)

**Comment by jeznorth** [comment]
Cannot reproduce in build 1.0.21.
