### ISSUE TITLE
(Beta - Android) Deep Link for connectionless proof is sitting on "Making connection" screen

### ISSUE THREAD

**Issue by loneil** [bcgov/bc-wallet-mobile#2072]
Not sure if you folks want issues created in the repo for things found on beta builds?

### Description of problem
With the latest build I have on Android I seem to have it getting stuck when using the existing connectionless deep links that we use in VCAuth-N deployments.
I don't think this is related to anything with my specific wallet setup (it was working for me until recently) but I could reinstall and try fresh if you want as well.

This isn't happening on the public build on iOS.

When clicking one of the deep links with a format like `bcwallet://aries_proof-request?c_i=<encoded>` it seems to now be getting stuck on the "Just a moment while we make a secure connection" screen.
The proof is there in the background, but I need to go back to home to get at it.

See videos below.

### Expected behavior
When I click the deep link the wallet should foreground the proof request.

### Steps to reproduce

1 Have the BC Wallet open (clear old proofs for any confusion)
2 On mobile device navigate to https://a2a-test.apps.silver.devops.gov.bc.ca/pre-vc-auth/ and enter
3 Click the Open in BC Wallet link on the mobile page
4. The wallet sits on the connection screen.

### Screenshots and/or log output

**Video of Android on latest beta build 1.0.18 1792**

https://github.com/user-attachments/assets/3cc8ada2-dd6a-4ccd-bb31-f6105bb5ceec

![image](https://github.com/user-attachments/assets/eb95f527-0791-4380-b27f-4fdaccd6322f)

**Video of iPad on public release build 1.0.17 1760**

https://github.com/user-attachments/assets/e8256724-8588-459e-98b0-62929212bcf1

### Environment
- [x] Occurs on Android
- [ ] Occurs on iOS

Build #:

Android Device Model: 1.0.18 1792

iOS Device Model: N/AS

### Severity
- [ ] High
- [ ] Medium
- [ ] Low

**Comment by bryce-mcmath** [comment]
Fixed in the latest build
