### ISSUE TITLE
Initialize agent on proxy startup (2060.io proxy npm package)

### ISSUE THREAD

**Issue by bryce-mcmath** [bcgov/bc-wallet-mobile#2090]
Right now, the indy vdr proxy package we are using initializes the agent after the first request made. It would be much better to initialize the agent on server startup so that some unlucky random user has to wait extra long for their request.

Repo: https://github.com/2060-io/credo-ts-indy-vdr-proxy

**Comment by cvarjao** [comment]
Duplicates #2113
