### ISSUE TITLE
Missing Biometric Prompt during setup

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#2111]
- Given the user has previously denied the use of biometrics
- When the user tries to enable biometrics
- Then a pop up appears to inform them they need to enable biometrics in their settings (see content below)

**Popup content:**
Title: Enable biometrics
Body: To unlock BC Wallet with your biometrics, please allow biometrics use within your device's settings.
Button label: Open settings
Button redirect: To device's biometrics settings

Title: Activer la biométrie
Body: Pour déverrouiller BC Wallet avec votre biométrie, permettrez la biométrie dans les paramètres de votre appareil.
Button label: Ouvrir les paramètres
Button redirect : To device's biometrics settings

---

- Given the user does not have biometrics set up on their device
- When the user tries to enable biometrics
- Then a pop up appears to inform users that they do not have biometrics set up

Title: Biometrics is not enabled
Body: To unlock BC Wallet with your biometrics, please set up your biometrics in your device's settings.
Button label: Open settings
Button redirect : To device's biometrics settings

Title: La biométrie n'est pas activée
Body: Pour déverrouiller BC Wallet avec votre biométrie, configurez votre biométrie dans les paramètres de votre appareil.
Button label: Ouvrir les paramètres
Button redirect : To device's biometrics settings

**Comment by jeznorth** [comment]
@tom11-nguyen please connect with @knguyenBC regarding design artifacts (if required.)

**Comment by jleach** [comment]
@tom11-nguyen Are you able to confirm and fix this issue as part of this PR:

https://github.com/openwallet-foundation/bifold-wallet/issues/999

Cc: @cvarjao

**Comment by knguyenBC** [comment]
Given the user has previously denied the use of biometrics
When the user tries to enable biometrics 
Then a pop up appears to inform them they need to enable biometrics in their settings (see content below)

**Popup content:**
Title: Permettre la biométrie
Body: To unlock BC Wallet with your biometrics, please allow biometrics use within your device's settings.
Button label: Open settings
Button redirect: To device's biometrics settings

Title: Activer la biométrie
Body: Pour déverrouiller BC Wallet avec votre biométrie, permettrez la biométrie dans les paramètres de votre appareil.
Button label: Ouvrir les paramètres
Button redirect : To device's biometrics settings

---

Given the user does not have biometrics set up on their device
When the user tries to enable biometrics
Then a pop up appears to inform users that they do not have biometrics set up

Title: Set up your biometrics
Body: To unlock BC Wallet with your biometrics, please set up your biometrics in your device's settings.
Button label: Open settings
Button redirect : To device's biometrics settings

Title: Activer la biométrie
Body: Pour déverrouiller BC Wallet avec votre biométrie, configurez votre biométrie dans les paramètres de votre appareil.
Button label: Ouvrir les paramètres
Button redirect : To device's biometrics settings

---

Given the user can't have biometrics set up on their device
When the user tries sets up their security
Then the biometrics screen does not appear

**Comment by tom11-nguyen** [comment]
https://github.com/user-attachments/assets/0228adab-ffc4-488e-b501-d2f0962621f2
Added a video demo for happy path.

**Comment by jeznorth** [comment]
Moving back to 'spring backlog' to address content issues.

**Comment by tom11-nguyen** [comment]
@jeznorth 'Biometrics is not enabled' title is one of the ACs, when the biometric is unavailable to the app. Could you elaborate the scenario you are facing ?

**Comment by jeznorth** [comment]
Verified that both the scenarios (for that particular notification) do in fact have the correct content.
