### ISSUE TITLE
VDR Proxy - Production Ready Deployment

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#2113]
- [x] Caching
- [x] Fully started and ready on container startup
- [x] No delayed initialization triggered by first request
- [x] HA deployment
- [x] Update to latest credo (0.5.11)
- [x] Update VDR Proxy client on BC Wallet and align Credo deps

**Comment by bryce-mcmath** [comment]
@cvarjao the updated version of the proxy package requires `@credo-ts@0.5.11` as a peer so we will have to upgrade Bifold/BC Wallet as well
