### ISSUE TITLE
Bug with Present Proof flow in BC Wallet

### ISSUE THREAD

**Issue by mathieuglaude** [bcgov/bc-wallet-mobile#2117]
### Description of problem

- We have encountered an issue with the verification flow in BC Wallet.
- When the DID who created the Schema ID and the DID who created the Cred Defn ID are different, the BC Wallet is throws an error.
- For example, if the SchemaID is FkPAh5o3s9PSmb8g9cFnQg:2:Person:1.0 and cred defn ID isFkPAh5o3s9PSmb8g9cFnQg:3:CL:726654:Person, the verification process runs properly.
- Whereas if the Schema ID is BDQvbqKN9CVBVn1UryetKL:2:digital_business_card:1.0.0 and Cred defn ID is FkPAh5o3s9PSmb8g9cFnQg:3:CL:60640:Digital Business Card, the BC Wallet fails to provide the proof presentation.
- These Schema IDs and CredDef IDs are created using BC Traction and are in BCovrin Test Ledger.
- I've attached a screenshot for reference.
- This is preventing us from running Present Proofs with a customer. Big roadblock for us right now.

### Screenshots and/or log output

![image](https://github.com/user-attachments/assets/ff16c8aa-09cc-43f0-8a9b-3c67425da829)

### Build #: 

version 1.0.18 Build (1801)

### Severity
- **[ ] High**

**Comment by cvarjao** [comment]
@mathieuglaude , do you have an example of a proof request we can use to replicate this issue?

**Comment by mathieuglaude** [comment]
@cvarjao here you go:

{
    "requested_attributes": [
      {
        "names": [
          "identifier",
          "role",
          "family_name",
          "cra_business_number",
          "business_type",
          "credential_id",
          "business_name",
          "given_names",
          "company_status"
        ],
        "restrictions": [
          {
            "cred_def_id": "FkPAh5o3s9PSmb8g9cFnQg:3:CL:60640:Digital Business Card",
            "issuer_did": "FkPAh5o3s9PSmb8g9cFnQg"
          }
        ]
      }
    ],
    "requested_predicates": []
  }

**Comment by cvarjao** [comment]
Thanks. I will create a test scenario to replicate that and I will get back to you

**Comment by cvarjao** [comment]
@mathieuglaude , was that on iOS or Android? or both?

**Comment by cvarjao** [comment]
I was able reproduce. The next version of BC Wallet will come with Credo 0.5.9. BC Wallet 1.0.18 was with Credo 0.5.3. I can't pin point exactly what was fixed, but it works with the beta builds (1.0.19). Would you like access to beta build to validate?

**Comment by cvarjao** [comment]
@mathieuglaude , not sure if you have seen my prior comment

**Comment by mathieuglaude** [comment]
Hi @cvarjao - yes that would be a good idea if possible so that we can test internally.

**Comment by bryce-mcmath** [comment]
@mathieuglaude were you able to test this out with a fresh install?

**Comment by mathieuglaude** [comment]
@bryce-mcmath - yes we tested and the issue was addressed. Thanks!
