### ISSUE TITLE
Auto lock app after user inactivity when app in foreground

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#2136]
- After x amount of time of the app open, but receiving no user input, auto-lock the app.
- Configurable amount of idling time:
    - 1 min
    - 3 min
    - 5 min (default)
    - Never

Related Issue:
- #2073

**Comment by al-rosenthal** [comment]
@cvarjao Should this inactivity timer reset if the app goes into the background/ foreground? or should it maintain and update the timer according to how long it was in the background.

For example: 
1. User interacts with the app, timer reset for 5 minutes
2. User doesn't interact with app and timer runs down to 3 minutes
3. User pushes app into the background for 2.5 minutes
4. App is brought back to foreground and the user doesn't interact for 30 seconds
5. 5 minute timer is hit and the user is logged out

**Comment by knguyenBC** [comment]
I think the timer should reset if thrown into the foreground but not the background.
