### ISSUE TITLE
Find a replacement for survey monkey

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#2141]
Our surveymonkey license has expired so we'll need to quickly find a new replacement.

Acceptance criteria
- Review other survey tools (free, paid)

Survey tools reviewed
- [ ] CHEFS. Not a good choice as its survey builder is very limited. It's more designed for forms rather than surveys.
- [ ] CMS Lite forms. Not scalable. responses are received via individually via email.
- [ ] Maze. Powerful tool however, data is stored in US and a PIA and STRA would have to be done.

**Comment by knguyenBC** [comment]
Will continue with SurveyMonkey for now.
