### ISSUE TITLE
Disable Mobile Verifier History by default

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#2157]
Problem:
- Mobile verifier history is enabled by default
- Mobile verifier can re-enable the history

Acceptance Criteria:
- As a verifier, no proof request history is saved in the wallet
- As a verifier, I can't re-enable proof request history

**Comment by knguyenBC** [comment]
Tried on iOS new install and data retention was enabled by default still.

**Comment by knguyenBC** [comment]
Looks good. off by  default, can't enable history as its completely removed from dev options.
