### ISSUE TITLE
VCAuthn deep link not working for iOS

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#2168]
Receiving and successfully sending the information, but returning to the service page (Courthouse libraries), VC-AuthN did not redirect me, Stuck in perpetual loading.

Works fine with the showcase.

### Steps to recreate
- Get a non-revoked version of the LSBC credential
- Go to the courthouse libraries proof on the same device
- Use deeplink to open BC Wallet
- Share information successfully and return to the service page/vc-authn

on iOS build 1890. iPhone SE

**Comment by bryce-mcmath** [comment]
Seems to be a websocket issue with VCAuthn, Lucas is creating a ticket on their side.
