### ISSUE TITLE
Incorrectly selecting revoked credentials

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#2169]
### Issue
A revoked credential is being automatically selected first. I have to change the credential to a non-revoked one manually.

### Steps to reproduce
- Get a revoked and non-revoked version of the LSBC credential and person credential
- Go to the ACM website and scan QR code
- Receive proof request

affected  iOS  only.
Device used: iPhone SE, build 1890

**Comment by knguyenBC** [comment]
I tried again with reissued credentials (Person and LSBC credential) and it seems to work fine now. Unless others are able to replicate, I would close.
