### ISSUE TITLE
A successful proof request doesn't send users to the "information sent successfully" modal

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#217]
After accepting a proof request and the request was sent successfully, the BC Wallet app continues to display the "sending the information securely" modal. The modal should:

change to "information sent successfully" if the request was successful 
or 
change to "Credentials were not accepted" modal if the proof request failed
or
an error modal if something went wrong in the background (i.e. internet was cut off)

**Comment by amanji** [comment]
Can we please retest this to confirm or add some more descriptive information to exactly reproduce the bug?

**Comment by knguyenBC** [comment]
Retested and still has the same problem. Used the Mines BPA sandbox. Attached a video of what is happening. I'm signing into the demo using VCs and gaining access. What the wallet should be doing is switching the modal to the "information sent successfully" modal. But it's currently stuck at the "sending..." modal.  What is happening and didn't happen before was that error message though. That's a new bug.

https://user-images.githubusercontent.com/68872187/159339301-b9375c56-67e2-48e5-ac4a-907e99ff30c4.mp4

.

**Comment by jleach** [comment]
@knguyenBC Tested this AM and it seems to be working fine. I was also able to reproduce the error modal in the case where my tails file was broken (last week).

https://images.zenhubusercontent.com/429950091/2ffd91ab-5e0d-45ea-bf6a-56f677f46f58/proofok.mov

**Comment by knguyenBC** [comment]
Is this with a new build that isn't released yet? currently on build 134.
