### ISSUE TITLE
spike: Connection Reuse (Aries 0434)

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#2170]
[Aries RFC 0434](https://github.com/hyperledger/aries-rfcs/blob/main/features/0434-outofband/README.md#connection-reuse)

## Acceptance Criteria
- Create invitation to connect with connection re-use enabled using aca-py/traction
  -  code test case in https://github.com/cvarjao/afj-perf-test
- Test against BC Wallet App

**Comment by bryce-mcmath** [comment]
Connection reuse is now working in BC Wallet so long as the other agent is using the correct protocol.
