### ISSUE TITLE
Review/Refactor Agent Initialization

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#2174]
During debugging it was noticed there may be opportunity to improve Agent initialization. For example, doing it more like Paradigm or at least moving the logic out of the overly long and complicated Splash screen and into its own file.

**Comment by bryce-mcmath** [comment]
Here is an example from Paradym that's fairly clean: https://github.com/animo/paradym-wallet/blob/9f1f7f35b740a8f92e6f92bd11fcde64418c9420/apps/paradym/app/_layout.tsx#L49
