### ISSUE TITLE
Wade - Knowledge Transfer

### ISSUE THREAD

**Issue by jeznorth** [bcgov/bc-wallet-mobile#2188]
- [ ] Show Case App
- [ ] Rust Lib
- [ ] OCA

**Comment by jeznorth** [comment]
Outputs should be delivered via:

- BC Wallet Showcase (readme, discussions tab?
- OCA (readme?)
- Rust Lib (discussion under BC Wallet repo)

**Comment by wadeking98** [comment]
Rust libs: https://github.com/bcgov/bc-wallet-mobile/discussions/2195
Showcase: https://github.com/bcgov/BC-Wallet-Demo/blob/main/DEVELOPER/BC%20Wallet%20Showcase.md
