### ISSUE TITLE
In app guides are being triggered even if user selects the dismiss "X"

### ISSUE THREAD

**Issue by bryce-mcmath** [bcgov/bc-wallet-mobile#2197]
In the most recent build, in app guides are still being enabled when the user presses the "dismiss" X icon. That button should have the same behaviour as the "Don't use in app guides" button

**Comment by knguyenBC** [comment]
Based on the discussion we had with @nodlesh, I believe we're continuing with that behaviour. i.e. dismiss (X or done button) do the same thing whereas the "Do not use app guides" button at the beginning fully disabled app guides.
