### ISSUE TITLE
Attestation presentation shows in Chat

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#2201]
The attestation credential presentation shows in chat. When viewed, it partially shows, then disappears.

https://github.com/user-attachments/assets/f761cadb-92b1-4022-8d82-41eab7a128aa

**Comment by knguyenBC** [comment]
@cvarjao Reading this, why does this need design? Is it not simply a bug? We should remove any visibility of the attestation flow.

**Comment by cvarjao** [comment]
duplicates #2063
