### ISSUE TITLE
Proof requests displays error when requesting for missing attributes from credential

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#2208]
### Description of problem
When receiving a proof request requesting for the Photo from the Person credential AND the holder has a Person credential WITHOUT a photo, this screen appears as below. States the credential is missing and OCA is not displayed:

![image](https://github.com/user-attachments/assets/891fa607-73ee-48ba-818f-eb2ba00b9669)

I suspect that this issue/error happens for instances where a verifier is asking for credential schema's with optional attributes and the holder has a credential but is missing requested attributes.

### Acceptance Criteria

Given a proof request requests for a credential that exists in a holder's wallet (matches cred or schema ID)
When the credential is missing a requested attribute
It should say under the missing attribute "<attribute_name> is missing"
And the holder is unable continue sharing information

**Wireframes as an example**
To note: 
- OCA should still continue to be displayed
- Requested revoked credentials follow the same logic
- Follow the same GUI for "requirements not met" (i.e. red text, X icon, etc.)
![Image](https://github.com/user-attachments/assets/dcf25b1d-41e9-4a00-81ce-a2fb7ca71cb9)

### Steps to reproduce
- receive a Person credential without a photo attribute
- Receive a proof request requesting for a photo attribute

### Environment
- [X] Occurs on Android
- [X] Occurs on iOS

Build #:

Android Device Model: 

iOS Device Model: 

### Severity
- [ ] High
- [ ] Medium
- [ ] Low

### Related Issue
- #428

**Comment by jeznorth** [comment]
Follow up with Marcos about replication.

**Comment by jleach** [comment]
@jeznorth I was able to reproduce our dev instance of Traction with a manually crafted attestation proof request. If not me whoever gets this ticket can reach out to me for the details on how to reproduce it.

**Comment by knguyenBC** [comment]
@knguyenBC Add detailed design specs (with wireframe)

**Comment by al-rosenthal** [comment]
Steps to test Manually:
	1.	Download latest version of the app
	2.	Initialize wallet (set pin)
	3.	Get your person credential
	4.	Open a browser and navigate to https://traction-sandbox-tenant-ui.apps.silver.devops.gov.bc.ca
	5.	Under the form input click the `Create Request`
	6.	Fill out the details (these are not important for the sandbox)
	7.	Keep the wallet ID and wallet key (you’ll need these to gain access )
	8.	Navigate back to the login screen and input the wallet ID and Key you saved from a previous step
	9.	In the side bar click Connections -> invitations 
	10.	On the main page click `Create Invication`
	11.	Leave the default settings and name the connection 
	12.	Once done you should see a QR code 
	13.	Open the BC wallet app and scan that QR code, you should see a message on your device saying ‘You connected with “tenant name”’
	14.	In the side bar now click ‘Verification’
	15.	On the main page click ‘Create Presentation Request’
	16.	In the connection drop down, select the connection you just created and replace the Proof request section with this object:
	```{
	  "name": "proof-request",
	  "nonce": "1234567890",
	  "version": "1.0",
       "requested_attributes": {
       "studentInfo": {
       "names": ["given_names", "family_name", "country", "first_name"],
       "restrictions": [
          {
           "cred_def_id": "RGjWbW1eycP7FrMf4QJvX8:3:CL:13:Person"
          }
         ]
        }
       },
      "requested_predicates": {}
    }```

	17.	You should now see a proof request on your device
	18.	The proof request should show given names, surname, country and first name. This first name field doesn’t exist on the person credential and will be marked as a missing attribute

**Comment by jeznorth** [comment]
Closing as work done in conjunction with #2302.
