### ISSUE TITLE
Notification in T&C is cut off

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#221]
Notification in terms and conditions is not properly scaling to the screen size, cutting the text off.

![20220310_163648.jpg](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/43d6cfbe-f267-4783-bb15-f995d2541b24)

**Comment by jleach** [comment]
Looks good to me. Please test again and if it fails LMK what sized screen you  are using.

![IMG_0B39ABAB3F1F-1.jpeg](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/b72db693-e519-464c-8222-63df0bf84eb6)

**Comment by knguyenBC** [comment]
Yes, but now we have a different problem. [See ticket 285](https://app.zenhub.com/workspaces/bc-wallet-6148e7423fe04b001444e2bd/issues/bcgov/bc-wallet-mobile/285).
