### ISSUE TITLE
Update terms and conditions screen to final version

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#222]
The content is described as an "End user license agreement" or EULA. The title and the label of the screen should reflect the same terminology. 

Please update:
- [x] Title from "terms and conditions to "End user license agreement"
- [x] Current checkbox label to "I have read, understand and accept the terms of this EULA."
- [x] Final copy of EULA text

**Comment by cvarjao** [comment]
@knguyenBC  will clarify the preferred terminology ("terms and conditions" vs EULA)
