### ISSUE TITLE
Error when using "19+ and photo" proof request: Proof record is in invalid state

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#2222]
As a verifier, enable mobile verifier feature and select the "19+ and photo" proof request
As a holder, scan the QR Code (this will show the error)

<img src="https://github.com/user-attachments/assets/891ebfa7-b7a3-48e7-bed2-b85f6108b939" width="200">

**Comment by jleach** [comment]
I get a bunch of unhandled promise rejections. I think navigation is borked. Like its trying to show a proof when it should not be. Looking...

@cvarjao Able to confirm this error is shown on the verifiers device? Also, was this prod or main you saw it on?

**Comment by jeznorth** [comment]
Testing with 1.0.21 (2082) and still seeing this issue. One thing to note is that once I close the error notification I see the 'Information sent successfully' screen.

**Comment by jeznorth** [comment]
Verified fixed (build 2090)
- Android
- IOS
