### ISSUE TITLE
Setting wallet to French doesn't translate everything

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#224]
Setting wallet to French doesn't translate everything.
Also concerned that the French translation is using incorrect terminologies.
The Quebec wireframes use different words:
Credentials = Attestations
Scan = Capturer
Preferences = Réglages

![20220310_173956.jpg](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/d3032a23-624d-42ef-bb48-949d7672d1f3)

**Comment by jleach** [comment]
I just merged the PR from IDLabs that will, I hope, greatly improve the French translations and address this issue.
