### ISSUE TITLE
Update to work with latest changes from Bifold

### ISSUE THREAD

**Issue by bryce-mcmath** [bcgov/bc-wallet-mobile#2250]
There have been some semi-breaking changes in recent Bifold PRs that will need to be adjusted for slightly.

Here is a list to start with, there may be other small things:
- Unnecessary padding around proof request loading component
- Remove `ConfigurationProvider` and `defaultConfiguration` (old) usage from Bifold, export new `defaultConfig` from Bifold so we can use it in our DI (should be spread in `container-imp.ts` for `TOKENS.CONFIG`, without this currently we are missing Chat entirely)
- Export `OpenIDCredentialRecordProvider` from Bifold and wrap BC Wallet `App.tsx` with it the same with it is in Bifold

**Comment by jeznorth** [comment]
I've manually ran through both android and IOS devices and can't seem to find anything unexpected here. Should we close or can we get some additional eyes on this before closing?
