### ISSUE TITLE
Deep Link not working when app is already opened

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#2252]
### Description of problem
Opening the wallet with a deep link is not working

### Steps to reproduce

- Setup BC Wallet
- Leave wallet open
- open a website with a deep link (or use the test case below)
```shell
# From terminal 1
git clone https://github.com/cvarjao/vc-test-bench.git
cd vc-test-bench.git
yarn install
yarn ts-node src/setup-from-sandbox.ts
ngrok http "file://${PWD}/tmp"

# From terminal 2
export HOLDER_TYPE=manual
yarn jest --runInBand --detectOpenHandles --forceExit src/deep-links.test.ts

 # open the file generated with QR Code: ./tmp/__qrcode.png and scanning it using the built-in camera app
```
- click on the deep link
- Nothing happens. When the payload supposed to be processed and show a proof request

### Environment
- [x] Occurs on Android
- [x] Occurs on iOS

Build #: 1.0.21-2066

Android Device Model: 

iOS Device Model: 

### Severity
- [ ] High
- [x] Medium
- [ ] Low

**Comment by bryce-mcmath** [comment]
@al-rosenthal found an issue with this feature when you get locked out while backgrounded and then open a deeplink. Working on a fix

**Comment by bryce-mcmath** [comment]
Note: Best to test this from a Testflight build, as @jleach and I discovered there is some odd behaviour in local development

**Comment by knguyenBC** [comment]
here's a video of what I'm experiencing: https://drive.google.com/file/d/1-vOJFgg5Exx0KriLo1rO6CoI4EJxjWj4/view?usp=sharing
