### ISSUE TITLE
Cancelling/Declining a proof request shows an error

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#2253]
### Description of problem
- Cancelling/Declining a proof request shows an error
- Cancelling/Declining a proof request via mobile verifier shows an error
- Accepting a proof request via mobile verifier shows an error

### Expected behavior
Cancelling/Declining a proof request does NOT show an error

### Steps to reproduce
- Open BC Wallet
- Scan QR Code for a proof request (e.g.: https://justice.gov.bc.ca/dars/pre-vc-auth/ )
- Cancel/Decline proof request

### Environment
- [x] Occurs on Android
- [x] Occurs on iOS

Build #: 1.0.21-2066

Android Device Model: 

iOS Device Model: 

### Severity
- [ ] High
- [ ] Medium
- [x] Low

**Comment by bryce-mcmath** [comment]
I am unable to reproduce this with the latest build. @cvarjao or @jeznorth can you confirm?

**Comment by cvarjao** [comment]
@bryce-mcmath , I am still seeing it with build 2084

**Comment by cvarjao** [comment]
Just got an update. It is fixed in build 2086

**Comment by bryce-mcmath** [comment]
@cvarjao oh sorry it hadn't quite finished publishing yet, it's build 2086 that it seems to be fixed for me
