### ISSUE TITLE
Why you need a PIN screen doesn't have an always shown Continue button on Android

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#2264]
### Description of problem
On Android the Continue button is not visible all the time as it is on iOS. You Have to scroll down to press Continue. I assume this should be like iOS. See Screen Shot

### Expected behavior
Continue Button is always visible at the bottom of the screen.

### Screenshots and/or log output
<img width="631" alt="Screenshot 2024-11-12 at 2 13 44 PM" src="https://github.com/user-attachments/assets/8df2cb8b-9f63-4408-986e-6b81c72673e7">

### Environment
- [X] Occurs on Android
- [ ] Occurs on iOS

Build #:
2084

Android Device Model: 

iOS Device Model: 

### Severity
- [ ] High
- [ ] Medium
- [X] Low

**Comment by jeznorth** [comment]
Verified fixed (IOS / Android).
