### ISSUE TITLE
Remove "Secure your wallet" screen from change PIN flow

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#2270]
### Issue
When changing your PIN, the new "Secure your wallet" screen appears that contains content that is irrelevant/unecessary to a PIN change (information about why you need a PIN for example). 

### Acceptance Criteria
- Remove the screen from the change PIN flow

**Comment by jeznorth** [comment]
"Secure your wallet" screen appears to be removed from this workflow as expected. Verified IOS/Android.
