### ISSUE TITLE
Proof request credentials do not group properly

### ISSUE THREAD

**Issue by al-rosenthal** [bcgov/bc-wallet-mobile#2302]
### Description of problem
- proof request details does not properly group 'From your wallet' sections and 'Missing from your wallet' sections, currently all credentials in a proof request appear under the same header
- 'Not in your wallet' text is currently not displaying correctly for credentials that are missing

### Expected behavior
- Proof requests that contain credentials that exists and do not exists in the users wallet should be "grouped"
- Missing credentials say "Not in your wallet"
- Attributes for missing labels do not say " <x attribute>is missing"
- Multiple examples in the image attached
![Image](https://github.com/user-attachments/assets/5561c4bd-2baf-48a3-8ad9-c0bcd439f335)

### Steps to reproduce
- Issue a proof requests containing a credential that does not exist in the users wallet and a credential that does
- See proof request

### Environment
- [x] Occurs on Android
- [x] Occurs on iOS

Build #:

Android Device Model: 

iOS Device Model: 

### Severity
- [ ] High
- [ ] Medium
- [ ] Low

**Comment by jeznorth** [comment]
Verified fixed
