### ISSUE TITLE
Remove Contact

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#231]
As a holder I want to remove a contact from my wallet so that I can keep my wallet organized and clear of unnecessary contacts.

#### Scenario: No credentials issued from that contact
GIVEN [the holder is in the Contact detail screen](https://xd.adobe.com/view/be5d6531-658b-4d7c-8ec2-634825d724fe-eb0e/screen/dd94f541-764f-4893-9201-999a98e9bd69/)
AND there are no credentials issued by this Contact in the holder's wallet
WHEN the holder selects "Remove this Contact" 
THEN the holder is presented [a modal sheet](https://xd.adobe.com/view/be5d6531-658b-4d7c-8ec2-634825d724fe-eb0e/screen/6ca48815-3a72-45e4-a0ea-7398dbba2bf3/) with more details on removing Contacts
AND a "Remove this Contact" button is available.

GIVEN the holder is [in the modal sheet with more details on removing Contacts](https://xd.adobe.com/view/be5d6531-658b-4d7c-8ec2-634825d724fe-eb0e/screen/6ca48815-3a72-45e4-a0ea-7398dbba2bf3/)
AND there are no credentials issued by this Contact in the holder's wallet
WHEN the holder selects "Remove this Contact"
THEN the Contact is removed from the wallet
AND the holder is taken back to the Contact list screen

#### Scenario: 1 or more credentials issued from that contact
GIVEN the holder is in the [Contact detail screen](https://xd.adobe.com/view/be5d6531-658b-4d7c-8ec2-634825d724fe-eb0e/screen/daf37101-7a90-4d36-bc20-8f71d1f6bc7f/)
AND there are 1 or more credentials issued by this Contact in the holder's wallet
WHEN the holder selects "Remove this Contact"
THEN the holder is taken back to an [modal screen](https://xd.adobe.com/view/be5d6531-658b-4d7c-8ec2-634825d724fe-eb0e/screen/daf37101-7a90-4d36-bc20-8f71d1f6bc7f/) saying that it can't be removed because there are credentials issued by this contact in there wallet
AND a "Go to Credentials" button is available
AND a "Cancel" button is available

GIVEN the holder is in the [modal screen](https://xd.adobe.com/view/be5d6531-658b-4d7c-8ec2-634825d724fe-eb0e/screen/daf37101-7a90-4d36-bc20-8f71d1f6bc7f/)
WHEN the holder selects "go to credentials"
THEN the wallet takes the holder to the Credential List screen

GIVEN the holder is in the [modal screen](https://xd.adobe.com/view/be5d6531-658b-4d7c-8ec2-634825d724fe-eb0e/screen/daf37101-7a90-4d36-bc20-8f71d1f6bc7f/)
WHEN the holder selects "Cancel"
THEN the wallet takes the holder to the Contact detail screen

**Comment by cvarjao** [comment]
@knguyenBC , please break out Option2 to another user story. We will start with a simple removal.

**Comment by knguyenBC** [comment]
Readjusted the acceptance criteria. Added wireframes

**Comment by cvarjao** [comment]
It will need changes to the react hooks library which might slow the release

**Comment by nodlesh** [comment]
The following are a set of derived test scenarios from the acceptance criteria. I'm adding them here in case someone could give a quick review and see if I'm missing anything. Any scenario tagged with @minor or @trivial may not be implemented at this time. If you feel they should be, let me know and I'll raise the priority. 

I also add these here as an example of an abstraction away from the BC Wallet UI as compared to the Acceptance Criteria, and to make the tests at this level more robust and immune to UI changes.

```gherkin
   @T005.1-Connect @RemoveContact @normal @AcceptanceTest @Story_231 @wip
   Scenario Outline: Remove an Issuer contact where no credentials are issued from that contact
      Given the holder is connected to an Issuer
      And there are <no credentials> issued by this Contact in the holder's wallet
      And the holder is viewing that Contact's details
      When the holder Removes this Contact
      And the holder reviews more details on removing Contacts
      And the holder confirms to Remove this Contact
      Then the holder is taken to the Contact list
      And the holder is informed that the Contact has been removed
      And the Contact is removed from the wallet

      Examples:
         | no credentials             |
         | Offered and Rejected       |
         | Issued and Deleted         |
         | Issued Revoked and Deleted |


   @T005.2-Connect @RemoveContact @normal @AcceptanceTest @Story_231 @wip
   Scenario Outline: Remove a Verifier contact after a proof presentation
      Given the holder is connected to a Verifier
      And there has been a <proof> by this verifier
      And the holder is viewing that Contact's details
      When the holder Removes this Contact
      And the holder reviews more details on removing Contacts
      And the holder confirms to Remove this Contact
      Then the holder is taken to the Contact list
      And the holder is informed that the Contact has been removed
      And the Contact is removed from the wallet

      Examples:
         | proof      |
         | successful |
         | rejected   |


   @T005.3-Connect @RemoveContact @normal @AcceptanceTest @Story_231 @wip
   Scenario: Remove a contact where 1 or more credentials are issued from that contact and Cancels by going to Credentials
      Given the holder is connected to an Issuer
      And the holder has credentials
         | credential                | revocable | issuer_agent_type | credential_name |
         | cred_data_drivers_license | True      | AATHIssuer        | Drivers License |
         | cred_data_photo_id        | True      | AATHIssuer        | Photo Id        |
      And the holder is viewing that Contact's details
      When the holder Removes this Contact
      Then the holder is informed that it can't be removed because there are credentials issued by this contact in their wallet
      And the holder goes to credentials
      And the holder is taken to the Credential List
      And the Contact is not removed from the wallet


   @T005.4-Connect @RemoveContact @normal @AcceptanceTest @Story_231 @wip
   Scenario: Remove a contact where 1 or more credentials are issued from that contact and Cancels
      Given the holder is connected to an Issuer
      And the holder has credentials
         | credential                | revocable | issuer_agent_type | credential_name |
         | cred_data_drivers_license | True      | AATHIssuer        | Drivers License |
         | cred_data_photo_id        | True      | AATHIssuer        | Photo Id        |
      And the holder is viewing that Contact's details
      When the holder Removes this Contact
      Then the holder is informed that it can't be removed because there are credentials issued by this contact in their wallet
      And the holder Cancels
      And the holder is taken to Contact's details
      And the Contact is not removed form the wallet

   @T005.5-Connect @RemoveContact @normal @NegativeTest @Story_231 @wip
   Scenario: Remove a contact where 1 or more credentials are issued and revoked from that contact and Cancels
      Given the holder is connected to an Issuer
      And the holder has credentials
         | credential                | revocable | issuer_agent_type | credential_name |
         | cred_data_drivers_license | True      | AATHIssuer        | Drivers License |
      And the credential has been revoked by the issuer
      And the holder is viewing that Contact's details
      When the holder Removes this Contact
      Then the holder is informed that it can't be removed because there are credentials issued by this contact in their wallet
      And the holder Cancels
      And the holder is taken to Contact's details
      And the Contact is not removed form the wallet

   @T005.6-Connect @RemoveContact @minor @AcceptanceTest @Story_231 @wip
   Scenario Outline: Remove an Issuer contact then try to issue a credential based on that connection
      Given the holder is connected to an Issuer
      And there are <no credentials> issued by this Contact in the holder's wallet
      And the holder is viewing that Contact's details
      When the holder Removes this Contact from the wallet
      And the issuer attempts to issue a credential to the holder with the same connection
      Then the issuer is informed that the holder and issuer are not connected?
      And the issuer will be informed that the connection is invalid?

      Examples:
         | no credentials             |
         | Issued and Deleted         |

   @T005.7-Connect @RemoveContact @minor @ExceptionTest @Story_231 @wip
   Scenario: Remove a Verifier contact then try to request a proof based on that connection

   @T005.8-Connect @RemoveContact @minor @ExceptionTest @Story_231 @wip
   Scenario: Remove contact after a Credential Offer but before Accepting

   @T005.9-Connect @RemoveContact @minor @ExceptionTest @Story_231 @wip
   Scenario: Remove contact after a Proof Request but before Sending

   # Messaging/Chat currently not implemented/turned off in BC Wallet
   @T005.10-Connect @RemoveContact @trivial @ExceptionTest @Story_231 @wip
   Scenario: Messaging/Chat after contact removal
```

**Comment by nodlesh** [comment]
@amanji @knguyenBC The contacts list and details pages in 756 do not nook like the designs. Was updating the UI part of this ticket?

**Comment by amanji** [comment]
I don't believe the contacts UI was part of the ticket. It was just to add removal functionality and associated modals/messages, etc.

**Comment by knguyenBC** [comment]
@nodlesh which ticket are you talking about? ticket 756 doesn't seem like the right ticket you're referencing.

**Comment by nodlesh** [comment]
@knguyenBC 756 is the app build number. This ticket here is what I'm referring to. 

@amanji Where exactly in the app is the Remove ContactFunctionality? Are we sure it was merged? When I click on a contact there is only chat, no remove.

**Comment by bryce-mcmath** [comment]
Here is the Contacts list branding ticket: #797

**Comment by knguyenBC** [comment]
@nodlesh I took a look at your test scenarios and they seem correct. For Scenario 6, I don't think we have control on what the verifier/contact will see if they attempt to use a severed connection. The wallet doesn't get notified of anything if the verifier tries to send something though. The UI changes are in a different ticket. This ticket just focuses on the feature, irrelevant to the UI.

**Comment by nodlesh** [comment]
@knguyenBC Re: Scenario 6, yes true, however in the test harness I have access to the issuer and verifier, so I can see what they do in this instance and it will really make sure the connection is severed. I make that section of the test just to see what happens.
