### ISSUE TITLE
Extra spacing between PIN input labels and fields

### ISSUE THREAD

**Issue by bryce-mcmath** [bcgov/bc-wallet-mobile#2311]
### Description of problem
There is extra unnecessary spacing between labels and fields for PIN inputs.

### Expected behavior
There is no extra space unless it is taken up by an error message when error messages are configured to be above inputs.

### Steps to reproduce
Navigate to Change PIN screen

### Screenshots and/or log output
![Image](https://github.com/user-attachments/assets/d1ee3664-1486-44ca-8816-ec2f14aeeb38)

### Environment
- [x] Occurs on Android
- [x] Occurs on iOS

Build #:

Android Device Model: 

iOS Device Model: 

### Severity
- [ ] High
- [ ] Medium
- [x] Low

**Comment by jeznorth** [comment]
Spacing appears fixed (verified on IOS and Android)
