### ISSUE TITLE
Hide 'Language' option in Settings for M1

### ISSUE THREAD

**Issue by alexgmetcalf** [bcgov/bc-wallet-mobile#232]
Because M1 won't have a full French translation, hide the language option in 'Settings' for M1.

**Comment by swcurran** [comment]
Any reason why not? We can’t get the labels for the credential attributes, but all the static content for the app can be available in French.  Just a priorities issue?

**Comment by alexgmetcalf** [comment]
> Any reason why not? We can’t get the labels for the credential attributes, but all the static content for the app can be available in French. Just a priorities issue?

Yes just that, I believe it’s all there technically.

**Comment by cvarjao** [comment]
We are working with IDLab and will be providing French translation
