### ISSUE TITLE
Get Aries Test Harness up and running locally

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#2323]
The dev team need to get up to speed running the automated test suite for the BC Wallet. Needs to be done while QA available to answer questions.

**Comment by Musk1045** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WR240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by jleach** [comment]
Got a remote test running although it seems to crash on start. Will debug a little more but I think that's a win and maybe good enough for this ticket. Ran into some problems with the test containers and had to debug and get 'em working with ARM64 as per [this pr](https://github.com/openwallet-foundation/owl-mobile-wallet-test-harness/pull/263).

**Comment by bryce-mcmath** [comment]
All of the devs learned the ropes and had some measure of success getting the setup to work with remote tests, local tests, or both. Think this is good enough for now. One of us can do a deeper dive once the SauceLabs biometrics issue is fixed and the rest of the tests are able to run again.
