### ISSUE TITLE
Update loading screens with loading animations

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#240]
The images from the following screens are updating to their animated counterpart.

- [x] [Connection delay screen](https://xd.adobe.com/view/3db881d4-e963-42ec-a2c4-6b5ca23862a3-68eb/screen/a894d4b1-c3f5-4f4c-b2a1-f592c48e7169/) -> [Connection-loading-image.gif](https://drive.google.com/file/d/13GsIpJB-vw5w99UFbWaOy4MuUDvasDNX/view?usp=sharing)

- [x] [Issuing delay screen](https://xd.adobe.com/view/3db881d4-e963-42ec-a2c4-6b5ca23862a3-68eb/screen/5fe463ea-b1e9-40f1-a144-fb04ec2cdf01/) -> [Adding-credential-loading-image.gif](https://drive.google.com/file/d/13JxXypdWGjMS5zMkJH5Wcv6NHSFgurGO/view?usp=sharing)

- [x] [Credential added](https://xd.adobe.com/view/3db881d4-e963-42ec-a2c4-6b5ca23862a3-68eb/screen/a61d515d-3290-4fb8-90a3-2d2d36b3cc21/) ->[credential-added-image.gif](https://drive.google.com/file/d/13QoBInOpopizQaCEVp3cdAnnLvOVMZij/view?usp=sharing)

- [x] [Sending information](https://xd.adobe.com/view/74b73461-45e5-4f2b-b219-79ffe9c852a7-21e4/screen/9a1b95d0-fe2a-4917-af5d-5b0130d5ee5f) -> [Sending-information.gif](https://drive.google.com/file/d/13TeWmKupitswsI7e40KkPPEypInOWMb-/view?usp=sharing)

- [x] [Sending information - success](https://xd.adobe.com/view/74b73461-45e5-4f2b-b219-79ffe9c852a7-21e4/screen/be44c7f0-4663-449b-9934-c86be5fedfbc/) -> [Sending-information-success.gif](https://drive.google.com/file/d/13YPwvu90abN-vCVGrv-leXtLD43xQkfk/view?usp=sharing)

- [ ] [Sending information - fail](https://xd.adobe.com/view/4193cf78-97a9-423e-8229-e27ad896e3fe-14c0/) -> [Sending-information-fail.gif](https://drive.google.com/file/d/13gUWNvj82pcNf5eE2X4yQkkRpcZBcKv9/view?usp=sharing)

**Comment by jleach** [comment]
@amanji Think we should use GIFs or use SVGs with a transform / animation? Looks like animated gifs require some extra packages to work.

**Comment by amanji** [comment]
The SVGs might work out of the box for us. Worth a try IMO

**Comment by jleach** [comment]
Looking into this.

**Comment by jleach** [comment]
@knguyenBC For the various sending animations. Would it work, at least for M1, to use the same circle as connection loading but just change the graphic in the centre? Would be a bit faster. For the success / fail we could swap that graphic out for the check or X graphic. LMK.

**Comment by knguyenBC** [comment]
Something like this? 
![image](https://user-images.githubusercontent.com/68872187/165148568-93fe69f3-3f57-4b2b-9b49-9c436b3136ba.png)

**Comment by jleach** [comment]
Sure, that'll work better. Was thinking I could replace everything in the circle with the check or the X but in any case this'll work better (more reusable and simple to animate).

**Comment by jleach** [comment]
@knguyenBC Can we do the same for [this](https://drive.google.com/file/d/13JxXypdWGjMS5zMkJH5Wcv6NHSFgurGO/view?usp=sharing) animation, least for M1? It will be a little hard to animate those lines - might not be worth the hours for M1.

**Comment by knguyenBC** [comment]
@jleach How about if the animation is simplified like this: 
![image](https://user-images.githubusercontent.com/68872187/165166950-e82fea37-40cb-481b-a134-dda8e06369e3.png)
Similar to this gif: https://zellusmarketing.com/wp-content/uploads/2021/02/Email-Gif-1.gif

**Comment by jleach** [comment]
@knguyenBC Ok, I've made the loop for now w/o the blue lines at the top. I'll create a bug to add those in a later iteration.

**Comment by jleach** [comment]
For those new sending images above, are you able to add them to XD so I can export them?

**Comment by knguyenBC** [comment]
The images in the XD file now.

**Comment by jleach** [comment]
The finial animation, sending fail, isn't really doable because I don't have any state to tell me that it failed. This is all dealt with at the AFJ layer and we don't get any feedback. My options for state are:

```
export declare enum ProofState {
    ProposalSent = "proposal-sent",
    ProposalReceived = "proposal-received",
    RequestSent = "request-sent",
    RequestReceived = "request-received",
    PresentationSent = "presentation-sent",
    PresentationReceived = "presentation-received",
    Declined = "declined",
    Done = "done"
}
```

There might be an option in the future for the agent to [report a problem](https://github.com/hyperledger/aries-rfcs/blob/main/features/0035-report-problem/README.md).

**Comment by jleach** [comment]
On todays Bifold UG call James noted, as I did above, this will be more doable with the "report a problem" API.
