### ISSUE TITLE
Getting the BC VC Pilot Credential -- initiated from BC Wallet

### ISSUE THREAD

**Issue by swcurran** [bcgov/bc-wallet-mobile#241]
We plan to have a limited distribution VC used to control who can receive the IDIM Person VC.  For now, we are implementing that with the a standard deployment of Issuer Kit, as outlined. [here](https://github.com/bcgov/trust-over-ip-configurations/issues/84). This issue proposes an alternative flow that is based on the idea of the Holder initiating the issuance from the BC Wallet, using (more or less) the same technique as we'll use with the flow for getting the IDIM Person VC.

Flow:
[Wireframes depicting the suggested flow](https://xd.adobe.com/view/de0de348-9fef-481b-864e-d6c295e1e4cc-8b5e/)

- We have an Admin Console, similar to what we have with the Issuer Kit admin console to allow for the manual entry of data about VC holders, and then trigger the sending of an email to the Holder-to-be.
     - A difference in this implementation is that a shorter (6 digit) code is used for the access token, and it is printed in the email for the user to see, not as a query parameter on a URL.
     - The email still coaches them to get and install the BC Wallet.
- After installation of the wallet, the lack of a BC VC Pilot credential results in the display of a link to get the VC.
     - This functionality should be a new configuration of the planned approach to get an IDIM Person VC.
     - Ideally the configuration allows the same technique to be used for both -- I'll get to that later (see below 'generalization").
- On click the button, the user goes to an instruction screen with a button to click.
- Button triggers the same flow as is planned with IDIM:
    - a connection is established with the BC VC Pilot Issuer
    - then a web session is opened in a secure browser session (embedded in the BC Wallet) to a give URL with a query parameter of the `thid` of the DID Exchange protocol.
    - Stuff happens (below) in the web session and then it exits back to the wallet.
- On return to the wallet, a credential issuance from the BC VC Pilot Issuer will occur.
- Done -- and since the BC Wallet now has a BC VC Pilot Credential, the button for IDIM connection/flow is now visible.

The web app behaviour for the BC VC Pilot is as follows:

- Landing page opens with text and request for the access token code from the email.
- User enters their code (assuming they know it). 
- App looks up the code entered in the user list (admin DB)
    - Print error and allow retry or cancel if not found/expired
- Display screen with instructions and a "Close" button (or comparably named)
- Close the browser and return to the steps above.

### Generalizing this functionality:

This technique of a BC Wallet triggering a connection to an issuer should be generalized, with the following parameters:

- The public DID of the issuer
- The URL of the issuer
- The name of the button to display for initiating the interaction from BC Wallet
- Text for the screen to get started
- A condition for when to display the button for initiating the interaction
    - this is likely the trickiest part, as we need a way to say things like "I have VC of type X, but not a VC of type Y".

The Wallet registration process might be an array of these triggers that are checked regularly until all are complete. This would allow, for example, the BC Wallet user to get the BC VC Pilot credential, and then get the IDIM Person VC in sequenced.  Later, we might use this to get credentials from the BC Wallet publisher credential, to verify the type of wallet.

**Comment by jleach** [comment]
Relates to #168

**Comment by jleach** [comment]
I think this is done as per the steps outlined in #407. Next steps are to polish the UI and take it from "Crawl" to "Walk"
