### ISSUE TITLE
Create PIN screen issues

### ISSUE THREAD

**Issue by alexgmetcalf** [bcgov/bc-wallet-mobile#242]
- [x] Add a top heading: “Create a PIN”
- [x] Add a top paragraph below that heading: “Enter a six-digit PIN to secure your Wallet.”
- [x] Change first label to “Enter PIN”
- [x] Change second label to “Re-enter PIN”
- [x] Change button label to “Create PIN”
- [x] Change the placeholder text in both fields to "Six-digit PIN"
- [x] If the enter field is empty, change the error message to "You need to create a six-digit PIN to use BC Wallet."
- [x] Do not allow decimal points in PIN, ideally by disabling the decimal point as an input option in the numeric keypad. If not possible, and if decimal points are used, display the error message: “Please use only numbers in your PIN, without a decimal point.”
- [x] If the PIN is too short, change the error message to "Your PIN must be six digits in length." Ideally, blank the fields after the error message is dismissed.
- [x] If PINs don’t match but are both six digits in length, change error message to: “The entered PINs do not match. Please try again.” Ideally, blank the fields after the error message is dismissed.
- [ ] If nothing entered in re-enter field, change error message to: “Please re-enter your PIN.”
- [ ] If PIN in re-enter field is too short, change error message to be the ‘do not match’ error message. Ideally, blank the fields after the error message is dismissed.
- [ ] If re-enter field automatically loses focus after sixth digit is entered (i.e. the current behaviour), consider also auto-switching focus from enter field to re-enter field when the sixth digit is typed into the enter field.

Wireframes detailing PIN design here: 
https://xd.adobe.com/view/35c82052-5c29-4343-bab0-7dc84cebb129-609b/screen/62425d77-fc48-48bb-a5ed-66572f8e0380/ 

NOTE: If complicated, we can delay the show/hide password button

References:
- https://www.npmjs.com/package/react-native-pin-entry
- https://www.npmjs.com/package/react-native-smooth-pincode-input

**Comment by jleach** [comment]
@alexgmetcalf Mustafa from Ontario is working to integrate the new PIN mechanics. Should crush all the above mentioned issues with one broad stroke.

**Comment by jleach** [comment]
Mustafa has integrated a PR with groundwork. He's going to work on integrating the rest of the PIN / security improvements.

**Comment by knguyenBC** [comment]
Per our conversation, I updated the design so that the PIN uses a single theme. Here's a video for intended smooth transitions between the OS loading screen>PIN input>Loading Screen>BC Wallet Home. Let me know if this is doable.
https://images.zenhubusercontent.com/429950091/b54bf6c9-5503-486a-a21a-4cc38f283130/adobe_xd_2022_06_01_16_26_25.mp4

Also a link to the wireframes: 
https://xd.adobe.com/view/bbcb53d6-8df0-440b-9549-3da805362bf6-ee98/
