### ISSUE TITLE
Support Deep links

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#253]
The wallet needs to support deep links for common functionality so that issuing and presenting from browser sessions on the same device are supported (i.e. without QR codes).

Implementing the `didcomm://` and `bcwallet://` protocol. 

As example, our [demo app](https://bc-wallet-demo.apps.silver.devops.gov.bc.ca/demo) support a "open in wallet" link:

#### Scenario: User only have BC Wallet installed using a link with bcwallet:// protocol
Given that the user is on the demo website on their phone with a QR Code being displayed
When the user clicks on "Open in BC Wallet" (bcwallet://)
Then BC Wallet is open and the user continue with the protocol

#### Scenario: User only have BC Wallet installed using a link with didcomm:// protocol
Given that the user has a link to "Open in Wallet (Webpage, email, etc) on their phone with a QR Code being displayed
When the user clicks on "Open in Wallet" (didcomm://)
Then BC Wallet is open and the user continue with the protocol

#### Scenario: User has no wallets installed that implements "bcwallet://" protocol
Out of Scope

#### Scenario: User has multiple wallets installed that implements "bcwallet://" protocol
Out of Scope

Future Work:
- Listen for a domain instead of custom protocol.

**Comment by alexgmetcalf** [comment]
@cvarjao Question raised from @swcurran about when we'll see this in the wallet. Have assigned it a high priority to at least update team on ETA.

**Comment by jleach** [comment]
@cvarjao What will be the payload in the URLs? For example, will it be `bcwallet://example.com?c_u=abcqwe` where `c_u` is a typical invitation? Or do we just want the wallet to open and do nothing for those protocols?
