### ISSUE TITLE
Receiving a proof request and offer in succession

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#260]
In some cases, issuers might want to verify their holders identity before sending them their credentials via VCs. The process currently is connect->request-> home->offer notification.

This ticket is to explore streamlining this flow.

It might be helpful to look into [Action Menu Protocol](https://github.com/hyperledger/aries-rfcs/tree/main/features/0509-action-menu)

**Comment by cvarjao** [comment]
This is partially addressed by using goal codes. When using [aries.vc.issue](https://github.com/hyperledger/aries-rfcs/tree/main/concepts/0519-goal-codes#ariesvcissue), the any presentation request received before the issuance will be presented, and the flow ends with the credential acceptance. Might be improved in the future with more granular defined flows.
