### ISSUE TITLE
support for imageUrl in invitation

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#275]
This can potentially provides a default icon for credentials issued from a connection. Or show a logo for the verifier on a proof request?

for AIP1:
```
{
"@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/connections/1.0/invitation",
"@id": "d50a86d1-4a0e-4261-b96e-d95f84a7dac3",
"recipientKeys": ["7UsJMdBHBGKR5cZAF3WCZvgvPKufX4gq7c6RnsAwf37m"],
"label": "faber.agent",
"imageUrl": "https://robots.txt/ian",
"serviceEndpoint": "http://host.docker.internal:8020"
}
```
see `imageUrl`

for AIP2:
```
???
```

**Comment by wadeking98** [comment]
I know this is supported in some wallets. If you run through the BC Wallet demo with Lissi it will display the logo. I could probably get this working quickly, the question is if we want to pursue this since it will probably be replaced by OCA styling in the future

**Comment by wadeking98** [comment]
resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/648

**Comment by nodlesh** [comment]
@wadeking98 How is this testable with BC Wallet at this time?

**Comment by nodlesh** [comment]
@wadeking98 How is this testable with BC Wallet at this time?

**Comment by nodlesh** [comment]
@wadeking98 How is this testable with BC Wallet at this time?
