### ISSUE TITLE
Understanding  what is being proposed by ON

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#276]
Ask ON to create a discussion topic in [bifold](https://github.com/hyperledger/aries-mobile-agent-react-native/discussions/categories/ideas)

**Comment by alexgmetcalf** [comment]
Draft / exploratory flow diagrams for ON security approach are available and I've reviewed them. Waiting to see how how the delivered dev work matches up.

**Comment by alexgmetcalf** [comment]
We have all the knowledge we need from this I suggest.
