### ISSUE TITLE
How to demo BCLS workflow?

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#28]
What is the BCLS test environment?
What is the Court  Services test environment?

https://github.com/bcgov/law-society-demo/blob/master/docs/Demo.md

**Comment by cvarjao** [comment]
Court Services team is working on providing a recorded demo

**Comment by WadeBarnes** [comment]
We used to have this demo app hosted in openshift; https://github.com/bcgov/law-society-demo/blob/master/docs/Demo.md

**Comment by cvarjao** [comment]
I got access to a test account
