### ISSUE TITLE
Pipeline runs should include checks

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#280]
**Build Pipeline**

When a build pipeline is run, the following checks should be included:

- [ ] Running tests agains our bespoke code;
- [ ] Run code quality agains our bespoke code;

**Hooks Should be Triggered**

- [ ] When a developer commits / pushes code Husky should run the appropriate checks agains bespoke code.

**Comment by bryce-mcmath** [comment]
Done as part of my linting work, PR up
