### ISSUE TITLE
Onboarding screens have reverted back to lorem ipsum.  

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#285]
Onboarding screens use old graphics and lorem ipsum. On iOS, iPhone SE, BC Wallet v1.0.1 build 155.

https://images.zenhubusercontent.com/429950091/35b72fca-9a2d-4ad1-9728-66e55f6020d6/20220421_1317520636_trimmed.mp4

**Comment by jleach** [comment]
@knguyenBC The tutorial content was fixed by @cvarjao today or yesterday and I just put in a PR for the new TOS fixes noted in #222. Next build should be looking good!
