### ISSUE TITLE
Automatically open proof request or credential offer when a connection is made

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#29]
**User stories**

As a holder I want the proof request or credential offer to be presented automatically right after scanning a QR code from a verifier or issuer so that I don't have to manually open the request or offer myself.

**Background**
User research has observed moments of confusion in between the process of scanning a QR code and receiving a credential offer or proof request. Many factors play into this confusion:
- Users see the "success" notification of a connection and assume that the process is done and begin putting the phone away. They expect to have a credential in their wallet or access to the service when a connection was made.
- Users are taken to the home screen (Trinsic) and nothing happens. They're not sure what to do next.

The purpose of this ticket is to linearize the process in receiving a credential or accepting a proof request. Users are taken to a loading screen. This loading screen is when the wallet and the issuer or verifier is making a connection and then sending them either a credential offer or proof request that **opens automatically** (no notification is received from the perspective of the user. From their perspective, they automatically are taken to the intended flow). This solution removes the confusion of when a flow is complete with loading screens and eliminates the unnecessary selection of a notification to open up the offer or request. 

#### Scenario: [Presenting a credential](https://xd.adobe.com/view/74b73461-45e5-4f2b-b219-79ffe9c852a7-21e4/)
Given Wallet has been setup
When holder scans a QR Code to connect
Then the user is taken to the "Connecting..." screen, AND waits for presentation request
  AND then automatically taken to a the "presentation request" screen
  AND there is an "Approve" Button
  AND there is a "Decline" Button

#### Scenario: [Receiving a credential](https://xd.adobe.com/view/3db881d4-e963-42ec-a2c4-6b5ca23862a3-68eb/)
Given Wallet has been setup
When holder scans a QR Code to connect
Then the user is taken to the "Connecting..." screen, AND waits for a credential offer
  AND the automatically taken to a the "credential offer" screen
  AND there is a "Accept" Button
  AND there is a "Decline" Button

Note: Is there any hint for the purpose of establishing a connection? For Issuing credential, or for verifying credential? 

Reference:
https://github.com/hyperledger/aries-rfcs/blob/main/features/0023-did-exchange/README.md
https://github.com/hyperledger/aries-rfcs/blob/main/concepts/0519-goal-codes/README.md

**Comment by cvarjao** [comment]
@knguyenBC, do we have a link to a wireframe for this?

**Comment by nodlesh** [comment]
@knguyenBC I think the `Presenting a credential` link in the description is not setup to point to the wireframes.

**Comment by knguyenBC** [comment]
@nodlesh fixed the link. Sorry.
