### ISSUE TITLE
Proof Request requested fields not showing correctly

### ISSUE THREAD

**Issue by fernandohar** [bcgov/bc-wallet-mobile#302]
The issue started with build 155, When viewing details of New Proof Request, requested fields are displayed as "Not available in your wallet" even though they actually exist in the wallet. The "Share" button is displayed (expected and correct behavior)
![IMG_6214](https://user-images.githubusercontent.com/13148965/165825231-df71a7e0-a4bb-4d3a-8f1d-8c8b79066aba.PNG)

There was no such problem with build 134.

**Comment by cvarjao** [comment]
@fernandohar , this issue should have been fixed on build 185
