### ISSUE TITLE
Add skeleton loading during proof request initialization

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#304]
Currently, the when the proof request is being loaded, the content displays X Not Available until the content is loaded. There should be some sort of loading element such as a skeleton load. 

Wireframes:
![image.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/26cc12ee-39f3-4e36-a0fe-c4874d3a7775)

Skeleton loading animation example (ignore the layout, the purpose is to show how the skeleton loading is animated):
https://xd.adobe.com/view/d4081c88-476a-4640-9bf8-85e9e28a9d63-815b/

**Comment by jleach** [comment]
Looking into what we can do about this one.

**Comment by jleach** [comment]
I though this might make a good skeleton loading animation:

![screen-gif](https://media.giphy.com/media/qTD9EXZRgI1y0/giphy.gif)

**Comment by cvarjao** [comment]
@knguyenBC  will do some investigation on a reusable loading component.
