### ISSUE TITLE
Missing blue bar on top of "Decline screen"

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#314]
Missing blue bar on top of decline screen. Blue bar features the title labelled "Decline credential?" and a home button.

Wireframe for reference
![image.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/27bd5f4a-eee7-49e7-864b-7676e3acf5a3)

**Comment by jleach** [comment]
@cvarjao @knguyenBC Can add for sure. Do we need the "home" button in the top right? Reading through the Apple's thoughts on the subject usually a modal requires people to make a decision to escape it. We're providing an escape hatch that doesn't move the process forward - no?

https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/modality/

**Comment by knguyenBC** [comment]
The home button acts as a way for people to escape/dismiss the modal. We want to avoid using "cancel" or "dismiss" to avoid people thinking that that's a way to decline the offer/request. I would keep it in for now.
