### ISSUE TITLE
Connectionless proof request stuck on "Sending the information securely"

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#319]
Introduce a intermediate screen that shows something along the line "Your information has been sent".

Add a new modal for connectionless proof requests:
![image.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/ad5ffbd5-6f6f-4c60-bb18-6fb20d95f55f)

In comparison to to updating the old modal for connected proof requests
![image.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/29ec1c38-b415-44eb-a1c0-026ecfe0abf0)

**Comment by knguyenBC** [comment]
Added modal design for connectionless proof requests
