### ISSUE TITLE
Failed Connection to Mediator is not being handled and user can use app, but gets errors on scans.

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#326]
**Steps to Reproduce:**
Starting the wallet from a fresh install, when the wallet fails to connect to the mediator, there is nothing different to the user except no mediator in the contacts screen. There is no error, and the initialization message displays and disappears as if all was ok. The user, if they don't go into contacts, (which they won't) will press scan to scan a qr code and then get a message stating `Unable to accept connection`.

When closing the app and reopening the app, the user will again see the initialization message again and it will go away as if no problem. There is still no connection to the mediator listed in the contacts screen. 

**What was Expected:**

- The wallet shouldn’t let you do anything until there is a successful connection to the mediator. 
- The wallet should let me know it can't connect to the Mediator.
- The wallet should let me know what my next steps are if I can't connect to the Mediator.

**Environment:**
Reproduced in Sauce Labs on iOS and Android, along with my own local iPhone. 
Build 164

**Workaround:** 
Have a successful connection to the mediator. However in the automated acceptance tests we are failing to connect to the mediator more than we are successful. This is a blocker for the automated tests.

**Severity:**
High

**Priority:**
High

**Comment by jleach** [comment]
Should be un-blocked in Build 171.

**Comment by amanji** [comment]
@alexgmetcalf Could I get some guidance on message wording for this?

**Comment by amanji** [comment]
We need messaging for this. Should it be similar to when there is an unsuccessful login?

**Comment by alexgmetcalf** [comment]
Blast from the past. I'll get wording for you.
