### ISSUE TITLE
The text below modal overlaps the go back to home button

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#328]
During the connection modal loading screen, when the text appears below during a delay, it overlaps the button as seen below.
![image.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/67e19a59-2d7a-4166-af51-623260d95ce1)

**Comment by amanji** [comment]
This is an issue that specifically affects smaller screens, so those need to be tested against
