### ISSUE TITLE
Proof request "Details" button should be in blue

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#332]

**Comment by knguyenBC** [comment]
Please use link colour: #1A5A96

**Comment by cvarjao** [comment]
When clicking on details from the proof request screen immediately after scanning a QR Code there is no back button

**Comment by nodlesh** [comment]
@jleach has the back button been added as part of this ticket as well or do we need a new bug for that?

**Comment by jleach** [comment]
@nodlesh Will be fixed.
