### ISSUE TITLE
Status bar content fades into light grey background

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#336]
Status bar background be black with 40% opacity to ensure proper text contrast.

Link to styleguide: https://xd.adobe.com/view/1ac84b48-4eed-4334-a59a-9a99e3633e1b-4f9b/screen/1c09d1cc-17e4-44b7-8535-3a1ee2b141c7/

ex. 
![image.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/41d827e7-9b48-4dcb-b0c2-e187d6a19438)

**Comment by knguyenBC** [comment]
The status bar during proof request and credential offer loading screens now has black text on a blue background, rendering the status bar illegible.  on android (build 175). ![20220517_112748.jpg](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/363d934c-40c3-4ebf-b0d1-7ac62d3da9f0)
![20220517_113608.jpg](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/a3381750-506e-4db4-b382-718cc61c8be3)

**Comment by knguyenBC** [comment]
On iPhone SE: loading screen still has status bar as white text on a light background

![20220517_150843.jpg](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/c66cf6f7-6fe7-41ee-86fb-140067eb0b2a)

**Comment by knguyenBC** [comment]
Also effecting the PIN creation screen

**Comment by jleach** [comment]
I have one last PR in to try and fix this. If it does not work well on both iOS and Android we will need to hide the status bar.
