### ISSUE TITLE
Unable to Receive LSBC Credential (TEST)

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#337]
- Similar to #338
- Check with Wade B. if TEST/PROD have the same configuration

**Comment by knguyenBC** [comment]
Credential offer and proof request worked for my device.
On android OS: version 11.1.2.2
phone model: oneplus 
app build: 1.0.1-165
Credential type: test
video: https://drive.google.com/file/d/18JGUN1kdqPxl6BEu7TrLMnJc-URJFbxg/view?usp=sharing
