### ISSUE TITLE
Determine what to do with chat functionality

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#340]
In recent PRs chat functionality has been introduced. We need to decide what to do with it.

![IMG_0BE309857F9B-1.jpeg](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/8d37b633-9468-4f74-be71-29bc2560341c)

**Comment by knguyenBC** [comment]
Disable the chat feature. Keep the contacts list.
