### ISSUE TITLE
Revoked credential UI is wrong

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#343]
Revoked UI red colour does not follow the style guide and design.

![20220517_110424.jpg](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/17fbba01-18a5-495d-a8b0-fa7112e87948)

![20220517_110601.jpg](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/b4a26963-9974-4643-992f-27c0dfaecd1e)

**Comment by jleach** [comment]
@knguyenBC I can change the color to match but we don't have a revocation date so I won't be able to show "Revoked: May 31, 2021"

**Comment by jleach** [comment]
Ok, colour updated in the next build. Still cannot put the label "Revoked: May 31, 2021" in because we don't have that data. Best to move it to M2 or M3 designs.

![Screen Shot 2022-05-19 at 3.09.15 PM.png](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/3539daff-3a1a-4a3f-ad86-cc4a1ed9bf1e)

**Comment by knguyenBC** [comment]
> Ok, colour updated in the next build. Still cannot put the label "Revoked: May 31, 2021" in because we don't have that data. Best to move it to M2 or M3 designs.
> 
> ![Screen Shot 2022-05-19 at 3.09.15 PM.png](https://camo.githubusercontent.com/8126569277fe72863da343e94d72c9570865d5daa63d5e8ad2fac027b9113cf3/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563326661316237636534663636333831636438643032642f33353339646166662d336131612d346133662d616438362d636334613165643962663165)

That's fine. It can just say "revoked" and the date can be left out.

**Comment by knguyenBC** [comment]
The updates didn't carry over in the latest build (179). I still see the same as the initial screenshot posted in the ticket.

**Comment by knguyenBC** [comment]
The updates didn't carry over in the latest build (179). I still see the same as the initial screenshot posted in the ticket.

**Comment by knguyenBC** [comment]
![20220530_143226.jpg](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/3cd0fea3-3049-48ef-9625-f887d14faf6c) Still not correct UI.
