### ISSUE TITLE
Revoked credentials aren't rendering with the revoked credential UI after a proof request

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#344]
After a proof request, all revoked credentials no longer appear with the revoked credential UI. 

The screenshot was taken after a proof request. All but one (the top one) should be red. 
![20220517_113956.jpg](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/210c5768-3760-45ea-a727-2f4f0b9fdd9d)

**Comment by cvarjao** [comment]
There is an ongoing problem with revoking credential which it means that there are multiple non-revoked credentials. This is issue is being tracked outside of the wallet.
