### ISSUE TITLE
content below loading animation overlaps other content on screen

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#345]
The content "this is taking longer than usual..." overlaps the go back to home button when the content appears. The screenshot below is from an iPhone SE.

![20220517_150447.jpg](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/4a2a59fe-f0f1-44d2-8e39-6c637842acae)

**Comment by cvarjao** [comment]
Should we support old devices?

**Comment by amanji** [comment]
This is an issue that specifically affects smaller screens, so those need to be tested against
