### ISSUE TITLE
Proof request loading animation transition to be smoother

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#347]
transition from the "sending information securely" modal to the "information sent successfully" modal is a jumpy. animation block is not aligned and therefore the transition is not as smooth.

https://images.zenhubusercontent.com/429950091/a3b2fdfd-b6d0-42e9-8eed-bbfea0292bfc/20220517_1545257497.mp4

**Comment by hannahgov** [comment]
I tested this out on version 203 will test on 277 once I have it on android
