### ISSUE TITLE
Declining a presentation of a revoked credential traps user on "Proof request declined" screen on iOS

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#350]
**Steps to Reproduce**
Have Zoomed turned on in Display and Brightness.
Have a credential issues and revoked
A verifier sends a proof request for the revoked credential
The holder denies the presentation, it is actually the only option they have in this case
At that point they get the Proof Request Declined screen with no buttons to get out

![IMG_0163.PNG](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/af3670d7-8b16-48f6-a3dc-ce24e002aab4)

**Environment**
Have only tested on iOS with zoomed view turned on.

**Workaround**
You have to close the app and reopen to get back to the home screen. 

**Possible Root Causes**
On this iPhone I have zoomed view turned on (Accessibility). This may push the button out of the view port but no scrolling is possible. It may happen on Android as well if the zoomed option exists.

**Priority**
Medium

**Severity**
Medium

**Comment by cvarjao** [comment]
Needs a spike to look into zoom features for both iOS and Android

**Comment by cvarjao** [comment]
fixed
