### ISSUE TITLE
App not formatting properly with zoomed view selected for iOS (Accessibility)

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#351]
**Steps to Reproduce**
On iOS Select Zoomed in Display and Brightness.
![IMG_0164.PNG](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/7ff2e4bf-4e5f-46cc-985c-7997b8ce93ac)

**Result**
![IMG_0161 2.jpg](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/80895301-d6e9-4f27-82bd-fb85e09db2f5)

![IMG_0162.PNG](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/4b6219d7-b724-4361-aa90-b818c492832f)

**Workaround**
Don't have zoom turned on

**Priority**
Medium

**Severity**
Low

### Solution
Enable scrolling for the entire app.

**Comment by knguyenBC** [comment]
more examples from someone who is testing the app with enlarged text enabled on their device: ![image.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/201d5d6f-a96e-4a9d-9bf6-8d2c39ac6171) screenshot is from iPhone X, OS version 15.6.1

**Comment by knguyenBC** [comment]
Can this be solved by allowing scrolling in the app?
