### ISSUE TITLE
Unable to present revoked credential

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#352]
If a verifier is not explicitly requesting proof of non revocation, the holder should be able to send a revoked credential

**Comment by nodlesh** [comment]
This bug can be reproduced with AATH test T001.2-HIPE0011 here https://github.com/hyperledger/aries-agent-test-harness/blob/e1a6c9569236c2bd4aaf32b296daf71c3b2db53e/aries-test-harness/features/0183-revocation.feature#L44

**Comment by jleach** [comment]
Current ticket touches on this so I'm going to do it at the same time.
