### ISSUE TITLE
An error message suddenly appears after opening a proof request notification

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#358]
After receiving a proof request notification in the wallet. Opening the proof request, an error message appears. After dismissing the error message however, the proof request flow continues as intended. See video below. (error message appears at 7s).

Build 184, Android. Tried it with Access to Court Materials.

https://images.zenhubusercontent.com/429950091/d75604c2-0be0-4014-9170-cb3818dcfff8/20220524_0957197168.mp4

**Comment by amanji** [comment]
Do you recall what service this was for?

**Comment by amanji** [comment]
If you are using the Animo Demo (demo.animo.id) The error is caused by a Credential Definition not found on Sovrin Staging Net. Here is the error log:

```
 ERROR  ERROR: Error retrieving schema 'q7ATwTYbQDgiigVijUAej:2:Animo ID:1.1' from ledger 'SovrinStagingNet' {
  "error": {
    "name": "IndyError",
    "message": "IndySdk: Error Domain=IndyErrorDomain Code=309 \"(null)\" UserInfo={message=Error: Item not found on ledger\n  Caused by: Structure doesn't correspond to type. Most probably not found\n  Caused by: data did not match any variant of untagged enum Reply\n, indy_backtrace=}",
    "indyCode": 309,
    "indyName": "LedgerNotFound",
    "indyCurrentErrorJson": null
  },
  "schemaId": "q7ATwTYbQDgiigVijUAej:2:Animo ID:1.1"
}
 ERROR  [IndySdkError: IndyError(LedgerNotFound): IndySdk: Error Domain=IndyErrorDomain Code=309 "(null)" UserInfo={message=Error: Item not found on ledger
  Caused by: Structure doesn't correspond to type. Most probably not found
  Caused by: data did not match any variant of untagged enum Reply
, indy_backtrace=}]
```

This issue is not specific to BC Wallet or Bifold. Taking a look at Indy Scan and this Credential Definition is not published on Sovrin Staging Net.

**Comment by knguyenBC** [comment]
> Do you recall what service this was for?

I used the test credentials with the Access to court materials service

**Comment by amanji** [comment]
Unable to reproduce this on iOS or Android Emulator either for LSBC Demo

**Comment by knguyenBC** [comment]
Doesn't happen on iOS for me. iPhone SE, build 184, tried on access to court materials service. It does however hang on the "connecting" modal. https://images.zenhubusercontent.com/429950091/93332588-2483-4abb-b34a-5370175a0a50/20220524_1447473559.mp4
