### ISSUE TITLE
Clean up error codes, and error message screen

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#361]
- [x] Do a pass of where errors are thrown
- [x] Make error codes unique (where)
- [x] Show the underline error message (why)
- [x] Make error codes translatable
- [x] Extract codes and message to spreadsheet

Style guide:
[Guidance
](https://xd.adobe.com/view/1ac84b48-4eed-4334-a59a-9a99e3633e1b-4f9b/ )

Wireframes:
[Details on how to present error codes
](https://xd.adobe.com/view/4f9b250e-27d3-4d8b-af48-c6b90520d0ee-1ac8/screen/f335271e-7999-4fe4-a09f-61b66444873e)

**Comment by cvarjao** [comment]
Todo:
- [ ] Provide a list of error codes and their respective title and description.
- [ ] Localized/translatable error title/description

**Comment by jleach** [comment]
Here are the error codes and messages in an Excel file. [Bifold Error Codes](https://app.zenhub.com/files/429950091/8f2d657d-10d4-41e2-8100-093731abaff8/download)

**Comment by jleach** [comment]
Created [PR#359](https://github.com/hyperledger/aries-mobile-agent-react-native/pull/359). Checking with ID labs to see if they can create the Fr translations for the error messages.

**Comment by alexgmetcalf** [comment]
Updated error messages
[wallet-errors.xlsx](https://github.com/bcgov/bc-wallet-mobile/files/8994510/wallet-errors.xlsx)
.

**Comment by alexgmetcalf** [comment]
I don't have a way to test this... @amanji @jleach can you advise on how I can review? Then we can close this off.
