### ISSUE TITLE
Error when scanning a QR code for proof request (error 1026)

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#362]
![Clipboard - May 24, 2022 11_32 AM.png](https://images.zenhubusercontent.com/5c75a872bb88ef3edd6c33ec/a79831b7-8e9d-40ff-84c0-4c5d1baa7fec)

**Comment by amanji** [comment]
Issue related to revocation in LSBC. Not sure if its something we can handle in the wallet.

**Comment by cvarjao** [comment]
Being fixed in the aca-py project
