### ISSUE TITLE
Revocation

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#37]
**User Stories**
- As a holder I want to be notified as soon as possible when a credential in my wallet has been revoked, so I understand and feel comfortable with the state of my wallet.
- As a holder I expect the wallet to use the minimum data and external communications possible to identify revoked credentials, so I feel confident my wallet is working within any data limits my device may have.
- As a holder I expect it to be clear that a presentation has failed because of a revoked credential, so I can take any desired remedial action.

**Background**

Credential revocation will be supported in v1.0.

Once an issuer revokes a credential and the ledger is updated, there are three options for the wallet to identify that a credential it holds has been revoked:

1. Use an existing connection between the holder and the issuer, where the issuer proactively notifies the holder that the credential has been revoked. There is no protocol for this in AIP 1.0 but there is in AIP 2.0, so this is not a workable Wallet v1.0 approach.

2. Have the wallet poll the ledger at regular intervals, and/or when certain wallet actions are taken. For example, the wallet could poll the ledger once a day, or upon opening / waking.

3. (Required as part of AIP 1.0 protocols) When a presentation is sent, the verifier agent may inform the wallet that the presentation failed because one or more credentials was identified as revoked. The wallet then updates its registry of credentials to mark the appropriate VCs as revoked, and the user is informed.

(Note: a verifier may still choose to accept a revoked credential as part of a presentation.)

Given the nuances of these three options, Wallet v1.0 will definitely support (3) and likely support (2).

**Wireframes:**
See Adobe XD file "Collective Digital Wallet UI Design concepts"  and go to "credential list" and "credential details" section to see credential UI for revoked credentials.

**Summary revocation convo with Ian:**
https://docs.google.com/document/d/19MxZrZ519Vkrf-bx9oyRegIt2TpSixM8GN_j7Jxkahk/edit?usp=sharing 

Out of Scope:
- Offline

**Comment by nodlesh** [comment]
[Existing Revocation Integration Tests](https://github.com/hyperledger/aries-mobile-test-harness/blob/dc2435528960e4a9a6bcedde5d128d8d68d82406/aries-mobile-tests/features/bc_wallet/proof.feature#L70)

[iOS Test Results](https://allure-mobile.vonx.io/allure-docker-service-ui/projects/ios-multi-device-full)
[Android Test Results](https://allure-mobile.vonx.io/allure-docker-service-ui/projects/android-multi-device-full)

**Comment by jmdkumar08** [comment]
Done
