### ISSUE TITLE
"Added to Contacts" Notice

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#373]
When a user scans a new QR code, and a new contact is automatically added, display a "Added to Contacts" [notice](https://xd.adobe.com/view/3db881d4-e963-42ec-a2c4-6b5ca23862a3-68eb/screen/a523d262-2549-4da9-9c2e-35ba1a84d7e8/) on the Credential Offer or Presentation Request

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/407
