### ISSUE TITLE
Change information approved screen to "Information received" 

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#375]
Match content
![image.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/c6b5ad7c-3681-4f23-951e-76c713e94ab7)

Wireframes: https://xd.adobe.com/view/74b73461-45e5-4f2b-b219-79ffe9c852a7-21e4/ 

### Acceptance Criteria
Given the holder is completing a proof request with a connected organization (a contact)
When the holder selects "Send"
Then the holder is presented with an animated loading modal stating "Sending the information securely…"
And then the holder is presented with an animated loading modal stating "Information received" once a response from the verifier is received that the information was sent successfully and received
And a "Done" button is present

**Comment by nodlesh** [comment]
Proof tests will need to be updated with the screen change when implemented.

**Comment by wadeking98** [comment]
Changes completed, should I close the issue or should I wait until the test have been updated?
