### ISSUE TITLE
Refactor application navigation mechanics

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#377]
- [ ]  Navigator Stack per tab in the bottom
- [ ] Leverage Groups instead of Navigation Stack
- [ ] Modals be in 1 group, avoid using 'Modal'  component (when possible)

**Comment by jleach** [comment]
Waiting on a PR from Indecio / Ryan to be merged.

**Comment by jleach** [comment]
Waiting on a PR from Indecio / Ryan to be merged.

**Comment by hannahgov** [comment]
Will look at this in January
