### ISSUE TITLE
Random divider in specific areas

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#380]
Looks like an extra divider is hiding behind the thicker divider and extends to screen width. Should not be there.

![Screenshot_20220531-111612_.jpg](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/14e8b404-b4ac-4bc2-9b9e-3efb96a997a5)

**Comment by wadeking98** [comment]
Can't seem to reproduce. @knguyenBC can you please confirm that this is still an issue?

**Comment by knguyenBC** [comment]
It's still an issue . Updated to build 270 on android and still see them in a proof request but not a credential offer or credential details screen. But maybe its just my phone?

**Comment by wadeking98** [comment]
okay, I might have to try it on a different emulator. It's not working on my phone

**Comment by knguyenBC** [comment]
I'm using a oneplus 6, android version 11 and OxygenOS version 11.1.2.2 if that helps

**Comment by bryce-mcmath** [comment]
I've tried a few different Android devices (I don't have access to a OnePlus 6 admittedly) and I can't reproduce this on any of them or on iOS. I also went looking for where in the code a border like this could come from and couldn't find anything. It's kind of annoying little thing if it's still happening on the OnePlus but I think it's not worth being prioritized right now

**Comment by knguyenBC** [comment]
I think this is fixed. I haven't seen this issue in a while. We can close it.
