### ISSUE TITLE
App crash on iOS on wallet initialization page from fresh install w/ build 188

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#381]
Steps to Reproduce:
Starting the wallet from a fresh install on iOS, when the wallet attempts to initialize after creating a pin, the initialization screen displays for a while and then the app crashes. 

Upon reopening the app and entering your pin, the wallet initialization screen stays on screen indefinitely.

Environment:
Reproduced in Sauce Labs on iOS  along with my own local iPhone 6s.
Build 188

Video and a device log in Sauce Labs if it helps.  (need login) https://app.saucelabs.com/tests/7c2749b4b12f484b88ffacc23eb0192e#102 

Workaround:
None, I have had to rollback to build 186, where this wasn't an issue. 

Severity:
High

Priority:
High

**Comment by jleach** [comment]
Fixed in Build 190.
