### ISSUE TITLE
Add a "no internet connection" toast notification when the wallet is offline

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#386]
As a user, I want to know when my wallet is offline so that I know if my wallet is functioning properly and if I need to fix my internet connection so that it functions properly.

### Wireframes (please read comments for more guidance): 
https://xd.adobe.com/view/5ff8dab2-4b51-4f21-b9c8-7955664e17c7-0aab/

Follow the [style guide](https://xd.adobe.com/view/1ac84b48-4eed-4334-a59a-9a99e3633e1b-4f9b/screen/a9a3c1dd-b34f-4ca4-981a-4551adebf4ca/) for UI guidance.

### **Acceptance Criteria** for the crawl phase
**Scenario: [Holder opens BC Wallet while mobile phone is offline**](https://xd.adobe.com/view/5ff8dab2-4b51-4f21-b9c8-7955664e17c7-0aab/screen/3b21392d-37f3-4336-8baa-be6274bb6c42/)
Given the mobile phone does not detect internet connection
When the holder opens BC Wallet, 
And successfully enters their PIN
And initialization ends (failing silently)
Then they are presented with a dismissible "no internet connection" toast notification

**Scenario: [BC Wallet does not detect internet connection while in use](https://xd.adobe.com/view/5ff8dab2-4b51-4f21-b9c8-7955664e17c7-0aab/screen/95d60d47-cc29-4cee-ad6e-2e36134d7c77/)
Given the holder is using the app
When BC Wallet does not detect internet connectivity
Then they are presented with a dismissible "no internet connection" toast notification

**Scenario: [BC Wallet is offline and returns back online](https://xd.adobe.com/view/5ff8dab2-4b51-4f21-b9c8-7955664e17c7-0aab/screen/2c0c70e9-69c0-4412-8baf-8ff8c8b75ef8/)
Given the holder is using the app
And BC Wallet is offline
When BC Wallet suddenly goes back online
Then they are presented with a temporary "Your internet connection is back" toast notification
And the toast notification goes away after 5 seconds

**Scenario: BC Wallet is offline and holder changes screens *optional*
Given BC Wallet is offline
When the holder navigates from one screen to another screen
Then they are presented with a dismissible "no internet connection" toast notification

### References:
- https://reactnative.dev/docs/0.61/netinfo
- https://github.com/react-native-netinfo/react-native-netinfo

**Comment by alexgmetcalf** [comment]
Diagram of possible offline handling actions at each stage of core journeys: https://docs.google.com/presentation/d/138O8GMlqPeHXvAZmuGkidjy4pb8u6WkkXLlMV_B4kyQ/edit?usp=sharing

**Comment by knguyenBC** [comment]
@amanji I've updated the wireframes to match our conversations. Note that the toast notifications are placed at the base of the screen.

**Comment by nodlesh** [comment]
@knguyenBC @amanji @alexgmetcalf 
Does the app need to be online for any of the onboarding process, including creating the PIN? OR will it fail the same as the first scenario above and show the "no internet connection" after they have created the PIN and the app initializes (failing silently)?

**Comment by nodlesh** [comment]
@amanji @knguyenBC @alexgmetcalf 
A few questions here based on the Acceptance Criteria. 

The Acceptance Criteria state that when the connection is restored, a message would be displayed stating that. However, that doesn't happen. 

The No Internet connection message stays on screen if not dismissed and when the internet is restored, it remains until dismissed. 

The acceptance criteria state that moving from screen to screen will redisplay the no internet connection message. It does not. If no internet and dismissed, navigating to another screen does not display the message again. The criteria state "optional" in the title, so I assume this wasn't implemented? If so, and we still want that functionality, we should move it out of this story. 

The behaviour above is the same for both Android and iOS. 

Are these issues changes to the Acceptance Criteria or valid issues? If they are valid, then I'd recommend moving this story back to Sprint Backlog or In Progress.

**Comment by nodlesh** [comment]
@alexgmetcalf I'm assuming the diagram you posted are just recommendations of potential possibilities and not requirements outright? For example the disabled scan button is only in your diagram and not in any story formally.

**Comment by alexgmetcalf** [comment]
@nodlesh That's right, it was an exploration only 👍

**Comment by knguyenBC** [comment]
@nodlesh a message should appear stating that connection is restored. @amanji was there misalignment on what was considered crawl/walk/run? or was this missed?

The no internet connection message should be dismissible, not present another dismissible internet connection message. And, good catch, it should auto-dismiss when internet connection is restored

We can remove the optional feature for the crawl phase and move it to another phase.

We might need another huddle on this. I'll move it back to in progress.

**Comment by nodlesh** [comment]
@knguyenBC What was meant by the last scenario then?
```gherkin
Scenario: BC Wallet is offline and holder changes screens optional
Given BC Wallet is offline
When the holder navigates from one screen to another screen
Then they are presented with a dismissible "no internet connection" toast notification
```
Should this simply be the message stays on screen even when navigating from screen to screen until it is purposefully dismissed by the user? 


Also, in your wireframes, you have some explanatory text under some of the no internet messages. Should this also be implemented in this ticket or is in the walk?

**Comment by knguyenBC** [comment]
The intent for the crawl phase was to have a dismissible toast notification (i.e. a notification that can dismiss on its own after a period of time or by the user) appear when internet is offline. If the user moves from one screen to another and the notification has disappeared/been dismissed, then the notification reappears. If the user moves from one screen to another and the notification has not disappeared/been dismissed, then it'll look like the state hasn't changed. 

The notification with explanatory text is meant for, in crawl phase, to be used when the user opens their wallet when the internet is offline or when internet is offline during a proof request or credential offer flow. For the crawl phase, it was not intended to have the temporary toast notification to open another notification with explanatory text (which is what is happening now). That's a concept for walk/run phase when we'll have a persistent banner across the wallet when it goes offline. 

I think offline behaviour ticket requires another huddle
