### ISSUE TITLE
First cell focused on pin-create should be top left

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#388]
When you create a new PIN the first cell selected by default is the lower left. It should be the upper left because it'll be more consistent with usage expectations.

![IMG_31036311E049-1.jpeg](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/e4b5bb75-f60f-4283-8a21-20ca5a42b9a9)

**Comment by amanji** [comment]
Are we still seeing this in the latest build?
