### ISSUE TITLE
Status bar on PIN screen should be dark on iOS.

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#389]
The status bar should be dark or hidden on iOS depending on what the designs call for.

![IMG_31036311E049-1.jpeg](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/c1ad93b1-9a48-43d7-b345-6f1f5b527a94)

**Comment by nodlesh** [comment]
What was fixed here? Current build looks the same to me as this screenshot above.
![Screen Shot 2022-10-20 at 6.43.42 PM.png](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/52e2f4b7-8b9f-4aa3-8692-5b6299965e0e)
