### ISSUE TITLE
Details of a proof request has an unnecessary loading time

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#397]
The loading delay might not be necessary if we pass the detail from the prof request screen to the details screen

Selecting the details of an attribute in a proof request, the content takes some time to load. [See video](https://images.zenhubusercontent.com/429950091/68724ff4-1424-473a-b8e5-b1c4400fed6e/20220620_1449520057.mp4). 

While the content is loading, the placeholder text is not appropriate. It features the Anima ID label and a random date. ([see screenshot](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/1f76d9b5-6db5-4d55-b8f3-ee50d7a8adb6)):

**Comment by amanji** [comment]
Wondering if it would be worthwhile to add a loading screen/skeleton here?
