### ISSUE TITLE
Determine the feasibility of compiling Indy SDK for x86

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#4]
AFJ depends on the Indy SDK to communicate with ledgers. This SDK compiles for Arm architecture but not x86 architecture. It would be good to have it compile for both so that it can run on iOS simulators to speed up development and testing.

**Comment by cvarjao** [comment]
May be related to https://github.com/rust-lang/rust/issues/81632

**Comment by cvarjao** [comment]
Need some more testing for running on M1 Macs:
https://discord.com/channels/905194001349627914/941708242030063656/983892723637583892

**Comment by cvarjao** [comment]
We are expecting this will be addressed by the new indy vdr/shared libraries
