### ISSUE TITLE
Submit App for Review

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#401]
We would like to submit both iOS and Android version of the app for review but hold them back for manual release so that we can complete the review process and early as possible.

- [x] Submit for iTunes review
- [x] Submit for Google Play review.

**Comment by jleach** [comment]
Need to deal with #427 as part of the Google Play release.

**Comment by jleach** [comment]
Done on Jul 15th at 3:50pm

**Comment by jleach** [comment]
Updates required.

**Google Play**

As per [this video](https://www.youtube.com/watch?v=b0I1Xq_iSK4&t=57s) we need "prominent disclosure" for why the app is accessing the camera:

- [ ] Add prominent disclosure screen to Android indicating why the camera is being used and what the data will be used for;
- [ ] Add prominent disclosure to privacy policy. 

**Apple iTunes**

- [x] Update the look of the iOS screen shots so they look like iOS devices, specifically the device frame and status bar need to acutely match the look and feel of a real device.

**Comment by jleach** [comment]
Both apps are ready for release. Only outstanding issue addressed in ticket #434. Moving this issue to done.
