### ISSUE TITLE
Mediator Load/Stress test

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#404]
What to test:
- Websocket connections 
- Connecting
- Issue/Receive Credential 
- Present Credential
- Which Ledger to use? candy-dev? bcovrin?

Goals:
- Can we leverage [Aries Agent test harness](https://github.com/hyperledger/aries-agent-test-harness)?
   - Does ACA-py/AATH connects using websockets as well?

- A bunch (100 / 200 / 500 / 1000) of Vanilla ACA-py Agent running in parallel
      - Develop an issuer/verifier agent controller (ACA-py - Faber)
      - Develop holder agent (ACA-py/AFJ - Alice)
- Monitor/Report the CPU/Memory impact
- Impact of idling Websocket connection
- Outcome: Understand the impact of # connections vs response time (graph)
- Outcome: Understand how to rune the automatic scaling in OpenShift

**Comment by wadeking98** [comment]
@cvarjao can I close this now that I've done the stress test?

**Comment by swcurran** [comment]
Please share the repo and approach!  Love to see that.

**Comment by cvarjao** [comment]
@wadeking98, can you share a brief summary the results in here? Is the mediator service scalable (can it run with multiple pods)? If so, did you check if the load is being roughly evenly spread across pods?

**Comment by cvarjao** [comment]
Also, what was it covered? did it covered the receiving and forwarding of a DID message?

**Comment by wadeking98** [comment]
@swcurran here is the repo: https://github.com/wadeking98/gohammer. I've also posted it on the bcgov chat.
install the tool using `go install github.com/wadeking98/gohammer@latest`

**Comment by wadeking98** [comment]
This is how I ran the stress test:
I got the connection invitation url `https://aries-mediator-agent-dev.apps.silver.devops.gov.bc.ca?c_i=eyJlbmMiOiJ...` and used it in the tool like so `gohammer -u https://aries-mediator-agent-dev.apps.silver.devops.gov.bc.ca?c_i=eyJlbmMiOiJ4Y2h... -t 80 -dos`.
I then tried the bc wallet while the stress test was running, I only noticed about a half second delay while logging in to the BC Wallet and I was still able to accept credentials and send proof requests easily.

The agent scales well and the load seems to be distributed roughly evenly

**Comment by cvarjao** [comment]
Isn't it a bit too superficial? It seems to really just test connectivity. Maybe the initial connection to the mediator but not messaging exchange.

Any suggestion on how we can test the proof request flow? 100s or 1000s of simultaneous proof request? Since we are using websocket, does it support having millions of active connections? And 100/1000s of simultaneous messages?

**Comment by wadeking98** [comment]
it is a bit superficial, I wasn't sure how to stress test messaging exchange. My tool doesn't support websockets yet

**Comment by wadeking98** [comment]
I might need to walk through the flow with you clecio so I can get a better sense of how it works and know which parts of the mediator you want to test

**Comment by nodlesh** [comment]
This may or may not be applicable, but there is load testing tool for aries agents. 
 https://github.com/My-DIGI-ID/aries-cloudagent-loadgenerator

This is a thread on discord about Load Generation/Mediators
https://discord.com/channels/905194001349627914/1032306231756464168
The thread contains results of Mediator load testing. 

@wadeking98 We can get Ian to demo this Load Generator to us.

**Comment by cvarjao** [comment]
@WadeBarnes has ran load testing, and it is with his team
