### ISSUE TITLE
Implementation of BCSC with IDIM Phase 2

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#407]
FYI the workflow the the BCSC will be (I think this is what we all talked through):

- [x] 1. Watch for a “BC VC Pilot Certificate” credential;
- [x] 2. When the credential arrives, enable the button on the home screen;
- [x] 3. When that button it touched, use a hard-coded reusable connection invite to connect to the BSCS agent;
- [x] 4. Once a connection is established:
- [x] 5. Expect a proof request to come in asking for the “BC VC Pilot Certificate” credential;
- [x] 6. Once a proof is acknowledged, display the WebView along with the query param for the tID (1);
- [x] 7. User interacts with the WebView;

Please see a [detailed diagram of the workflow](https://app.mural.co/t/digitalidentityandtrust0399/m/digitalidentityandtrust0399/1646684933683/e94524d1dac5d1d8764a608ee9799c447431424f?wid=0-1647542875263&sender=uaf080de663fb91ec05ae1496)

TODO:
- Include a "close button"
- Authentication tab (Secure WebView) instead of WebView

**Comment by jleach** [comment]
1-8 working in the current "crawl" implementation. Pending PR review.

**Comment by nodlesh** [comment]
Tests for this feature are defined in https://github.com/hyperledger/aries-mobile-test-harness/blob/main/aries-mobile-tests/features/bc_wallet/bcsc.feature

Test results for iOS are located here, https://allure-mobile.vonx.io/allure-docker-service-ui/projects/bc-digital-id-ios

for Android here, https://allure-mobile.vonx.io/allure-docker-service-ui/projects/bc-digital-id-android
