### ISSUE TITLE
Populate the OCA Source file for the Person credential

### ISSUE THREAD

**Issue by swcurran** [bcgov/bc-wallet-mobile#410]
[Revised description: July 22, 2022]

Given that we are close to agreement on the Person credential, it would be good to get going on the OCA implementation in the Bifold Wallet.  To start, we need to have an OCA Source file for the credential that we can process.

I've taken the OCA Source file that @alexgmetcalf and @PatStLouis worked on and put it [here](https://docs.google.com/spreadsheets/d/16-MN_xcMIg43y4tveOC895vc8Tg8Od2U/edit?usp=sharing&ouid=109116496535883458301&rtpof=true&sd=true).  It is editable, so feel free to revise.

To test, do the following:

- Download the Google Sheet as an Excel (.xlsx) file (`File -> Download -> Microsoft Excel (xlsx file)`)
- Go to: https://browser.oca.argo.colossi.network/ - this is a tool to convert and preview OCA data
- Click on the "Select OCA File" and choose your downloaded Excel file
- Click on the "Convert" button
- If the "Convert" gives an error, you probably want to undo your changes - and let me (@swcurran ) know. The debugging information is not obvious...
- Click the `Click here to download OCA Bundle` button and save the file, renaming to something easy as you do (e.g., "OCABundle.zip")
- On the left menu, click the "Preview" button
- At the top, click the "Pick OCA Bundle zip file" button and pick the OCA Bundle file you just saved.
- You should see the Bundle in a "Form" view, with the ability to switch between CA-EN, and CA-FR.
  - Form view is intended for data entry, while the also available "Credential" view is intended for displaying as a credential.
  - For now, all we care about are the English and French phrases and how they will look in the Wallet.

So, the task is to load the OCA Bundle using these instructions, in parallel look at the BC/QC Wallet, envision the phrases in the credential Wallet and adjust them in the Google Sheet to get to UX that you are happy with. Iterate through the steps until you are happy.  Also -- if there is information that should be on the screen, but is not available, please add a comment here about what that is, so we can see about addressing that.

Bonus points:

* Create a second spreadsheet that is the starting point for all future OCA Source files, with instructions.
* Create another OCA Source file for the credential that we are using temporarily for those that are "part of the program" -- the one that gets the person the Person credential.

**Comment by swcurran** [comment]
Note that I'm asking @alexgmetcalf to work on this sooner than later to kickstart this OCA effort.  That is not following the Scrum methodology the team is following. Feel free to adjust the timing of this work as appropriate.

**Comment by alexgmetcalf** [comment]
[Spreadsheet](https://docs.google.com/spreadsheets/d/1i3Q6e4h7cwiP0yxLoWbwrkWXA4PHEgxhb_Rn3xOs6p8/edit?usp=sharing) updated with draft content.

**Comment by PatStLouis** [comment]
We've been contributing some translations for the Bifold project so we had a go at this. Since we don't have write permission I've created a copy and attached the .xlsx file here. All columns have been translated at the exception of the Attribute Name.

[OCA Source Pan-Canadian Person Schema.xlsx](https://github.com/bcgov/bc-wallet-mobile/files/9123380/OCA.Source.Pan-Canadian.Person.Schema.xlsx)

**Comment by swcurran** [comment]
Awesome - thanks.  I'll add these to the document.  Feel free to request access to the file.

**Comment by swcurran** [comment]
@alexgmetcalf @PatStLouis -- I've updated the description of this task to give details of how you can test and revise the spreadsheet. Note that I've used a new Google Sheet as the source so that we can collaborate on the work. The Google Sheet should be the source for the eventual OCA file we create.

As noted above, the key to the exercise is making sure that what we're putting into the spreadsheet will actually look good in the wallet, and to note anything that we need that is missing from the OCA file.
