### ISSUE TITLE
Fix Mediator trust ping response message

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#415]
Review proxy configuration

**Comment by wadeking98** [comment]
@jleach I think the reason we're not getting a ping back is because we have response_requested false here:
![image.png](https://images.zenhubusercontent.com/5fc52e1a365e55a8d5b3f428/5db4d2c0-3873-4875-a2ac-f94205b6399f)
I don't think this issue is a concern.

**Comment by jleach** [comment]
Excellent. Feel free to close.
