### ISSUE TITLE
SPIKE: Understand the message timing protocol

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#416]
The [message timing protocol](https://github.com/hyperledger/aries-rfcs/tree/main/features/0032-message-timing) might a good way to help us troubleshoot and identify slowness in the process.

- What is the message timing protocol?
- how can it help us identify slowness?
- is it supported by AFJ and ACA-py?

**Comment by jmdkumar08** [comment]
@amanji - Message timing protocol is implemented at framework level. It does not seem to point to what is causing credential delay.
