### ISSUE TITLE
Add enable biometrics screen to onboarding process

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#419]
As a user, I want to be able to choose to turn on biometrics so that I can choose the level of security for myself

### Acceptance Criteria
**Scenario: Holder has successfully created their PIN during onboarding**
Given the holder has successfully created their PIN during onboarding
When the Holder selects "Create PIN"
Then the Holder is taken to the [Biometrics page](https://xd.adobe.com/view/35c82052-5c29-4343-bab0-7dc84cebb129-609b/screen/a584635a-e2a6-4126-bbd9-baf33e6d438e)
And the option "use device biometrics" is default selected

**Scenario: Holder has chooses to use biometrics**
Given the Holder has selected to use biometrics to unlock BC Wallet
When the Holder opens the app
Then they are prompted to use their highest secure biometrics settings from their device

**Comment by nodlesh** [comment]
@alexgmetcalf @knguyenBC Was this closed because of a superseding ticket not yet implemented? Just wondering if I should ignore this one?

**Comment by nodlesh** [comment]
@alexgmetcalf @knguyenBC I think I see it in #421. If we could, maybe when we close a ticket we mention why and if relevant a takeover ticket?

**Comment by knguyenBC** [comment]
I believe there was a duplicate ticket so we closed it. putting a reason why we closed it is a good idea.

**Comment by alexgmetcalf** [comment]
Yes it was a duplicate of [#421](https://github.com/bcgov/bc-wallet-mobile/issues/421), good idea on the reasoning, I'll ask Clecio to do that going forwards. EDIT: Except I closed this one, haha, okay I'll do it too!
