### ISSUE TITLE
Add security customization in settings for enabling/disabling biometrics

### ISSUE THREAD

**Issue by alexgmetcalf** [bcgov/bc-wallet-mobile#422]
As a person who is wary of my privacy and security, I want to set my security settings to maximum security so that I can be reassured that my digital wallet will not be used maliciously

As an early-adopter, I want to customize the login experience of the app so that I can choose the option that I am comfortable with and doesn't impact the wallets convenience.

[Wireframes for Settings](https://xd.adobe.com/view/f239cc67-e22a-4178-84ae-4cf06b1dff23-a76a/) and select Biometrics in the settings to start the flow.

### Acceptance Criteria
[**Scenario: Holder enables Biometrics in app**](https://app.mural.co/t/digitalidentityandtrust0399/m/digitalidentityandtrust0399/1661808127835/fad19a32b9a164538e74a1c6c4a9897152a2ec5a?wid=0-1661816665611)
Given Biometrics is not enabled or added on their device
When the Holder selects to enable Biometrics in BC Wallet
Then an [error notification ](https://xd.adobe.com/view/f239cc67-e22a-4178-84ae-4cf06b1dff23-a76a/screen/ecde0712-a6db-473f-b05e-f0b6f0f5a785)appears
And the error notification contains a link to the device's phone settings.
And a button to dismiss the notification

Given the Holders device has fingerprint or facial data stored within their device security
When the Holder selects to enable Biometrics in BC Wallet
Then the holder is prompted enter their wallet PIN
Then the holder is prompted to confirm their biometrics
And the toggle button switches to "ON" state when fingerprint or face is verified.

**[Scenario: Holder disables biometrics in BC Wallet](https://app.mural.co/t/digitalidentityandtrust0399/m/digitalidentityandtrust0399/1661808127835/fad19a32b9a164538e74a1c6c4a9897152a2ec5a?wid=14-1661817922052)**
Given biometrics is enabled on the BC Wallet
When the Holder selects to disable biometrics in BC Wallet
Then the holder is prompted to enter their Wallet PIN

**Comment by knguyenBC** [comment]
I updated the ticket to reflect the more updated flow and added more details. The wireframes are also updated.

**Comment by knguyenBC** [comment]
Reviewed build 457. When enabling biometrics, the app does not prompt for biometrics after entering their wallet PIN.

**Comment by knguyenBC** [comment]
When enabling biometrics in BC Wallet for the first time (in setup), the app does not prompt for biometrics confirmation. See expected flow here: https://app.mural.co/t/digitalidentityandtrust0399/m/digitalidentityandtrust0399/1661808127835/fad19a32b9a164538e74a1c6c4a9897152a2ec5a?wid=0-1661816237725

**Comment by knguyenBC** [comment]
Can't cancel or go back from the PIN input screen after enabling/disabling biometrics. Please add a a header and back button to PIN input screen
