### ISSUE TITLE
Show variation of PIN screen if biometrics fail

### ISSUE THREAD

**Issue by alexgmetcalf** [bcgov/bc-wallet-mobile#426]
As a Holder, I want my wallet to have fail-safes during app entry, so that it's difficult for someone attempting to break into my wallet

As a Holder, I want my wallet to have a PIN entry fail-safe, so that if biometrics fails due to technical or environmental situations, then I can still enter into my wallet

### Acceptance Criteria

**Scenario: Holder has multiple failed attempts to open the app**
Given biometrics has been enabled on both the device and the wallet app
When there are multiple failed biometrics attempts (use OS logic on number of attempts)
Then an [alternative PIN entry screen](https://xd.adobe.com/view/af2fe4ac-c770-4f75-8666-c45602ba2443-fa7c/screen/541a37bb-f81b-4142-9b46-21a15af4fcd8) is displayed stating that biometrics was not successful and a PIN is required to enter

**Comment by jleach** [comment]
@alexgmetcalf I've done some testing and will do more but this doesn't seem doable. On iOS the call just blocks and waits when the OS triggers a time-out and neither platform tell the number of failed attempts.

Looked through the API and I don't see anything that signals back failed tries. All dealt with by the OS not the app.

Example:
On iOS if biometrics fails 3 times you get a 1 min time-out. This is done by the OS and the user can cancel. The Wallet is not informed of the 3 failed attempts or the 1 min delay. Only if it succeeds or is canceled by the user.

**Comment by jleach** [comment]
Looked through the [API](https://www.npmjs.com/package/react-native-keychain) and I don't see anything that signals back failed tries. All dealt with by the OS not the app.

**Comment by jleach** [comment]
@alexgmetcalf I believe it's possible to fallback to the PIN if if biometry fails or is canceled.

**Comment by jleach** [comment]
Nm. Looks like the wallet already falls back to PIN. We just need UI updates as best as possible.

**Comment by knguyenBC** [comment]
@jleach Did we find out if it's possible to show an alternative screen? Currently, failing biometrics prompt, the prompt informs the user that they're locked out and the user can continue to unlock their wallet using the app PIN. Although that behaviour doesn't match the acceptance criteria, it works.

**Comment by nodlesh** [comment]
Tested with build 683. 
On Android when biometrics fails, it just says try again later, but brings you back to the pin screen. That pin screen doesn't match the design in the acceptance criteria. 
On iOS when biometrics fails, it does not say try again later, but brings you back to the pin screen. That pin screen doesn't match the design in the acceptance criteria.

**Comment by wadeking98** [comment]
resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/646
