### ISSUE TITLE
Pre-OCA Styling -- convert the word "bc" to "BC"

### ISSUE THREAD

**Issue by swcurran** [bcgov/bc-wallet-mobile#429]
I ran through the ISED Business Banking Initiative issuers and verifiers, and there are several credentials issued by "bc_registries". In the BC Wallet, those are displayed as "Bc Registries".  Although this will be dealt with when we are able to use OCA, it would be good (assuming it is easy) to enhance the prettifying of identifiers to display such if the if the word "Bc" could be changed to "BC". 

Only do this if it is extremely easy as we will (I hope!!) have OCA soon enough.

**Comment by swcurran** [comment]
Example screenshot:

![image](https://user-images.githubusercontent.com/1018050/179366038-8d52b88e-7575-4659-bf2f-91e4e4d8eb8e.png)

**Comment by wadeking98** [comment]
I believe BC Wallet displays the credential base on the schema name, not the credential definition name. We'd have to issue a new schema to the ledger and update some configurations. I could do it in an afternoon but there might be some interruptions to the ISED demo as I update though. I'd rate the change as about a medium

**Comment by wadeking98** [comment]
On a side note BC Wallet should probably be using the credential definition as the title rather than the schema id. I can create a ticket for this change if you'd like

**Comment by swcurran** [comment]
No -- we don't want to change the objects on the ledger -- don't do that.

In the wallet (somewhere) there is code that converts schema type strings like "bc_person_schema", "bcPersonSchema", and "bc-person-schema" (and perhaps some other standard conventions) into capitalized words: "Bc Person Schema".  What I'm suggesting is adding after that conversion, anything that "Bc" to "BC". No change should be made to the objects themselves.

**Comment by swcurran** [comment]
Not sure we should change which string we are using (schema_id, cred_def_id).  I think that "schema_id" is used because a ton of implementations use "default" in the CredDefId, which looks bad.  OCA will fix all of this, making those strings irrelevant.  This use of those strings just a fallback because in many cases (all cases, right now) -- it is all we have.

**Comment by cvarjao** [comment]
@swcurran , we are not doing any string processing. The best way is to use the tag part of credential definition  id and using a fallback to the schema name. That logic has being implemented already, do we have our credential definition IDs properly tagged?
