### ISSUE TITLE
Prominent Disclosure of camera usage

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#434]
"[...] A prominent disclosure should be presented in cases where users may not reasonably expect their personal and sensitive user data to be required for policy-compliant features or functionality within an app. [...] Present the disclosure to the user in the app, right before requesting permission or capability. The message cannot be in the app description or website. The ideal location would be in the user flow where users are informed of the steps to grant permission in Android settings."
"Your in-app disclosure must accompany and immediately precede a request for user consent and, where available, an associated runtime permission."

## References:
- https://support.google.com/googleplay/android-developer/answer/10144311#personal-sensitive
- https://support.google.com/googleplay/android-developer/answer/11150561?hl=en#zippy=%2Cuser-interface-ui%2Cuser-experience
- https://www.youtube.com/watch?v=b0I1Xq_iSK4

Wireframes:
https://xd.adobe.com/view/4ae721e1-2016-4667-b6a4-074eb69b51c0-1fb4/ 

![image.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/69ec16d8-4f88-4091-b1fa-3d3c08a6e4df)

Acceptance Criteria
Given that camera app permissions have not been allowed
When the Scan button is selected
Then the camera use disclosure is displayed

Given that camera app permission have not been allowed
When the Holder accepts the camera use disclosure
Then the OS's camera permission is displayed

Given that camera app permission have not been allowed
When the Holder denies the camera use disclosure or the OS's camera permission
Then the Holder is taken to the screen that initiated the camera use (i.e. the Home, Credential List, etc.)

**Comment by jleach** [comment]
@knguyenBC Interested in grinding out some UX for this? See the YouTube video I added in the description, It has an excellent example of what they would like to see form a UI perspective. The use would be: The first time they user accesses the camera, we will show something to explain how and why we want to use the camera. Then, anything Apple and Google do to ask for app permission will be displayed.

**Comment by jleach** [comment]
Reached out to Ryan and Indeco to see if they have anything to contribute on this subject. Otherwise I'll do something similar to what is shown in the Google video above.

**Comment by jleach** [comment]
Reached out to Ryan and Indeco to see if they have anything to contribute on this subject. The work they did was just to refactor the ToS into two things. One for ToS and another for a Privacy Policy.

**Comment by jleach** [comment]
Here is what our current "crawl" implementation looks like:

![IMG_6576.PNG](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/8b1f91ad-2e6c-47b5-9f31-70372387eaa6)

**Comment by knguyenBC** [comment]
Sweet! Do you have a video? I'm a little confused with interface I see here. Thanks! I'll look into it today

**Comment by jleach** [comment]
> Sweet! Do you have a video? I'm a little confused with interface I see here. Thanks! I'll look into it today

https://fullboarca-my.sharepoint.com/:v:/g/personal/jason_leach_fullboar_ca/EdIflWDLS2dPic3I2UMERlUB-ySwf0lKBPeL3Lr9C13O4A?e=Xrm6uF

**Comment by knguyenBC** [comment]
@jleach Updated the ticket with wireframes and an acceptance criteria

**Comment by knguyenBC** [comment]
An issue where users select "don't allow" navigates users to an inescapable black screen within the app. Please see this URL for an improved flow that fixes this situation: https://xd.adobe.com/view/4ae721e1-2016-4667-b6a4-074eb69b51c0-1fb4/
