### ISSUE TITLE
Create BC Wallet Privacy Policy

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#435]
A quick way to have a privacy policy page published. Can be based on BCSC app.

- Camera Usage
- Biometrics
- Analytics

## References
- [Google Play Policy - Declared permissions and in-app disclosures](https://www.youtube.com/watch?v=b0I1Xq_iSK4&t=57s)

**Comment by alexgmetcalf** [comment]
Live on BC Gov site and now linked from in-app EULA.
