### ISSUE TITLE
Evaluate how an OCA Credential Overlay can be used for credential presentation layout

### ISSUE THREAD

**Issue by swcurran** [bcgov/bc-wallet-mobile#437]
We are interested in using the OCA "Credential Overlay" to define a beautiful way to display a credential -- ideally with a background image overlaid with labels and data.

From what I can determine, here is how we might use that overlay in the Bifiold/BC Wallet.

To prepare the multilingual parts of on OCA Bundle, we use a source Excel file and a converter to create the OCA Bundle. To try that out, you can follow the instructions in #410 .  Included in the OCA Bundle produced by the conversion is a `credential_overlay` JSON file that is generated in a default way.  I've attached one generated from the Person credential OCA Source:

Credential Overlay: [credential_overlay.json.txt](https://github.com/bcgov/bc-wallet-mobile/files/9172222/credential_overlay.json.txt)
 
As I understand it (but we'll confirm with the HCF Devs), to create a custom credential layout, we would take that output and hand-bomb the layout to what we want. Sounds painful, but I'd be interested in your assessment on how bad that is.  I'm not sure how the overlay would get used in the Wallet. Is there tooling that can help with this?  Or is this just the same as laying out any page?

When regenerating an OCA Bundle, the Excel file and the "hand-bombed" Credential overlay are both inputs to the process, and the default overlay is not used. 

I don't have any idea how this works with HTML vs. SVG in presenting the credential.

**Comment by swcurran** [comment]
Here is another example of this technique being used in a more advanced case -- a Swiss Passport, with the data overlaid on paged images.

Attached are two files -- the OCA Bundle itself, and the JSON Credential Overlay.

To see what the credential looks like when this overlay is used:

- Download the OCA Bundle
- Open up the OCA Preview Tool: 
- At the top, click the "Pick OCA Bundle zip file" button and pick the OCA Bundle file you just saved.
- Click on the "Credential" tab to see the rendering, and use the dropdowns to switch pages and languages.

In looking at the Credential Overlay file, one can see the URLs for custom fonts and the background image. I don't know how the SAI URL works -- pretty sure it is a "Self Addressed Identifier" resolved by the viewer they are using. But I also assume that could be just a normal URL as well.

OCA Bundle:
[Swiss Passport Credential Overlay.json.txt](https://github.com/bcgov/bc-wallet-mobile/files/9172307/Swiss.Passport.Credential.Overlay.json.txt)

[20220722 Swiss Passport.zip](https://github.com/bcgov/bc-wallet-mobile/files/9172305/20220722.Swiss.Passport.zip)
JSON Credential Overlay:

**Comment by cvarjao** [comment]
we have decided for adopting OCA
