### ISSUE TITLE
Enable main branch protection

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#438]

**Comment by jleach** [comment]
What would you like enabled?
- [x] Require a pull request before merging
- [x] Require approvals (1)
- [x] Require status checks to pass before merging
- [x] Require branches to be up to date before merging
- [ ] Require conversation resolution before merging
- [ ] Require signed commits
- [ ] Require linear history
- [ ] Require deployments to succeed before merging
- [ ] Include administrators
- [ ] Restrict who can push to matching branches
- [ ] Allow force pushes
- [ ] Allow deletions
