### ISSUE TITLE
Understanding Credential branding via SVG

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#439]
Understand the pros and cons of using SVG to render credentials in comparison to react native

Notes:
- SVGs can be leveraged as an attack vector. Might not be an issue if they are hard coded but might be an issue of remote content is loaded.
- SVGs render as an image or image-like object. That’ll reduce accessibility and testability since screen readers and Appium can’t query an image.
- SVGs may impact the memory footprint of the app.

**Comment by cvarjao** [comment]
We are not pursuing SVG  as it provides too much control and potential security and performance problems
