### ISSUE TITLE
Can gain access to the app with an incorrect PIN

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#464]
**Steps to Reproduce**
See attached video.

Start the app fresh and creating a PIN of 369369 
Then restarting the app, 
entering a PIN of 123123 
Click Enter (in the video I had to click twice, no error or message the first click)

**Result**
I was let into the app, and got an invalid key error. Though it didn't seem to go through the initialization routine. 

 https://images.zenhubusercontent.com/429950091/2fdb6747-3601-4580-a971-6118e7185c39/authenticatepin.mp4

**Environment**
This was with app build 270 on iOS on Sauce Labs. 

**Workaround**
Unknown

**Priority**
High

**Severity**
High

**Comment by cvarjao** [comment]
Duplicates #465
