### ISSUE TITLE
Stuck on "Sending Information" when going through a connectionless proof request

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#468]
Device: iPhone 7 with iOS 15.6

Steps to Reproduce:
1) Access the [Demo app](https://bc-wallet-demo-law-dev.apps.silver.devops.gov.bc.ca/) as Lawyer
2) Follow the steps and go through "Login To Court Services"

At this step the wallets gets stuck on "Sending the information securely" and offer no option to go back.

**Comment by nodlesh** [comment]
Can confirm this is also happening since iOS build 270 in the nightly regression tests using the Candy UVP issuer and Pan Canadian Chat verifier. https://allure-mobile.vonx.io/api/allure-docker-service/projects/ios-multi-device-full/reports/87/index.html#testresult/1f11f3c867fe8c12

**Comment by wadeking98** [comment]
I resolved this in my PR here: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/406
