### ISSUE TITLE
Remove credential popup cutting off the remove button

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#469]
Device: iPhone 7 with iOS 15.6

Steps to Reproduce:
1) Obtain a credential from the [demo app](https://bc-wallet-demo.apps.silver.devops.gov.bc.ca/)
2) Go to the credential details
3) Select the newly added credential
4) select "remove credential"

Using iPhone 7 (small screen factor) the bottom of the screen is cut off, and can't select "remove from wallet"

![signal-2022-08-11-141619](https://user-images.githubusercontent.com/1348549/184244103-7fb7d965-73f0-45d8-964f-c6beddf97ed4.png)

**Comment by wadeking98** [comment]
Resolved by https://github.com/hyperledger/aries-mobile-agent-react-native/pull/411
