### ISSUE TITLE
In App Notifications

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#47]
**User Stories**

- [x]  As a holder I need to be temporarily notified within the app, in an unobtrusive way, when certain processes are successfully completed.

- [x] As a holder I need temporary notifications to be easily dismissed at a time of my choosing, so I can ensure I've read the notification before it is removed.
- [x] As a holder I need to be notified within the app when there are things that require my attention and action, such as approving a presentation request or receiving an offered credential.
- [ ] As a holder I need to be notified by my device's OS when there are in-app notifications that require my attention and action but I'm not currently using the wallet app.
- [ ] As a holder I want notifications outside of the app to take me directly to the in-app notification that needs my attention, so I minimize the number of steps required to take action.
- [x] As a holder I need to be able to easily review all the notifications that need my attention and attend to them in an order of my choice, so I can prioritize actions as I see fit.
- [x] As a holder I need to browse my notifications in reverse chronological order, so I can make better assessments of what notifications to address first.
- [x] As a holder I expect quick access to the most recent notification so I can take quick action on what is likely to be at the forefront of my mind.
- [x] As a holder I need to see an informative summary of a notification before I go into its detail and get asked to take action on it.
- [x] As a holder I want to be notified when the state of my wallet is notably changed, or changed or used in a way I might not reasonably expect as part of my current actions, so I always feel secure and in control of my wallet.

**Background**

The user needs to be notified of various wallet activities and requests.

Notifications will take three forms:

Temporary notifications. These are about events that have just occurred, and are for events small enough to not warrant a formal step in a process. For example: "Changes to settings saved √". They may also be used to signpost the user to a permanent notification, for example: "New credential offer". These notification types are likely not reflected in the wallet's history and do not have a home anywhere in the app. They may be implicitly dismissed by a user action that moves away from the current screen.
Appearance: some form of overlay to the screen the user is currently on.
Action type: Dismiss informally (e.g. swipe away or tap 'X'), or single action (e.g. go to screen about a new credential offer).

Queued notifications. These notifications live in a permanent home in the app, and stay there until actively dismissed or interacted with. They may be used to handle VC actions (e.g. agree to receive an issued VC), or to be notified of bigger wallet changes (e.g. VC has been revoked). These are likely to be reflected in the wallet's history.
Appearance: (a) badge indicator in tab bar (number in red circle), (b) summary on app Home Screen, and (c) notification details on app's Notifications screen. Note: (a) and (b) stay visible until the notification is interacted with and completed.
Action type: Dismiss formally (e.g. 'Dismiss' or 'OK') or take action (e.g. 'Review credential').

Push notifications. These notifications are OS-level only, i.e. either iOS or Android. They show up using the OS notification systems, such as an app icon badge and/or on the Lock Screen. They have a direct correlation to the queued notifications: each push notification corresponds to a queued notification.
Appearance: dictated by OS.
Action type: links directly to notifications screen inside app.

**Comment by alexgmetcalf** [comment]
**New summary:**

The user needs to be notified of various wallet activities and requests.

Notifications will take three forms:

1. Temporary notifications. These are about events that have just occurred, and are for events small enough to not warrant a formal step in a process. For example: "Changes to settings saved √". They may also be used to signpost the user to a permanent notification, for example: "New credential offer". These notification types are likely not reflected in the wallet's history and do not have a home anywhere in the app. They may be implicitly dismissed by a user action that moves away from the current screen.
     Appearance: some form of overlay to the screen the user is currently on.
     Action type: Dismiss informally (e.g. swipe away or tap 'X'), or single action (e.g. go to screen about a new credential offer).

2. Queued notifications. These notifications live in a permanent home in the app, and stay there until actively dismissed or interacted with. They may be used to handle VC actions (e.g. agree to receive an issued VC), or to be notified of bigger wallet changes (e.g. VC has been revoked). These are likely to be reflected in the wallet's history.
     Appearance: (a) badge indicator in tab bar (number in red circle), (b) summary on app Home Screen, and (c) notification details on app's Notifications screen. Note: (a) and (b) stay visible until the notification is interacted with _and_ completed.
     Action type: Dismiss formally (e.g. 'Dismiss' or 'OK') or take action (e.g. 'Review credential').

3. Push notifications. These notifications are OS-level only, i.e. either iOS or Android. They show up using the OS notification systems, such as an app icon badge and/or on the Lock Screen. They have a direct correlation to the queued notifications: each push notification corresponds to a queued notification.
     Appearance: dictated by OS.
     Action type: links directly to notifications screen inside app.

**Comment by jmdkumar08** [comment]
Done
