### ISSUE TITLE
Missing "back home" button from modal screens

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#477]
The "go back to home" button should always appear on full modals.
The message "it is taking longer than usual" is the part that is hidden, and displays after a 10s timeout

#### Scenario 1: Modal screen is displayed
Given the the user has scanned a QR CODE
When the user is `<state>`
Then user can select "go back to home"
And "takes longer than usual ..." message is hidden
Examples:
state
Waiting for Credential Offer
Waiting for Proof Request
Waiting for Credential
Waiting for Confirmation Proof Request has been sent

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/418
