### ISSUE TITLE
Add backdrop to all popups

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#481]
Any popups that layer on top of the existing screen but does not fill the entire screen, please add a translucent (50 %) backdrop.

These include:
[Scan notifications](https://xd.adobe.com/view/cfc523f6-fb60-45fd-bb3d-a09fa3d04c98-9a96/)
[Scan errors](https://xd.adobe.com/view/4f9b250e-27d3-4d8b-af48-c6b90520d0ee-1ac8/)
[PIN entry error notifications](https://xd.adobe.com/view/4f9b250e-27d3-4d8b-af48-c6b90520d0ee-1ac8/screen/b83b82dc-f939-4202-b8ba-05ef1329edcc)
[What are Contacts popup](https://xd.adobe.com/view/3db881d4-e963-42ec-a2c4-6b5ca23862a3-68eb/screen/792cc66f-b40a-4bb2-ab36-27528679bbe5/)
[No internet connection errors](https://xd.adobe.com/view/5ff8dab2-4b51-4f21-b9c8-7955664e17c7-0aab/)

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/415
