### ISSUE TITLE
The application should handle the user declining the OS biometry prompt.

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#487]
The iOS app (and perhaps Android) needs to properly handle the scenario where the user chooses to use biometry but declines the second prompt supplied by the OS. See screenshot. In this case the application should not enable biometry.

### Acceptance Criteria

Scenario: Holder has chooses to use biometrics
Given the Holder has selected to use biometrics to unlock BC Wallet
AND the Holder has declined the OS prompt to use biometry
Then the app keeps them on the Use Biometry screen;
AND the "Use Biometrics" switch is turned to "disabled".

### Checklist

- [ ] Holder has chooses to use biometrics
- [ ] Fix the wallet name in the shown alert so it reads "BC Wallet"

![IMG_6622.PNG](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/2d915d0d-43e3-4364-9ce5-42a4d44753b8)

**Comment by wadeking98** [comment]
With my new PR the user is able to fall back to pin when declining biometrics. Is this still an issue if the user can fall back to using the pin?

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/449
