### ISSUE TITLE
Review OWASP mobile application security verification standard

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#488]
Review the attached OWASP standard and determine what is applicable and meaningful for the BC Wallet to implement. 

[https://app.zenhub.com/files/429950091/89ad3ea1-c951-44ca-a95b-21e362c4099b/download](https://app.zenhub.com/files/429950091/89ad3ea1-c951-44ca-a95b-21e362c4099b/download)

**Comment by jleach** [comment]
@cvarjao FYI. This exists now.

**Comment by cvarjao** [comment]
@wadeking98  has reviewed and we have provided to OCIO Security team
