### ISSUE TITLE
Need public-friendly min OS and device descriptions for M2 launch

### ISSUE THREAD

**Issue by alexgmetcalf** [bcgov/bc-wallet-mobile#490]
We need to have the official OS and device requirements for iOS and Android, for the M2 launch.

They need to be written in a comms-friendly way for web pages and so forth, so in a way that a member of the public can understand what they need.

**Comment by nodlesh** [comment]
Testing has been working with numbers decided on at the beginning of 2022 based on coverage of the population. 

iOS 12+ at that time covered 99% of users. (Could be more than that now.)
Officially been testing on 12+ but have run 11 with no problems.
Android 8+ hits about 94% of users.
SDK 30 has been the minimum that has been tested officially.

**Comment by alexgmetcalf** [comment]
Proposed that we go with:

iOS 12.0 or later
Android 11 (Red Velvet Cake) or later   [this is the version of Android that aligns with SDK 30]

**Comment by nodlesh** [comment]
I think that is reasonable. Can adjust in future milestones if need be.

**Comment by nodlesh** [comment]
There is talk of moving the app to API 32 in #432 https://app.zenhub.com/workspaces/bc-wallet-6148e7423fe04b001444e2bd/issues/hyperledger/aries-mobile-agent-react-native/432

Android SDK 32 is Android 12. For the Canadian market, this may only give us 46% of the Android user base.
SDK 30/Android 11 give us 62% of the Canadian Android market.

**Comment by nodlesh** [comment]
It may be worse than 46% since Android 12 can have either API 31 or 32. I don't know the amount of Android 12 users in Canada that have API 12.
