### ISSUE TITLE
Stuck in biometrics loops opening the app

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#494]
In the process of opening the app, the biometrics on/off screen is presented. If biometrics is left off, clicking continue sent me to enter my PIN, then when entering my PIN, I was then asked to "Authenticate to retrieve secret" (can't screenshot this screen) by using my fingerprint. I authenticate using my fingerprint but it puts me into a loop of entering the PIN and then authenticating with my fingerprint. 

I have uninstalled and reinstalled the app to get out of the loop. At the biometrics screen, this time, I enabled biometrics. I'm now stuck at the persistent loading screen after continuing from the biometrics screen.

I then closed the app and reopened the app. I'm being asked to authenticate to retrieve secret (this phrasing should be changed to something else). The app allows me in but I'm presented with this home screen.
![20220822_121303.jpg](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/7609a111-ac01-42d1-8f48-3b076a0c021a)

Closing and opening the app (and reauthenticating) presents the home screen properly.

Build: 1.0.1-227
Device: Oneplus 6
Android version 11
OxygenOS version 11.1.2.2

**Comment by nodlesh** [comment]
@knguyenBC What device are you on? I'd like to try and reproduce the bug.

**Comment by knguyenBC** [comment]
@nodlesh I updated the ticket to include that information. Thanks for the reminder

**Comment by knguyenBC** [comment]
Can't replicate this anymore on build 457. Looks good.
