### ISSUE TITLE
Standardized Toggle Component

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#498]
Toggle component is defined in the [style guide](https://xd.adobe.com/view/eb9e0945-61d7-40ca-8e8e-bf4bd0c72934-becd/screen/8e863a95-8c83-47db-92ed-d9cf13332153)

Just by looking at the colors/contrast, it is not clear if it is in on or off.

Updates to the toggle design were made:
![image.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/a8594444-82c4-4ab2-b9a2-23f584a35f17)

**Comment by knguyenBC** [comment]
A new updated toggle design helps to clarify if the feature is on or off.

**Comment by cvarjao** [comment]
closing stale issue. A style guide/system is being reviewed and updated
