### ISSUE TITLE
Credential branding v1

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#50]
- During transactions with the wallet (proof request, credential offer) the organization's branding (logo) is displayed in the ID Holder's wallet
- Credential theming - Organization branding (logo, colour) is displayed in the connections list of the ID holder's wallet
- Field Labeling: 
   - Crawl: Lookup Table based on credential definition ID and/or schema id, fallback to best effort transforming
   - Walk: OCA/Registry discovery
   - Support for the [OCA label overlay](https://oca.colossi.network/v1.1.0-rc.html#label-overlay)
Schemas:
- LSBC Membership Card
- Pilot Invitation Credential
- Verified Person Credential

**Comment by jmdkumar08** [comment]
Done
