### ISSUE TITLE
BC Wallet crashed after scanning a verifier QR code and now doesn't open

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#500]
Tried to gain access to Access to Court Materials and once I had scanned the QR code, the wallet crashed. The wallet now no longer opens and crashes every time I try opening it.

This is happening for both iphone and android. I tried twice on both devices. Same result.
Tried the app on the BC Wallet showcase lawyer use case and it didn't work.
Tried the app on the BC Wallet showcase student use case however and it works fine. 

Build: 277

Device: iPhone SE
Software version 15.5

Device: OnePlus 6
Android version 11
OxygenOS version 11.1.2.2

**Comment by wadeking98** [comment]
addressed by this PR: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/414
Waiting for changes to be out in the next build
