### ISSUE TITLE
SCRUM Process 

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#51]
- Ceremonies
  - Daily standup @ 9:00AM PST
  - Backlog Refinement: Every Tuesday 11AM - 12PM
  - Sprint Planning: Every other Thursday 9AM - 10AM
  - Sprint Review: Every other Wednesday 11AM - 11:30AM
  - Sprint Retrospective: Every other Wednesday 11:30AM - 12PM

- Definition of Ready
  - User Story Format and description
  - Acceptance Criteria
  - Estimated ( Story Points)

- Definition of Done (Dev team)
   - It Works
   - Merged to the main branch
   - Unit Testing

- Definition of Review/QA
  - Should we consider this to mean this is where the testing team, dev, or UX reviews issues, conducts testing, etc.?

- Definition of Closed (Product Owner)
  -  Acceptance criteria is met

- Team Agreements

- Definition on what is a "bug"

- Tools
  - GitHub Issues + ZenHub
  - Mural Boards

- Guiding Principles
  - Agile Mindset
  - [The Twelve-factor App](https://12factor.net/) Principles
  - [ToIP Principles of SSI](https://trustoverip.org/wp-content/uploads/2021/10/ToIP-Principles-of-SSI.pdf)
  - [DIACC Digital Identity Wallet Principles](https://diacc.ca/wp-content/uploads/2020/12/Making-Sense-of-Digital-Wallets_VF.pdf)
  - [DIACC Digital Identity Ecosystem Principles](https://diacc.ca/the-diacc/principles/)

- Estimation (Story Points)
- Epics (do they go to print backlog) vs Tasks vs Stories vs Spike
   - Format (As a ... I want ... So That ...)
   - Acceptance Criteria (Given .. When ... Then)
   - We should be aiming to work with Stories (testable)
   - How do we represent and split UX and Coding work? Decision: UX Work get their own tickets and use the "UX Work" Label
   - Epics MUST have User Story 
   - User Story MAY have an epic
   - User Story MUST have one or more tasks
   - We may have reporting purposes epics to support high level grouping (with a a specific label)
- Labels:
  - Epic
  - User Story
  - Task
  - Spike

- Backlog Management
   - [INVEST](https://explainagile.com/blog/invest-principle/)
   - [3 Cs](https://www.agilealliance.org/glossary/three-cs/)
   - Columns / States
   - Who moves to what column

Glossary:
- DIACC: [Digital Identity and Authentication Council of Canada](https://diacc.ca/)
- ToIP: [Trust over IP](https://trustoverip.org/)

**Comment by jozuruome** [comment]
Some of the information here might need to be updated @cvarjao
