### ISSUE TITLE
Question - Local Environment - Unable to get past the pin setup screen on Android emulator

### ISSUE THREAD

**Issue by dinbtechit** [bcgov/bc-wallet-mobile#513]
Hi, I am trying to run BC wallet locally. On Android Emulator (pixel 4 - Android Version S 31)

Stuck on the following screen. The **Create Pin** button doesn't do anything. I don't see any error related to this in the logs: Any help is massively appreciated!
 
![image](https://user-images.githubusercontent.com/17984781/186971329-2df90f68-2e5f-4f72-a5e2-2e5ea6cb3140.png)

**Here are the steps I followed:** 

Note - The developer documentation no longer works. Looks like I need to start metro first. Please advice.
1. git cloned bc-wallet-mobile -> master branch
2. installed and started the app using the following command.
    ```
     npm run install:all --legacy-peer-deps
     cd app
     npm run start
     # In a new terminal session
     npm run android
    ```

Not sure if I am missing anything!

> Note: I have von-network and issuer-kit-dev running locally and would like to use the bc-wallet to scan the QR code.

**Comment by cvarjao** [comment]
@dinbtechit ,  Make sure you have enabled biometrics security in the emulator, as well registering the emulated fingerprints (I usually just use "finger1":
https://stackoverflow.com/a/45181265

**Comment by dinbtechit** [comment]
That worked, thank you @cvarjao!
