### ISSUE TITLE
List of issues with biometrics enabled in app and on device on android

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#516]
**Issues:**
- [x] app asks for biometrics authentication before entering into the biometrics screen in onboarding. App should only prompt once.
- [x] When opening the app, the app does not prompt biometrics until after entering PIN. If PIN is incorrect but biometrics is correct, app does not successfully unlock. App should prompt biometrics automatically and without the need of a PIN.
- [x] app prompts biometrics twice, once after entering the PIN and again while the app is loading. App should only prompt once.
- [x] OS level message says "authenticate to retrieve secret". It should say "Open BC Wallet with your biometrics"
- [ ] app does not unlock with face ID/face unlock even with it enabled on device

**What I did:**
I went through onboarding and right after creating a PIN, the app asks for biometrics authentication, after I authenticate, it goes into the biometrics screen, then after continuing with biometrics toggled on, it asks for biometrics again. 

Right after enabling biometrics, the app is loading for a very long time. I had to close the app and open it again. Now, I have to enter my PIN and authenticate with biometrics twice to enter the app 

OS level message to use biometrics says "authenticate to retrieve secret". This message is not plain language. It doesn't make sense to the average user.

My device has face data. After I opened the app and tried to unlock using face ID. It didn't work. I have to use fingerprint.

Build: 284
Device: OnePlus 6, Android 11

**Comment by cvarjao** [comment]
Done. The face authentication for Android will be moved to its own ticket.
