### ISSUE TITLE
App Hangs in Onboarding-Initialization when Biometrics is not enabled on the device

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#518]
Steps to Reproduce

If Biometrics is not enabled on the device, user can create a PIN but the app just hangs on the loading screen with no indication that biometrics is required.

### Expected Result
Even though biometrics is not enabled the app should behave gracefully on initialization

### Environment
iPhone 13, iOS 15.6.1

### Workaround
Enable Biometrics

### Severity
High

### Priority
High

**Comment by nodlesh** [comment]
@amanji Can you verify the steps you made here? I'm assuming you selected to use Biometrics in the onboarding setup?

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/449
