### ISSUE TITLE
App is prompting for Biometrics after entering PIN on Android

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#519]
### Steps to Reproduce
App does not prompt biometrics until after entering PIN. If PIN is incorrect but biometrics is correct, app does not successfully unlock

### Expected Result
If Biometrics is used for authentication to the app, that should be what is presented to the user initially. Only if Biometrics fails should the PIN be accepted. 

### Environment
OnePlus 6, Android 11

### Workaround
This may be a timing issue and if you wait on the PIN page the biometrics comes up. However, this workaround isn't viable for release. 

### Severity
High

### Priority
High

**Comment by knguyenBC** [comment]
Checked on iOS and Android and it no longer does this
