### ISSUE TITLE
Failed Biometrics and correct pin shows initialization screen perpetually on Android

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#521]
### Steps to Reproduce
On Android 12 if the user fails biometrics and then enters the correct PIN, then the user will get stcuk on the loading screen forever

### Expected Result
A correct PIN after a failed biometrics should allow access to the app. 

### Environment
Android 12

### Workaround
None Known

### Severity
High

### Priority
High

**Comment by nodlesh** [comment]
@wadeking98 Can you add what phone or emulator you used here? Thanks.

**Comment by wadeking98** [comment]
I used my physical device: Samsung galaxy a13 on android 12

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/449
