### ISSUE TITLE
App crashes when device sleeps after setup and when initializing

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#522]
Steps to Reproduce
Reproducible by reinstalling the app, setting up pin and select biometrics, while the app is initializing, let the phone sleep. Open the app. If it doesn't crash here, let it sleep again without doing anything then reopen the app.

Expected Result
No crash. :)

Environment
iPhone 6S iOS 15.5

Workaround
Don't let the device sleep

### Severity
High

### Priority
High

**Comment by nodlesh** [comment]
Just an FYI that this is still an issue with build 309.
The thing is, if your sleep time is smaller than what it takes for initialization to happen a user can see this crash a lot when onboarding or opening the app.

**Comment by nodlesh** [comment]
This issue still manifests in build 511.

**Comment by nodlesh** [comment]
Still in build 595

**Comment by jleach** [comment]
@nodlesh Still an issue. I don't see this behaviour but I do recall it being an issue. Maybe @amanji work fixed this a few weeks ago.

**Comment by hiteshgh** [comment]
@nodlesh - can you pls re-test and close if working

**Comment by nodlesh** [comment]
I cannot reproduce this in the latest build 1077. However I can't get it to sleep in the timeframe of the wallet initializing. Not sure if I should close this or not.

**Comment by nodlesh** [comment]
Closing this since no one has seen it in a long time.
