### ISSUE TITLE
Perpetual initialization with device biometrics on and app biometrics off on Android

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#523]
### Steps to Reproduce
On Android 12 with biometrics on device enabled but disabled on the app. after initial setup is complete, close the app and restart it. User gets stuck on loading screen forever after entering pin. Does not happen on Android 11. 

### Expected Result
Initialization screen doesn't take forever. ;-)

### Environment
Samsung galaxy a13 on android 12

### Workaround
None known

### Severity
High

### Priority
High

**Comment by jleach** [comment]
@nodlesh Still an issue? Seems like we would have fixed this before release.

**Comment by hiteshgh** [comment]
@nodlesh - can you pls re-test and close if working

**Comment by nodlesh** [comment]
Cannot duplicate this issue in the latest build 1077. Closing.
