### ISSUE TITLE
Perpetual initialization and error with fingerprint removal from device before onboarding

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#524]
### Steps to Reproduce
Biometrics disabled: hangs forever after biometrics screen. Removed finger print from device, went through onboarding to biometrics screen. Once arriving at the biometrics screen an error pops up saying no fingerprints are enrolled. clicking continue results in the loading modal hanging indefinitely.

### Expected Result
Biometrics selection in app should handle the case where no fingerprints are enrolled. 

### Environment
Android

### Workaround
None known

### Severity
High

### Priority
High

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/449
