### ISSUE TITLE
"Continue" button on enable Biometrics stuck in clicked state and user cannot continue on Android

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#525]
### Steps to Reproduce
With biometrics enabled on the device, then Enabling biometrics in the app results in the continue button being stuck in the clicked state and not being able to continue.

### Expected Result
Continue Button to actually continue the process. 

### Environment
Android

### Workaround
None known

### Severity
High

### Priority
High

**Comment by jleach** [comment]
@nodlesh Still an issue?

**Comment by nodlesh** [comment]
Closing this issue, it no longer manifests in build 647.
