### ISSUE TITLE
Biometrics with App PIN fallback

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#526]
As a user I want to be able to choose to use biometrics or my app PIN to enter my digital wallet so that when I'm met with a situation where I can't use my fingerprint or face (wearing gloves, mask, etc,) I can still enter into my wallet without any issues

[See Biometrics and App PIN fallback flow and behaviour](https://app.mural.co/t/digitalidentityandtrust0399/m/digitalidentityandtrust0399/1661808127835/fad19a32b9a164538e74a1c6c4a9897152a2ec5a?wid=0-1661813415640)

### Acceptance Criteria
Given biometrics is turned on 
And the Holder has opened the app
And they are presented with biometrics authentication
When the Holder selects "cancel"
Then they are prompted to enter their wallet PIN
And they are prompted with the option to enter using their biometrics

Given the Holder has biometrics enabled to access their wallet
When the Holder has selected to enter using their biometrics
Then biometrics authentication is prompted

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/449
