### ISSUE TITLE
Implement complete error handling 

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#529]
Many of the error conditions just have `// TODO:(xx)` in the catch clause. We need to go through the app and make sure that something meaningful is done in each error state where applicable.

**Comment by nodlesh** [comment]
How can we make this testable? What are the errors and how might we trigger them?

**Comment by bryce-mcmath** [comment]
I don't know if there's really a way outside of local development to manually trigger errors. The way I tested locally is by adding a `throw new Error('Example error message')` line but that's not really possible from Testflight. Here's the PR to see what errors are now handled that weren't: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/951/files

Maybe it's just not testable

**Comment by nodlesh** [comment]
@bryce-mcmath Are these errors triggered in unit tests? Some of these are tested in the regression tests, like the PIN errors. I'm thinking we just move this to closed if there is also some coverage in the unit tests.

**Comment by bryce-mcmath** [comment]
There is some. Let's close it.
