### ISSUE TITLE
Credential Title in Credential Card is wrapped instead of ellipsis on Android

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#535]
### Steps to Reproduce
See screenshot. 
![Screenshot_2022-08-31-14-52-47.png](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/bb839c5c-3da2-4f51-8479-dbe3318d1ec5)

### Expected Result
The Credential title to not wrap, but have ellipsis ... like on iOS 

### Environment
Android 

### Workaround
None known

### Severity
Low

### Priority
Medium

**Comment by amanji** [comment]
https://github.com/hyperledger/aries-mobile-agent-react-native/pull/459
