### ISSUE TITLE
Feedback when a button is clicked

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#541]
Focus on these screens first:
- Create PIN
- Biometrics Disclosure Screen
- Enter PIN

Please follow the [style guide as spec'ed here](https://xd.adobe.com/view/eb9e0945-61d7-40ca-8e8e-bf4bd0c72934-becd/screen/8e863a95-8c83-47db-92ed-d9cf13332153/specs/)

**Comment by amanji** [comment]
Is there more detail to this ticket?

**Comment by knguyenBC** [comment]
Updated the style guide to use correct terminologies and guidance on when to use pressed/pending state, an animated loading icon, or a loading screen

**Comment by wadeking98** [comment]
Blocked by: https://github.com/hyperledger/aries-mobile-agent-react-native/issues/554

**Comment by wadeking98** [comment]
Chatted with Kim and the difference in style of the button toggle isn't a priority for now

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/556
