### ISSUE TITLE
Update EULA

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#542]

**Comment by alexgmetcalf** [comment]
EULA is missing two links in the Privacy section, implemented as links in the source Word doc: "Province’s Privacy Statement for government websites" and "BC Wallet App Privacy Policy".

**Comment by jleach** [comment]
@alexgmetcalf You mean these links? I see them in the latest build.

![image](https://user-images.githubusercontent.com/390891/188541946-a97b6a30-34e6-4046-90b0-1705146cadab.png)

**Comment by alexgmetcalf** [comment]
No just below them, the words—they're links in the Word doc but not expanded.

**Comment by jleach** [comment]
@alexgmetcalf Ok. You want to see the text not the actual URL itself?

**Comment by alexgmetcalf** [comment]
I think we still have crossed wires :) I mean these two links that aren't implemented as links in the app:
<img width="702" alt="image" src="https://user-images.githubusercontent.com/75134312/188542658-5a8d380c-8ddb-4dd0-9b72-4c3201633dfe.png">

**Comment by jleach** [comment]
@alexgmetcalf Fixed in PR #544. Our BC Wallet App Privacy is not on-line so that link won't work.

Cc: @cvarjao
