### ISSUE TITLE
Remove repetitive accessibility labels and add labels that provide context

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#550]
- [x] On a few screens, the page title and heading are repetitive. ex. On the first screen of onboarding, the page title and heading are read out as, “BC Wallet. BC Wallet heading,”  - 

- [x] This issue also exists on the dashboard/wallet home screen where it reads out, “BC Wallet. Home heading.”

### Fixes
- [x] Remove repetitive heading in onboarding screens that repeat the words "BC Wallet". Screen include the onboarding screens, and the home screen
- [ ] Change "Welcome" label on the first onboarding screen to read "Welcome to BC Wallet"
- [ ] Update the icons located in all notification/alerts so they're labelled as decorative
- [x] iOS only - swiping mechanism on the app interferes with the swiping mechanism of the OS's VoiceOver
- [x] On android, the "I agree" checkbox comes before the associated text (I have read, understand...). The associated text should read first and then prompt to agree

**Comment by jleach** [comment]
The ask here is, for example, that the screen reader reads different text than what people can see with their vision.

**Comment by cvarjao** [comment]
needs to be re-assessed

**Comment by knguyenBC** [comment]
I checked this ticket and the unchecked items are still an issue. Should they all be separate tickets?

**Comment by cvarjao** [comment]
@knguyenBC, please break it down to multiple tickets and close this one.

**Comment by knguyenBC** [comment]
Broken down to 1137-1139
