### ISSUE TITLE
Match onboarding PIN screen and Enter PIN screen to design

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#551]
Current designs do not provide enough context as to what the user needs to do. The first items focused are the input fields and not the content above. 

Once a PIN is entered, the screen reader loops back to “Remember your PIN” instead of moving to the next field. This issue also repeats when you confirm your PIN in the second edit field. In both cases, a user must swipe through all text and individual digit fields before reaching the “Create PIN” button. This behaviour also repeats when users must subsequently re-enter their password to log in.

When password is entered, it reads “maximum length reached” and then cycles back to the first field. You must manually swipe through each digit field and the visibility icon to submit your entry.

When re-entering PIN to unlock the app, the screen reader reads out (on Android) “Samsung keyboard. BC Wallet. Editing edit box out of list predictions. Keyboard displayed.”

### Fixes
- [x] Ensure the focus switches to the next item on the screen when a user enters their PIN. On the Create your PIN screen, ensure that after a user enter their first PIN, that the next element focused in the confirmation PIN. [see video to see was build 447 is doing below]
- [x] Ensure content above input fields are focused first. Currently the input fields are focused first. [see video to see was build 447 is doing below]
- [ ] When rereading the PIN, the screen reader reads the PIN as a single number (ex. 1 0 0 0 0 1 will read one hundred thousand and one). It should read each individual digit.

**### Videos:**
**Video showing screen reader reading in wrong order**
https://images.zenhubusercontent.com/429950091/e6422e9f-a02b-4fcf-bda6-63fbfb22cd04/20221018_1653335071.mp4

Video showing how screen readers read the PIN input
https://images.zenhubusercontent.com/429950091/c3b235d2-4ed4-4768-a358-7f72bece1224/20221018_1701377812.mp4

**Comment by cvarjao** [comment]
please add a video

**Comment by knguyenBC** [comment]
Videos added

**Comment by jleach** [comment]
Ok, I've made some changes. Lets see how they improve things. The last point is not doable without either re-writing the PIN input, contributing back to the original project, or some otherwise noteworthy effort. I created #754 to track that last point.

**Comment by nodlesh** [comment]
@knguyenBC Are you ok with the last item not completed? Should we move that into a new issue and move this to Done?

**Comment by knguyenBC** [comment]
We can move this to done. Jason already created a new ticket for the last point.
