### ISSUE TITLE
Proof request waiting screen stuck when verifier sends no ack

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#553]
The "presentation ack" ([RFC 0037](https://github.com/hyperledger/aries-rfcs/blob/main/features/0037-present-proof/README.md)) message from verifier to holder is not mandatory.
The user gets stuck in a waiting screen and cannot go back home

Example from Idramp:

Issuer: https://wallets.idramp.com/
Verifier: https://sowl-demo-hlforum.esatus.com/

**Comment by swcurran** [comment]
It would be nice to handle this like the other "This is taking longer than expected..." message, but ideally with different wording, such as "We've not heard back from the verifier reviewing your data -- do you want to stop waiting?"

**Comment by jleach** [comment]
Thanks. Will look into this. The wallet takes into account the `ack` is optional but I must be missing something.

**Comment by knguyenBC** [comment]
Is this from a connectionless proof request? What should be happening if there isn't any response from the verifier is a completely different loading screen. It should just say "Information sent successfully" with a "Done" button that bring them back to Home. No loading involved.

**Comment by jleach** [comment]
@cvarjao What in the docs indicate its not mandatory? I though it was when a connection is present and not possible for connection less?

**Comment by cvarjao** [comment]
The RFC doesn't really state it is mandatory or optional. So it is open for interpretation which led to some people interpreting as optional

**Comment by jleach** [comment]
Noted. I've fixed the issue. PR eminent.
