### ISSUE TITLE
Add timestamp to issued date on credentials details

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#554]
When issuing the same credential on the same day, without a timestamp, people don't know which one is the correct one to remove/delete

Please add a timestamp to the issued date of credentials
See wireframes: https://xd.adobe.com/view/5edd5ca1-8978-4b3f-bf87-9ef21548b877-0b8e/screen/1f026cd1-73ae-4d62-af4e-e85fa0e5af21

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/573

**Comment by nodlesh** [comment]
@wadeking98 Is this feature in build 629?

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/595
