### ISSUE TITLE
Developer Mode for Person Credential issuance configuration

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#555]
This is for introducing a hidden way of unlocking advanced features/settings for helping with troubleshooting or testing. Similarly to Android [Developer Options](https://developer.android.com/studio/debug/dev-options#enable), this can be unlocked by tapping a specific location a number of times.

As a developer
I want to be able to see credential details (including metadata, perhaps JSON?)
so that I troubleshoot errors

As a tester
I want to be able to change some advanced settings
so that I can run tests against different endpoints

### Scope:
- Get BC Digital ID endpoint configurations - [IDIM Environments](https://github.com/bcgov/trust-over-ip-configurations/issues/79)

[Settings wireframes include developer mode](https://xd.adobe.com/view/f239cc67-e22a-4178-84ae-4cf06b1dff23-a76a/)
See [layout in style guide ](https://xd.adobe.com/view/eb9e0945-61d7-40ca-8e8e-bf4bd0c72934-becd/screen/c9288b11-44ac-4696-a492-0faba38b73eb/)for guidance on how to form the developer mode

#### Scenario: Turn on developer mode
Given the user is in the [settings screen](https://xd.adobe.com/view/f239cc67-e22a-4178-84ae-4cf06b1dff23-a76a/)
When the user taps 10 times the wallet version label
Then the use seems a [toast](https://xd.adobe.com/view/f239cc67-e22a-4178-84ae-4cf06b1dff23-a76a/) saying "Developer Mode Enabled"
   And the "[Developer Settings" section is visible under settings](https://xd.adobe.com/view/f239cc67-e22a-4178-84ae-4cf06b1dff23-a76a/screen/2486fb7d-fe7a-4327-8276-80a4778bdb7b/)
   And "[Developer Mode" option is visible and turned on](https://xd.adobe.com/view/f239cc67-e22a-4178-84ae-4cf06b1dff23-a76a/screen/1c830eab-5716-4d20-ba4f-52c62f9fbd99/)

#### Scenario: Turn off developer mode
Given the user is in the settings screen
  and developer mode is on
When the [user taps developer mode toggle](https://xd.adobe.com/view/f239cc67-e22a-4178-84ae-4cf06b1dff23-a76a/screen/1c830eab-5716-4d20-ba4f-52c62f9fbd99)
Then developer mode is turned off and related settings are hidden (preserve changes)

Notes:
- Some settings may come from Bifold
- Some settings may come from BC Wallet

**Comment by knguyenBC** [comment]
I updated settings to include developer mode. Not sure what settings would be in there but it should be scalable to accommodate whichever settings are needed in there.

**Comment by nodlesh** [comment]
Regression tests will continue to fail as of build 549+ until this ticket is implemented, merged, and the tests implement the developer mode settings and change the web view URL. Right now it goes to a PROD web view and it is missing the Log in with test IDs.

**Comment by nodlesh** [comment]
There is no Developer Mode Enabled message as in the wireframes.
There is also no toggle to turn off developer mode as in the wireframes. 

Move this to Sprint Backlog?
