### ISSUE TITLE
Pausing and resuming communication with the wallet when app goes to background

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#568]
We would like to control wallet unlock / initialization and networking independently. As part of [AFJ 989](https://github.com/hyperledger/aries-framework-javascript/pull/989) they are separating this functionality. We should be able to unlock / initialize the wallet, then once successful, start network communication with the mediator.

We should be able to use [AppState](https://reactnative.dev/docs/appstate) module to determine when the app is sent to the background or foreground. Testing and validation required.

**Comment by amanji** [comment]
Blocked by AFJ upgrade

**Comment by cvarjao** [comment]
Don't have enough information. Closing for now.
