### ISSUE TITLE
review biometrics package

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#570]

**Comment by wadeking98** [comment]
I've talked to Jason and I've come back with some findings. Before Clecio's change the user was prompted for biometrics 3 times. Once at the Pin create screen, and twice on the Biometrics screen. Clecio's change reduces the biometrics prompts to once at the Pin create screen and once at the biometrics screen. Switching between sdk 30 and 32 doesn't make a difference to the package. I tested compileSdkVersion = 32 on android 31 and 30 and it works but to compile anything greater that  compileSdkVersion = 30, you need java 11 and to add the `android:export="true"` tag to the main activity in the android manifest file. `targetSdkVersion` in the build.gradle file does not do anything functional, it only lets developers know what version of the sdk the app has been most tested against.

**Comment by wadeking98** [comment]
@jleach Do we still need to review the biometrics package now that I've fixed the biometrics issue in android?

**Comment by jleach** [comment]
@wadeking98 I don't think so if everything is working ok.
