### ISSUE TITLE
Unlock the wallet using the generated hash

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#571]
We would like to unlock the wallet using a generated hash rather than a stored hash of the PIN. This will allow us to fall back to the PIN unlock if biometrics fails. As part of this we can deal with #568 where we separate unlocking the wallet and starting communications with the mediator.

- [x] Stop saving the hash to the keychain if when PIN is used for authentication;
- [x] Save the hash to the keychian when biometrics is used;
- [ ] Use the wallet to test if the hash is correct in both cases (PIN and Biometrics).

**Comment by wadeking98** [comment]
I could tackle this one. I'm assuming we'll only be storing the generated hash if the User is using biometrics, correct?

**Comment by jleach** [comment]
@wadeking98 I think you'll need this one merged in first [446](https://github.com/hyperledger/aries-mobile-agent-react-native/pull/446). Once a PR is in for this change move on it #568. They're pretty independent changes.

**Comment by wadeking98** [comment]
@jleach in the biometrics case, is it necessary to load the wallet key from biometrics storage AND verify it against the wallet? checking the wallet key would add a few seconds to log on time and I don't think it would be possible for the wrong wallet key to end up in biometrics storage anyway

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/449
