### ISSUE TITLE
Photo attribute

### ISSUE THREAD

**Issue by alexgmetcalf** [bcgov/bc-wallet-mobile#574]
Explore the possibility of having a photo in the wallet (as an attribute of a VC) that can be marked as non-shareable.

- Wallet recognizes specific credential definitions and identifies the photo attribute
- Credential detail screen UI indicates in some way that the photo attribute is non-shareable
- Proof requests for photo attribute are rejected

Questions:
- [ ] Photo size requirements/limitations (BCSC photos ~200-300Kb)

**Comment by swcurran** [comment]
My thoughts on this and the use of OCA to achieve this capability.

While there is info in the OCA bundle about the attribute that is useful for this feature -- e.g. that it is an image and the format of the image -- it is not clear to me that there is a good way to mark an attribute as "not shareable" in OCA. There is not that concept in OCA already, and I can't see it as a common feature that will be generally useful across the community.  As such, I think (at least for now) this should be implemented as a "BC Wallet" feature that gets applied when specific CredDefs are loaded.

**Comment by alexgmetcalf** [comment]
> As such, I think (at least for now) this should be implemented as a "BC Wallet" feature that gets applied when specific CredDefs are loaded.

Okay, I'll update the ticket detail to reflect.
