### ISSUE TITLE
Add a Photo to the VP VC credential

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#575]
As a Holder, I want to see my photo associated with my BC Digital ID, so that I have a more personal connection to the credential

The Photo is a non-shareable attribute
The photo ID is not meant to be used as a valid photo ID

**Comment by trinitywolfe** [comment]
Are you thinking it'd be the photo from the person's BC Services Card (if their card has a photo) or just a photo that someone takes?

**Comment by knguyenBC** [comment]
It should be a photo (if available) from their BC Services Card.

**Comment by knguyenBC** [comment]
Closed because this is a duplicate ticket to this [ticket #574](https://app.zenhub.com/workspaces/bc-wallet-6148e7423fe04b001444e2bd/issues/bcgov/bc-wallet-mobile/574 )
