### ISSUE TITLE
Automate receiving the BCSC Verified Person credential

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#584]
When the BCSC Verified Person credential arrives the WebView should be closed automatically as part of completing the workflow.  

- [x] Wait for credential offer to arrive, close WebView, and display credential offer

Please see a [detailed diagram of the workflow](https://app.mural.co/t/digitalidentityandtrust0399/m/digitalidentityandtrust0399/1646684933683/e94524d1dac5d1d8764a608ee9799c447431424f?wid=0-1647542875263&sender=uaf080de663fb91ec05ae1496)

**Comment by jleach** [comment]
Final issue fixed. I think the feature is alpha complete.

**Comment by nodlesh** [comment]
Tested in test automation and running in the nightly regression.
