### ISSUE TITLE
Biometrics (Face ID) first time failure on iOS makes user enter app PIN then Face ID again

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#589]
### Steps to Reproduce (see attached video :44-:58)
With Fave ID Biometrics enabled on the device, close the app and reopen.
Fail the first Face ID (:49)
At this point the first cell of the App PIN is in focus and the iOS keyboard is displayed. (:52)
Enter the proper APP PIN and click Enter (:55)
Face ID Verification is then displayed again. (:57)

### Expected Result
User would not go to the Enter App PIN, but would get another Face ID Verification after the failed one. Once the failure of the Face ID happened 3 times (I think), the user would get the Device PIN to enter, if no device PIN they would get the App PIN to enter.

### Environment
iOS 15.7
iPhone 11
Face ID enabled

### Workaround
Properly Authenticate on the second Face ID Verification screen and you will be allowed into the app.

### Severity
Medium

### Priority
Medium

### Video
https://images.zenhubusercontent.com/429950091/42b90a15-e294-4cef-b121-62d1b483a290/video.mp4

### Test Impact
This case is formally tested in Test `T002-Security` in [security.feature](https://github.com/hyperledger/aries-mobile-test-harness/blob/main/aries-mobile-tests/features/bc_wallet/security.feature)

**Comment by wadeking98** [comment]
I can't test this on IOS but it should be patched once bifold is updated to latest in bcwallet

**Comment by hiteshgh** [comment]
@nodlesh - can you pls re-test and close if working

**Comment by nodlesh** [comment]
The issue in this ticket is resolved. Tested in latest build 1077.
