### ISSUE TITLE
Biometrics (Fingerprint) can be cancelled causing app to get into a bad state

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#590]
### Steps to Reproduce (see attached video :44-:58)
With Fingerprint Biometrics enabled on the device, close the app and reopen.
Fail the first Fingerprint (:03)
Click Cancel (:05)
Enter the proper APP PIN and click Enter (:11)
Fingerprint Verification is then displayed again. (:12)
Keep failing the Fingerprint and entering a proper PIN and you will eventually get into the perpetual initialization screen.

### Expected Result
Cannot cancel Fingerprint, or if you do, accept the App PIN.

### Environment
iOS 15.7
iPhone 6S
Fingerprint enabled

### Workaround
Properly Authenticate on any of the Fingerprint Verification screens and you will be allowed into the app.

### Severity
Medium

### Priority
Medium

### Video
https://images.zenhubusercontent.com/408537088/a0ee40be-52f0-4c72-be32-f4d277f5068e/failbiometricsfinger720.mov

### Test Impact
This case is formally tested in Test `T002-Security` in [security.feature](https://github.com/hyperledger/aries-mobile-test-harness/blob/main/aries-mobile-tests/features/bc_wallet/security.feature)

**Comment by alexgmetcalf** [comment]
To help diagnose, I'd add that the reasoning message for the biometrics changes to "Authenticate to retrieve secret".

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/449
