### ISSUE TITLE
Add a unlock with biometrics button to login screen

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#595]
Currently, if people decide to cancel the biometrics prompt (either by accident or on purpose), there isn't an intuitive way to bring back the prompt again.

Please add a "Log in with biometrics" button below the "Enter button" in the secondary button UI. 

Note: the biometrics prompt should still automatically be prompted the moment the Holder opens the app. 

Please see the [video that illustrates the desired behaviour](https://images.zenhubusercontent.com/429950091/73e8e75a-c87f-4a3a-b66b-d9d645586dc2/adobe_xd_2022_10_05_17_03_02.mp4) with the biometrics button
Note: the video features old terminology. Please follow [ticket 626 ](https://app.zenhub.com/workspaces/bc-wallet-6148e7423fe04b001444e2bd/issues/bcgov/bc-wallet-mobile/626)

### Acceptance Criteria
Given the user has biometrics enabled to log into their wallet
When they are prompted to log into the app
Then they are presented with a[ button to [Unlock with biometrics](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/67d7bc50-7ccd-465e-8aa3-b1c5a9c768cc) **(alongside the automatic prompt for biometrics)**

Given the user has biometrics enabled to log into their wallet
And the user has cancelled the biometrics prompt
When the user selects "Unlock with biometrics"
Then they are prompted again to unlock the app using biometrics

Given the user does NOT have biometrics enabled
When they are prompted to unlock the app
Then they are NOT presented with a biometrics button
And are [prompted to enter the wallet PIN only](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/2e8b48ed-c59c-45b2-b73f-0c181e12b711)

**Comment by knguyenBC** [comment]
Added link to wireframes. This is ready for development

**Comment by cvarjao** [comment]
Having the "Enter PIN" field visible might be a bit confusing. For example the ICBC Banking app has an small option for "Use password instead"

**Comment by cvarjao** [comment]
![signal-2022-10-04-114048.png](https://images.zenhubusercontent.com/5c75a872bb88ef3edd6c33ec/b50a9b13-aa68-45fb-bde3-661052712b76)

**Comment by knguyenBC** [comment]
Biometrics should prompt automatically and the prompt overlays over the wallet PIN screen. That should mitigate any confusion as to which login method to use. But I do see some inconsistent language though. "**Login** using biometrics" and "Enter". I'll update it so it's consistent

**Comment by knguyenBC** [comment]
Added a video, updated wireframes and added an extra acceptance criteria to help clarify and illustrate the behaviour

**Comment by knguyenBC** [comment]
Updated the ticket with the new screenshots. Reviewed the terminology changes with John.

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/496

**Comment by knguyenBC** [comment]
on iOS iphone SE, when I cancel the biometrics prompt, the PIN input is automatically focused which subsequently prompts the keyboard. The keyboard covers the buttons and I can't dismiss the keyboard. In the scenario that someone would want to prompt biometrics again, they would not be able to easily. The only way to dismiss the keyboard is if I type a PIN in (any number) to remove the focus on the PIN input.
