### ISSUE TITLE
Screen reader reads list of notification incorrectly

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#601]
Screen readers read all the headings first of all the notification, then the notification content of all the notifications, then the buttons. 

The screen reader should read in order:
- Heading
- notification content
- button label

Then move on to the next notification.

See video:
https://images.zenhubusercontent.com/429950091/b0e30e0a-8b6e-4101-88ab-b68074c690cf/20221018_1710370439.mp4

**Device**:
Only saw issue on iOS, not on Android
Build 447

**Comment by jleach** [comment]
After reading docs and some trial and error I think this issue **won't** be fixable in the current component. Notifications are a horizontals "table" of cells. I think the screen reader is going through the list and reading the first element as a way to summarize the table contents rather than detailing each card.

**Comment by knguyenBC** [comment]
New update reads the notifications in the correct order but somehow (only on iOS) overrides the ability to tap the notification to open it. See video. At the end you see me struggling to open the notification with Voice Over. I also couldn't tap it using Voice Control. https://images.zenhubusercontent.com/429950091/fc035d38-cadd-4c77-a713-2d9a4c9dab17/20221205_1631296255.mp4

**Comment by nodlesh** [comment]
Should we move this back to Sprint Backlog or In progress?

**Comment by nodlesh** [comment]
@knguyenBC Can you recheck this? Should this be closed or is there something else needing to be completed here?

**Comment by knguyenBC** [comment]
Checked. The issue with iOS devices not being able to select the notification is still there.

**Comment by nodlesh** [comment]
@cvarjao  Moving back to the top of Estimated/Ready to be slotted for upcoming sprint.

**Comment by jleach** [comment]
I think we should wait for #1028 to be finished before working on this.

**Comment by cvarjao** [comment]
we are putting this on hold as we have plan to switch to vertical list of notifications
