### ISSUE TITLE
Detects if biometrics have been disabled on the device

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#607]
Detect changes in biometrics, notifies the user, and disabled biometrics authentication

### Scenario: Disables biometrics on the devices
Given the user has previously enabled biometrics
  and have disabled biometrics on the device
When the user opens the app
Then
   Notifies user that biometrics have been disabled on the device
   and disables biometrics authentication
   and the user us prompted to use app PIN

[Wired Frames](https://xd.adobe.com/view/af2fe4ac-c770-4f75-8666-c45602ba2443-fa7c/)

- [User Flow](https://app.mural.co/t/digitalidentityandtrust0399/m/digitalidentityandtrust0399/1661808127835/fad19a32b9a164538e74a1c6c4a9897152a2ec5a?wid=0-1661816654839&sender=udd49d732231dcec4105b0090)

**Comment by wadeking98** [comment]
@cvarjao Is this a duplicate of #606 ?

**Comment by cvarjao** [comment]
No. #606 is for detecting that the enrolled biometrics have changed since it was last enabled.
#607 is for detecting that the use disabled biometrics all together in the OS.

**Comment by wadeking98** [comment]
@cvarjao could you elaborate on the difference between `enrolled biometrics` and `biometrics on the OS`

**Comment by jleach** [comment]
Might be fixed by [466](https://github.com/hyperledger/aries-mobile-agent-react-native/pull/466)?
