### ISSUE TITLE
Lock app after being on background for over 5 minutes

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#608]
### Acceptance Criteria
Given BC Wallet is open in the background 
When the app is brought foreground
   and it has been more than 5 minutes in the background
Then the app will lock the user out of the wallet
And [notification will appear that informs people that they were logged out](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/ce9d1eee-3dc5-4774-af96-ec59d31ef273)

Reference
- https://stackoverflow.com/a/56180589

**Comment by wadeking98** [comment]
Depends on: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/456

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/456
