### ISSUE TITLE
present multiple credential proof request

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#614]
As an verifier, I want to be able to request multiple credentials in a proof request, so that I can increase the identity assurance level

As a wallet holder, I want to be able to see which credentials my attributes are coming from so that I can ensure that the correct information is being sent over

(When multiple credentials are being asked there is no easy indication in the UI where each attribute is coming from)

### Crawl

Specs: https://xd.adobe.com/view/fc9338af-128f-487b-87e2-c35cca9811f1-a9c0/

**Acceptance criteria**
Given a verifier is requesting attributes from multiple credential schemas that the wallet holder can provide
When the wallet holder opens the proof request notification
Then they are presented with the [proof request that informs them of the attributes requested](https://xd.adobe.com/view/fc9338af-128f-487b-87e2-c35cca9811f1-a9c0/)
And where the attributes are coming from (which credential)
And a "Send" and "Decline" button

Given a verifier is requesting attributes from multiple credential schemas that the wallet holder does not have in their wallet
When the wallet holder opens the proof request notification
Then they are presented with the [proof request that informs them of the attribute labels requested](https://xd.adobe.com/view/f63f7e5f-9ba9-484a-ac93-14a19084e6f0-a36c/) (in human-readable format)
And they are notified of credential schemas requested that are not available in their wallet
And a "back to home" and "Decline" button

Given a verifier is requesting attributes from multiple non-revoked credential schemas of which the wallet holder has some revoked
When the wallet holder opens the proof request notification
Then they are presented with the [proof request that informs them of the attributes requested](https://xd.adobe.com/view/f63f7e5f-9ba9-484a-ac93-14a19084e6f0-a36c/screen/d4b67d13-0fe5-44b5-bb08-65e3feb62cc3)
And where the attributes are coming from (which credential)
And notified which credential is revoked
And a "back to home" and "Decline" button

**Comment by wadeking98** [comment]
resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/634

**Comment by knguyenBC** [comment]
@wadeking98 UI for requested credentials that are revoked is incorrect. This is the screenshot for build 772. The member card is revoked and does not reflect the revoked UI.  ![20230404_190706.jpg](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/6ca7f495-3b18-4b2e-918b-7ee6662c32f2).

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/706

**Comment by nodlesh** [comment]
This Story is still in Review/QA because the Acceptance Criteria(AC) has not been fully tested (manual or automated). I don't know where these can be tested manually to cover the AC. 
The automated regression tests need to be expanded to cover the AC, there are two multiple credential proof tests running, T010.1-Proof and T010.2-Proof in https://github.com/hyperledger/aries-mobile-test-harness/blob/main/aries-mobile-tests/features/bc_wallet/proof.feature.
These two tests just do an accept and a decline of a multi-credential proof with two revokable credentials that are not revoked.

**Comment by wadeking98** [comment]
@nodlesh Should I assign to you then if you wanted to do more testing?

**Comment by hiteshgh** [comment]
Assigned to @knguyenBC

**Comment by nodlesh** [comment]
I believe it should be assigned to me. Unless Kim has a manual way to test this?

**Comment by knguyenBC** [comment]
Checked AC. works as expected. closed.
