### ISSUE TITLE
Detect if there is connectivity to ledger

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#616]
While we wait for #403, can we detect if the app is unable to reach the ledger, and inform the user of possible remediation step (E.g.: Turn off wifi, and use mobile network 3G/LTE/5G)

### ACCEPTANCE CRITERIA
Given the app is open
When the user unlocks the wallet  and there is no connectivity to a ledger
Then users see a dismissible error notification (see notification section of style guide) popup message

Given the user sees an error notification detailing there is no connectivity to a ledger
When the error notification is dismissed
The the user is taken to the home screen of the app

**Content of notification**
Header:  Oops! Something went wrong
Body: You may experience issues adding or proving your credentials. Try turning off Wi-Fi on your mobile device.
Button: Okay

**Comment by knguyenBC** [comment]
Updated the acceptance criteria and add updated content for notification.

**Comment by nodlesh** [comment]
Is this in build 594? Doesn't seem so.

**Comment by nodlesh** [comment]
Build 595 doesn't seem to have it either. 
iOS is not showing any offline message and the initialization goes on perpetually.
Android shows the offline message right away, but then goes into initialization perpetually.

**Comment by nodlesh** [comment]
Doesn't seem to be in build 629 either. 

@cvarjao @jleach Am I missing something here? Is this implemented. Always get a perpetual initialization. Should we move this back to the backlog?

**Comment by nodlesh** [comment]
Testing with 683, not sure I know how to make that error display. With out an internet connection and then unlocking the app, is gives the Opps message, but the body is not what is listed above. It says to restart the app. 
![IMG_6459C70B58D8-1.jpeg](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/8a0657a3-2724-40f7-aa31-447a4963c83c)

**Comment by jleach** [comment]
I did this as part of #543. It shows a toast if the app cannot connect to at least one ledger. If it can, it is assumed that there is no firewall in place because they usually operate on an all or nothing basis. If one of the ledgers is down for some reason that's a different issue.

**Comment by amanji** [comment]
@jleach I think this is more to have a way to reliably reproduce non-connectivity

**Comment by jleach** [comment]
@amanji I think what we need to do then is when the wallet starts run through the two network checks: 1. Is my device connected to a network; and 2) can I connect to a ledger. Both exist already. They just need to be brought into the Splash screen a bit more gracefully.
