### ISSUE TITLE
Remove references to "login" and replace term to Unlock/Locked

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#626]
There's inconsistent language between the main call-to-actions on the PIN screen. This is the current PIN screen: 
![20220920_181208.jpg](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/62506ea1-df35-43fc-8a51-b4532beb7814)

Please update the following:
Enter PIN -> Enter your wallet PIN
Enter -> Unlock

**Comment by wadeking98** [comment]
Resolved By: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/478
