### ISSUE TITLE
Timeout on Initialization shows message then perpetual loading

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#627]
### Steps to Reproduce 
When the initialization happens (when onboarding or opening the app), it can timeout, displaying the following;
![Screen Shot 2022-10-04 at 7.49.58 PM.png](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/3d1f9644-3ef8-4ac3-b277-ebf2a05fa55b)
This timeout message goes away and seems to go into perpetual initializing.

This seems to happen more in Sauce Labs than in the real world. There seems to be some extra latency when including the SL environment.  

### Expected Result
This is what needs to be nailed down. There was a [conversation on RC](https://chat.developer.gov.bc.ca/group/bc-digital-wallet-core-team?msg=JF8eDv35zx6w8fvXL) about what should happen. There may need to be more conversation on this. This is what @knguyenBC said.

> The app should allow people to continue to enter into the app. The app should not, in any way, bar people from entering their wallet. There’s already a “big brother” sense looming around the app and we want to make sure we tamp it down as much as possible. Also, there are things they can do, such as change anything in settings, delete credentials, simply review their credentials etc. If they try to continue to use their wallet for a proof request or credential offer, it should provide them another error. If anything, this error you posted Sheldon, might be better off removed as a user facing error as they’re not able to do anything to correct it.

### Environment
iOS 15.7
Haven't got a timeout on Android to see if the same thing happens.

### Workaround
Close and reopen the app is usually successful

### Severity
Medium

### Priority
Medium

### Test Impact
The timeout is not formally tested yet, but it occasionally happens and causes a test failure in the test pipeline. It can impact any and all tests.

**Comment by knguyenBC** [comment]
Discussed at standup. Team huddle required. Ticket might be divided into multiple tickets as this task is not trivial.

**Comment by cvarjao** [comment]
we will improve the error handling and how it it displayed while also investigating the root cause
