### ISSUE TITLE
BCSC Workflow not loading webview on Android

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#629]
### Steps to Reproduce (see attached video 4:35)
On Android, follow the flow to get a Person credential from BC Digital ID.
When the proof of the certificate is successful the web view is not loaded with the login to BC Digital Services Card Account Login. 

### Expected Result
As in iOS the browser web view in the app would load for 31+ and 30- will bring you to chrome. 

### Environment
Android devices API level 31+ and 30-. Both seem to have the similar behaviour. 

### Workaround
No workaround known on Android

### Severity
High

### Priority
High

### Video
https://images.zenhubusercontent.com/429950091/32f613e7-9451-4daa-9000-e82c09092ad5/bcscworkflowandroidbug.mov

### Test Impact
This case is formally tested in Test `T001-BCSC` in [bcsc.feature](https://github.com/hyperledger/aries-mobile-test-harness/blob/main/aries-mobile-tests/features/bc_wallet/bcsc.feature)

**Comment by jleach** [comment]
@nodlesh That part of the workflow can be a bit glitchy, although, I just tested on an Android emulator and it works. If you could retest that would be great. In any case, I need to work on improving that workflow.

As a work around, are you able to "Go back to home" then open the notification and continue with the workflow? Assuming you see one notification waiting for you.

**Comment by nodlesh** [comment]
I'll retest with the latest build (511) to get a fresh assessment. But, not sure I understand what you are saying above. At this point the webview loads to initiate getting the actual person credential. If the web view doesn't load I can't authenticate as a BC SC person and get the red issued. Am I misunderstanding what you are saying? 

Also this issue is blocking Divya's testing as well on her real device. Same issue.

**Comment by jleach** [comment]
@nodlesh  

Clecio, Hannah confirmed in v1.0.5 that Android works as expected and is evidenced by [Kim's video](https://drive.google.com/file/d/17S2mR2vUpwiP6F0jQtVF7sq5cuCIrJ1_/view?usp=sharing). I've asked what version of Android they use for more info. There is a "this link has expired" note that first appears, this is a BSCS issue. I've asked Kim or Clecio to bring it to Marco's attention. Also, as noted by Kim's video pressing "Cancel" during authentication causes an error. This I can fix.

**Comment by nodlesh** [comment]
Can confirm. This is now working on Android (build 519). Tested on my personal Android device and multiple Android devices in Sauce Labs. This ticket can be closed.
