### ISSUE TITLE
Handle revocation notification message

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#63]
As a Holder, I want to be notified as soon as possible if my credential is revoked so that I can take appropriate action to regain my credential and not accidentally use my revoked credentials and be unsuccessful in a proof request.

Handle revocation message:
- Display notification
  * [Display notification for revoked credential](https://xd.adobe.com/view/efd8f0c6-3ba0-436e-b72c-2dad62569aa2-ba8b/screen/668ba2f8-3e64-41f9-9bbf-986f7d4f5405)
- Mark credential as revoked 
  * [Revoked credential in Credential List](https://xd.adobe.com/view/045a1969-719a-4aa5-848f-637ef1b7051a-5109/screen/3a68ab92-5a8f-4e5b-a3ec-7fc5e40cd22c/specs/)
  * [Revoked credential detail](https://xd.adobe.com/view/615be678-5184-40cc-ab24-11a379a51233-3408/)
- Update testing harness to support revocation

### Acceptance Criteria:
Given a credential has been revoked
When the holder open the wallet
Then a notification appears in their notification stating that the credential has been revoked
And opening that notification will take the user to the revoked credential details

Given a credential has been revoked
When the holder goes to the revoked credential details
Then they will see a dismissible notification at the top displaying the revocation date and revocation message by the issuer
And they will see a revocation status below the issued date in the credential details

Given a credential has been revoked
When the holder dismisses the dismissible notifications at the top displaying the revocation date and revocation message by the issuer
Then that notification is permanently dismissed and can not be brought back again

## Blocked By
- https://github.com/hyperledger/aries-framework-javascript/issues/493
- https://github.com/hyperledger/aries-framework-javascript/pull/579

#### Scenario: Holder is Notified that their credential has been revoked
Given that a revocable credential is being stored in the wallet
   And a connection to the issuer exists
When the issuer revoke a credential
   And sends a revocation message to the holder
  Then The holder receives a revocation message notification

#### Scenario: Holder review revocation message
Given that holder has received a revocation message
   And a notification is showed in the notification list
When the holder selects the message in the notification list
  Then the holder is taken to the credential details of the revoked credentials
    and a revoked message is presented
    and a dismiss button is available on the message
    and a revoked status is available below the issued by data

#### Scenario: Holder prompts the revocation message again
Given the holder has a revoked credenital
When the holder selects the (i) info button next to the revoked status
Then the revoked message is presented again
          

Questions:
- How the holder get a notification/message of revocation?

**Comment by cvarjao** [comment]
AFJ should handle the revocation message, fetch revocation registry entries, and flag credential as revoked

**Comment by cvarjao** [comment]
being worked under https://github.com/hyperledger/aries-mobile-agent-react-native/pull/504

**Comment by knguyenBC** [comment]
Reviewed the revocation message with Akiff and updates are good to complete this ticket. Bugs were identified and will be added as new tickets. These bugs include were : 1. Card UI doesn't update with revocation UI unless user closes and opens the wallet 2. When a user receives a proof request, then their credential is revoked, the proof request does not update with the new credential status.

**Comment by cvarjao** [comment]
I unable to reproduce/test this locally

**Comment by cvarjao** [comment]
Needs to check the layout. The icon and the colors are not matching the design

**Comment by nodlesh** [comment]
@knguyenBC The acceptance criteria in this ticket states that the Credential details after a revoke, would have an `Okay` and `Keep`. Is this still the way we want it or should we change the acceptance criteria to `Dismiss` instead?
Assuming if `Keep` is selected, the notification stays?
<img width="256" alt="Screenshot 2023-03-07 at 11 08 40 AM" src="https://user-images.githubusercontent.com/44370861/223483027-54a46c43-7391-405f-bf21-fd7300f70506.png">

**Comment by knguyenBC** [comment]
Updated to ticket to reflect the newest designs and flows.

**Comment by knguyenBC** [comment]
@wadeking98 the third acceptance criteria is not met: Scenario: Holder prompts the revocation message again.

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/819

**Comment by jainavinash845** [comment]
Hi @cvarjao @wadeking98 @nodlesh 

After revoking a credential from agent side, We are using following attributes in Revoke APi
{
"comment": "string",
"connection_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"cred_ex_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"cred_rev_id": "12345",
"notify": true,
"notify_version": "v1_0",
"publish": true,
"rev_reg_id": "WgWxqztrNooG92RXvxSTWv:4:WgWxqztrNooG92RXvxSTWv:3:CL:20:tag:CL_ACCUM:0",
"thread_id": "string"
}
 But I am not receiving any notification for revoked credential on app.
Instead I am getting the following error in the console:

WARN WARN: Failed to process revocation notification message {
"error": {
"name": "AriesFrameworkError",
"message": "Incorrect revocation notification threadId format: \n79389b4b-efc4-425e-b951-3e5ed07ecd5f\ndoes not match\n"indy::<revocation_registry_id>::<credential_revocation_id>"",
"stack": "Error\n at captureStackTrace ([http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:114073:32)\n](http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:114073:32)%5Cn) at BaseError ([http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:114111:22)\n](http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:114111:22)%5Cn) at construct (native)\n at _createSuperInternal ([http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:114012:406)\n](http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:114012:406)%5Cn) at call (native)\n at BaseError ([http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:114032:26)\n](http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:114032:26)%5Cn) at construct (native)\n at _createSuperInternal ([http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:113991:406)\n](http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:113991:406)%5Cn) at call (native)\n at AriesFrameworkError ([http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:114004:25)\n](http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:114004:25)%5Cn) at v1ProcessRevocationNotification$ ([http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:185308:121)\n](http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:185308:121)%5Cn) at call (native)\n at tryCatch ([http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:20534:23)\n](http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:20534:23)%5Cn) at invoke ([http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:20680:32)\n](http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:20680:32)%5Cn) at anonymous ([http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:20574:30)\n](http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:20574:30)%5Cn) at call (native)\n at tryCatch ([http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:20534:23)\n](http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:20534:23)%5Cn) at invoke ([http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:20599:30)\n](http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:20599:30)%5Cn) at anonymous ([http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:20624:19)\n](http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:20624:19)%5Cn) at tryCallTwo (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)\n at doResolve (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)\n at Promise (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)\n at callInvokeWithMethodAndArg ([http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:20623:33)\n](http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:20623:33)%5Cn) at enqueue ([http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:20627:157)\n](http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:20627:157)%5Cn) at anonymous ([http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:20574:30)\n](http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:20574:30)%5Cn) at anonymous ([http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:20641:69)\n](http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:20641:69)%5Cn) at v1ProcessRevocationNotification ([http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:185295:82)\n](http://localhost:8081/index.bundle?
},
"threadId": "79389b4b-efc4-425e-b951-3e5ed07ecd5f"
}

Can anyone help in what I might be doing wrong?
