### ISSUE TITLE
Update VPVC Pilot Invitation E-mail Text

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#631]
https://github.com/bcgov/trust-over-ip-configurations/blob/main/openshift/templates/issuer-api/config/bcvcpilot/invite-email.html

Please find the content for the email here:
https://docs.google.com/document/d/1PCQ3pR-8ovJ_xOc-FkEGSFI12ffoXQxBsnr4crIIBa0/edit?usp=sharing

**Comment by knguyenBC** [comment]
Updated the ticket with the email content

**Comment by wadeking98** [comment]
Resolved by: https://github.com/bcgov/trust-over-ip-configurations/pull/115

**Comment by wadeking98** [comment]
Issues with different email clients rendering the HTML differently. @cvarjao How high of a priority is this?
