### ISSUE TITLE
Update VPVC Pilot Invitation Main Page Text

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#632]
https://github.com/bcgov/trust-over-ip-configurations/blob/main/openshift/templates/issuer-web/config/bcvcpilot/terms-and-conditions.html

Please find the content for the main page here:
https://docs.google.com/document/d/1PCQ3pR-8ovJ_xOc-FkEGSFI12ffoXQxBsnr4crIIBa0/edit?usp=sharing

**Comment by knguyenBC** [comment]
Updated the ticket to include the content for the main page

**Comment by wadeking98** [comment]
resolved by: https://github.com/bcgov/trust-over-ip-configurations/pull/113
