### ISSUE TITLE
BC Wallet app is not resuming when user selects Cancel on AriesBifold alert 

### ISSUE THREAD

**Issue by DImalika** [bcgov/bc-wallet-mobile#649]
Repro Steps:
-Install the BC Wallet app
-Accept the pilot invitation and credential offer in the BC Wallet app
-Select BC Digital ID button and open the Proof of Request and accept
-Opens the AriesBifold alert and select Cancel
Actual Result:
![IMG_4633](https://user-images.githubusercontent.com/115668531/196265949-eacaed05-eafe-4ecf-b848-06d324556f36.PNG)

The BC Wallet app buffers and never resumes back to the back. Force closing the app resolves the issue.

Notes:
iOS X OS 15.6.1
BC Wallet version 1.0.3 (404)
https://idimjira.gov.bc.ca/browse/IASP-14515

**Comment by wadeking98** [comment]
This appears to no longer be an issue
