### ISSUE TITLE
Can able to add 2nd BC VC pilot credential offer to the BC Wallet app 

### ISSUE THREAD

**Issue by DImalika** [bcgov/bc-wallet-mobile#650]
Repro Steps:
-Install BC Wallet app and setup
-Receive and accept the BCVC Pilot credential app
-Attempt to add second BCVC Pilot credential by getting the email invitation

Actual Result:
-Can able to add second BCVC Pilot credential 
![Screenshot_20221017-112557](https://user-images.githubusercontent.com/115668531/196268029-712845bd-475b-4ac1-b894-38490a6ca7b1.jpg)

Notes:
Occurring on both iOS X (OS 15.6.1- 404) and Android (OS 11 V445)
https://idimjira.gov.bc.ca/browse/IASP-14501

**Comment by cvarjao** [comment]
This is the expected behaviour, the wallet will store as many credentials as you want
