### ISSUE TITLE
BC Digital ID button is active when the app is force closed and reopens

### ISSUE THREAD

**Issue by DImalika** [bcgov/bc-wallet-mobile#651]
Repro Steps:
-Install BC Wallet app and setup
-Receive and accept the BCVC Pilot credential app
-Select the BC Digital ID button  
-Opens the Proof of Request 
-Now navigate back to the home screen 
Actual Result:
-BC Digital ID button is in Active state and can able to receive 2nd proof of request
https://idimjira.gov.bc.ca/browse/IASP-14500
![File (10)](https://user-images.githubusercontent.com/115668531/196277505-5ba4d8bd-0777-4d5d-a086-0a3eb0cb93e9.jpg)

**Comment by cvarjao** [comment]
closing a stale issue. This will also be addressed by future app-2-app integration
