### ISSUE TITLE
Splash "Splash" from top left corner of the header just buffers 

### ISSUE THREAD

**Issue by DImalika** [bcgov/bc-wallet-mobile#652]
Repro Steps:
-Install the BC Wallet app
-Select "Splash" from top left corner of the header
Actual Result:
-App just buffers have to force close the app
https://idimjira.gov.bc.ca/browse/IASP-14594
![home screen](https://user-images.githubusercontent.com/115668531/196296558-5f81b1d6-e885-45fa-8250-5d15c43b5a78.jpg)

**Comment by cvarjao** [comment]
duplicates #460
