### ISSUE TITLE
Get Credential button waiting state

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#654]
### User story
As a user, I would like some feedback when a button is pressed so that I know if I pressed it and the app is actively doing something or if it's simply frozen.  

### Overview
Please add an animated loading icon to the "Get your Person credential" button so people are provided feedback that the button is pressed, something is happening and to wait.

Please use the active button state for the "Get your Person credential button. [See the style guide on buttons](https://xd.adobe.com/view/eb9e0945-61d7-40ca-8e8e-bf4bd0c72934-becd/screen/8e863a95-8c83-47db-92ed-d9cf13332153/).

Please animate the loading icon as seen on this video: 
https://images.zenhubusercontent.com/429950091/4f156b94-12fe-41e5-8d56-338d1109ea47/adobe_xd_2022_10_20_14_50_15.mp4

Please use the "[autorenew](https://fonts.google.com/icons?selected=Material%20Icons%3Aautorenew%3A)" icon from the material icons library, animated clockwise.

### Acceptance Criteria
Given the Holder an Invitation Credential
When the Holder select "Get your Person credential" button
Then the button changes to its active state
And an animated loading icon replaces the static "credential" icon

Given the Holder has selected "Get your Person credential" button
And the button is in it's active state
Ad the wallet is waiting for a proof request
When the proof request arrives and is displayed in the wallet
Then the button "Get your Person credential" button changes back to its default state

**Comment by knguyenBC** [comment]
Added story, designs and acceptance criteria. This is ready for dev.

**Comment by wadeking98** [comment]
@knguyenBC and @cvarjao does that mean we're getting rid of this spinner here?
![image.png](https://images.zenhubusercontent.com/5fc52e1a365e55a8d5b3f428/25e1fb63-1ccb-48ce-8d99-a1da40ad1a56)

**Comment by knguyenBC** [comment]
Yes please remove the spinner.
