### ISSUE TITLE
Need TestIDs on the Home and Credentials buttons at the bottom of the app

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#660]
For test automation I have used accessibility id to get at the Home and Credentials buttons at the bottom of the app. With the addition of Home notifications indicator I can no longer get access to this button consistently. The accessibility label now looks like `Home (0 Notifications)`. 

I would really appreciate TestIDs on the Home and Credentials buttons created.

**Comment by jleach** [comment]
Added in PR [501](https://github.com/hyperledger/aries-mobile-agent-react-native/pull/501).
