### ISSUE TITLE
Update credential branding style guide

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#664]
Stephen Curran - we’ve revised the list of elements in the Credential Branding overlay (new list: https://github.com/swcurran/aries-rfcs/tree/oca4aries/features/0755-oca-for-aries#aries-specific-branding-overlay), and I hoped you could update the Credential Branding Style Guide (link below) to use this. The document will itself become an Aries RFC so that Issuer/Holders can understand the data to provide and how to use it, respectively. As such, the doc should be generalized to be used by all issuers/holders (and even verifiers). Reasonable?

https://docs.google.com/document/d/1_tMS2F3A9y6xStVM-37-qlf4mXU-hYDW/edit

**Extra clarification** from Stephen Curran
You can overrule of course, but here is the intention on the first.

In the body, the issuer may indicate two of the attributes from the credential should be displayed on the body (middle section) of the Card. “primary_attribute” and “secondary_attribute” contain the names of the attributes – e.g. for the Person credential, BC as an issuer might pick “family_name”, and “birth_dateint”. The wallet could put the (multilingual) label and data values on the Card. Does that make sense?

What is displayed in the footer area is one thing, and based on what the Issuer puts in the OCA file will be either an attribute of their choice, an attribute that holds the expiry date, an attribute that holds the issue date, or the date that the wallet received the credential.

Of those 4 possibilities – currently the BC Wallet is showing the last one. BC Wallet is labeling “Issue Date” as the date the wallet received the credential – even though there might be an “issue_dateint” attribute in the credential.

**Comment by nodlesh** [comment]
Who can review this to move it to Done?
