### ISSUE TITLE
Open in a Trusted Digital Wallet option is not functional 

### ISSUE THREAD

**Issue by DImalika** [bcgov/bc-wallet-mobile#669]
Repro Steps:
-Install the BC Wallet app to accept terms of use and create pin
-Receive the email invitation for BC VC pilot app
-Proceed all through the invitation and accept
-The QR code screen displays
-Select the "Open in a Trusted Digital Wallet" option right below the QR code

Actual Result:
"Open in a Trusted Digital Wallet" option is not functional
![File (10)](https://user-images.githubusercontent.com/115668531/197623119-2b1bc8be-0779-402e-8256-e648501c080c.jpg)

**Comment by wadeking98** [comment]
Resolved by: https://github.com/bcgov/trust-over-ip-configurations/pull/106
