### ISSUE TITLE
Back button from Notifications screen is missing

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#670]
On the Notification list screen, the back button is missing. There should be a back button that takes the user back to the Home screen.

![signal-2022-10-25-115625_003.png](https://images.zenhubusercontent.com/5c75a872bb88ef3edd6c33ec/f991427a-372e-4924-adc8-2f124dd3fab8)

![signal-2022-10-25-115625_002.png](https://images.zenhubusercontent.com/5c75a872bb88ef3edd6c33ec/4842a64b-843a-49a4-926b-59f21b147c27)

Device:
iPhone SE, Build 457

**Comment by wadeking98** [comment]
resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/507
