### ISSUE TITLE
Android: chat message display shows as white text on white background

### ISSUE THREAD

**Issue by loneil** [bcgov/bc-wallet-mobile#677]
On my phone, in the Messages screen, the sent messages from the app are unable to be seen as they appear to be colored white on the white bubbles (see image below). The correct message text is in there I can tell, as I can copy/paste it out of the bubbles. As well, in the Type Message Here entry field the text is invisible (white).

App version: 1.0.3 Build (466)

Android Details: Pixel 6, Android 12.

![Screenshot_20221027-111035](https://user-images.githubusercontent.com/17445138/198367323-56dab1fb-6d1d-4876-af7d-494451bbd329.png)

**Comment by cvarjao** [comment]
Need to update BC Wallet Theme

**Comment by P-WHao** [comment]
Hi, which app you used to sent a message to the bifold app ya?
