### ISSUE TITLE
Credential Offer TestIDs in iOS 15 are not present in iOS 14

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#679]
The automated end to end integration tests gets the information from the credential offer page based on the testIds of 
`com.ariesbifold:id/CredentialCard`
`com.ariesbifold:id/CredentialCardHeader`
`com.ariesbifold:id/CredentialIssuer`
`com.ariesbifold:id/CredentialName`
to name a few. 

These testids are present when running on iOS 15+ but when running on a device with iOS 14 these testids are not present and the test fails. There are testids in the page for iOS 14, just not the credential card testids.

Hopefully there is a way to get these testids consistent over iOS versions.

See attachments for full page contents that Appium picks up in the different iOS versions. [https://app.zenhub.com/files/310693687/433ca90b-b967-43da-832c-b8382ef9c1c7/download](https://app.zenhub.com/files/310693687/433ca90b-b967-43da-832c-b8382ef9c1c7/download)

**Comment by cvarjao** [comment]
@nodlesh, should we drop testing support for iOS14? we will only test for iOS15+

**Comment by cvarjao** [comment]
Won't fix
