### ISSUE TITLE
biometrics UX bugs

### ISSUE THREAD

**Issue by CharlesMacpherson** [bcgov/bc-wallet-mobile#685]
My device is a Samsung Galaxy A51, Android. Using latest Google Play release from last week.

(1) Upon being prompted for app authentication when opening, "enter your wallet" pin flashes briefly after using finger print.
(2) when attempting to turn off biometrics the app freezes for a few seconds then quickly catches up with all the buttons your presses while it was frozen.
(3) once turned off, you cannot turn biometrics back on. The app asked for the app PIN and seems to accept it, but when you go back into the settings, Biometrics is still turned off.
(4) with Biometrics turned off, re-opening the app prompts for both PIN and biometrics
(5) device prevents taking a screen shot while device is asking for biometrics, but does not prevent screen shot when PIN screen is shown.
- Disable screenshot can't be able to be done in iOS

Split into 5 tasks, get details from Charles

**Comment by jmdkumar08** [comment]
@cvarjao needs to break it down.

**Comment by hannahgov** [comment]
@CharlesMacpherson could you try this again? and let us know your Android version. Please let us know which version of the BC Wallet app as well.

**Comment by CharlesMacpherson** [comment]
Samsung A51 Android 12

#1 is resolved.
#2 is resolved.
#3 is resolved.
#4 is resolved.
#5 is s till true. but it's not really an issue, more of a OS feature.
