### ISSUE TITLE
Control when Get Person Credential button can show up

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#693]
how can we release a new build with the Get Person Credential feature but control when exactly that features get enabled.

- Automatically enabled on Monday, November 21st
- Needs to be submitted for review earlier, and manually publishing through app stores

```text
(lawyer credential exists and date >= nov21) OR Invitation Credential
```

**Comment by jleach** [comment]
I think we'll know well in advance when we want to release it and we can just queue up a build with it enabled, get it approved by Apple and Google, then manually release it. On the iTunes store you can even schedule this for a prescribed time.
