### ISSUE TITLE
UX features to protect against "bad" verifiers

### ISSUE THREAD

**Issue by alexgmetcalf** [bcgov/bc-wallet-mobile#70]
The wallet UX can help protect the holder from presenting information to "bad" verifiers by implementing a set of basic checks and subsequent warnings for connecting and/or presenting proof requests.

Examples may include warning the holder if:

- A presentation request asks for the entire contents of any one VC
- A presentation request asks for more information than is deemed 'common'  based on the presentation history in the wallet
- Based on some form of analysis, information is being asked for that could be asked for in different, and less personal, manner (e.g. asking for proof of being over a certain age, rather than DOB)
- Based again on analysis, information is being asked for that could uniquely identify the person.

The warning may require the user to make an additional confirmation of the presentation after reviewing the message.

Solution Options:
- Identify verifiers that do not have a public DID
- Identifiers verifiers which public DID are not in a trusted registry (of our choice. e,g,: CANdy)

References:
- https://diacc.ca/voila-verified/

**Comment by knguyenBC** [comment]
I wonder if we can accomplish this by doing something similar with "trusted" organizations. For example, provide a simple notification that indicates that this is a suspicious presentation request (based on the above stated criteria) and the user can expand to read more on the specifics.

**Comment by CharlesMacpherson** [comment]
To have a verifier considered "safe", we could have them either present a verified org VC or have a public DID on Candy. If they don't meet that criteria the wallet could warn the user that is an unknown actor and may increase their risk.

**Comment by cvarjao** [comment]
closing stale issues. This is coming as verified contact ( #1978 , #1931 )
