### ISSUE TITLE
Notification not being shown

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#724]
When I have an empty wallet, the first credential offer notification doesn't show in the notification section
It looks like the offer is received, and restarting the app will bring offer in the notifications section

<Original issue pre build 549 - Sheldon>When I am using demo issuers like CANdy Unverified Person (https://openvp-candy-issuer-test.apps.silver.devops.gov.bc.ca/), or BC VP Pilot (https://bcvcpilot-issuer-admin-test.apps.silver.devops.gov.bc.ca/), with an empty wallet, I cannot get the credential offer without closing the app and reopening, then I get the offer notification and can continue. This happens on both iOS and Android, in the Automation Sauce Labs environment and my personal devices. This does not happen when tests are executed with my test harness issuer agents. This seems to diminish, though I can’t confirm it won’t happen, when there is already a credential in the wallet.

The issuer state at time of the problem:
<img width="876" alt="Screenshot 2022-11-14 at 11 44 49 AM" src="https://user-images.githubusercontent.com/44370861/202797931-0a3972f1-3cea-4f82-9802-1d2066229cee.png">

The continual app state at time of the problem, unless I shut it down and restart.
<img width="513" alt="Screenshot 2022-11-14 at 11 44 58 AM" src="https://user-images.githubusercontent.com/44370861/202798097-bbc9d1e6-aeab-4727-a4ea-3df03d4853e9.png">

**Comment by nodlesh** [comment]
This is no longer an issue. Tested in 594
