### ISSUE TITLE
User should not be able to tap back before enter pin screen is displayed when disabling biometrics

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#725]
Users can tap "back" before the "Enter PIN" screen is loaded.

**Comment by cvarjao** [comment]
@CharlesMacpherson , can you provide with your device Model and Android version?

**Comment by CharlesMacpherson** [comment]
Android 12 on Samsung Galaxy A51. It used to be worse, on build 557 it is okay, but I was able to catch it (press back before the PIN screen came up) and it just freezed up a bit, but actually didn't let me hit back, just delayed the PIN screen for a second.

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/562
