### ISSUE TITLE
Hide mediator service from contact for fresh install

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#727]
- Is there a way to differentiate a mediator from any other contact?
- Can we identify at least the mediator(s) currently being used by AFJ?

Acceptance Criteria
Given that an user has just installed the app
When the app is open
Then contact list should not show the mediator

**Comment by amanji** [comment]
This enhancement should be available with the merge of https://github.com/hyperledger/aries-framework-javascript-ext/pull/173/files, therefore moving to blocked for now.

**Comment by amanji** [comment]
The connection type may be available in AFJ 0.2.5. Therefore, will look at upgrading Bifold dependencies

**Comment by amanji** [comment]
Currently fixed by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/567

Will require migration script to convert existing connections before AFJ upgrade to include tags for `ConnectionType`

**Comment by nodlesh** [comment]
Verified on both Android and iOS in build 629
