### ISSUE TITLE
View List of Credentials

### ISSUE THREAD

**Issue by amanji** [bcgov/bc-wallet-mobile#73]
As an Holder, I would like to see all the credentials I own within my wallet in an organized way so that I can quickly review and manage my credentials.

As an issuer, I would like to present my organizations logo, so that I can advertise my organization and increase the level of trust to my customers.

### Definition of ready:
- User flow and wireframes are completed
- Acceptance criteria defined

## Wireframes
Lo-fi
https://xd.adobe.com/view/97aae1a4-dca6-4101-bda2-fb7fc70c9132-c2f9/ 

Hi-fi
https://xd.adobe.com/view/5edd5ca1-8978-4b3f-bf87-9ef21548b877-0b8e/ 

### Scenario: Holder selects a credential
Given the holder is in the credential list screen
When the holder taps on a credential
Then the holder is taken to the credential detail screen of that credential

~### Scenario: Holder's credential is revoked
Given the holder has a credential revoked
When the holder is viewing the credential list
Then the UI of the revoked credential changes to that of the UI of a revoked credential~

### Scenario: Holder receives a new credential
Given the holder receives a new credential
When the holder has just completed the credential offer flow
And the holder has accepted the credential offer
Then the credentials are ordered to most recent to least recent (top to bottom)

**Comment by knguyenBC** [comment]
Checked and it seems as though, on both android and iOS, the credential list is shown after accepting a credential.
