### ISSUE TITLE
VPVC Pilot invitation Deep link not working

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#732]
Context: After receiving invitation e-mail, reviewing credentials, and in the screen with the QR Code.
Nothing happens when taping "Open Wallet App"

**Comment by cvarjao** [comment]
blocks #669

**Comment by wadeking98** [comment]
Seems like this is an issue in the wider issuer-kit codebase, working on a fix

**Comment by cvarjao** [comment]
Duplicates #669
