### ISSUE TITLE
Settings subheading are sticking on scroll

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#736]
Setting subheadings are sticking to top on scroll. This is only appearing on iOS. See attached video https://images.zenhubusercontent.com/429950091/c5937ed5-3277-4ed2-aa70-d5ca72c2292d/20221121_1503073791.mp4

Subheading should scroll with the rest of the content.

**Comment by amanji** [comment]
Fixed by https://github.com/bcgov/bc-wallet-mobile/pull/755

**Comment by knguyenBC** [comment]
Reviewed build 586 on iOS and Android. No sticking. Looks good.
