### ISSUE TITLE
Allow notifications to be dismissed without opening them

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#745]
As a wallet holder, I want to be able to delete/dismiss notifications without opening them so that I don't have to open notifications from issuers/verifiers I don't recognize and I feel safer using the wallet.

**Research background**
When participants in a study were asked how they plan to deal with notifications from an organization they don't recognize, some participants hesitated to open the notification but wished to delete it. 

To delete notifications from their notification list is not intuitive. People want to "delete" or "remove" and do not connect that declining the notification is the same effect.

**DoD**
- [x]  Wireframes
- [x]  Acceptance criteria

**Solution:**
Add a "close" button to notifications and a "delete this request/offer" button to proof requests and offers.

### Acceptance Criteria
[Given the wallet holder has a notification](https://xd.adobe.com/view/efd8f0c6-3ba0-436e-b72c-2dad62569aa2-ba8b/screen/61b6e5b0-b146-4116-b6f3-356b3f0a08ab/)
When the "close' button on the notification is selected
Then a [modal sheet](https://xd.adobe.com/view/eb9e0945-61d7-40ca-8e8e-bf4bd0c72934-becd/screen/4c69b7e3-3b7e-4f99-844e-2b65ec172bbf/) describing the delete action slides up 
And contains a "delete" and "close" call-to-action

[Given the wallet holder has opened the credential offer](https://xd.adobe.com/view/3db881d4-e963-42ec-a2c4-6b5ca23862a3-68eb/screen/a523d262-2549-4da9-9c2e-35ba1a84d7e8/)
When the "Delete this offer' button is selected
Then a [modal sheet](https://xd.adobe.com/view/eb9e0945-61d7-40ca-8e8e-bf4bd0c72934-becd/screen/4c69b7e3-3b7e-4f99-844e-2b65ec172bbf/) describing the delete action slides up 
And contains a "delete" and "close" call-to-action

[Given the wallet holder has opened the proof request](https://xd.adobe.com/view/74b73461-45e5-4f2b-b219-79ffe9c852a7-21e4/screen/9eb4a24e-9690-496c-b85e-d8bb19b4f235/)
When the "Delete this request' button is selected
Then a [modal sheet](https://xd.adobe.com/view/eb9e0945-61d7-40ca-8e8e-bf4bd0c72934-becd/screen/4c69b7e3-3b7e-4f99-844e-2b65ec172bbf/) describing the delete action slides up 
And contains a "delete" and "close" call-to-action

**Comment by nodlesh** [comment]
@cvarjao @knguyenBC Can we link this to the Dev Story? I can't find the dev story.

**Comment by knguyenBC** [comment]
I can't seem to find the dev story either. I believe @wadeking98 had worked on this. Wade did you have a dev story ticket?
