### ISSUE TITLE
Update Button Design Guide

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#746]
A buttons goes through the following states:

- Active or Focused
- Pending
- Disable

**Comment by knguyenBC** [comment]
Style guide has been updated with the correct terminologies. : https://xd.adobe.com/view/eb9e0945-61d7-40ca-8e8e-bf4bd0c72934-becd/screen/8e863a95-8c83-47db-92ed-d9cf13332153
