### ISSUE TITLE
Unable to configure the mediator to run in an HA configuration.

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#750]
The mediator runs fine as a stand alone pod but when configured to be HA (3 or more pods) it does not work. Likely cause is either the HAProxy -> Caddy (proxying our web sockets) or Caddy -> Agent.

Spike Goals:
- Understand why we can't run the mediator in HA configuration
- Test ACA-py websocket/proxy plugin

**Comment by cvarjao** [comment]
Stephe, Ian and Shaanjot are looking into that

**Comment by cvarjao** [comment]
@jleach , any ETA when a fix might be available?

**Comment by jleach** [comment]
Shaanjot hopes to get back to mediator this week and wrap up the changes (get a PR in) next week. But Stephen also noted it will take some time to be reviewed by the community to make sure we get it right. The fix is likely several weeks out. @cvarjao

**Comment by swcurran** [comment]
The design is now ready and I'm starting to share it. It's the design that needs to be reviewed and agreed upon.

**Comment by cvarjao** [comment]
@esune, @swcurran, I am closing this issue from the wallet side. Is there a different ticket from ACA-py or medaiator repositories?

**Comment by swcurran** [comment]
I’ll add it.  It will be on Aries Mediator Service.

**Comment by swcurran** [comment]
@cvarjao — AFAIK based on the last SM/PO meeting, this is not an immediate priority for the Wallet team, correct?
