### ISSUE TITLE
Direct link - reliability

### ISSUE THREAD

**Issue by watkinspd** [bcgov/bc-wallet-mobile#756]
I have been using the direct link bcwallet:// I think there may be some assumptions that result from using the app to scan QR codes that are not true when a request is loaded via direct link. For example, it often happens that if the wallet app has been dormant, or is not running at all, then when a direct link is used, the app just opens to the Home Screen - nothing else happens. (My testing is on iOS).
Secondly, if you have approved a request and leave the app at the ‘information sent successfully’ screen and then use digital showcase with another direct link request - the wallet shows a blank screen with only the wallet header - the home button in upper right corner will navigate to the home page and show the request.

This behaviour is repeatable when using the digital showcase.

**Comment by wadeking98** [comment]
I'm increasing the estimate because I think I'll have to do some work with the navigation functionality. (eg: add a ?next parameter to the route so the app knows where to direct the user after authentication)

**Comment by wadeking98** [comment]
Resolved by:
- https://github.com/bcgov/BC-Wallet-Demo/pull/120
- https://github.com/hyperledger/aries-mobile-agent-react-native/pull/568

**Comment by wadeking98** [comment]
This is just waiting for me to rollout changes to test and prod for the showcase demo, otherwise it is done
