### ISSUE TITLE
Scan a QR code

### ISSUE THREAD

**Issue by amanji** [bcgov/bc-wallet-mobile#76]
* As a holder I need to use my device's camera to scan a QR code so I can start receiving VCs to my wallet.
* As a holder I need to use my device's camera to scan a QR code so I can start presenting things from my wallet.

### Acceptance criteria:
**Scenario: Opening the Camera Scan function**
Given the Holder has enabled permission for BC Wallet to use the device's camera
When the Holder selects the "Scan" button
Then the Holder is taken to the apps Camera Scan function
And the Holder is presented with the following features: Exit Camera Scan, Flash on/off

[See Getting a credential wireframe](https://xd.adobe.com/view/3db881d4-e963-42ec-a2c4-6b5ca23862a3-68eb/)

**Scenario: Using the Camera Scan function to scan a credential offer QR code** 
Given the Holder is using the Scan function in BC Wallet
And has enabled permissions for BC Wallet to use the device's camera
When the Holder scans a QR code that is offering a credential
Then the Holder is taken to the "Connecting..." Screen/modal

[See Getting a credential wireframe](https://xd.adobe.com/view/3db881d4-e963-42ec-a2c4-6b5ca23862a3-68eb/)

**Scenario: Using the Camera Scan function to scan a proof request QR code** 
Given the Holder is using the Scan function in BC Wallet
And has enabled permissions for BC Wallet to use the device's camera
When the Holder scans a QR code that is requesting or a proof
Then the Holder is taken to the "Connecting..." Screen/modal

[See Receiving a resentation request wireframes](https://xd.adobe.com/view/74b73461-45e5-4f2b-b219-79ffe9c852a7-21e4/)

**Comment by knguyenBC** [comment]
Checked on both Android and iOS against the acceptance criteria and everything passes
