### ISSUE TITLE
Selecting the Cancel button on Terms of Use screen throwing an error

### ISSUE THREAD

**Issue by DImalika** [bcgov/bc-wallet-mobile#768]
Repro Steps:
-Selected person credential button from BC Wallet app
-In app browser opened and selected to login with BCSC app
-Successfully logged in to account
-I have selected "cancel" button which is below the Send Credential button

Actual Result:
-In app browser closed and navigated to home screen of the wallet app and throwed the above error

Notes:
Issue is occurring only on iOS 1.0.7(575)
https://idimjira.gov.bc.ca/browse/IASP-14716

![File (10)](https://user-images.githubusercontent.com/115668531/205361075-9f71061f-bd8a-4af1-be57-51ecfc76ce49.jpg)

**Comment by cvarjao** [comment]
@jleach , are we handling the redirect back to `bcwallet://bcsc/v1?did={theirDid}&status=cancel`?
