### ISSUE TITLE
Display/Accept Presentation Request

### ISSUE THREAD

**Issue by amanji** [bcgov/bc-wallet-mobile#77]
As a holder I need to approve any presentation request so I feel in control of how my wallet's contents are used.

[HiFi Wireframe](https://xd.adobe.com/view/74b73461-45e5-4f2b-b219-79ffe9c852a7-21e4/screen/9eb4a24e-9690-496c-b85e-d8bb19b4f235/)

#### Scenario: View Presentation Request
Given the holder has received a presentation request notification
When the holder selects a "presentation request notification" from the home screen
Then they are brought to the presentation request screen
  AND the most recent credential is initially suggested
  AND they can see the verifier's name
  AND a list of claims being requested with their respectively matched VC claim value
  AND a link to the details of the credential
  AND there is a "Decline" Button
  AND there is a "Send" Button

NOTE: [Presentation Negotiation](https://github.com/hyperledger/aries-rfcs/tree/main/features/0454-present-proof-v2#negotiation-and-preview) is out of scope for this story

**Comment by cvarjao** [comment]
@knguyenBC , please add link to wireframe

**Comment by amanji** [comment]
Can we update the Acceptance Criteria to:
   
* Given the holder has received a presentation request notification
* AND the holder selects a "presentation request notification" from the home screen
* AND they are brought to the presentation request screen
* THEN they see a presentation request
* AND they can see the verifier's name
* AND a list of claims being requested with their respectively matched VC claim value
* AND the most recent credential is initially suggested for each attribute
* AND a link to the details of the credential
* AND there is a "Decline" Button
* AND there is a "Share" Button

A separate acceptance criteria would be when the user selects the presentation request they are taken to the presentation request screen (which is actually captured on the home and notification screens)
