### ISSUE TITLE
Limit random generated colors

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#773]
Random generated colours for credentials is too expansive. There's a risk of credentials being florescent colours which is not legible.

If we can limit the saturation of colours to avoid the above scenario.

**Comment by bryce-mcmath** [comment]
Addressed in this [merged PR](https://github.com/hyperledger/aries-mobile-agent-react-native/pull/610), waiting to have bc-wallet-mobile submodule update after `moment` install
