### ISSUE TITLE
Revisit Modal Screens Design

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#774]
Currently, modal screens are being used for purposes that don't typically use modal screens. This has caused the team to stretch the capabilities of modals, causing bugs and inconsistent UX.

Change the following screens to modals
- [Decline?/Credential declined](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/d1213177-9895-4a53-aac3-81b2f5e7aaea)
- [Decline/Proof request declined](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/f02cd662-64c9-4bcf-9f38-6ac3bf33efdd)
- [Remove from wallet](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/9b5e6787-e024-4d11-bc24-27cc0caa403a)
- [Remove contact](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/58a3e5bd-45ac-4443-9e9b-23bf0c002748)

Please see updates to [style guide for use of modals](https://xd.adobe.com/view/eb9e0945-61d7-40ca-8e8e-bf4bd0c72934-becd/screen/4c69b7e3-3b7e-4f99-844e-2b65ec172bbf/) such as transitions, scroll, etc.:

**Comment by nodlesh** [comment]
@knguyenBC Is there a reason we should keep this in Review/QA? Can we move it to done?

**Comment by knguyenBC** [comment]
We can move it to done. I think I've aligned with @amanji and @jleach on this.
