### ISSUE TITLE
A black screen appears when tapping "Scan" in BC Wallet

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#775]
From Lawyer: 

"I have installed the bc wallet ap but when I click “scan” to scan the QR code the screen turns black.  Is there something that can be done to rectify this?"

Device: iPhone 7 software version 15.7.7

A solution that fixed the bug for the lawyer was to uninstall and reinstall the wallet.

**Fix:** Add a message stating that camera use is required to use the camera. 
Please use a full screen modal as laid out in the [style guide](https://xd.adobe.com/view/eb9e0945-61d7-40ca-8e8e-bf4bd0c72934-becd/screen/4c69b7e3-3b7e-4f99-844e-2b65ec172bbf/)

### Acceptance Criteria
Given the Holder has not allowed camera permission for BC Wallet on their mobile device
When the Holder selects the scan button
Then they are presented with a [full screen modal informing them that camera use is required](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/e99654a2-0c34-4739-bc6b-d2ddc55a75bd)
  and a primary button labelled "Open settings" that opens the device's settings
  and a secondary button labelled "not now" that takes them back to the home screen

**Comment by nodlesh** [comment]
For issues like this it would be great to get their device specifics. Type, OS, OS Level.

**Comment by knguyenBC** [comment]
Added the device specs

**Comment by jleach** [comment]
@knguyenBC This happens when they denied access to the camera. It could be fixed by going into Settings -> Privacy -> Camera -> BC Wallet and allowing the app to use the camera. We could add a message saying this to alert the user to the problem.

**Comment by knguyenBC** [comment]
Sounds like a good plan. I'll draft something and update this ticket.

**Comment by knguyenBC** [comment]
@jleach Updated the ticket to include solution for this issue, wireframes, reference to style guide, and acceptance criteria.
