### ISSUE TITLE
Auto publish to some TestFlight groups after build

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#777]
Currently Target groups:
- **IDIM Team**
- **The Team**

A test notes seems to also need to be applied when releasing to a group

**Comment by jleach** [comment]
I think this will be straight forward. As per the [docs](https://github.com/codemagic-ci-cd/cli-tools/blob/master/docs/app-store-connect/publish.md) we can add the `--whats-new` arg to add release notes and `--beta-group` to add additional external groups. I gave it a two because of testing.
