### ISSUE TITLE
PIN Validation messages incorrect (regression)

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#778]
As of build 586, when creating a PIN, If the pin is invalid,  `27463A` or `2357`, the incorrect error below is displayed.

Result:
![Screenshot 2022-12-08 at 6.58.26 AM.png](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/7091ee89-877b-4dfc-ac61-17d55dfa70a2)
![Screenshot 2022-12-08 at 7.12.10 AM.png](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/34ec834e-0282-407b-920b-d360d37dd78e)

Expected Result:
![Screenshot 2022-12-08 at 6.59.46 AM.png](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/af9f7e4a-87b5-4518-8d5c-61ed52f0f67e)
![Screenshot 2022-12-08 at 7.14.31 AM.png](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/124f7d49-1503-49eb-8380-0da8027367f5)

Environment:
Happens on both Android & iOS

Priority:
Medium

Severity:
Low

Impact:
Regression test T006-Security

Report:
https://allure-mobile.vonx.io/api/allure-docker-service/projects/ios-multi-device-full/reports/198/index.html#behaviors/d81cfc8cf180b485d245541956968052/6d97ed9d795f3bb2/

**Comment by amanji** [comment]
This was fixed by @jcdrouin21

https://github.com/hyperledger/aries-mobile-agent-react-native/pull/559
