### ISSUE TITLE
Update create pin screen UX

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#779]
**### Background**
People are experiencing confusion over the PIN screen. People view this screen and believe they need to input a PIN they received rather than input their own PIN that will be used to secure their wallet. This confusion is in part due to a bug that removed the header of the PIN screen that would give people more context. However a review of the current design is necessary to uncover potential improvements.

**DoD**
- User flow
- Wireframes
- Acceptance criteria

**Comment by hannahgov** [comment]
[Quebec](https://www.figma.com/file/yAyB5mvtV0fD27eddSo5d4/Tutoriels?node-id=1%3A29&t=wq0MIhWaa5PLAFM7-1) shared their flow with me and I'm going through past research to see if there are any findings on this that will help

**Comment by hannahgov** [comment]
I don't see anything in the Quebec designs on the PIN screen (flow or wireframes). I've done a lot of digging and maybe part of the confusion is because the app doesn't require a login/account name? such as phone number and password as an example. I've started to created alt designs in XD.

**Comment by hannahgov** [comment]
I created a few new screens based on testing. I would like us to try using a single box approach for PIN creation and login screens. XD [link](https://xd.adobe.com/view/6bbfc64d-d17e-402e-89d7-1a53d355ae5d-3eec/).

**Comment by hannahgov** [comment]
Reviewed with Kim, creating a dev ticket to complete the work.
