### ISSUE TITLE
Verifier Branding in Presentation Request

### ISSUE THREAD

**Issue by amanji** [bcgov/bc-wallet-mobile#78]
As a holder I want, as part of the presentation request, to see the verified name and branding of the verifier so I feel more confident in who I'm presenting my wallet's contents to.

Alternatively:

As a holder I want to see information about the verifier such as their logo, official name, and appropriate colours, so I feel more confident that I am presenting my wallet's contents to the right verifier.

**Comment by swcurran** [comment]
Not sure I like the wording of that as it bypasses the phishing angle.  While I agree we need to make it look good (as Peter talked about yesterday), we also have to do that in a way that IS trusted by the Holder -- not just making them feel more confident.

Perhaps:

`As a holder I want, as part of the presentation request, to see the verified name and branding of the verifier so I feel more confident in who I'm presenting my wallet's contents to.`

That will encourage us to always question how the name and branding is verified. For example, we (the Wallet Team) vets the verifier and includes the name and branding in a configuration in the wallet of "trusted verifiers".

**Comment by amanji** [comment]
Can this be closed?

**Comment by cvarjao** [comment]
same as #70
