### ISSUE TITLE
Upgrade react native to 0.72

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#781]
- Updating the packages
- Looking through the dependencies

**Comment by nodlesh** [comment]
Issues related to the initial testing of the React Native 0.72 upgrade.

Both platforms have issues on the the `Done` button after getting the credential, and the **`Go back to home`** button on the Information sent successfully screen.

On iOS the buttons just grey out and goes nowhere. App has to be restarted to continue. 
On Android tapping those buttons crashes the app. 

## Android
### Test in Sauce Labs
https://app.saucelabs.com/tests/050f53af70db4c1e9b9f25f75f4bd50a

### Video

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa1J0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2d0c8a413bc99a8fb3f120aa0b718e993391be69/AndroidDoneCrash.mp4)


### Logs
[AndroidLogs.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa1p0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e5fca61a4ffa40882ad29ac88fb2aca25dc46ff2/AndroidLogs.zip)

### Debug Tools

Sauce Labs has some new debugging tools that may help with crashes. You will need a SL account to use it. If you don’t have one reach out to Sheldon or Clecio.

[https://sl-b44d4dd24eee4b3dba47b5afb2a1baa6.sp.backtrace.io/p/BC-Wallet_ca-bc-gov-BCWallet_android_ead2/debug?filters=JTVCJTVCJTIyX2RlbGV0ZWQlMjIlMkMlMjJlcXVhbCUyMiUyQyUyMjAlMjIlNUQlNUQ%3D&fingerprint=ace3b2d637421f20cdbb2b0a9f8b049e9f0463011eb6df5cca52ebd8c7df5d51&debug=(a,0,0)](https://sl-b44d4dd24eee4b3dba47b5afb2a1baa6.sp.backtrace.io/p/BC-Wallet_ca-bc-gov-BCWallet_android_ead2/debug?filters=JTVCJTVCJTIyX2RlbGV0ZWQlMjIlMkMlMjJlcXVhbCUyMiUyQyUyMjAlMjIlNUQlNUQ%3D&fingerprint=ace3b2d637421f20cdbb2b0a9f8b049e9f0463011eb6df5cca52ebd8c7df5d51&debug=(a,0,0))

## iOS

### Test in Sauce Labs

https://app.saucelabs.com/tests/1c8de4eb1a314c638f7d852308964349

### Video

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2h0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a30b6a94acf4c90bb186c7972335ccd566d8613f/iOSDoneAndBTHStall.mp4)


### Logs
[iOSLogs.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2x0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e8c3d17139d311dae179b13c36dd5aa2df1ad497/iOSLogs.zip)

**Comment by cvarjao** [comment]
@nodlesh , there is a new build from PR #1410 , can you test that out when you have a chance?

**Comment by nodlesh** [comment]
@cvarjao sure, will do it first thing tomorrow morning.

**Comment by nodlesh** [comment]
Issues reported above on both Android and iOS have been resolved in this build. I was able to run end to end with no issues with the showcase on real devices. 

Android Results:
https://app.saucelabs.com/tests/c80982974d0b492bb4764fbd86d633a0

iOS Results:
https://app.saucelabs.com/tests/00a1f904dcd0426da90b8f5cee25941a

**Comment by nodlesh** [comment]
@cvarjao The regression tests executed last night against this 0.72 RN build of the wallet was successful. No anomalies detected. Looking good from that vantage point.
