### ISSUE TITLE
Implement OCA Bundle Branding 0.2

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#782]
- Update Credential List
- Update the Proof Request
- Update Credential Offer

Update credential details as part of ticket #782.

Dependent on the credential details
Specs: https://xd.adobe.com/view/045a1969-719a-4aa5-848f-637ef1b7051a-5109/ 

Accessibility Features:
- Adaptable Font Size based on Zoom/Text Size set on the device

**Comment by hannahgov** [comment]
@cvarjao Please estimate this work, new ticket will be created for the details
