### ISSUE TITLE
Implement OCA Bundle for Credential Details Branding 0.2

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#785]
Update credential details screen according to related ticket #782.

Dependent on the credential details
Specs: https://xd.adobe.com/view/045a1969-719a-4aa5-848f-637ef1b7051a-5109/

**Comment by nodlesh** [comment]
@knguyenBC Could you give your ok on this one?

**Comment by nodlesh** [comment]
@knguyenBC Could you apply your eagle eyes to this one?

**Comment by knguyenBC** [comment]
Credential details looks good.
