### ISSUE TITLE
"get Person credential" button is inaccessible with text enlargement/zoom

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#788]
Text enlargement on OS pushes the "get your person credential" button down from view on the home screen. 
Screen should scroll. 

- The home screen is not scrollable

**Comment by wadeking98** [comment]
I'll take a look at it

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/575

**Comment by nodlesh** [comment]
This fix is not in 629. Waiting for a newer build.
