### ISSUE TITLE
Contact List and Detail Branding

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#797]
- Name
- Logo
- Other Links
   - Terms and Conditions
   - Support
   - Report a problem
   - Privacy Policy

**Mismatches**
[Contact list wireframes](https://xd.adobe.com/view/be5d6531-658b-4d7c-8ec2-634825d724fe-eb0e/)

Chat screen
- Send button Icon
- "info" icon -> vertical ellipsis icon
-  Bottom drawer when selecting the "+" button does not match [style guide for modals](https://xd.adobe.com/view/eb9e0945-61d7-40ca-8e8e-bf4bd0c72934-becd/screen/4c69b7e3-3b7e-4f99-844e-2b65ec172bbf/)
-  Chat messages should be default top aligned
-  No timestamp (messages that appear the current date should provide just the timestamp, messages that appear after the current date should have date and timestamp)

**Comment by cvarjao** [comment]
Mostly done. @knguyenBC  will update the wireframes to reflect it

**Comment by knguyenBC** [comment]
Updated.

**Comment by nodlesh** [comment]
This is a design story correct? Can we add the design label on it?

**Comment by knguyenBC** [comment]
Was the work Bryce did to match the design in a different ticket?

**Comment by bryce-mcmath** [comment]
I just used this ticket, hope that's ok

**Comment by nodlesh** [comment]
@knguyenBC How close should the screens be to the design? If it is off at all should I put this ticket back in Estimated Ready? 
For example, How it looks now. 
![IMG_1F3344640234-1.jpeg](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/3498930d-c3c3-427a-bea5-bcc6fc4a7690)

The wireframe:
![Screenshot 2023-06-22 at 12.02.53 PM.png](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/614defdc-b717-473a-8156-0b7c4a7d1211)

**Comment by knguyenBC** [comment]
Icons, layout should be identical. If any icons are missing from the library, I'll add them.

**Comment by nodlesh** [comment]
Moving this to Estimated Ready.

**Comment by nodlesh** [comment]
@bryce-mcmath It seems like we are still missing the [+] in the bottom left corner? The image is from an iPhone 14 - iOS 16.5.1
Should this go back into the Sprint?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc2h4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2e24a099b7b6a44e3def4d0dd5be9f2f2594c09e/Screenshot%202023-09-06%20at%2010.37.07%20AM.png)

**Comment by bryce-mcmath** [comment]
@nodlesh that only appear when mobile proofs are enabled

**Comment by nodlesh** [comment]
Right you are. Verified fixed in 1179. Closing.
