### ISSUE TITLE
Mobile Verifier - Tech Preview (MVP)

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#800]
### User Story
TBD

### Acceptance Criteria
- Feature initially hidden under "dev mode"
- Ability to request presentation from an existing contact (connection)
- Ability to connect + request presentation
   - A way to produce connection and connectionless proof request
- Predefined list of baked-in proof requests
   - Full Name: Based on Person Credential
   - Proof of Over 19 years old: Based on Person Credential
   - Full Name + Proof of Over 19 years old: Based on Person Credential
   - Practising  Lawyer: Based on LSBC Member Credential
   - Practising  Lawyer + Full name: Based on LSBC Member Credential + Person Credential
   - Current Student: Based on showcase student credential
- Present QR Code to be scanned by another wallet app
- Show status of presentation (Success/Fail) and details (attributes, predicates)

### Todo
- [ ] Mockup of failed presentation
- 
### Out of Scope
- Create / Import / Customize Proof Requests: Only predefined ones are available as is
- URL Shortening

Concepts/Low-Fidelity for mobile app wallet as verifier

### Crawl / Walk / Run

**Crawl/MVP**
[See user flow](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/af6c4fed-7df8-490b-90b5-31ff517b3a99)
[See wireframes](https://xd.adobe.com/view/993bddd5-51cd-435b-b1bf-6b2224de6d99-cc68/)

**Fly/Blue sky**
[See wireframe concepts](**url**)

- Proof Request Templates
- Proof Request Wizard

**Comment by cvarjao** [comment]
Please connect with the Traction team. They might have some insights on this

**Comment by swcurran** [comment]
In the Mobile Verifier meetings we've talked about:

* designing a "Presentation Request Template" that a mobile user can
* discover from a trusted repository,
* select
* customize by entering data for parameters that meet their verification needs, and
* add the configured presentation request to their list of verifications

Later, when they go to do a verification, they can select from their list of verifications to trigger a real-time verification request.

Here are some thoughts on the requirements for the "Presentation Request Template" (PRT) system.

- The trusted repository might initially be built into the wallet, or accessed from a trusted, remote location.
- While the list is small, "discovery" may be limited to browsing the list, but eventually searching across PRTs will be needed.
   - Searching should include the ability to use the multilingual data from the PRT -- at least name and description
- PRTs must be curated.
- PRTs are technical components and (initially at least) are intended to be created by developer-types.
  - In other words, at least initially an interface for non-technical users is not needed.
- PRTs may have multilingual tags that enable searching within the repository.
- PRTs must have a name and description that is user-friendly and multilingual.
  - I suspect that OCA can be used to handle the multilingual elements of these requirements.
- During discovery, the user should be able to view a user-friendly view of the PRT in the language of their choice to see the schema(s),issuer(s) and set(s) of requested attributes in the PRT.
- The PRT format must allow PRT creators to define parameters for the mobile user to complete after selecting a PRT to be added to their own PR List. 
- The PRT must indicate where verification runtime values based on time are to be inserted into the Presentation Request sent to the holder.
   - Example: A predicate for "expiry" that verifies the credential is not expired (no entry needed by the mobile user)
   - Example: A predicate based on birthdate to confirm that the holder is older than a given age, entered by the mobile user.

**Comment by Jsyro** [comment]
Great start, but this is something else to consider;

PRT's should/could be directly linked to any governance documents/structures that they facilitate, not just a user-friendly description.

**Comment by swcurran** [comment]
Discussed some with @cvarjao and @knguyenBC .  Some feedback:

- Need to have clear terminology about:
   - the things in a repository (or somewhere) — what I call “PR Templates”
   - the things that a user has imported and customized in their verifier — perhaps “PRs” or “Proofs”
   - an instance of the use of a “Proofs” with a specific holder — perhaps “verifications"
- We need to separate the technology for this — e.g. a PR Template format, PR Template repository, search, import, customization — from the governance of who might operate the repository, curation of the repository, who is allowed to contribute templates, how to link the templates back to the submitter.
- That last bit could go to the technology. For example, the PR Template format might have to include the DID of the submitter and a signature verifiable using their DID — e.g. the PR Template might itself be a verifiable credential — a signed piece of data.  🤯

**Comment by swcurran** [comment]
A couple of other thoughts on this:

- We should work towards an Aries RFC for this to standardize the structure and make it reusable across the community.  We have lots of groups building UIs for building Presentation Requests, and I would theorize that enabling verifiers to consume pre-constructed PRTs such as this would be more useful.
- In defining a versioned standard we should build it with the assumption that there will be more than just AnonCreds Presentation Requests defined.  While we don’t have to support others, (notably the DIF Presentation Exchange protocol) immediately, we should be able to define the standard that allows it to be supported in the future.  Not sure if there are other such request protocols — DIF PE is the most mature that I know of.

**Comment by knguyenBC** [comment]
updated this ticket to include the MVP flow and wireframes as discussed with @swcurran and @cvarjao.

**Comment by cvarjao** [comment]
things to consider: Connection vs Connectionless
