### ISSUE TITLE
Create PIN Screen on iOS, keyboard blocking entry of second PIN with Zoom enabled.

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#801]
Steps to Reproduce
On iOS Select Zoomed in Display and Brightness.
![image.png](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/a3d01efc-1a6e-4292-8f03-98d586d63396)

Result:
Create PIN Screen
![IMG_EAB48DE8163A-1.jpeg](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/95c5af9f-8639-4d23-8072-ed64975381ed)

Environment:
iPhone 6s, iOS 15.7.1

Workaround
Don't have zoom turned on
Another possible workaround is to just keep typing, since the next row of pin numbers is automatically selected after the first row is done. Doing this blind and clicking Continue will properly set the pin. 

Priority
Medium

Severity
Medium

Solution
Enable scrolling?

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/586

**Comment by nodlesh** [comment]
This issue is not fixed in build 647. Waiting to verify fix in the next build.

**Comment by nodlesh** [comment]
Though the screen is scrollable now on build 650, it is not sticking to the upper portion of the screen, it is snapping down under the keyboard. 

https://images.zenhubusercontent.com/429950091/27e8b497-0c34-4f2a-af68-b611a658a434/rpreplay_final1674074795.mov

Moving this issue back to the Sprint Backlog for review in sprint planning.

**Comment by nodlesh** [comment]
This issue is resolved.
