### ISSUE TITLE
When creating a new connection the UI shows multiple overlapping text

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#808]
Some times when a creating a connection the screen text shows overlapping text. I think this occurs when the connection takes longer than expected. Not confirmed though.

![IMG_7167.PNG](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/410a4438-4014-4a2f-b6d1-b008f415a87c)

**Comment by jleach** [comment]
I can't reliably reproduce this. I'm creating the issue to raise awareness and track in case others experience this problem.

**Comment by jleach** [comment]
Still watching this one. When one of us can reproduce it we will fix.

**Comment by cvarjao** [comment]
We haven't seem in a while, closing for now
