### ISSUE TITLE
Display/Accept Non-Revocable Credential Offer

### ISSUE THREAD

**Issue by amanji** [bcgov/bc-wallet-mobile#81]
As a holder I need to see the contents of the offered VC so I understand what I'm accepting and feel confident in its validity.

#### Scenario: Holder View contents of VC
Given A QR code has been scanned
  AND a connection has been successfully made
  AND a  holder has received a Non-Revocable credential offer
When Holder taps on the credential offer notification
Then holder sees the contents of the VC in the [credential offer screen](https://xd.adobe.com/view/3db881d4-e963-42ec-a2c4-6b5ca23862a3-68eb/screen/a523d262-2549-4da9-9c2e-35ba1a84d7e8/)
  AND see a button to accept the credential
  AND see a button to decline the credential

Note: The content is defined in the wired frame. Issuer Name, Credential Name, Issue Date, List of Claims/Attributes
Note: Issue date may not be available yet

**Comment by cvarjao** [comment]
@knguyenBC , please add link to wireframe
