### ISSUE TITLE
timeout error message appears after a long loading

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#812]
From a user
"App doesnt load at all. Following a fresh install. The app displayed some introductory text discribing the app's function . Then it asked me to create a 6 digit pin to proceed. After picking a pin, I was prompted to enter the pin and followed by a "loading" spinner screen. About 30 sec later A message pops up saying that the action has timed out. That is the extent of my experience with this app. "

Device: Google Pixel 4
Device language: English
App version code: 557
App version name: 1.0.6
Android version: Android 13 (SDK 33)

**Comment by jleach** [comment]
I've seen this also on iOS, most recent build, first time using the app. May be more exaggerated on AFJ 0.3.2 but no data to compare.

**Comment by nodlesh** [comment]
I cannot duplicate this issue with build 557 on the device specified nor 647 (the latest build). I recommend Closing. @cvarjao Should we monitor this or close?

**Comment by nodlesh** [comment]
@cvarjao Should we close this since it is being monitored in another repo? My vote is to close this.

**Comment by nodlesh** [comment]
Closing this issue since there has been no complaint of this happening in a long while.

**Comment by cvarjao** [comment]
we have got a very similar report (via email) of this issue from someone (in Germany) running iPhone 13 Pro Max running iOS 16.5.

Screenshots:
<img width="482" alt="Picture1" src="https://github.com/bcgov/bc-wallet-mobile/assets/1348549/0a3a0932-5dcf-413e-a223-cb04e2d447b9">

<img width="482" alt="Picture2" src="https://github.com/bcgov/bc-wallet-mobile/assets/1348549/f6c953bf-17e3-4a1a-a274-9dc46c90d568">
