### ISSUE TITLE
App Settings Menu should fade in

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#813]
It currently slides from right on iOS.
for android it just fades in, for iOS it slides from the right. Please keep the **fade in** behaviour consistent for both OS's.

build: 640
device: android

**Comment by bryce-mcmath** [comment]
@knguyenBC I see this still has a spike label, have we firmly decided that we're going with the fade in behaviour for both?

**Comment by knguyenBC** [comment]
I can't remember why it was changed to a spike. I would say fade in for both. For iOS the screen slides to left. Which is odd behaviour. Usually a left sided menu button slides to right, especially if its a sheet. I remember conversations where replicating that behaviour was difficult to do. So a fade in was easier.

**Comment by nodlesh** [comment]
Fade works on iOS in build 1077.
