### ISSUE TITLE
Add Person credential button to "add credential" modal sheet

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#816]
The Person credential offer can be dismissed so that people who do not want the person credential in the future is not bothered by the notification forever. However if people change their minds or accidentally dismissed the notification. They can get their Person credential from these two locations:

**"add" credential modal sheet**
https://xd.adobe.com/view/5edd5ca1-8978-4b3f-bf87-9ef21548b877-0b8e/

These options are always available

**Comment by wadeking98** [comment]
closing this issue since it's been deployed to google play
