### ISSUE TITLE
Fix repo history so that all commits have DCO 

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#818]
Some of the commits in our repo got in before we added the bot to ensure the presence of the "Sighed-off-by" commit message. We'll need to go back through the history, probably with a rebase, and fix any erroneous commits. There should be tools to help with this.

DCO is **not** required for merge-commits AFAIK.

**Comment by swcurran** [comment]
I suspect this is not worth doing - unless there is a good tool. If BC Gov does not requires DCO (which it should IMHO), this particular repo is unlikely to be moved to Hyperledger or some other organization, where DCO would be required. As such, this can probably be ignored.  Perhaps other BCGov Digital Trust repos, but not this one.

**Comment by cvarjao** [comment]
We have enabled DCO required from now on, but we are not rewriting history for now
