### ISSUE TITLE
Credential Offer Success/Failure Notification

### ISSUE THREAD

**Issue by amanji** [bcgov/bc-wallet-mobile#82]
As a holder I need to know if the credential successfully arrived so I am kept informed about the contents of my wallet.

### Scenario 1: Holder is waiting for Connection (failure)

[Error modal wireframes](https://xd.adobe.com/view/4f9b250e-27d3-4d8b-af48-c6b90520d0ee-1ac8/)

Given the holder has scanned a QR code invitation
And waiting for connection to be established
When the connection fails to be established
Then a temporary error notification (toast) is displayed with an error message
And go back to the home screen

_Alternative_

Given the holder has scanned a QR code invitation
And waiting for connection to be established
When the connection fails to be established
Then a full screen modal is displayed with an error message and a button to back to the home screen

### Scenario 2: Holder is waiting for a Credential (failure)

[Error modal wireframes](https://xd.adobe.com/view/4f9b250e-27d3-4d8b-af48-c6b90520d0ee-1ac8/)

Given a credential offer has been received
And accepted
When the credential fails to be delivered to the user
Then a temporary error notification (toast) is displayed with an error message
And go back to the home screen

_Alternative_

Given a credential offer has been received
And accepted
When the credential fails to be delivered to the user
Then a full screen modal is displayed with an error message and a button back to the home screen

### Scenario 3: Holder is waiting for a connection (success)

[Getting a credential wireframes](https://xd.adobe.com/view/3db881d4-e963-42ec-a2c4-6b5ca23862a3-68eb/)

Scenario: Holder is waiting for Connection (success)
Given the holder has scanned a QR code invitation
And waiting for connection to be established
When the connection is established
Then the screen automatically takes the Holder to the offer screen

### Scenario 4: Holder is waiting for a credential (success)

[Getting a credential wireframes](**https://xd.adobe.com/view/3db881d4-e963-42ec-a2c4-6b5ca23862a3-68eb/**)

Given a credential offer has been received
And accepted
When the credential is delivered to the user
Then a full screen modal is displayed with a success message and a Done button

Given the holder accepts a credential offer from an issuer they are connected with
When the holder selects "Done"
Then the screen moves to the credential list page

**Comment by nodlesh** [comment]
For the first one, I think it is probably ok the way it is, but I might refactor it a little to be slightly more detailed or clear. So this one... 
```
Scenario: Holder is waiting for Connection (failure)
Given the holder has scanned a QR code invitation
And waiting for connection to be established
When the connection fails to be established
Then a temporary error notification (toast) is displayed with an error message
And go back to the home screen
```

...I would change to something like this:
```
Scenario: Holder is waiting for Connection (failure)
Given the holder has a valid QR code invitation (is it true that the QR code is valid in this case?)
When they scan the QR code invitation
(I don't think we need (but you can) state they are waiting, that is a side effect of the scan)
And the connection fails to be established for <reason>
Then a temporary error notification (toast) is displayed <error message> (are there specific errors for the different reasons?)
And they are taken back to the home screen (I'd reframe this to taken, so it is not misinterpreted that the user manually goes back to the home screen)

Examples:
| reason                                                           | error message |
| timeout?                                                        | this is taking too long man! |
| no internet connectivity at point of scan? | No internet |
| what other reasons?                                    | I don't know |
```

**Comment by knguyenBC** [comment]
A minor changes to the following scenario:

Scenario: Holder is waiting for Connection (success)
Given the holder has scanned a QR code invitation
And waiting for connection to be established
When the connection is established
Then the screen automatically takes the Holder to the offer screen

**Comment by jleach** [comment]
@knguyenBC A few ways I deviated from the designs (and why):

- We don't have any branding (logo) ATM so I just re-used the first letter of the issuer like we did in credential list
- We don't have a great way to show who issued the credential (yet) so I've used what exists now until we figure out a better way;
- I removed the duplicates of usage of branding. In the design we have the logo at the top, then just below. Not sure if duplicating them so close adds much but LMK if you want it as per the designs;
- I changed "Issued: Pending" to "Issued: Jan 21, 222". Since its an "offer" that is not yet accepted "Pending" seems implied to me also, a date fits better with the word "Issued". LMK if Pending is what you want. It'll be hard coded as an offer is always "Pending" until a following screen (After they hit Accept or Decline).
 
![IMG_D8A4F9F69B37-1.jpeg](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/56f75c1d-a9b3-4db2-8fef-24718a88e40d)

**Comment by nodlesh** [comment]
@knguyenBC The Getting a Credential links above to the wireframes don't seem to work. Would you be able to update them? I'm try to figure out what this screen should look like. 
![Screen Shot 2022-03-24 at 9.05.27 AM.png](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/f7ff792b-4bb9-4db3-ad31-8f1dddc8978f)

**Comment by knguyenBC** [comment]
@nodlesh I've fixed the "getting a credential" link. Should work now :)

**Comment by cvarjao** [comment]
Remaining scenario added to the backlog as #372
