### ISSUE TITLE
"this is taking longer than usual" message appears immediately after accepting a credential offer

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#825]
"this is taking longer than usual" message appears immediately after accepting a credential offer. The expected behaviour is for that message to appear after 10 seconds. 

Tested on android
Build: 647

**Comment by nodlesh** [comment]
@bryce-mcmath @knguyenBC Looking at this in build 743. It seems that after the cred offer, it takes ~5 seconds before the taking longer message appears. Is this acceptable?

**Comment by knguyenBC** [comment]
Should be 10 seconds.

**Comment by nodlesh** [comment]
@cvarjao Moving this back to Estimated/Ready to be slated for upcoming sprint.

**Comment by nodlesh** [comment]
Verified fixed in build 823.
