### ISSUE TITLE
Going to credential tab should always default to credential list screen

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#826]
**Current behaviour:**
user is in Credential list screen -> user selects lawyer credential-> opens lawyer credential details screen -> users go to home tab ->user goes to credentials tab -> open lawyer credentials details 

**Expected behaviour:**
user is in Credential list screen -> user selects lawyer credential-> opens lawyer credential details screen -> users go to home tab ->user goes to credentials tab -> **credential list screen**

**Comment by wadeking98** [comment]
This also happens with the notifications list screen in the home menu

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/607
