### ISSUE TITLE
Add "What are Contacts" content from settings

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#828]
Please add screen which the following content
Header: What are Contacts?
Body: 
Adding organizations as a Contact will allow you to:

- Get updates to credentials issued by this organization
- Get offered new credentials
- Fast-track proof requests

You can always remove Contacts at anytime from your Contacts list. [please link the words "Contacts list" to the Contacts list screen]
Use of your credentials is never shared with your Contacts.

![image.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/fee3a417-d3e0-42a4-8951-0bf122fbde0e)

Wireframes:
https://xd.adobe.com/view/f239cc67-e22a-4178-84ae-4cf06b1dff23-a76a/

Acceptance Criteria:
Given that the user has set that app to use English language
When the the user opens the "What are contacts" from the App Settings
Then the user can se the screen in English

Given that the user has set that app to use French language
When the the user opens the "What are contacts" from the App Settings
Then the user can se the screen in French

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/599
