### ISSUE TITLE
Initialization & loading  flow

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#829]
- provide some granular status (perhaps starting with 2 steps)
- initializing x of `n` ledgers
- tips and hints while waiting : [see wireframes](https://xd.adobe.com/view/1fa13810-e597-4029-8e89-7643ee880a4b-4af2/)
- better error messages (provide some indication of the cause)

**Comment by knguyenBC** [comment]
The tips aren’t read out when voice over is enabled. It simply says “tips”. Can you ensure that the tips are read out when they switch as well?

**Comment by bryce-mcmath** [comment]
They are apparently read out on Android but not iOS. Not sure why this is, potentially an issue / bug with the `FlatList` component in React Native. #861 has been created to track this issue, hopefully Jason or Akiff can take a look at it
