### ISSUE TITLE
Experiment with and consider updating the OCA for Aries Style Guide to support a "Stacked" layout

### ISSUE THREAD

**Issue by swcurran** [bcgov/bc-wallet-mobile#838]
A request from the Aries community from an OCA for Aries discussion on Wednesday at the Aries Working Group ([Meeting Page with Recording](https://wiki.hyperledger.org/display/ARIES/2023-01-18+Aries+Working+Group+Call)) was to add a "stacked" layout so that many more credentials would be visible on screen in a list.  The proposed stacked layout would be the Credential List layout, but with only one full layout, and the rest showing only the top of the card layout -- cut off below item 6 -- the Credential Name (from the Meta overlay, `name` item).

The minimum change to satisfy the request would be to just say, "A stacked layout can would look like this..." and show where the cutoff line would be.

A consideration would be to tighten up the top of the layout (items above element 6) so that the top is a little smaller and separated from the rest of the layout of the credential in the list view.

Is there a reason not to use this view?

Here is a sample of the type of stacked layout.  The credentials in this image don't match the Credential List layout (and would in an implementation) -- this is just provide to show the concept.

![image](https://user-images.githubusercontent.com/1018050/213595689-cecc1c05-5ebf-45dc-bf08-2d3f3411de06.png)

In experimenting with this, are there any other suggestions?

**Comment by swcurran** [comment]
@knguyenBC -- requesting that you look at this issue and collect feedback. As appropriate, please update the Google Doc Style Guide.  I notice that the recording from last Wednesday's call is not there yet.

**Comment by knguyenBC** [comment]
@swcurran Here are UI designs for the stacked and non-stacked view of credentials https://xd.adobe.com/view/e5820613-50d3-458b-b2c7-1028ab5386c9-b0d1/

**Comment by swcurran** [comment]
Thanks. Looks like header of the stacked view is unchanged from before, correct?  In other words, the stacked view is the same as the card list view that we already had, but with everything below the header cut off.

For the Style Guide then, I just need to add the stacked view picture, right?

**Comment by knguyenBC** [comment]
Exactly. Header is unchanged. If a user has enlarged text in their device settings then the header height increases. https://xd.adobe.com/view/045a1969-719a-4aa5-848f-637ef1b7051a-5109/screen/36ea8856-83d9-445e-9cc3-3d23ddf5d6b8/ 
I can update the style guide.

**Comment by knguyenBC** [comment]
Style guide updated.
