### ISSUE TITLE
Migrate the mediators to the Gold / Gold DR clusters for continued service

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#845]
The brief outage in the Kamloops DS recently has uncovered a weakness in our infrastructure. To fully become HA we need to ensure that infrastructure issues don't impact the availability of our mediator and ability to provide services. By migrating to Gold / DR this will be realized.

**Comment by WadeBarnes** [comment]
Prior to this we need to figure out how to make the mediator service HA.  There are still a number of things we need to work out in this regard.

**Comment by jeffaudette** [comment]
will track this for now until we have a ticket on the ent apps side

**Comment by jeffaudette** [comment]
Clecio to bring to SM/PO this week @cvarjao

**Comment by cvarjao** [comment]
@esune , is there a ticket somewhere else so we can close this one?

**Comment by esune** [comment]
As per @WadeBarnes comment above, we need to sort out how to make the service HA first - logged https://github.com/bcgov/DITP-DevOps/issues/146 to track that, so this issue can be closed.
