### ISSUE TITLE
Update create pin screen and the login screen

### ISSUE THREAD

**Issue by hannahgov** [bcgov/bc-wallet-mobile#848]
After researching other apps and deigns of these screens I feel making the following changes will help reduce confusion around the [PIN screens](https://xd.adobe.com/view/489eb6bf-e073-46ac-b56b-a57f8f2176f2-1dcd/).

**Background**
People are experiencing confusion over the PIN screen. People view this screen and believe they need to input a PIN they received rather than input their own PIN that will be used to secure their wallet. This confusion is in part due to a bug that removed the header of the PIN screen that would give people more context. However a review of the current design is necessary to uncover potential improvements.

Linked to design ticket #779

**Comment by bryce-mcmath** [comment]
@knguyenBC There are some wireframes with an updated design. Is this ticket ready for dev work now?

**Comment by hannahgov** [comment]
I believe this was ready to go a while back, Kim can confirm.

**Comment by knguyenBC** [comment]
@hannahgov the wireframes still have ALT designs. Can you update the file so that it only presents the final design?

**Comment by hannahgov** [comment]
I updated my link. I didn't realize I have to hit update for it to not show as ALT.
