### ISSUE TITLE
Alignment of the close button looks off on custom notifications

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#849]
In the screen shot below the "X" in the top right of the notification looks misaligned or too cramped in that corner. 

![IMG_0023.jpg](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/e35897b5-bd85-4c78-9212-73469a17a859)

**Comment by hiteshgh** [comment]
@jleach - can you pls re-test and close if working

**Comment by nodlesh** [comment]
This looks good in build 1079. Closing.
![IMG_A15E10CC089F-1.jpeg](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/f2054df9-b0fe-4cd8-9e02-3251eb6ee3c8)
