### ISSUE TITLE
Can't tap/select buttons that are hidden behind the scan button without activating the scan buton

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#859]
As I'm navigating to a button at the bottom of the screen using talkback/voice over I can't tap/select the button when it's hidden behind the scan button. Example below: When I try to tap/select the "Start" button, the camera gets activated.

![image.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/72ecddf5-50db-42fa-b97b-2835485d66aa)

Device: iPhone 6
Build: Version 1.0.7 build 676

**Comment by cvarjao** [comment]
The content doesn't scroll enough to access the start button at the bottom

**Comment by jleach** [comment]
I tried on two different iphones, one with a 5.4" screen (the iPhone 6 is 4.7" so still a bit smaller) and it looks ok. Are you able to confirm if this is still an issue. It's quite an old ticket and I want to be sure that someone didn't already make an adjustment.

In the screen shot below I can scroll down far enough to make the "View" button not obscured by the scan button.

![IMG_F8808EF7BF91-1.jpeg](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/4d537b20-e4a4-4a43-8c3d-38f8aa09f2bc)

**Comment by knguyenBC** [comment]
This issue is fixed by that extra padding then.
