### ISSUE TITLE
Stuck on Person Credential screen after clicking "send credential"

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#860]
After going through the flow of opening the BCSC App, Go back to the wallet and accepting the Terms, and clicking on "send credential" it goes back to the "Person Credential" splash screen.

Expected Behaviour:
The flow after selecting "Send Credential" should take the user back to the BC Wallet Home screen where the Credential offer automatically opens once its been received by the wallet.

Workaround:
- Close/cancel the screen and the credential offer is waiting in the home screen

https://user-images.githubusercontent.com/1348549/215219018-315d1fb9-ed0c-40ce-9d7c-20aec48ab37a.mov

**Comment by knguyenBC** [comment]
The flow after selecting "Send Credential" should take the user back to the BC Wallet Home screen where the Credential offer automatically opens once its been received by the wallet.

**Comment by jleach** [comment]
I think this can be a two part fix: First I'd add some logic to dismiss the screen when the IDIM site returns "success"; if it returns "cancel" maybe the user would want to try again so I'd leave them on this page so they can manually exit. The second step would be to add logic to make the home screen "BCView" automatically process the notification. I though it did this but it may not have been added back after the notable refactoring to the workflow. In any case not overly complicated to add it back in.

**Comment by jleach** [comment]
Fixed main issue. Users will be returned to the home screen now. A new ticket will be created to automatically start the workflow to handle the offer.
