### ISSUE TITLE
Initialization Flow Experience

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#871]
### User Story:
As a wallet user
I want the setup to be as quick as possible
So that I can start using the app as soon possible

### Acceptance Criteria:
- start and background wallet initialization as soon as possible
- perceived improved experience by seeing shorter loading screen

Notes:
- give something to distract users (onboarding, EULA, tips, ...)
- Check for technical limitations (e.g.: PIN/Biometrics is a requirement to start the initialization)

Wireframes:
https://xd.adobe.com/view/29c6299f-de61-4d73-8e92-aacb36565e4f-7c95/

**Comment by knguyenBC** [comment]
Clarify the position of the EULA in the flow and revisit whether or not the gains (time saved) of this initialization flow is worth the effort.

**Comment by knguyenBC** [comment]
Clarified that EULA can be placed after PIN/biometrics screens.

**Comment by knguyenBC** [comment]
Concluded that reorganizing the initial onboarding screens does not provide enough value. Will explore simply adding expectations to the first "tip" when initialization starts.
