### ISSUE TITLE
Tips/Text cutoff at Initialization Waiting screen with large font size

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#875]
[Video](https://drive.google.com/file/d/1PcyncOMMbSDL5n24KiZktNEPkByOhBem/view?usp=sharing)

Please ensure that ALL screens are scrollable with text/features/elements extend past the fold. 
Please refer to the [style guide](https://xd.adobe.com/view/eb9e0945-61d7-40ca-8e8e-bf4bd0c72934-becd/screen/85451f18-0e57-43a3-aff5-39c4151a8d16/) for more guidance

**Comment by nodlesh** [comment]
Verified fixed in build 823.
