### ISSUE TITLE
Presentation Request Selective Field Disclosure

### ISSUE THREAD

**Issue by amanji** [bcgov/bc-wallet-mobile#88]
As a holder I need to be able to choose, where applicable, which VC fields are used for a presentation so I can choose the most appropriate information to present.

Notes: this supports the [credential presentation negotiation protocol](https://github.com/hyperledger/aries-rfcs/blob/main/features/0347-proof-negotiation/README.md) where a user may provide an alternate presentation request that they can satisfy

**Comment by cvarjao** [comment]
closing stale issues. Selective Disclose is already supported when verifiers can ask for specific attributes instead of the whole credentials. The credential negotiation feature is tracked under #144
