### ISSUE TITLE
Revocation Notification Layout

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#881]
- notification design should follow the error notification colour palette (red)
- [link to styleguide](https://xd.adobe.com/view/eb9e0945-61d7-40ca-8e8e-bf4bd0c72934-becd/)

**Comment by bryce-mcmath** [comment]
Updating estimate to 3 because I had to refactor a component pretty extensively

**Comment by knguyenBC** [comment]
Looks good. Checked build 772 with the showcase.
