### ISSUE TITLE
unable to scan QR code after upgrading from 1.0.6-557 to 1.0.7-690

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#886]
How to reproduce:
- Install 1.0.6-557, go through a showcase
- Upgrade to 1.0.7-690, go through a showcase (fails here)

[Video](https://drive.google.com/file/d/1AIp9U-dIqXqWDHmM3ow7xoJWT5fntq-o/view?usp=share_link)

**Comment by jleach** [comment]
Closing. Moved to Bifold repo as issue [625](https://github.com/hyperledger/aries-mobile-agent-react-native/issues/625).
