### ISSUE TITLE
Get Person Credential page has no TestIDs

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#897]
### Steps to Reproduce
``` gherkin
Given I have a gone through the process of getting a BC VC Pilot Invitation credential
 | https://bcvcpilot-issuer-admin-test.apps.silver.devops.gov.bc.ca |
And I have selected to Start to Get Person Credential in the Person Credential Notification on the Home screen
When I am on the Get Person Credential page
Then There are no TestIDs to access the Get Person Credential or Get this Later buttons
```

### Expected Result
There would be the standard `com.ariesbifold:id/GetYourPersonCredential` and `com.ariesbifold:id/GetThisLater` testIDs.

 
### Environment
BC Wallet build 691
Tested on Android

### Workaround
I have been using the Accessibility IDs, which work fine.

### Severity
Low

### Priority
Low

### Screenshots or Video
![Screenshot 2023-02-09 at 5.08.28 PM.png](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/637e86be-62a0-4c2c-81c4-7db0890fa187)

### Test Impact
T001-BCSC, T002-BCSC

**Comment by hiteshgh** [comment]
@nodlesh - can you pls re-test and close if working

**Comment by nodlesh** [comment]
Cannot test yet until test refactoring. Test is failing and not getting as far as needed to verify this issue.

**Comment by nodlesh** [comment]
The verification of this issue is blocked by #1360.

**Comment by hiteshgh** [comment]
@nodlesh #1360 is unblocked

**Comment by nodlesh** [comment]
This is still an issue. No TestIds for those buttons on the page.  Checked in build 1179.

**Comment by nodlesh** [comment]
TestIDs are now present. Closing.
