### ISSUE TITLE
Link is not valid when selecting "Get your Person credential"

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#898]
### Steps to Reproduce
``` gherkin
Given I have a gone through the process of getting a BC VC Pilot Invitation credential
 | https://bcvcpilot-issuer-admin-test.apps.silver.devops.gov.bc.ca |
And I have selected to Start to Get Person Credential in the Person Credential Notification on the Home screen
And I am on the Person Credential screen
When I select Get your Person Credential
Then the web view displays "The Link is not valid"
```

### Expected Result
To get options to login to the BC Services Card Account

 
### Environment
BC Wallet build 691
Tried the Environment set to Production and Test
Tested on Android

### Workaround
None known. It may be that a refresh would bring the page up, but didn't try that in the automated tests. 

### Severity
High

### Priority
High

### Screenshots or Video
![Screenshot 2023-02-09 at 5.14.25 PM.png](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/44b121ed-8589-419e-8ecc-f2239aa95525)

### Test Impact
T001-BCSC, T002-BCSC

**Comment by jleach** [comment]
I can't find the bug but I seem to remember adding a delay on Android for this and I can see the logic still exists. I delay for 5sec on android (3 on iOS) before opening the link to give time to the back-end mechanics to finish setting things up. Will confirm if more delay is the issue or not.

**Comment by jleach** [comment]
Cannot reproduce. There is a slight delay added (5s Android, 3s iOS) to allow back-end systems to do what they need to. Perhaps this was just a edge case that tool longer than expected. Punt this back to me if the problem surfaes again.

![Screenshot 2023-02-15 at 11.15.15 AM.png](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/78afb0ae-09c0-4daa-9252-8efc0c7e7905)

**Comment by nodlesh** [comment]
Have not seen this in a while. Closing.
