### ISSUE TITLE
Presentation Request Cancelation

### ISSUE THREAD

**Issue by amanji** [bcgov/bc-wallet-mobile#90]
As a holder, I would like the option to cancel a proof request after approving a proof request so that I can try again if the transaction goes wrong or if I decide to change my mind last minute.

Note: It is not possible to cancel because there is no guarantee that the information has already been shared with the verifier. May need technical deep dive to find a solution for this feature.

**Comment by knguyenBC** [comment]
Added wireframes of the delayed flow.

**Comment by cvarjao** [comment]
@knguyenBC  will fix the description

**Comment by cvarjao** [comment]
A proof request cannot be cancel. We will provide user navigation features to allow user to navigate out of the flow.
