### ISSUE TITLE
Remove Settings title from Menu header

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#900]
The "Settings" screen is no longer just for settings. The "Settings" label is misleading. Please change to "Menu".
Also change accessibility label of "hamburger menu" to "Menu"

**Comment by jleach** [comment]
![Screenshot 2023-04-24 at 11.29.13 AM.png](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/d15a5979-2121-4ae0-875e-17e2731bdacc)!

[Screenshot 2023-04-24 at 11.29.27 AM.png](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/9457f5ab-e4ec-45d8-9f8a-b08ce4cdafdb)

**Comment by knguyenBC** [comment]
Perfect

**Comment by jleach** [comment]
![Screenshot 2023-04-24 at 11.29.13 AM.png](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/c45adef9-8e05-49ca-a932-fbb84cc2af3b)

![Screenshot 2023-04-24 at 11.29.27 AM.png](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/944d820b-2842-4ccd-a172-46e5fd1f0fc0)
