### ISSUE TITLE
What are Contact screen has unnecessary scrollable content 

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#901]
Bullet points in the "What are Contacts?" screen are unnecessarily scrollable. All other content is static. Content should be static and scrollable unless content is pass the view screen.

https://images.zenhubusercontent.com/429950091/afa1d1e0-53a3-49dc-9f28-89c586185415/rpreplay_final1676070947.mp4

Device: iOS, iPhone SE, build 695

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/724

**Comment by nodlesh** [comment]
Verified fixed in build 823.
