### ISSUE TITLE
Implement Jest testing in bc-wallet-mobile

### ISSUE THREAD

**Issue by bryce-mcmath** [bcgov/bc-wallet-mobile#903]

**Comment by bryce-mcmath** [comment]
The majority of the scaffolding is done (the single test added is passing) but there is an issue with Jest not liking tests of components that import from bifold that was taking me too long to sort out. Possibly solvable by editing `jest.config.js`. Mocking bifold seems to make these tests pass but I don't think that's a valid solution.

**Comment by jamshale** [comment]
I'm new to this project but maybe mocking bifold is a valid strategy? The tests in this project shouldn't be testing bifold. I should be assuming bifold is tested within bifold. There is still a lot of valuable testing that could be done with a mocked bifold in this project.

**Comment by bryce-mcmath** [comment]
@jamshale just seeing this. I think I wasn't very clear, sorry about that. What I mean is that if a screen in BC Wallet uses a button imported from Bifold the tests won't run until I use a mock the button component in it's entirety. So it's essentially not testing the real thing unless I have a copy of Bifold in the __mocks__ folder. There should be some configuration way around this issue but I haven't been able to find it. I think it's due to the fact that Bifold is a submodule and not a regular dependency.
