### ISSUE TITLE
Define user flow for providing feedback

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#905]
[Feedback flow](https://app.mural.co/t/digitalidentityandtrust0399/m/digitalidentityandtrust0399/1634147263262/84c4b0f485a1366bd5cd451bed26c833fb14a621?wid=0-1677105283258)

### Crawl
- webform for feedback
- Separate webform for bugs/issues

### Run
- via chat / built-in

**Comment by knguyenBC** [comment]
Reviewed with design team on flow. Will talk with dev team on survey implementation into the app
