### ISSUE TITLE
Releaset BC Wallet with fix to resolve first credential issue. 

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#906]
There is an [issue](https://github.com/hyperledger/aries-mobile-agent-react-native/issues/625) with the upgrade to AFJ 0.3.3 that will delay the release of 1.0.7 until it is understood and fixed. We would like to release the fix from [645](https://github.com/bcgov/bc-wallet-mobile/issues/645) to fix a production issue.

More info in this Rocket.Chat [conversation](https://chat.developer.gov.bc.ca/group/bc-digital-wallet-core-team?msg=BkSSC6gtasJER4H2B)

**Comment by jleach** [comment]
@cvarjao I think this won't take too long to fix. I recommend doing it locally and publishing the fix manually to avoid fooling with the Bifold repo. That's where the fix will need to go. To do it through the CICD system it will be more like a 3 because we'll need to point our submodule to a branch based of whatever 1.0.6 was linked to.

Also, when pushed to TestFlight it may break insillations as AFJ does not have a downgrade option.

**Comment by cvarjao** [comment]
Related to #1512
