### ISSUE TITLE
Upgrade mediator to 0.8.0 in the TEST environment

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#908]
- [ ] Get a OpenShift image build working properly
- [ ] Rollout to TEST environment
- [ ] Test mediator upgrade

### Blocked By
- [x] hyperledger/aries-cloudagent-python#2123
- [x] hyperledger/aries-cloudagent-python#2124
  - Workaround,  hyperledger/aries-cloudagent-python#2125

**Comment by WadeBarnes** [comment]
You're actually going to want to use [ACA-py v0.8.0-rc0](https://github.com/hyperledger/aries-cloudagent-python/releases/tag/0.8.0-rc0), which has added support for building and publishing container images.  When updating our services we should also be switching over the the new [ACA-py container images](https://github.com/hyperledger/aries-cloudagent-python/pkgs/container/aries-cloudagent-python) as the base images.

**Comment by WadeBarnes** [comment]
BTW [ACA-py v0.8.0-rc0](https://github.com/hyperledger/aries-cloudagent-python/releases/tag/0.8.0-rc0) is the latest release.

**Comment by jleach** [comment]
I'll update the [Dockerfile](https://github.com/hyperledger/aries-mediator-service/blob/main/acapy/Dockerfile.acapy) to pull in the new [base image](https://github.com/hyperledger/aries-cloudagent-python/pkgs/container/aries-cloudagent-python)

**Comment by jleach** [comment]
Blocked by hyperledger/aries-cloudagent-python#2123. Waiting...
