### ISSUE TITLE
In-app guide: Credentials List Screen (v1)

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#913]
### Description of feature / user story
As a new user of BC Wallet, I would like to see a description of important features in the wallet so that I have a good understanding on how to use it

### Acceptance Criteria
Given the holder enabled in-app guides
When they enter the credential list screen
Then they are presented with an in-app guide that describes how to get credentials

Given the holder has dismissed (tapped done) the in-app guide
When they enter the credential list screen
then they are NOT presented with the in-app guide again.

### Wireframes or relevant image assets / links
https://xd.adobe.com/view/97441d12-756f-4bff-897d-b1bf29ed7c65-c217/screen/426ea4c2-5ecb-45ea-9bf1-abc4cb9a8804/

**Comment by jleach** [comment]
Verified in 1.0.15-1452
