### ISSUE TITLE
Upgrade the mediator service in all environments to use ASKAR wallet storage

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#918]
Currently the mediators use the INDY wallet format. We would like them to all be upgraded to use the ASKAR format.

Environments:

- [x] dev
- [x] test
- [x] prod

**Comment by WadeBarnes** [comment]
If you need to migrate the wallets, you'll need to use the migration scripts being developed here; https://github.com/Indicio-tech/acapy-wallet-upgrade.  Once complete these will become part of the Hyperledger project.  You can check with the Indicio team on Hyperledger Discord regarding the current state of the scripts.

Depending on the content of the wallets it might be easier to start over with a new wallet.

**Comment by WadeBarnes** [comment]
This was completed a while ago.  All mediator instances are using Askar storage.
