### ISSUE TITLE
Review implications of AFJ targeting Android 30+

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#921]
We currently support android 28+, new Indy VDR/Shared Objects/Askar/AnonCreds will target 30+

- Target currently supported Android/iOS
- Reduced [user audience](https://gs.statcounter.com/os-version-market-share/android/mobile-tablet/canada)
- Ask BCSC currently device distribution
- What do we need to do to support old versions?
- Current Minimum [Supported Android](https://endoflife.date/android): 10
- Current Minimum [Supported iOS](https://endoflife.date/ios): 12

**Comment by jleach** [comment]
@cvarjao Is this still a thing? I think we managed to get AFJ building all the way down to API 26 or so which means we don't need to worry about 30+. If you agree please close.

**Comment by jleach** [comment]
@cvarjao Is this still a thing? I think we managed to get AFJ building all the way down to API 26 or so which means we don't need to worry about 30+. If you agree please close.

**Comment by cvarjao** [comment]
This has been resolved, and AFJ/Shared components targets API 26
