### ISSUE TITLE
Fix BC Wallet Build for Card Branding

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#922]
Layout and image slice cropping needs a little work
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/1348549/220426283-fb5149f2-a0b3-46e3-accb-077678399bf5.png)

**Comment by nodlesh** [comment]
I want to add to this issue in regards to the card branding. My issues were noticed on the Credential Offer screen. 
Issue 1:
The colors selected for some credentials are not Accessible. Actually no one can see the text on this particular example. 
<img width="281" alt="Screenshot 2023-02-21 at 11 09 42 AM" src="https://user-images.githubusercontent.com/44370861/220457061-dcdbf44b-f347-41f7-a46f-28aa716cbed5.png">

Issue 2:
I'm not sure it makes sense that the default icon in the left side has the first letter or number of the Issuer or cred definition?
<img width="221" alt="Screenshot 2023-02-21 at 8 35 46 AM" src="https://user-images.githubusercontent.com/44370861/220457477-ebc094c0-01d8-4f67-82af-5e5c9e95c173.png">

These issues were found on Build 709

**Comment by amanji** [comment]
Fixed by https://github.com/hyperledger/aries-mobile-agent-react-native/pull/639

**Comment by nodlesh** [comment]
Fix and subsequent issues not present in build 761.
