### ISSUE TITLE
Customize login security method

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#93]
As a person who is wary of my privacy and security, I want to set my security settings to maximum security so that I can be reassured that my digital wallet will not be used maliciously

As an early-adopter, I want to customize the login experience of the app so that I can choose the option that I am comfortable with and doesn't impact the wallets convenience.

DoD
- Wireframes and user flows are defined
- TBD

**Lo-Fi wireframes**
https://xd.adobe.com/view/dddddab2-f649-41d4-b2d8-d156d2ef1e1f-888e/

**Comment by jleach** [comment]
Hey, note the ON team is reworking the security / biometrics component.

**Comment by knguyenBC** [comment]
Right. I'll align myself with that they're doing.

**Comment by swcurran** [comment]
Are there any notes or wireframes on that?

**Comment by knguyenBC** [comment]
Looking at their working design file there hasn't been any updates on security settings.

**Comment by knguyenBC** [comment]
Talked to the UX team. The Ontario team is working on it :)

**Comment by jleach** [comment]
Saw it in the demo. Looks quite good! Yay Ontario.
