### ISSUE TITLE
Incorrect Person Credential Branding

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#931]
![signal-2023-02-23-092603](https://user-images.githubusercontent.com/1348549/220985341-108465a5-738d-43f5-8ac4-4ec3f17f927a.jpeg)

![signal-2023-02-23-092556](https://user-images.githubusercontent.com/1348549/220985377-affd467f-6c6f-4f45-855a-74712844a3e5.png)

![signal-2023-02-23-092539_002](https://user-images.githubusercontent.com/1348549/220985494-65a42392-7af9-4ab3-9ce3-11184e09d7be.png)

**Comment by knguyenBC** [comment]
@knguyenBC double check image size for person cred
