### ISSUE TITLE
Wait and automatically open Person credential offer

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#938]
As a wallet user
I want an easy and convenient flow for getting person credential
so that it is seamless, quick and easy to get a new person credential
[View full Person credential flow](https://xd.adobe.com/view/0f671997-ae72-4d7c-b880-2134f9dd3ee5-5a34/)

## Acceptance Criteria
Given that the user has tapped "Get Person Credential" Notification **from the home screen** OR **from the "add credential" drawer** in the credenntials list screen
AND the user in the review person credential page from IDIM
When user selects "I agree to the above terms" and selects "Send Credential"
Then user is taken to the [person credential screen](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/04910814-1d58-40ad-8c84-2efd5d3ce487) 
     the screen is in it's [waiting state](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/942d5de6-57a9-4214-b17c-9126b607f51e)
     and the moment the credential offer is received, [the wallet opens the credential offer screen](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/fb8dacb6-c20f-46ce-b641-756ac1e26037)

Impacted Build: 1.0.7-725

**Comment by nodlesh** [comment]
Tested and Automated with Build 750. 
Tests located here - https://github.com/hyperledger/aries-mobile-test-harness/blob/main/aries-mobile-tests/features/bc_wallet/bcsc.feature
