### ISSUE TITLE
Add a link to a support channel in-app

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#94]
As a novice user, I want access to a support channel so that when I have any issues with the app or system, I can easily get support.

**Blocked**
- communication/support channels are yet to be defined

**DoD**
- Wireframes are defined

**Lo-Fi wireframes**
https://xd.adobe.com/view/dddddab2-f649-41d4-b2d8-d156d2ef1e1f-888e/

**Comment by jmdkumar08** [comment]
Done
