### ISSUE TITLE
Missing Person Credential image

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#940]
There should be an image of a person credential preview

https://github.com/bcgov/bc-wallet-mobile/blob/dcbe7d856c7e5404aa0e5c7ecdc808830aad4f88/app/src/screens/PersonCredential.tsx#L108

**Comment by jleach** [comment]
We decided on todays free-style after scrum to fake the data for now as a "crawl" and in the future we'll show redacted for our walk solution.

**Comment by knguyenBC** [comment]
Please display the credential using the following data 
Primary attribute : Given names = Sample Given Name, 
Secondary attribute: Family Name = Sample Family Name

**Comment by wadeking98** [comment]
Changed the estimate to 5 because I needed to go into bifold and change how it displays credential attributes
