### ISSUE TITLE
Unable to get credentials on certain version of iOS and Android < 11.

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#941]
iOS devices failing to receive a credential
- iPhone SE (iOS 16.3.1) - Kim/Hannah
- iPhone X IOS 14.8 - SL regression
- iPhone 12 IOS 14.8 - SL regression
- iPhone11 (iOS 16.1) - CV

Android devices failing to receive a credential
- OnePlus 6 (Android 11)

[See list of full failed/successful devices](https://docs.google.com/document/d/1aQ78xuq1iTUI8cvU3pC_obxP_giYaioM62j0Om4qzug/edit#heading=h.sb1s4escv9h8)

**Kim:**
Attempted demos: Animo demo, BC Showcase demos, LSBC member card. 

**Steps** (on mobile data) :
Installed wallet > went through onboarding screens > initialization timeout (received an error) > restart the app > tapped scan > scanned QR code > Connecting... > end 

**Attempted fixes**
- restart the app - fail
- reinstall the app - fail
- use mobile data - fail
- change location - fail

**Comment by hannahgov** [comment]
This is happening on my iPhone SE phone with iOS 16.3.1. 
- Reinstalled the app
- Scanned BC Student credential, waited, eventually timed out
- Close and reopen the app
- Told the demo to resend the credential and it never got it

I repeated the same thing with the lawyers demo credential

**Comment by hannahgov** [comment]
With the mediator restart I was able to smoothly get credentials in both my devices:

iPhone SE (iOS 16.3.1) - PASS 
Google Pixel 7 Pro (Android 11) - PASS

**Comment by nodlesh** [comment]
Both the initialization timeout and the issue cred issue have been reproduced with Sauce Labs Devices. This is a fresh install on an android 10 API 29 device. This failure happened after just having a successful issue cred on a different Android 11 API 30 device on Sauce Labs.
Attached are the device and network logs from this failing test run. 
[https://app.zenhub.com/files/429950091/e0632e5e-2ed3-4868-8939-5eac8b08ab08/download](https://app.zenhub.com/files/429950091/e0632e5e-2ed3-4868-8939-5eac8b08ab08/download)

The same android 10 API 29 device with 557 (1.0.6 official) running, I had no issue initializing. I did get the first cred issue where I had to restart the app to get the cred offer. But I was able to get the credential with 557.

**Comment by knguyenBC** [comment]
(on wifi, at home) Reinstalled apps on both android and iOS > Still getting initialization timeout for both devices > closed/opened app again > got inside > iOS testing BC showcase demo, Android testing Animo demo > Connecting... (connection made , contact is in contacts) >taking longer than usual... > close/open app > nothing

(on DATA, at home) iOS testing BC showcase demo, Android testing Animo demo > Connecting... (connection made , contact is in contacts) >taking longer than usual... > close/open app > nothing

devices: OnePlus 6 (Android 11), iPhone SE (iOS 16.3.1)

**Comment by bryce-mcmath** [comment]
Successfully got cred and did proof from a fresh install on iPhone 13 with iOS 16 (physical device)
Timeout occurred with fresh install on Pixel 4 with Android 11 (emulator)

Consistently timing out on the Android emulator after many attempts, timeout error message appears in less than 25 seconds, not sure if that helps

**Comment by bryce-mcmath** [comment]
557 is consistently timing out on the above mentioned Android emulator setup now as well. iOS continues to work well.

**Comment by bryce-mcmath** [comment]
This is the error from the metro console I usually see when there is a timeout during initialization. I'm also finding the firewall message is popping up more often

![Screenshot 2023-03-02 at 3.23.36 PM.png](https://images.zenhubusercontent.com/63bc52dfbcde5d544793e7d3/e89fd70b-01ca-427e-b1af-b8fd3bcd15ed)

**Comment by jleach** [comment]
This is what I see when I trigger the timeout:

```console
 DEBUG  DEBUG: Wallet 'walletId' opened with handle '3'
 INFO  INFO: Agent storage is up to date.
 DEBUG  DEBUG: Starting WS outbound transport
 DEBUG  DEBUG: Starting HTTP outbound transport
 DEBUG  DEBUG: Provision mediation with invitation {
  "mediatorInvitationUrl": "https://aries-mediator-agent.vonx.io?c_i=removed-for-brefety"
}
```

Metro just sits here and the timeout error screen appears.

**Comment by jleach** [comment]
I can reproduce this quite easily with an AFJ test script so its not specific to the wallet (iOS or Android). I'm going to try and setup a scenario where I can trigger this in our test environment since prod needs to be restarted when this issue presents.

**Comment by knguyenBC** [comment]
Can receive credential in latest build (772)
