### ISSUE TITLE
Add a link to the showcase in the app home screen

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#942]
As a wallet user
I want play with the app
     and learn more about verifiable credential
so that I can understand how the wallet app works 

### Acceptance Criteria
Given the holder is in the menu screen of BC Wallet
When a holder taps ["Play with BC Wallet" under the "More information" section](https://xd.adobe.com/view/f239cc67-e22a-4178-84ae-4cf06b1dff23-a76a/)
Then the holder will be taken to the [BC Wallet showcase](https://digital.gov.bc.ca/digital-trust/showcase/) in an external browser

**Comment by knguyenBC** [comment]
Need more clarification from Clecio.

**Comment by nodlesh** [comment]
@cvarjao @knguyenBC  What is the state of this? Is this a UX design ticket only? Is there a dev Story created?  Can we close this?

**Comment by knguyenBC** [comment]
This is a ticket opened by Clecio. No UX really needed if it's simply adding another item in the Menu. Following closely the design of what's already there should suffice.

**Comment by wadeking98** [comment]
Resolved by: https://github.com/bcgov/bc-wallet-mobile/pull/1694

**Comment by jleach** [comment]
Verified in 1.0.15-1452
