### ISSUE TITLE
Unable to view person credential offer

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#944]
New credential offer (the person credential) does not open after tapping the view button on notification. 
Steps: select send credential>takes me to bottom drawer with person credential button loading>loads forever>goes to home>see notification of credential offer> taps credential offer notification> nothing happens

Steps to fix: close/open app>taps credential offer notification>offer opens.

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/657
