### ISSUE TITLE
"Learn about digital wallet" content

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#95]
As a novice user who is curious but cautious of digital wallets, I want to be able to find more information about how to use the wallet, my credentials, learn more about the system and others, so that I can clarify away any fears I might have with the security and privacy of the system and learn how to properly use the app in a safe and secure way.

**Blocked:**
- How this information will be relayed to users is yet to be defined. Will it be an external weblink accessible within the app? Will the information be within the app itself? 

**Lo-Fi wireframes**
https://xd.adobe.com/view/dddddab2-f649-41d4-b2d8-d156d2ef1e1f-888e/

**Comment by jmdkumar08** [comment]
Done
