### ISSUE TITLE
Issuer logo does not appear credential offer for LSBC member card

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#954]
Issuer logo does not appear credential offer for LSBC member card (it appears for the Person credential)

![20230306_170520.jpg](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/c30299dc-f11d-49a9-8a84-37ae3cf8c21b)

**Comment by cvarjao** [comment]
fixed
