### ISSUE TITLE
Remove top issuer logo in credential offer

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#955]
The Person credential offer adds the issuer logo. Not part of design.

![20230306_165531 (2).jpg](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/0f9ea142-5efb-4150-b28d-ded121e3b255)

**Comment by knguyenBC** [comment]
Discussed with Clecio. We'll keep the issuer logo in the design.

**Comment by cvarjao** [comment]
We are keeping the issuer logo.
