### ISSUE TITLE
Remove or change content of AriesBifold prompt

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#962]
When a user taps "Get Person credential" on iOS, they are presented with [a prompt that states "AriesBifold" wants to use "gov.bc.ca" to sign in](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/ffcf2ee0-7c8e-414c-913c-972eddb26b01). This message is confusing and causes people to think it's a scam/spam message that they hesitate to tap continue.

We should either remove the prompt or at the very least reword the prompt so that it makes sense.

**Comment by knguyenBC** [comment]
@cvarjao After speaking with @bryce-mcmath , the changes we have control over for the prompt won't be enough to help deter people feeling like it's a pop up scam. The only thing we have control over is change the name of our app which will still have the prompt say "BC Wallet" Wants to use "gov.bc.ca" to Sign In." Which still doesn't make much sense. Also, the body of the prompt is concerning as well.

I think it's important to fix this prompt (or remove it) to ensure that people go through the Person credential flow with confidence.

**Comment by jleach** [comment]
@knguyenBC @cvarjao This one already says "BC Wallet". If we want to get rid of it we need to do some notable refactoring and I'm not sure its worth it. That dialogue box is quite common and iOS and users should expect it if they use the Authentication view - which quite a few apps do.

**Comment by knguyenBC** [comment]
I think we discussed this is person last time as well. We can close this then.
