### ISSUE TITLE
Revocation content missing from Revoked Credential Details

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#965]
Bug:
~~missing (i) icon next to revocation status. This (i) icon opens the revocation message~~
Missing content at the bottom of the screen like revocation message and precise revocation date

Fix:
Design fixes. See new Acceptance Criteria below and wireframes

### Acceptance Criteria 
[[from ticket #63](https://app.zenhub.com/workspaces/bc-wallet-6148e7423fe04b001444e2bd/issues/gh/bcgov/bc-wallet-mobile/63)]

``` gherkin
Given a credential has been revoked
When the holder goes to the [revoked credential details](https://xd.adobe.com/view/615be678-5184-40cc-ab24-11a379a51233-3408/)
Then they will see a dismissible notification at the top displaying the revocation date and revocation message by the issuer
And they will see a revocation status below the issued date in the credential details

Given a credential has been revoked
When the [holder dismisses the dismissible notifications](https://xd.adobe.com/view/615be678-5184-40cc-ab24-11a379a51233-3408/screen/47fbeddd-9b8b-45f4-bb6f-73635d131306/) at the top displaying the revocation date and revocation message by the issuer
Then that notification is permanently dismissed and can not be brought back again
```
### Wireframes
[Revocation message in credential detail screen](https://xd.adobe.com/view/615be678-5184-40cc-ab24-11a379a51233-3408/)

### Screenshots of build 732
![Screenshot 2023-03-09 at 5.06.17 PM.png](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/e804018b-7a3a-49f0-98f0-10403dd9ad18)
 
### Environment
BC Wallet build 732
Tested on Android 11

### Workaround
None known

### Severity
Medium

### Priority
Medium

### Test Impact
T011.1-Proof, T011.2-Proof

**Comment by knguyenBC** [comment]
Ticket updated with wireframes and link to acceptance criteria of existing revocation ticket.

**Comment by cvarjao** [comment]
@knguyenBC, please update acceptance criteria and wireframes

**Comment by bryce-mcmath** [comment]
@knguyenBC is this ticket ready to go now?

**Comment by knguyenBC** [comment]
I've updated the ticket to include the changes as discussed with the team: removed the need to invoke another notification pop up. The revocation status is permanent and contains both the revocation message and date of revocation. The notification at the top is dismissible once and cannot be brought back again.

**Comment by nodlesh** [comment]
This is working as designed in build 1077.
