### ISSUE TITLE
requested attributes name used instead of credential name in credential card on proof request screen

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#967]
### Steps to Reproduce

``` gherkin
Given I have credentials
And I have a proof request that I can satisfy with a credential in the wallet
Then the credential card shows the requested_attributes` name instead of the credential name.
```
![Screenshot 2023-03-13 at 10.56.16 AM.png](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/e599f1c2-3fbc-48fc-82fc-483d829f70b2)

This is the proof request.
```
{
   "requested_attributes": {
      "photo_attrs": {
         "names": [
            "name"
         ],
      "restrictions": [
            {
               "schema_name": "photo_id_revokable",
               "schema_version": "1.0.0"
            },
            {
               "schema_name": "photo_id",
               "schema_version": "1.0.0"
            }
         ]
      }
   },
   "requested_predicates": {
   },
   "version": "0.1.0"
}
```
This also includes a proof of non-revocation that is not shown above. 

Notice `photo_attrs` is used instead of the credential name of `photo_id_revokable` or `photo_id`.

### Expected Result
The Credential Card would show the name of the credential

 
### Environment
BC Wallet build 743
Tested Android 11

### Workaround
None known

### Severity
Medium

### Priority
Medium

### Test Impact
T007-Proof

**Comment by wadeking98** [comment]
resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/659

**Comment by nodlesh** [comment]
Verified fixed in build 804.
