### ISSUE TITLE
Standardize vocabulary/taxonomy

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#97]
As an organization, I want a standardized digital ID ecosystem so that there is an easily adopted guidance, support and consistency for better customer experience

As an ID holder, I want to easy to understand vocabulary, so that digital wallets are easier to learn and understand.

As an ID holder, I want consistent language, so that digital wallets are easier to learn.

**DoD**
- An agreed upon list of terminologies used at the app level

Living Taxonomy documnent:
https://docs.google.com/spreadsheets/d/15kJWYZQSSpmvGDVOlo35dBeX8qTm_dVlSoMwX-MMLL4/edit

**Comment by knguyenBC** [comment]
Terms include: 
Credential Offer
Proof request/presentation request
Schema
Credential Name
Credential definition
Claim
Attribute

**Comment by alexgmetcalf** [comment]
Terminology document shared out to pan-Canadian team on Feb 8.

**Comment by alexgmetcalf** [comment]
Latest terminology (request access from me):
https://docs.google.com/spreadsheets/d/15kJWYZQSSpmvGDVOlo35dBeX8qTm_dVlSoMwX-MMLL4/edit

**Comment by alexgmetcalf** [comment]
I believe we now have a terminology list that 'works' for v1. I will create a new ticket that is for working through the text throughout the wireframes and updating it for consistent terminology and Tone of Voice.
