### ISSUE TITLE
Lawyer Credential Branding Update

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#970]
logo = LS---BW_240x240.jpg
background image = LSBCimagebackgound_1080x360_v2.jpg
primary background colour = #23485A
secondary background colour = #00698C

Files are in the Credential branding google drive

![image.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/c1a681e4-c7d6-479f-9f48-0be334614a44)

**Comment by knguyenBC** [comment]
Waiting for LSBC confirmation

**Comment by knguyenBC** [comment]
LSBC has confirmed. Will add design changes

**Comment by knguyenBC** [comment]
LSBC has confirmed. Will add design changes
