### ISSUE TITLE
Credential Branding redesign

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#974]
Propose a few layout options for some of our main credentials
- Document the design decision from v1.0 (card) to v1.1 (flexible)
   - Motivation
   - Principles
- highlight credential detail screen
-  a few colouring/image options for each credential 
- [x] Pilot Invitation Credential Branding Update
- [x] Student Showcase Branding Update
- [ ] Lawyer Credential Branding Update
- [ ] Person Credential Branding Update

**Comment by knguyenBC** [comment]
LSBC is in the midst of a branding update and will provide a new credential design when their rebranding is complete. The Person credential redesign is tasked by Trinity.

**Comment by knguyenBC** [comment]
Student and pilot credential design has been reviewed by execs and approved. A poll was conducted for both credentials and the winner was finalized. assets are available in google drive.
