### ISSUE TITLE
App Attestation (v1) | spike

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#981]
- How does it work for both Google/Apple stores?
- Any feature misalignment
- How can we implement it

**Comment by jleach** [comment]
Asked BSCS for their thoughts on the subject. We're going to meetup with them and compare notes. They've already implemented app attestation in the BCSC.

**Comment by jleach** [comment]
Noting 3rd party service provider and interesting links:
https://blog.jscrambler.com/securing-react-native-applications/
https://approov.io/product/app-attestation/

**Comment by jleach** [comment]
Moving to done. I think we understand the roadmap for this feature.
