### ISSUE TITLE
Monitor Connection Timeout errors from mediator

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#992]
- [ ] Reproduce the error (Jason has created some scripts) consistently from non prod (dev or test)
   - [ ] (Optional) Can we also reproduce the error with just AFJ
- [ ] Does time out happened on the client side only? or server side as well?
- [ ] Where those timeouts are set? and can we increase? server time out should be shorter (30s) than client side (45s)
- [ ] Come up with something we can use to track the connection timeout error (log files?)

```text

March 17th 2023, 14:59:22.548	aries-mediator-agent	2023-03-17 21:59:22,548 aries_cloudagent.transport.inbound.ws ERROR Unexpected Websocket message type received: WSMsgType.CLOSED: None, None
March 17th 2023, 14:56:39.975	aries-mediator-agent	2023-03-17 21:56:39,975 aries_cloudagent.transport.inbound.ws ERROR Unexpected Websocket message type received: WSMsgType.CLOSED: None, None

```

**Comment by cvarjao** [comment]
@swcurran , can you add this to aca-py backlog?

**Comment by swcurran** [comment]
Added as [issue 75 in the aries-mediator-service repository](https://github.com/hyperledger/aries-mediator-service/issues/75).

Closing this issue.
