### ISSUE TITLE
Issuer and credential name is not showing up in proof request

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#995]
This is a proof request from a lawyer trying to gain access to ACM with a LSBC member card but no person credential. 

The person credential missing the issuer name and credential name is being fixed in a different ticket but there should be an issuer and credential name on the LSBC member card.

Screenshot from lawyer.
![Artboard 1-100.jpg](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/6b64437b-2208-4d3d-be1a-911c3d423696)

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/726
