### ISSUE TITLE
Add "Give Feedback" to menu options

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#999]
### Story
As a user, I would like an opportunity to provide feedback on my experience using the app, so that I can take part in improving the user experience, vent any frustrations, or highlight any issues I've experienced.

### Acceptance critiera
Given that the holder is in the [menu/settings of BC Wallet](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/4917899e-116b-471b-ad96-771978860522)
When they select "Give Feedback"
Then they are taken to the [Feedback form](https://www.surveymonkey.com/r/7BMHJL8) via an in-app browser

Feedback form link : https://www.surveymonkey.com/r/7BMHJL8 
Form is live.

**Comment by knguyenBC** [comment]
Updated the ticket with the survey form.

**Comment by jleach** [comment]
Looking into how I might do this one. Right now its not overly doable because this is just a BC Wallet feature and I don't have the ability to customize settings just for BC.

**Comment by jleach** [comment]
Pumping the breaks on this one for now until we decide how to integrate it into settings.

**Comment by bryce-mcmath** [comment]
Draft PR for this feature here: https://github.com/bcgov/bc-wallet-mobile/pull/1113 

Would like to have some discussion about the implementation before I take out of draft

**Comment by bryce-mcmath** [comment]
Implementation has been merged in but will remain commented out until we are ready to un-gate the feature. The survey can still be seen in developer mode from the home screen
